### ISSUE TITLE
ERROR: All individuals have missing/invalid phenotype values.

### ISSUE THREAD

**Issue by dorks81** [rgcgithub/regenie#10]
Hi,

We are evaluating regenie v1.0 with UK Biobank size data. We completed step using the genotyped array data for chr18. However when we executed step 2 using a chunk of chr18 imputed bgen data, and error was thrown ERROR: All individuals have missing/invalid phenotype values. The exact same phenotype and covariables files were used in both steps. Will you please point me to where I may be making a mistake in my command?

  --step 2
  --bgen chr18.4.bgen
  --c covar.txt
  --p phenotype.txt
  --extract extract.maf01.snplist
  --b 200
  --pred height.chr18_pred.list
  --split
  --threads 8
  --chr 18
  --o chr18.4

**Comment by joellembatchou** [comment]
Hi,

Could you update to the most recent version go regenie (version 1.0.3) and re-run this command? 

Also note that the `--extract` command only work in step 1 (so all SNPs in the bgen file will be tested [those with MAC less than the threshold will be ignored])

**Comment by avsmith** [comment]
I see this same issue. If I feed at step2, the bgen file is rejected as having missing/invalid phenotype values. I can get the same files to work as follows. 1) Create a sample file from the bgen file with `qctool -g genotypes.bgen -os samples.txt` and 2) running regenie adding `--sample sample.txt` to the call. The sample names are not being recognized directly from the bgen file, but work when exported from same.

**Comment by joellembatchou** [comment]
Indeed, the `--sample` option can be used to specify the sample IDs which correspond to the BGEN file (in case the sample IDs are not included in the BGEN file <- this usually would not be the case if the file is created with PLINK2 `--export` function).
