### ISSUE TITLE
REGENIE meta-analysis 

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#100]
I've conducted REGENIE on a multi-ancestry sample, using ancestry as a covariate. Within this sample, if I'd like to conduct ancestry-specific analyses and then a meta-analysis instead, can you please advise how I might proceed...That is sny suggestions for specific tools for REGENIE meta-analyses?? 
(i.e. For example, for PheWAS R, there is a PhewWASMeta function where the input is the data frame containing phewas results..).

**Comment by joellembatchou** [comment]
Hi,

We do not have additional scripts for performing meta-analyses. After running the within-ancestry analyses in Regenie, you could use tools like [METAL](https://doi.org/10.1093/bioinformatics/btq340) to perform meta-analysis using the within-ancestry summary stats.

Cheers,
Joelle
