### ISSUE TITLE
Using the PGEN format: PSAM file variants and PGEN import error

### ISSUE THREAD

**Issue by wuttke** [rgcgithub/regenie#105]
**From the PLINK2 docs:**

https://www.cog-genomics.org/plink/2.0/formats#psam
`A text file which usually has at least one header line, where only the last header line starts with '#FID' or '#IID'.`

**Head of my PSAM file:**

```
#IID    SEX
1000046 NA
1000063 NA
```

**REGENIE output:**
`ERROR: Header does not have the correct format.`

**REGENIE source code:**

```
  while (getline(myfile, line)) { // skip to main header line
    tmp_str_vec = string_split(line,"\t ");

    if( tmp_str_vec.size() < 1 ){
      cerr << "ERROR: No blank lines should be before the header line in psam file.\n";
      exit(EXIT_FAILURE);
    }

    if( tmp_str_vec[0] == "#FID" ) break;
  }

  // check header
  if( (tmp_str_vec.size() < 2) || (tmp_str_vec[1] != "IID")){
    cerr << "ERROR: Header does not have the correct format.\n";
    exit(EXIT_FAILURE);
  }
```

I was able to "fix" this easily by using AWK.

**Comment by wuttke** [comment]
... but unfortunately later, I got errors from the pgen library.
Something about the reference allele being set in the header is not supported.

**Comment by wuttke** [comment]
` * pgen             : [xxx_chr22_noPhase.pgen] Tracking og reference alleles in header is not supported.`
The pgen was exported with "erase-phase".

**Comment by joellembatchou** [comment]
Hi,

We do assume the PSAM file has FID and IID columns both present (which as you mentioned is an easy fix in bash). For the error you mentioned, this seems to be from the PGEN library we are using. What is the PLINK2 command you used to get the PGEN file? I will add some changes which should address this error.

Cheers,
Joelle

**Comment by wuttke** [comment]
Thank you very much for your response. I've used this command:
`plink2 --vcf $VCF dosage=DS --out plink2_chr$CHR`

**Comment by joellembatchou** [comment]
Perhaps the documentation in [here](https://www.cog-genomics.org/plink/2.0/data#ref_allele) might be helpful, especially this
```
"--ref-allele <VCF filename> 4 3 '#'", which scrapes reference allele assignments from a VCF file, is especially useful.
```

We will work on addressing this error message in the next release.

Cheers,
Joelle

**Comment by Wainberg** [comment]
Thanks for the tip @joellembatchou! It looks like regenie is using an old version of pgenlibr.cpp that doesn't support "explicit non_ref flags" (whatever those are), but the plink developers implemented support for them in July 2019 in [this commit](https://github.com/chrchang/plink-ng/commit/f817dad4e5a9fd53bfd3f2c3e40808a8d2a22fde#diff-07bddd424159b6f68137abbbe89b59bf615b947f21052d5d00c4ea0005e3bdd5L101). So I think all that's needed to fix the bug is to update to a more recent version of pgenlibr.cpp.

**Comment by Wainberg** [comment]
As a stopgap, exporting to bgen with `plink2` --pfile $pfile --export bgen-1.3 --out $pfile` and then loading the bgen into regenie with `regenie --bgen ${pfile}.bgen --sample ${pfile}.sample` seems to work perfectly!
