### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by wuttke** [rgcgithub/regenie#106]
Version: REGENIE 2.0.2 (fresh download)
BGEN file:

 * bgen             : [xxxxx_chr22.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with xxxx named samples and xxxx variants with 16-bit encoding.
   -sample file: xxxxx_chr22.sample

Chromosome 22 [406 sets in total]
   -reading loco predictions for the chromosome...done (2606ms)
 set [1] : 6 variants...
     -reading in genotypes and building masks...**Segmentation fault**

I'm going to try with 8 bits.

**Comment by wuttke** [comment]
With 8 bit instead of 16 bits, it works. ;)
This is only minor, but at least a better error message would be helpful.

**Comment by joellembatchou** [comment]
Hi,

This error should be fixed in the next release.

Cheers,
Joelle
