### ISSUE TITLE
Regenie with repeated measures

### ISSUE THREAD

**Issue by gamalazim** [rgcgithub/regenie#107]
Can **REGENIE** be utilized to process repeated measurements of the same phenotype on the same individual (i.e., replicates or several measurements taken thru time)? In essence, the '_regenie_ _approach_' itself should be able to handle repeated measurements. I think also input files and model options should follow certain rules (if there is any) as when I tried, I got back the error:  '_Individual appears more than once in phenotype file:_'

Thanks   
Gamal

**Comment by joellembatchou** [comment]
Hi,

Regenie does not handle repeated measurements on the same sample, such as found in longitudinal data. We would recommend using other software which can work with such data sets. We will make note of this feature request to potentially incorporate it in a future version.

Cheers,
Joelle

**Comment by chrisraynerr** [comment]
Hello,

Was a repeated measures feature added to the program? 

Many thanks,
Chris
