### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by eleporcu** [rgcgithub/regenie#108]
Hello,

I tried to install regenie but I got this error message

src/Regenie.cpp: In function 'int chrStrToInt(std::string, int)':
src/Regenie.cpp:887:69: error: no matching function for call to 'regex_replace(const string&, std::regex, const char [1])'

Hoy can I fix it?

Thanks a lot
Eleonora

**Comment by joellembatchou** [comment]
regenie requires compilation with GCC version >= 5.1. Which GCC version are you compiling with?

**Comment by eleporcu** [comment]
Sorry, I was using an older version. Thank you!
