### ISSUE TITLE
optimal subset of variants for Step1 generating LOCO files

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#109]
If I am only testing 2 variants of specific interest for REGENIE association of binary traits in a cohort (~8,000+ samples). Is there an optimal number of variants to use for Step1 LOCO prediction?? That is, how many variants are optimal to use for Step1--generating LOCO predictors (i.e. randomly QC'ed subset or other??)..If any specific guidance or reports...I have a fully genotyped cohort but need to test/report only 2 specific variants of interest for association...Thanks.

**Comment by joellembatchou** [comment]
We recommend to  have around 500K variants (eg directly genotyped SNPs) for Regenie step 1. You can find details on QC we applied in the [Regenie pre-print](https://www.biorxiv.org/content/10.1101/2020.06.19.162354v2) as well as recommendations [on the website](https://rgcgithub.github.io/regenie/recommendations/#preparing-genotype-file).
