### ISSUE TITLE
ERROR: No sets are left to be analyzed. in gene burden testing

### ISSUE THREAD

**Issue by OmegaPetrazzini** [rgcgithub/regenie#112]
Hi, I am trying to run gene burden on LOF variants. I only have one mask so my mask_file looks:
Mask1   LoF

And my annotation file looks:
1:69849:G:A     OR4F5   exon    LoF
1:69869:T:A     OR4F5   exon    LoF
1:925960:C:T    SAMD11  exon    LoF
1:925996:C:T    SAMD11  exon    LoF
1:930221:C:T    SAMD11  exon    LoF
1:931053:G:A    SAMD11  exon    LoF

I am getting this when running
Options in effect:
  --step 2 \
  --bed UKBexomeOQFE_chr5 \
  --phenoFile phenotype_file.txt \
  --covarFile covariates_file.txt \
  --anno-file Anno_file.txt \
  --set-list Set_list.txt \
  --mask-def Mask_file.txt \
  --pred fit_l1_pred.list \
  --bsize 500 \
  --out regenie_gene_burden_chr5

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [UKBexomeOQFE_chr5.bim] n_snps = 777162
 * fam              : [UKBexomeOQFE_chr5.fam] n_samples = 198855
 * bed              : [UKBexomeOQFE_chr5.bed]
 * phenotypes       : [phenotype_file.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals = 174994
   -number of individuals remaining with non-missing phenotypes = 174994
 * covariates       : [covariates_file.txt] n_cov = 12
   -number of individuals with covariate data = 198681
 * number of individuals used in analysis = 174994
 * LOCO predictions : [fit_l1_pred.list] n_files = 1
   -file [fit_l1_1.loco] for phenotype 'Y1'
   -residualizing and scaling phenotypes...done (2ms) 
 * annotations      : [Anno_file.txt] 
   +number of annotations categories = 1
   +number of domains across all sets = 0
 * masks            : [Mask_file.txt] n_masks = 0
WARNING: Detected 1 masks with only unknown annotations (these are ignored).
 * aaf cutoffs      : [1 : 0.01 ] + singletons
 * set file         : [Set_list.txt] ERROR: No sets are left to be analyzed.

Looks like it's not finding the "LoF" annotation from the Anno_file.txt. Any help or suggestion will be very helpful.

Thank you!

**Comment by joellembatchou** [comment]
Hi,

It seems that the variants in the annotation file are not being recognized as present in the genotype file. Could you check if there are any special characters in the annotation file? (e.g. `cat -A Anno_file.txt`)?

**Comment by seuchoi** [comment]
I got the same error message.

**Comment by OmegaPetrazzini** [comment]
That was it thank you!

My position was in a different annotation. It was e.g. 1:69849:G:A and should have been e.g. chr1_69849_G_A.

Hope this helps seuchoi.

**Comment by seuchoi** [comment]
Oh.... got it.....
I had the same issue. 
My file was e.g. 1:69849:G:A and should have been e.g. chr1:69849:G:A
Thanks!!!!

**Comment by Shicheng-Guo** [comment]
I think I meet the same issue. There is a "$" sign at end of the line and it can be only seen with `cat -A`. I have tried sed and perl script to read and re-write, but the "$" sign are always there. Is there any suggestion to remove these "$" sign? 

```
rs1490922004 OR2L8 PD4$
chr1_247948931_T_C OR2L8 PD1$
rs779314525 OR2L8 PD4$
chr1_247949502_T_G OR2L8 PD2$
```
Thanks. 

> Hi,
> 
> It seems that the variants in the annotation file are not being recognized as present in the genotype file. Could you check if there are any special characters in the annotation file? (e.g. `cat -A Anno_file.txt`)?

**Comment by joellembatchou** [comment]
The "$" is fine as it indicates the end of the line and so will be recognized in Regenie as separate from the annotation PD4,PD1,....
