### ISSUE TITLE
regenie v2.0.2 || Only unphased bgen are supported

### ISSUE THREAD

**Issue by sariya** [rgcgithub/regenie#113]
I am trying to run step 2 in regenie where I run into error for unphased bgen. I have binary trait with case-control imbalance.
I used pre-compiled binaries. In the path I have bgen library. 

Data are on hg38 human genome reference build.

```
export PATH=$PATH:"~/bgen_binned/bin/"

./regenie_v2.0.2.gz_x86_64_Linux --step 1 \
  --bed updatedids_removedSNPs_hg38_notfoundTOPMED_alleles  \
  --covarFile regenie_phenotype.txt --covarColList AGE,SEX,PC1,PC2,PC3 \
 --remove  remove_individuals.txt \
  --phenoFile regenie_phenotype.txt --phenoCol AD --phenoColList AD  \
  --bsize 100 --bt --lowmem --out step1_MHAS_reg

qctool -g CHR22_rsq40_check.bgen  -os samples.txt 

./regenie_v2.0.2.gz_x86_64_Linux --step 2 \
--bgen CHR22_rsq40_check.bgen \
--covarFile regenie_phenotype.txt --covarColList AGE,SEX,PC1,PC2,PC3  \
--phenoFile MHAS_regenie_phenotype.txt \
--phenoCol AD --phenoColList AD \
--remove  remove_individuals.txt  --bsize 200 --sample samples_BGEN.txt \
--bt --firth --approx --pThresh 0.99 --pred step1_MHAS_reg_pred.list --out CHR22_bin_out_firth

```

Error:

> Association testing mode with fast multithreading using OpenMP
>  * bgen             : [CHR22_rsq40_check.bgen]
>    -summary : bgen file (v1.2 layout, zlib compressed) with 7234 named samples and 847317 variants with 8-bit encoding.
>    -index bgi file [CHR22_rsq40_check.bgen.bgi]
> ERROR: Only unphased bgen are supported.

I created bgen file using PLINK

```
plink2 \
--vcf chr"$chr".dose.vcf.gz \
--export bgen-1.2 'bits=8' --extract CHR"$chr"_rsq40_snps.txt --out CHR"$chr"_rsq40_check
```

VCF files were imputed using michigan imputation server (minimac)

I created index using:  `bgenix -clobber -g ./CHR"$chr"_rsq40_check.bgen -index`

I have tried importing dosage value in the bgen files using plink, but again I got same error:
```

plink2 --vcf chr"$chr".dose.vcf.gz 'dosage=DS' \
--export bgen-1.2 'bits=8' --extract CHR"$chr"_rsq40_snps.txt --out CHR"$chr"_rsq40
```

Any idea how to resolve this?

Thank you

**Comment by joellembatchou** [comment]
Hi,

As stated [here](https://www.cog-genomics.org/plink/2.0/input#vcf), it seems PLINK2 cannot losslessly convert from VCF to BGEN (I believe you should use the genotype probability GP field for the dosage). However, Regenie can also support PLINK2's PGEN format so you could run PLINK2 and convert to PGEN instead and pass that to Regenie.

**Comment by sariya** [comment]
Hi, thank you for your reply. I took help from issue at https://github.com/rgcgithub/regenie/issues/64

I create bgen file then convert into pgen file removing phase as
```
plink2 --double-id --vcf chr"$chr".dose.vcf.gz \
 --export bgen-1.2 'bits=8' --extract CHR"$chr"_rsq40_snps.txt --out CHR"$chr"_rsq40_checkforPGEN
```

Next remove phase:
```
plink2 --bgen CHR"$chr"_rsq40_checkforPGEN.bgen ref-first \
--sample CHR22_rsq40_checkforPGEN.sample --make-pgen erase-phase --out CHR22_pgen2
```

It generates 3 files: .pgen, .pvar and .psam. .psam has three columns as

```
#FID    IID     SEX
IID1       IID1       NA
IID2       IID2       NA
IID3       IID3       NA

```

```

./regenie_v2.0.2.gz_x86_64_Linux --step 2 \
--pgen CHR22_pgen2 \
--covarFile regenie_phenotype.txt --covarColList AGE,SEX,PC1,PC2,PC3  \
--phenoFile regenie_phenotype.txt --sample samples.txt \
--phenoCol AD --phenoColList AD \
--remove  remove_individuals.txt  --bsize 200 \
--bt --firth --approx --pThresh 0.99 --pred step1_reg_pred.list --out CHR22_bin_out_firth
```

The samples file is from the .bgen created using qctool.

I get error:
```

Association testing mode with fast multithreading using OpenMP
 * pvar             : [CHR22_pgen2.pvar] n_snps = 847317
 * psam             : [CHR22_pgen2.psam] n_samples = 7234
   -removing individuals specified in [remove_individuals.txt]
     +number of genotyped individuals to exclude from the analysis = 0
 * pgen             : [CHR22_pgen2.pgen]
 * phenotypes       : [regeni_phenotype.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
ERROR: All individuals have missing/invalid phenotype values.

```

In the step1_reg_1.loco file I have FID followed by an `_` by an IID. 


Should I manually edit the .psam file generated for the sex column or remove header with `#`?

**Comment by joellembatchou** [comment]
Could you check whether the ID information in the psam file matches with that in the phenotype file?

**Comment by sariya** [comment]
ow, actually no. The FIDs are different in phenotype file vs in the `.psam`. In phenotype file I've:
`
FID_1 IID_1
`

In the .psam file I've 
```
#FID    IID     SEX
IID1       IID1       NA  

IID2       IID2       NA  

IID3       IID3       NA  
```

This is due to  `--double-id` flag I used in plink conversion. If I had not used this, the FID column would have been zero `0`. I have not used `-const-fid` 

How do I fix this?

**Comment by joellembatchou** [comment]
It seems you would have to manually fix this as the VCF file seems to only contain IID in the ID field (instead of for example FID_IID). One way in bash would be 
```
sed 's/^IID/FID/g' CHR22_pgen2.psam > new_CHR22_pgen2.psam
mv new_CHR22_pgen2.psam CHR22_pgen2.psam
```

**Comment by sariya** [comment]
Thank you. manually editing FID column worked.
