### ISSUE TITLE
step2: does regenie use dosage (DS) or genotype (GT) from imputed data?

### ISSUE THREAD

**Issue by sariya** [rgcgithub/regenie#114]
Hi developers,

In step 2 does regenie use dosage (DS) or genotype (GT) value. I converted Topmed Michigan imputed data to bgen and then pgen file format. 
Upon running step2 what value is used when fitting the model (firth/spa) for alternate allele. Is it dosage value or the genotype value?

**Comment by joellembatchou** [comment]
Hi,

With PGEN format input, Regenie will use dosage if these are present in the file. Otherwise, it will use the hard-call genotypes.

**Comment by sariya** [comment]
thank you.~ :)
