### ISSUE TITLE
Offset prediction for chr23

### ISSUE THREAD

**Issue by GlastonburyC** [rgcgithub/regenie#115]
Hi, I'm running stage one of REGENIE v2.0.2:

```
regenie --step 1 --bed cleaned_genotypes/clean_eur_genotypes --phenoFile gwas_input_cases_controls.txt --phenoCol x --out regenie_output/ --bsize 1000
```

I've noticed that even though my genotypes only contain autosomes [1-22] I get a prediction for chromosome 23. For GLOW, this isn't the case, I get offset predictions only for 22 autosomes, which makes comparisons of the offset prediction difficult.

I thought setting `--chrList 1:22` in REGENIE may affect this, but it doesn't.

When I compare offsets calculated with REGENIE versus GLOW using the same input data, they look very different. I'm wondering if this has something to do with it?

**Comment by GlastonburyC** [comment]
Hi @joellembatchou thanks for responding, that's very helpful! Would you expect a good correlation between say, chr1 LOCO predictions when comparing REGENIE versus GLOW?

**Comment by joellembatchou** [comment]
Yes, we previously ran a few traits with the implementation in GLOW and found high correlation between the resulting LOCO predictions and those from REGENIE.
