### ISSUE TITLE
Individual (FID_IID=1212626_1212626) has missing blup prediction at chromosome 16 for phenotype X070.2.

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#117]
Any suggestion to handle the following issue in Regenie step 2? 

> Chromosome 16 [209 blocks in total]
>    -reading loco predictions for the chromosome...ERROR: Individual (FID_IID=1212626_1212626) has missing blup prediction at chromosome 16 for phenotype X070.2. Either set their phenotype to `NA`, specify to ignore them using option '--remove', or skip reading predictions with option '--ignore-pred'.
> For list of arguments, run with option --help
> 

Thanks. 
Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

Which Regenie version are you using?

**Comment by Shicheng-Guo** [comment]
(base) [sguo2@login02 regenie]$ regenie
              |============================|
              |        REGENIE v2.0.2      |
              |============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.

ERROR: You must provide an output prefix using '--out'
For more information, use option '--help' or visit the website: https://rgcgithub.github.io/regenie/

**Comment by joellembatchou** [comment]
Hi,

This has been fixed in commit fe9b7620edb7efd94fecc62bfbceabfeaae30c3e.

Cheers,
Joelle

**Comment by Shicheng-Guo** [comment]
Hi Joelle, this issue happens again for version 2.2. 

```
Chromosome 22 [1 sets in total]
   -reading loco predictions for the chromosome...ERROR: Individual (FID_IID=1000758_1000758) has missing blup prediction at chromosome 22 for phenotype X008.5. Either set their phenotype to `NA`, specify to ignore them using option '--remove', or skip reading predictions with option '--ignore-pred'.
For list of arguments, run with option --help
```
regenie version 2.2
```
base) [sguo2@login02 newburden]$ regenie
              |============================|
              |        REGENIE v2.0.2      |
              |============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.

ERROR: You must provide an output prefix using '--out'
For more information, use option '--help' or visit the website: https://rgcgithub.github.io/regenie/
```

**Comment by joellembatchou** [comment]
Are you running v2.2? (From the log it points to v2.0.2)
