### ISSUE TITLE
ERROR: Invalid AAF given at line n

### ISSUE THREAD

**Issue by kattttttt** [rgcgithub/regenie#118]
Hi, I have a problem with Step 2 of regenie, specifically with the aaf file:
I keep getting the error message
`ERROR: Invalid AAF given at line n`

When I check said line I get a variant like any other: 
chr2:89157151:T:C 0

The AAF for all variants that trigger this error message is 0, but I have other variants with AAF 0 that don't have any problems.

What exactly is the problem here?

**Comment by joellembatchou** [comment]
Hi,

The current requirement for the AAF file is that all AAF be above 1e-8 (corresponds to MAC 1 in 50M samples).  This requirement will be removed in the next release since there are other checks to identify monomorphic variants. For now, you could subset the file using
```
awk '{ if($2 > 1e-8) { print $0 }}' aaf_file.txt > subset_aaf.txt
```

Cheers,
Joelle

**Comment by kattttttt** [comment]
Thank you very much for the quick response! That explains everything.
