### ISSUE TITLE
How many `--extract` are allowed in Regenie step 2?

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#119]
`regenie` allow two `--extract` or not? I want to use two `--extract` to select SNPs to be used in the analysis. 

For example, the first `--extract` use to select INFO score>0.8 and second `extract` to select MAC>=5

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

Regenie does not allow mutilple extract files. You could easily bypass that in bash using 
```
cat info_qc.pass mac_qc.pass > extract_file.txt
```
and pass "extract_file.txt" to `--extract` in Regenie.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Multiple extract/exclude files are now allowed in v2.2.
