### ISSUE TITLE
Running step2 in different directory than step1 fails

### ISSUE THREAD

**Issue by avsmith** [rgcgithub/regenie#12]
If step2 is run in different directory, calling the predictors via path (for example: ` --pred ../step1/output/${trait}_pred.list`), the job fails with an error of `output/TRAIT_1.loco` not found.

**Comment by joellembatchou** [comment]
The file paths specified in the "../step1/output/${trait}_pred.list" are relative to the working directory from which Regenie is called. 

So either call Regenie from the same directory as in step 1 or edit the file "../step1/output/${trait}_pred.list" to have the absolute paths instead.

-> This can be avoided altogether by specifying absolute paths when using the option `--o`
