### ISSUE TITLE
WARNING: Detected 5 masks with only unknown annotations (these are ignored).

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#122]
I don't know why my masks are not recognized. All the masks I created is used in *.anno files. 

* masks            : [/home/sguo2/janssen4/ukb/WES-hg38/burden/WES.masks] n_masks = 0
WARNING: Detected 5 masks with only unknown annotations (these are ignored).

Thanks. 

Start time: Sun May 16 00:13:13 2021

              |============================|
              |        REGENIE v2.0.2      |
              |============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.

Log of output saved in file : UKB.PHECODE.WES.burden.chr22.X008.log

Options in effect:
  --step 2 \
  --pred /home/sguo2/janssen4/ukb/analytic/ukb_step1_pred.list \
  --bed /home/sguo2/janssen4/ukb/WES-hg38/plink/ukb23156_chr22 \
  --keep /home/sguo2/janssen4/ukb/analytic/step1/qc_pass.id \
  --covarFile /home/sguo2/janssen4/ukb/WES-hg38/UKB.cov.r2.Guo.txt \
  --covarCol PC{1:20} \
  --covarCol Year \
  --covarCol iSex \
  --covarCol YearSquare \
  --covarCol center \
  --phenoFile /home/sguo2/janssen4/ukb/analytic/UKB_PHENOME_20210218.Guo.vRegenie.txt \
  --phenoColList X008 \
  --bt \
  --anno-file /home/sguo2/data/Annotation/REGENIE_var_set/Canonical_Transcript/WES_chr1.anno \
  --set-list /home/sguo2/data/Annotation/REGENIE_var_set/Canonical_Transcript/WES_chr1.setlist \
  --mask-def /home/sguo2/janssen4/ukb/WES-hg38/burden/WES.masks \
  --aaf-bins 0.01 \
  --firth \
  --approx \
  --threads 12 \
  --bsize 400 \
  --split \
  --strict \
  --out UKB.PHECODE.WES.burden.chr22.X008

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [/home/sguo2/janssen4/ukb/WES-hg38/plink/ukb23156_chr22.bim] n_snps = 374002
 * fam              : [/home/sguo2/janssen4/ukb/WES-hg38/plink/ukb23156_chr22.fam] n_samples = 200643
   -keeping only individuals specified in [/home/sguo2/janssen4/ukb/analytic/step1/qc_pass.id]
     +number of genotyped individuals to keep in the analysis = 171165
 * bed              : [/home/sguo2/janssen4/ukb/WES-hg38/plink/ukb23156_chr22.bed]
 * phenotypes       : [/home/sguo2/janssen4/ukb/analytic/UKB_PHENOME_20210218.Guo.vRegenie.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals = 171165
   -number of individuals remaining with non-missing phenotypes = 171165
 * covariates       : [/home/sguo2/janssen4/ukb/WES-hg38/UKB.cov.r2.Guo.txt] n_cov = 24
   -number of individuals with covariate data = 171165
 * number of individuals used in analysis = 171165
 * LOCO predictions : [/home/sguo2/janssen4/ukb/analytic/ukb_step1_pred.list] n_files = 1
   -file [/expanse/projects/janssen4/dsci-csb/user/sguo2/ukb/analytic/step1/ukb_step1.2032506_1.loco] for phenotype 'X008'
 * annotations      : [/home/sguo2/data/Annotation/REGENIE_var_set/Canonical_Transcript/WES_chr1.anno]
   +number of annotations categories = 1
 * masks            : [/home/sguo2/janssen4/ukb/WES-hg38/burden/WES.masks] n_masks = 0
WARNING: Detected 5 masks with only unknown annotations (these are ignored).
 * aaf cutoffs      : [1 : 0.01 ] + singletons
 * set file         : [/home/sguo2/data/Annotation/REGENIE_var_set/Canonical_Transcript/WES_chr1.setlist] ERROR: No sets are left to be analyzed.
22 X008
Start time: Sun May 16 00:13:30 2021

**Comment by dianacornejo** [comment]
@Shicheng-Guo did you solve this issue. I'm getting the same but not sure if it's a formatting issue. Any help is welcomed!

**Comment by Shicheng-Guo** [comment]
> @Shicheng-Guo did you solve this issue. I'm getting the same but not sure if it's a formatting issue. Any help is welcomed!

format issue. check "new line". check the files is generated by the window system or not? regenie have well developed burden test implement

Shicheng
