### ISSUE TITLE
Installation and BGEN_PATH

### ISSUE THREAD

**Issue by ghferrari** [rgcgithub/regenie#124]
Hi,

I am trying to understand the installation requirements when building regenie from source. The install instructions at https://rgcgithub.github.io/regenie/install/ state:

> regenie requires the BGEN library so you will need to download and install that library.
In the source code edit the BGEN_PATH variable in the Makefile to the BGEN library path.

A standard install of BGEN from https://enkre.net/cgi-bin/code/bgen/dir?ci=trunk will install a folder `bin` with three executables, `bgenix`, `cat-bgen`, `edit-bgen`. This is noted under the `Installation` section at the page linked above.

However, the regenie `makefile` includes e.g. `-I${BGEN_PATH}/3rd_party/boost_1_55_0` and `-L${BGEN_PATH}/build/3rd_party/zstd-1.1.0/` and these paths are not part of a standard BGEN installation. Some of the paths are present in the source code. Some of them (the `build`) paths are created as part of the BGEN build process, but still not included in a BGEN installation.

So have I understood correctly that what's needed to build regenie from source is to have built and installed BGEN from source and then point regenie to the BGEN build directory?

Many thanks!

**Comment by Zilong-Li** [comment]
The BGEN_PATH is the root dir path of your downloaded bgen not related to the path of BGEN installation.  

Let's say you do the following :
 
 `cd ~ && wget http://code.enkre.net/bgen/tarball/release/bgen.tgz && tar -zxf bgen.tgz && cd bgen  && ./waf configure && ./waf` 

then the BGEN_PATH is `~/bgen`
