### ISSUE TITLE
*** Error in `./regenie': free(): invalid pointer: 0x00000000012c3dc8 ***

### ISSUE THREAD

**Issue by alhenry** [rgcgithub/regenie#13]
Hi,

I am trying to compile regenie with `make` using GCC libs ver 9.2.0 on Red Hat Enterprise Linux Server release 7.8.
I edited the following lines in the `Makefile`:

```
CFLAGS = -ldl
BGEN_PATH = /lustre/home/rmhiaah/bgen/
```
The `-ldl` flag is to avoid "undefined reference to symbol 'dlclose@@GLIBC_2.2.5'" error as per this [SO thread](https://stackoverflow.com/a/33035858)

The `make` command ran and exited without error, but with a couple of "skipping incompatible library" messages at the end as follows:

```
g++ -O3 -w -ffast-math -std=c++11 -ldl -fopenmp -o regenie ./src/Step1_Models.o ./src/Step2_Models.o ./src/Regenie.o ./src/Pheno.o ./src/Data.o ./src/Geno.o ./external_libs/pgenlib/include/pgenlib_misc.o ./external_libs/pgenlib/include/plink2_bits.o ./external_libs/pgenlib/include/plink2_base.o ./external_libs/pgenlib/include/pgenlib_read.o ./external_libs/pgenlib/pgenlibr.o ./external_libs/pgenlib/pgenlib_ffi_support.o     -L/lustre/home/rmhiaah/bgen//build/ -L/lustre/home/rmhiaah/bgen//build/3rd_party/zstd-1.1.0/ -L/lustre/home/rmhiaah/bgen//build/db/ -L/lustre/home/rmhiaah/bgen//build/3rd_party/sqlite3/ -L/lustre/home/rmhiaah/bgen//build/3rd_party/boost_1_55_0 -L/usr/lib/ -lbgen -lzstd -ldb  -lsqlite3 -lboost -lz
/usr/bin/ld: skipping incompatible /usr/lib//libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib//libdl.a when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib//libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib//libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib//libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib//libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib//libpthread.a when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib//libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib//libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib//libgcc_s.so.1 when searching for libgcc_s.so.1
```

Using this compiled software, I tried to run the [example step 1](https://rgcgithub.github.io/regenie/options/#getting-started) command and then got the following error message:

```
*** Error in `./regenie': free(): invalid pointer: 0x0000000000d26dc8 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7f0d72b6a299]
./regenie[0x4acb9c]
./regenie[0x411bd9]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0d72b0b555]
./regenie[0x41228c]
======= Memory map: ========
00400000-006a5000 r-xp 00000000 67:70864 216173240282792547              /lustre/home/rmhiaah/regenie/regenie
008a5000-008a9000 r--p 002a5000 67:70864 216173240282792547              /lustre/home/rmhiaah/regenie/regenie
008a9000-008ac000 rw-p 002a9000 67:70864 216173240282792547              /lustre/home/rmhiaah/regenie/regenie
008ac000-008ad000 rw-p 00000000 00:00 0
00d15000-00dd2000 rw-p 00000000 00:00 0                                  [heap]
...
...
```
I am wondering whether this error relates  to the "skipping incompatible library" messages above?
I'd appreciate if you have any advice / suggestions on this.

Many thanks

**Comment by joellembatchou** [comment]
It seems like this might be an architecture mismatch problem. Are the libraries used 32-bit or 64-bit (should be linking to 64-bit libraries)?

For example, for `/usr/lib//libdl.so` which appears in the first line of the  "skipping incompatible library" messages, if you use the following command, what is the output?
```
objdump -f /usr/lib//libm.a | grep ^architecture
```
(as of now, Regenie was only tested for Linux on x86-64 architecture)

Alternatively, there are pre-compiled binaries in the `bin/` directory. Could you try using the one for Linux?

**Comment by alhenry** [comment]
Hi, thanks for the quick reply. I think the machine itself is 64-bit, but the output of the command above was:

`architecture: i386, flags 0x00000150:`

which I think refer to 32-bit libraries?

The issue still persists after adding `-m64` flag in the Makefile as in:
```
CXXFLAGS = -O3 -w -ffast-math -std=c++11 -m64
CFLAGS = -ldl -m64
```

When I tried the pre-compiled binary for Linux, it cannot run with the following error message:
`./regenie_x86_64_linux: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory`

Any further suggestions? In the meantime I'll try to sort out the architecture mismatchproblem on my end

**Comment by alhenry** [comment]
Some more update:

On my system, I found that changing the flag `-L/usr/lib/` to `-L/usr/lib64/`
at the end of the `LPATHS` variable in the `Makefile` eliminates the warning message "skipping incompatible libraries" above.

However, the ```*** Error in `./regenie': free(): invalid pointer: 0x0000000000d26dc8 ***``` message still persists (only with a different memory address) during the test run with the example command

**Comment by alhenry** [comment]
Update:

it seems like the problem arises due to previous installation of bgen library which was compiled with older version of gcc. Recompile both bgen and regenie with newer version of gcc as well as changing the flag to `-L/usr/lib64/` as mentioned above solves this problem.

Thanks for helping troubleshooting this issue.
