### ISSUE TITLE
2.0.2 terminate ... std::runtime_error ... locale::facet::_S_create_c_locale name not valid Aborted (core dumped)

### ISSUE THREAD

**Issue by JakobBerg** [rgcgithub/regenie#130]
Hi, thanks for providing regenie.
I am trying to run step 1 with a bed file, but get an error message in the "fitting null model" step after the `* bed` line: 

terminate called after throwing an instance of 'std::runtime_error' 
  what():   locale::facet::_S_create_c_locale name not valid

then after the `* phenotypes`  I get

Aborted (core dumped)

any pointer in the right direction would be much appreciated here.
best regards

**Comment by joellembatchou** [comment]
Hi,

Which version of Regenie are you using?

**Comment by JakobBerg** [comment]
Joelle, thank you very much! 
I ended up just specifying all locale settings to en_US.UTF-8 

This made regenie run.
(I had the same issue both in 2.0.2 and in 1.0.7 - at this moment, I just verified this fixes 2.0.2)

Best regards
Jakob

**Comment by anbai106** [comment]
Sorry - I think your solution worked for me. I just got confused with the "\" symbol!
