### ISSUE TITLE
Step 2 - Filtering differences between burden mask "max" and "sum"

### ISSUE THREAD

**Issue by taylorcavazos** [rgcgithub/regenie#132]
Hi,

Thanks for developing such an efficient tool! I'm having some issues with the **burden testing** step, specifically when using `sum` to build masks.

When using the `max` feature I am able to successfully run the burden test for all of my gene sets; however, when using `sum` I get no output.

Here is an example of my log file when running `sum`:

```
* annotations      : [inputs/rare.highmod.cadd15.gene.annofile]
   +number of annotations categories = 2
 * user-given AAFs  : [inputs/kp_aaf_file.txt]
 * masks            : [inputs/include.mask] n_masks = 1
 * aaf cutoffs      : [1 : 0.01 ] + singletons
 * set file         : [inputs/rare.highmod.cadd15.gene.setlist] n_sets = 18646
WARNING: Detected 3462 sets with variants not in genetic data or annotation files.
WARNING: Detected 2 sets with only unknown variants (these are ignored).
 * # threads        : [16]
 * # tested sets    : [18646]
 * max block size   : [200]
 * rule used to build masks : sum
 * approximate memory usage : 402MB
 * using minimum MAC of 0.5 (masks with lower MAC are ignored)
 * using SPA correction for logistic regression p-values less than 0.05
```

After regenie builds masks and runs associations for all sets I get the following output:
```
Number of tests with SPA correction : 0
Number of failed tests : (0/0)
Number of ignored tests due to low MAC : 405647
```

Since I'm able to run association tests (and get output) for all sets using `max`, is there a different filtering strategy that is occurring with `sum`? Do I need to edit my gene sets in some way?

**Comment by joellembatchou** [comment]
Hi,

Do you also get no output if you analyze the phenotypes as quantitative (i.e. omit `--bt` in  the regenie command)?

**Comment by taylorcavazos** [comment]
Yes, I also don't get any output if removing the `--bt` flag.

**Comment by taylorcavazos** [comment]
What is also strange is that I do get results using the `comphet` method which seems to use similar code as `sum` aside from the final thresholding. 

My log file for `comphet` mask using the same gene-set, annotation/af files, and phenotypes is as follows:

```
Number of tests with SPA correction : 35402
Number of failed tests : (22/35402)
Number of ignored tests due to low MAC : 0
```

Is there a coding error when `sum` is used that may not be outputting the results at the end?

**Comment by joellembatchou** [comment]
I am not sure yet what is causing this; I will do more testing to assess what is going on.

Cheers,
Joelle

**Comment by taylorcavazos** [comment]
Thanks! Let me know if I could provide any additional information that might help with troubleshooting. 

Thanks again,
Taylor

**Comment by joellembatchou** [comment]
Hi Taylor,

Could you try running it in Regenie v2.2?

**Comment by taylorcavazos** [comment]
I just tested this and sum now works correctly! Thanks for releasing an update of the package. Closing this issue now.
