### ISSUE TITLE
Normal distributed continuous traits

### ISSUE THREAD

**Issue by OmegaPetrazzini** [rgcgithub/regenie#133]
Hi, thank you for doing this, works great!

Does REGENIE assumes continuous traits to be normally distributed? Do I have to normalise my phenotype file before running?

Cheers,
Omega

**Comment by joellembatchou** [comment]
Hi,

Yes the model used in Regenie for quantitative traits uses a normality assumption. As is commonly done in GWAS, you can use a rank-inverse normal transformation (RINT) on the phenotypes prior to running Regenie.

Cheers,
Joelle
