### ISSUE TITLE
Step 2: Error  doesn't exist

### ISSUE THREAD

**Issue by Alexander-Stuckey** [rgcgithub/regenie#134]
Hi,

I'm getting an issue when running step 2 of Regenie, in that it's complaining that a non-existent file doesn't exist. I'm finding this quite tricky to debug. Would you be able to offer any advice? I'm running Regenie from the latest 2.0.2 container from github.

`
              |=============================|
              |      REGENIE v2.0.2.gz      |
              |=============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : regenie.log

Options in effect:
  --step 2 \
  --minMAC 1 \
  --build-mask max \
  --bt \
  --firth \
  --approx \
  --firth-se \
  --bsize 1000 \
  --ref-first \
  --check-burden-files \
  --anno-labels test_anno_labels \
  --bgen chr16_maskedQC_filtered_fileset_for_testing.bgen \
  --sample ../inputs/-553918883/chr16_maskedQC_filtered_fileset_for_testing.sample \
  --anno-file full_functional_variant_filtered_list \
  --set-list chr16_maskedQC_group_file.tsv \
  --mask-def write_map_d420ba048d65af229f2c5613b195b402.tmp \
  --pred localised_prediction_list \
  --out regenie

ERROR:  doesn't exist.`

**Comment by joellembatchou** [comment]
Hi,

I think the phenotype file option is missing which may be what is causing the issue. I will edit the software to make the error more verbose.

**Comment by Alexander-Stuckey** [comment]
Thank you, it was indeed due to the missing phenotype file. Happy to have this closed off.
