### ISSUE TITLE
PgrGet1() error 4

### ISSUE THREAD

**Issue by idinsmore1** [rgcgithub/regenie#135]
Hello, 

I was running step 2 on a set of 45 binary phenotypes, ~30,000 samples, with a large set of imputed data and was nearly done with the analysis, then the process stopped with this error:
`block [51336] : PgrGet1() error 4` 

Any idea what this error could be? Thanks!

**Comment by chrchang** [comment]
This corresponds to a file reading failure (https://github.com/chrchang/plink-ng/blob/master/2.0/include/plink2_base.h#L327 ).

**Comment by dianacornejo** [comment]
@idinsmore1 hello! sorry I'm getting the same error. Where you able to fix this? The interesting thing it's that I'm using exactly the same genotype files and different phenotype files and those don't give any error. Is this reading failure coming from the genotype files?

**Comment by joellembatchou** [comment]
Hi,

This error is coming from the PLINK library. Are there many variants in the genotype file? If so, perhaps it would be better to split it into multiple jobs (so each job reads a subset of the larger file).

Cheers,
Joelle

**Comment by dianacornejo** [comment]
@joellembatchou the jobs are already split by chromosome and it does not make sense that it runs for some traits but not for others. Not sure what's going on there.
