### ISSUE TITLE
Replace Y1 etc in the regenie file with actual phenotype name?

### ISSUE THREAD

**Issue by seppinho** [rgcgithub/regenie#137]
Hi all,
It looks like that regenie labels all specified phenotypes with `.Y1`, `.Y2` etc in the *.regenie output file:
https://github.com/rgcgithub/regenie/blob/6d31b5165e098a08ff575e5a36c0cb6219247cc6/src/Data.cpp#L1882

Maybe there is an option that I missed but It could be quite useful to use the actual phenotype name specified in `--phenoColList` as a postfix in the output files. 

Thanks for your help!

**Comment by joellembatchou** [comment]
Hi,

This was initially done to reduce the length of the line if long phenotype names were given. In the next release, we will write an accompanying dictionary file which will have the trait name info, like
```
Y1 BMI
Y2 LDL
...
```

**Comment by seppinho** [comment]
Awesome. Thanks!
