### ISSUE TITLE
Install from the pre-compiled binaries

### ISSUE THREAD

**Issue by yystat** [rgcgithub/regenie#138]
Hi,

I have very dumb question. I'm trying to install regenie from the pre-complied binary `regenie_v2.0.2.gz_x86_64_Linux_mkl.zip` ([v2.0.2](https://github.com/rgcgithub/regenie/releases)), after I unzip it (using `unzip regenie_v2.0.2.gz_x86_64_Linux_mkl.zip`), I got the file `regenie_v2.0.2.gz_x86_64_Linux_mkl`, but then what should I do?

It looks like a .gz file, but I cannot `gunzip` it; it's not a folder/directory; and I cannot run it using `./regenie_v2.0.2.gz_x86_64_Linux_mkl`. Sorry for this very low-level question, but please help. Thanks!

Josh

**Comment by joellembatchou** [comment]
Hi Josh,

the file `regenie_v2.0.2.gz_x86_64_Linux_mkl` is the Regenie binary. You may need to use `chmod u+x regenie_v2.0.2.gz_x86_64_Linux_mkl` before running it. 

For example
```
> unzip regenie_v2.0.2.gz_x86_64_Linux_mkl.zip
> chmod u+x regenie_v2.0.2.gz_x86_64_Linux_mkl

# Now run regenie
> ./regenie_v2.0.2.gz_x86_64_Linux_mkl \
   --step 1 \
   --bgen myfile.bgen \
...
```

**Comment by yystat** [comment]
Thanks! I tried and it still does not work. Got the following error:
`error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory`

**Comment by joellembatchou** [comment]
Which operating system are you using? You may need to get the binary from Centos9 instead.

**Comment by leticiactavares** [comment]
Hi Joelle,

I am using linux and I am having the same problem.
I downloaded the pre-compiled version 'regenie_v3.2.6.gz_x86_64_Linux_mkl.zip'

I did as you mentioned above:
-> unzip regenie_v3.2.6.gz_x86_64_Linux_mkl.zip
-> chmod u+x regenie_v3.2.6.gz_x86_64_Linux_mkl

but when I try to run it, I got the error message:
-> ./regenie_v3.2.6.gz_x86_64_Linux_mkl
./regenie_v3.2.6.gz_x86_64_Linux_mkl: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

Could you help me, please?

Thanks,
Leticia

**Comment by leticiactavares** [comment]
Just updating, it worked with Centos (regenie_v3.2.6.gz_x86_64_Centos7_mkl).
