### ISSUE TITLE
sex-specific analysis?

### ISSUE THREAD

**Issue by ggstatgen** [rgcgithub/regenie#139]
Hi

Is there any way to use Regenie to run sex-specific association analyses on a cohort composed of both males and female (UKBB essentially) short of physically splitting the covariate and phenotype files and run two separate male- and female-specific analyses?

Also - can anyone who has performed a sex-specific analysis using Regenie advise on whether Phase I should also be run in a sex-specific way - I'd assume so, but I would like to be sure.

**Comment by joellembatchou** [comment]
Hi,

Regenie cannot automatically run sex-stratified analyses. You can use `--keep/--remove` to only select males/females in an analysis.

**Comment by joellembatchou** [comment]
It is now available in Regenie v2.2.2 (`--sex-specific <male/female>`).
