### ISSUE TITLE
categorical variable to dummy variable

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#143]
How regenie handle categorical variable and dummy variable? for example, access center to dummy variable is required or not? whether factor concept (R) is used in regenie? 

Thanks

**Comment by joellembatchou** [comment]
Hi,

You can use option `--catCovarList` to pass in the list of categorical covariates in the covariate file to Regenie and it will automatically convert these to dummy variables and include these as covariates in the model (
Currently, it allows for a maximum of 10 categories though you can use `--maxCatLevels` to allow for more.

**Comment by chengy1128** [comment]
Follow up on `--catCovarList` option, what if the Regenie didn't detect my categorical covariate in my Covariate file?
I have covarFile looks like 
```
FID IID BMI GenderComp Age
1000013 1000013 23.36 1 66
1000024 1000024 22.63 0 48
```
I want to flag GenderComp as a categorical covariate so I did: 
  ```
--covarFile Covariate_corrected.txt \
  --catCovarList 'GenderComp'
```
However, `Zeros occured in Var(Y) during logistic regression.`
 I believe I have a large enough data set. I'm grateful for any suggestions and comments.

**Comment by joellembatchou** [comment]
Is GenderComp a binary variable of 0/1? If so, the results will be the same treating it as quantitative vs as categorical.
For the logistic regression error, what is the case-control counts of the traits and does the error only occurs if you include GenderComp as a covariate?

**Comment by chengy1128** [comment]
> Is GenderComp a binary variable of 0/1? If so, the results will be the same treating it as quantitative vs as categorical.
> For the logistic regression error, what is the case-control counts of the traits and does the error only occurs if you include GenderComp as a covariate?

Yes the gender is 0/1, and Thank you for your explanation of the categorical variable. The case-control counts are balanced. I followed your suggestion to test my covariate and I realized that it is not the gender, however, my covariate"BMI" perfectly predict the "Obese". It makes sense.  Thank you again!
