### ISSUE TITLE
`approximate memory usage` in step 2 and set-up for `--mem` in slurm

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#145]
I am wondering how to set-up `--mem` for SLURM script with the best practice. I notice regenie has **approximate memory usage**, do you think 2 times of this memory (284M for the below example) will be enough to make sure this job works well? 

Thanks. 

```
#SBATCH --mem=30G
```

```
 * # threads        : [12]
 * block size       : [400]
 * # blocks         : [1598]
 * approximate memory usage : 284MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)
 * using SPA correction for logistic regression p-values less than 5e-08
```

**Comment by chengy1128** [comment]
In their paper Table 1 reported memory usage. My approximate memory usage is 10GB and I requested slurm 24GB. It worked.

**Comment by Shicheng-Guo** [comment]
> In their paper Table 1 reported memory usage. My approximate memory usage is 10GB and I requested slurm 24GB. It worked.

obviously, the memory depends on the sample size and the number of SNPs. I am wondering what's the best practice to set-up this value. I don't want to have any waste, for example, for my case, 500M is enough.

**Comment by joellembatchou** [comment]
We'd recommend adding a couple of GBs to the approximate memory usage (this is more for large-scale application like in UKB) as it does not take into account temporary memory allocations; so for example 3GB to be more conservative. For smaller runs where approximate memory usage is in MB, doubling or just adding an extra GB should be sufficient.
