### ISSUE TITLE
Regenie-v2.2: unexpected error for quantitative trait

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#146]
I received an unexpected error in version 2.2: ERROR: all individuals have missing/invalid values for phenotype 'X30620'.

it is a quantitative traits and 1000+ values for this trait. It should not happen, at least, for version 2.0.2 works well. 

Fitting null model
 * bim              : [/home/sguo2/janssen4/ukb/Genotyped-hg19/plink/ukb_cal_allChrs.bim] n_snps = 803113
   -keeping variants specified by --extract
     +number of variants remaining in the analysis = 530790
 * fam              : [/home/sguo2/janssen4/ukb/Genotyped-hg19/plink/ukb_cal_allChrs.fam] n_samples = 488377
   -keeping only individuals specified by --keep
     +number of genotyped individuals remaining in the analysis = 418237
 * bed              : [/home/sguo2/janssen4/ukb/Genotyped-hg19/plink/ukb_cal_allChrs.bed]
 * phenotypes       : [/home/sguo2/data/PHENO/UKB.quantitative_traits.Guo.vRegenie.irnt.178.txt] n_pheno = 178
   -dropping observations with missing values at any of the phenotypes
ERROR: all individuals have missing/invalid values for phenotype 'X30620'.

```
regenie
  --step 1 \
  --bed /home/sguo2/ukb/Genotyped-hg19/plink/ukb_cal_allChrs \
  --extract /home/sguo2/ukb/analytic/step1/qc_pass.prune.in \
  --keep /home/sguo2/ukb/analytic/step1/qc_pass.id \
  --phenoFile /home/sguo2/data/PHENO/UKB.quantitative_traits.Guo.vRegenie.irnt.178.txt \
  --covarFile /home/sguo2/ukb/WES-hg38/UKB.cov.r2.Guo.txt \
  --covarCol PC{1:20},Year,iSex,YearSquare \
  --threads 12 \
  --strict \
  --loocv \
  --lowmem \
  --lowmem-prefix tmpdir/regenie_tmp_preds.4011497 \
  --bsize 1000 \
  --out Ukb_quantitative_traits
```

**Comment by joellembatchou** [comment]
I see you are using `--strict`;  does it still fail if you omit this option?

**Comment by bicyclic** [comment]
Hi Joelle, was there a fix reported for this somewhere? I'm running into a similar issue in step 2.

The following step 1 command worked fine:
````
regenie
--step 1
--bed /usr/ukb_geno_chrAll_v2
--remove /usr/invalid_FIDIID.txt
--remove /usr/plinkButNotImputed_FIDIID.txt
--remove /usr/allAncestryQC_FIDIID.txt
--remove /usr/ExcludePhenoAll.txt
--exclude /usr/GenoQcAllAncestry.txt
--phenoFile /usr/fatPhenoCovarINT.txt
--phenoColList vat,asat,gfat,vatadjbmi3,asatadjbmi3,gfatadjbmi3,vatAsatRatio,vatGfatRatio,asatGfatRatio
--covarFile /usr/2021.03.11_datafreeze/fatPhenoCovarINT.txt
--covarColList age_instance2,age_instance2_sq,PC{1:10}
--catCovarList sex,genotyping_array,mriNum
--bsize 1000
--lowmem
--lowmem-prefix ./testrun/level0pred
--out ./testrun/step1_out
--gz
````
But the corresponding step 2 command gives me **"ERROR: all individuals have missing/invalid values for phenotype 'X30620'."**
````
regenie
--step 2
--bgen /usr/ukb_imp_chr22_v3.bgen
--remove /usr/invalid_FIDIID.txt
--remove /usr/plinkButNotImputed_FIDIID.txt
--remove /usr/allAncestryQC_FIDIID.txt
--remove /usr/ExcludePhenoAll.txt
--phenoFile /usr/fatPhenoCovarINT.txt
--phenoColList vat,asat,gfat,vatadjbmi3,asatadjbmi3,gfatadjbmi3,vatAsatRatio,vatGfatRatio,asatGfatRatio
--covarFile /usr/fatPhenoCovarINT.txt
--covarColList age_instance2,age_instance2_sq,PC{1:10}
--catCovarList sex,genotyping_array,mriNum
--bsize 1000
--pred ./testrun/step1_out_pred.list
--out ./testrun/step2_regenie
--gz
````
All the inputs with respect to the samples are identical to my eye, so I'm unsure about what's causing this.
Thanks!

**Comment by joellembatchou** [comment]
Are you using the most recent version of Regenie? And can you include the log (the part showing the sample counts in files before the analysis on the variants starts)

**Comment by pottj** [comment]
Hi there, I ran into the same problem in step 2 (using v2.2.4). I used the same phenotype file for step 1 & step 2.
[REGENIE_step2.log](https://github.com/rgcgithub/regenie/files/8122558/REGENIE_step2.log)

**Comment by pottj** [comment]
Update: I added the --sample flag and step2 finished without error. 
So I guess --bgen always needs its corresponding sample file within the options?

**Comment by bicyclic** [comment]
Hi pottj,

Yes I overlooked that! I added --sample back in and step2 finished without error. Thank you both!

Best,
bicyclic

**Comment by HackerLZH** [comment]
> Update: I added the --sample flag and step2 finished without error. So I guess --bgen always needs its corresponding sample file within the options?

Good!
