### ISSUE TITLE
Does regenie output R^2

### ISSUE THREAD

**Issue by catissoqt** [rgcgithub/regenie#149]
Dear  Team,

Is it possible to output R^2 or pve in regenie? I'm getting confused about how to calculate R^2 from the summary statistics. 

Thanks a million.

**Comment by joellembatchou** [comment]
Regenie does not currently output the proportion of phenotypic variance explained in Step 2. It does output the sample size, AAF, beta & se which you can use to obtain pve (see [here](https://doi.org/10.1371/journal.pone.0120758.s001) for formula).
