### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#15]
Can regenie be used for multi-allelic variants...If so which file format as input would you recommend? (If -pgen can accommodate?)...

**Comment by joellembatchou** [comment]
Regenie does not currently handle multi-allelic variants; you could filter these out or split them into bi-allelic variants.

**Comment by Apb58** [comment]
Is this something that could be handled via a rescaling of multi-allelic variants such that genotypes ranged between 0 and 1? For example, if I code a variant GT as 0/0.4, is this treated as a 0/1, 0/0, or ignored entirely?
