### ISSUE TITLE
Covariates in Regenie didn't affect too much to the results ?

### ISSUE THREAD

**Issue by chengy1128** [rgcgithub/regenie#150]
Hello Team,

I am running GWAS on Type2 Diabetes with the default `--firth  --approx `. My case-control ratio is around 1:3. I'm focusing on UKBB British white. 
 I tried two sets of covariates to compare:
1. Age, Age^2, sex, sex*age, PC1-10 (---NO BMI, 14 covaraites)
2. Age, Age^2, sex, sex*age, PC1-10, BMI (15 covaraites)

I'm sure the regenie read # of covaraites is correct
```
* covariates       : [PATH] n_cov = 14
   -number of individuals with covariate data = 460108
```
```
* covariates       : [PATH] n_cov = 15
   -number of individuals with covariate data = 460108
```

However, I don't see a huge difference between these two Manhattan plots.  Higher BMI  should greatly increase the risk of developing type 2 diabetes. What could be the problem that Regenie output similar LOG10P across these two covariates set models? 

-Thank you very much and have a wonderful day.

**Comment by joellembatchou** [comment]
Could you try with the recent Regenie v2.2.3?

**Comment by chengy1128** [comment]
> Could you try with the recent Regenie v2.2.3?
Sounds great, Thank you very much :-D
