### ISSUE TITLE
`--test additive` be supported [enhancement]

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#155]
Hi Joelle, hope `--test additive` can be supported in next version [enhancement] Thanks. Shicheng

**Comment by joellembatchou** [comment]
What do you mean? The additive coding is used by default in Regenie. Or are you referring to just make it more explicit by allowing for this argument in addition to recessive/dominant?

**Comment by Shicheng-Guo** [comment]
Great. Thanks!!
