### ISSUE TITLE
doubts for set files for gene based test || annotation for SNPs

### ISSUE THREAD

**Issue by sariya** [rgcgithub/regenie#156]
Dear Regenie team,

I'm interested in using regenie for an admixed population, with binary trait with case-control imbalance. 
I annotated snps from the plink files using annovar. HG38 human reference genome build. I have some doubts before I start transforming data for the regenie gene based burden analysis:

I have some genes (for example) on  CHR22 as:

```
DUXAP8	22	15784959	chr22:16041696:G:A, chr22:16107642:G:T, chr22:16107676:G:T	
TPTEP1	22	16601887	chr22:16593875:G:T, chr22:16594463:C:A, chr22:16594577:C:T,chr22:16595105:C:T
CCT8L2	22	16590751	chr22:16041696:G:A, chr22:16107642:G:T, chr22:16107676:G:T	
SLC25A18	22	17563439	chr22:17559209:A:G, chr22:17559210:T:C, chr22:17559384:G:A, chr22:17559478:G:A
SCARF2	22	20424815	chr22:20409710:G:A, chr22:20409738:C:T, chr22:20409773:T:C, chr22:20409930:A:G

```

The first three columns are: gene name, chromosome and gene (start) position, followed by comma separated SNP. SNPs are mostly intergenic (from Genotyped data), thus, their position is often before the gene start position. 
May you help me with following doubts:

1) Is it ok to put gene start position in 3rd column?

2) I have loads of SNPs that with their Base-pair before the gene start location. Is the fine by the regenie tool?

Thanks,

**Comment by joellembatchou** [comment]
(1) Yes that is fine for the 3rd column. It really is only used in the output sum stats file for the position value for the gene mask.
(2) Yes that is fine.

**Comment by yuhancui** [comment]
@sariya Hi, I am also using annovar for annotation before Regenie. May I ask you how did you get gene start position for each gene from annovar? My annovar output did not contain that information. 

I also noticed 'None' in Gene.refGene (e.g., "NONE;DDX11L1") column for intergenic. Did you get this situation? If yes, how did you deal with that "NONE"? Thanks in advance!

**Comment by sariya** [comment]
I used an external file with hg38 gene start end information (column based). It may need further curation due to duplicate gene names (sometimes; on different chromosomes) or special characters. I loaded gene start end file and parsed annotation output using an in house script.

For none gene, you can ignore none gene. :). It is unannotated thus None name. 

Hope it helps.

**Comment by yuhancui** [comment]
Thanks @sariya ! This is very helpful. I feel much clearer now.
