### ISSUE TITLE
Mix up of dominant and recessive results?

### ISSUE THREAD

**Issue by IoannaTach** [rgcgithub/regenie#157]
I am using regenie_v2.0.2 for single-point analysis of 9 binary traits. I have run the additive, dominant and recessive models focusing on mainly rare variants from whole exome sequence data. The results from the recessive model tend to be closer to the ones from the additive model, while the results from the dominant model tend to produce strange QQ plots. 

However, both for these binary traits when run with other software and for other binary traits, my previous observation is that the additive and dominant models produce similar results, while the recessive model doesn't always have a good fit and therefore produces strange QQ plot curves. This also makes sense for rare variants.

I am therefore wondering whether there has been any mix-up labelling the results using the dominant and recessive model???

**Comment by joellembatchou** [comment]
Which genotype data input format are you using in Regenie?

**Comment by IoannaTach** [comment]
For example, to run a dominant model:
Step1:

> cat ${softwarepath}/REGENIE_step1_portfolio_dominant.sh
#!/bin/bash -l
#SBATCH --mem=12GB
#SBATCH --cpus-per-task=8
#SBATCH --time=72:00:00
#SBATCH --partition=core

/bin/echo Running on: ${SLURM_JOB_NAME}. Starting: `date`
START=$(date +%s)

export PATH=${PATH}:/projects/cgr/software/regenie
myinputpath=/projects/cgr/users/kvrf354/extract_pedmap_step1
myoutputpath=/projects/cgr/users/kvrf354/extract_pedmap_step1/Portfolio/REGENIE_step1

regenie \
  --step 1 \
  --bed ${myinputpath}/forIBD_clean \
  --covarFile ${myinputpath}/Covariates_EURandUnrelated_PCs_TotalSyn.txt \
  --phenoFile ${myinputpath}/phenotypes_final.txt \
  --phenoColList allcomers,AKI,IGAN,FSGS,GN,CYS,TIN,HT,DKD \
  --covarColList Sex,Total.Sample.Variant.Synonymous,PC_EURandUnrelated_1,PC_EURandUnrelated_2,PC_EURandUnrelated_3,PC_EURandUnrelated_4,PC_EURandUnrelated_5,PC_EURandUnrelated_6,PC_EURandUnrelated_7,PC_EURandUnrelated_8,PC_EURandUnrelated_9,PC_EURandUnrelated_10,PC_EURandUnrelated_11,PC_EURandUnrelated_12,PC_EURandUnrelated_13,PC_EURandUnrelated_14,PC_EURandUnrelated_15 \
  --catCovarList Sex \
  --test dominant \
  --bsize 1000 \
  --loocv \
  --bt --lowmem \
  --lowmem-prefix ${myoutputpath}/tmp_rg_dominant \
  --out ${myoutputpath}/fit_bin_out_portfolio_dominant

/bin/echo Finished at: `date`
END=$(date +%s)
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"

**Comment by IoannaTach** [comment]
And step2:
> cat ${softwarepath}/REGENIE_exWAS_step2_portfolio_dominant.sh

#!/bin/bash -l
#SBATCH --mem=12GB
#SBATCH --cpus-per-task=8
#SBATCH --time=72:00:00
#SBATCH --partition=core

/bin/echo Running on: ${SLURM_JOB_NAME}. Starting: `date`
START=$(date +%s)

export PATH=${PATH}:/projects/cgr/software/regenie
myinputpath=/projects/cgr/users/kvrf354/extract_pedmap_step1
myoutputpath1=/projects/cgr/users/kvrf354/extract_pedmap_step1/Portfolio/REGENIE_step1
myoutputpath2=/projects/cgr/users/kvrf354/extract_pedmap_step1/Portfolio/REGENIE_step2_exwas
model=dominant

chrom=${SLURM_ARRAY_TASK_ID}
if [[ "${chrom}" == "23" ]]; then
        chrom="X"
fi
echo ${chrom}

regenie \
  --step 2 \
  --bgen /projects/cgr/users/kvrf354/extract_pedmap_step1/chr${chrom}_step1_exwas/output/chr${chrom}_step1_exwas/chr${chrom}_step1_exwas_2021_05_10_output.bgen \
  --ref-first \
  --sample /projects/cgr/users/kvrf354/extract_pedmap_step1/chr${chrom}_step1_exwas/output/chr${chrom}_step1_exwas/chr${chrom}_step1_exwas_2021_05_10_output.sample \
  --covarFile ${myinputpath}/Covariates_EURandUnrelated_PCs_TotalSyn.txt \
  --phenoFile ${myinputpath}/phenotypes_final.txt \
  --phenoColList allcomers,AKI,IGAN,FSGS,GN,CYS,TIN,HT,DKD \
  --covarColList Sex,Total.Sample.Variant.Synonymous,PC_EURandUnrelated_1,PC_EURandUnrelated_2,PC_EURandUnrelated_3,PC_EURandUnrelated_4,PC_EURandUnrelated_5,PC_EURandUnrelated_6,PC_EURandUnrelated_7,PC_EURandUnrelated_8,PC_EURandUnrelated_9,PC_EURandUnrelated_10,PC_EURandUnrelated_11,PC_EURandUnrelated_12,PC_EURandUnrelated_13,PC_EURandUnrelated_14,PC_EURandUnrelated_15 \
  --catCovarList Sex \
  --bt \
  --firth 0.01 --approx \
  --test ${model} \
  --pred ${myoutputpath1}/fit_bin_out_portfolio_${model}_pred.list \
  --bsize 400 \
  --split \
  --out ${myoutputpath2}/exwas_step2_${model}_chr${chrom}

/bin/echo Finished at: `date`
END=$(date +%s)
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"
