### ISSUE TITLE
Error using --extract command

### ISSUE THREAD

**Issue by QinFinnUK** [rgcgithub/regenie#158]
Hi Regenie team

It's really nice to use regenie.

It works well till I started to use --extract command. I am working with UKbiobank data. I was able to build the step 1 general genetic model, but when I tried to run associations for a subset of variants on chromosome 1 in step 2, error occurs, for some subsets of variants, --extract works, but for some other sets, it doesn't.

e.g. the SNPs in below file (all those are available in chr1.bgen file)
rs116213106
rs537308457
rs146131010
rs143488476
1:162774771_C_G
rs746579693
rs530088107

I pasted below my step2 regenie command and error messages.

Thank you!

Best, Qin

              |===========================|
              |      REGENIE v2.2.gz      |
              |===========================|

Copyright (c) 2020-2021 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : /hpc/scratch/rdip1/qxw33842/regenie/output/ukb_step2_QT_chr1.log

Options in effect:
  --step 2 \
  --bgen /GWD/appbase/projects/RD-TSci-UKB/500k_GWASdownload/Aspera_Download/V3_500Kdownload/EGAD00010001474/ukb_imp_chr1_v3.bgen \
  --ref-first \
  --sample /GWD/appbase/projects/RD-TSci-UKB/500k_GWASdownload/qc_map_files/ukb26041_imp_chr22_v3_s487395.sample \
  --keep /hpc/scratch/rdip1/qxw33842/regenie/marker_keep_sample.txt \
  --extract /hpc/scratch/rdip1/qxw33842/regenie/gwas_keep_snp_rsid1.txt \
  --phenoFile /hpc/scratch/rdip1/qxw33842/regenie/pheno.qt.txt \
  --covarFile /hpc/scratch/rdip1/qxw33842/regenie/covar.txt \
  --pred /hpc/scratch/rdip1/qxw33842/regenie/output/ukb_step1_QT_pred.list \
  --bsize 1000 \
  --gz \
  --out /hpc/scratch/rdip1/qxw33842/regenie/output/ukb_step2_QT_chr1

Association testing mode with fast multithreading using OpenMP
 * bgen             : [/GWD/appbase/projects/RD-TSci-UKB/500k_GWASdownload/Aspera_Download/V3_500Kdownload/EGAD00010001474/ukb_imp_chr1_v3.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with 487409 anonymous samples and 7402791 variants with 8-bit encoding.
   -index bgi file [/GWD/appbase/projects/RD-TSci-UKB/500k_GWASdownload/Aspera_Download/V3_500Kdownload/EGAD00010001474/ukb_imp_chr1_v3.bgen.bgi]
   -keeping variants specified by --extract
regenie: ./external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:408: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Array<bool, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = bool; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted

**Comment by chengy1128** [comment]
I realized your bgen is chr1 but the `--sample` file is chr22

**Comment by QinFinnUK** [comment]
yes, all the bgen files share the same -sample file

**Comment by Shicheng-Guo** [comment]
You can try to check whether you have same error with previous version: 2.0.2

**Comment by QinFinnUK** [comment]
@Shicheng-Guo that's a great suggestion, and yes v2.0.2 works, but not v2.2 or v2.2.1

**Comment by joellembatchou** [comment]
Could you try using this commit 2218c1a9ccb4a662fa923e3e3affb99a64bd98f8 where I've added a few check to better assess what is going on?

**Comment by joellembatchou** [comment]
Are there variants with the same ID in the BGEN file?
i.e. if you run
sqlite3 <bgi_file> "SELECT rsid FROM Variant" | sort | uniq -cd

**Comment by QinFinnUK** [comment]
thanks Joelle, there are over 22k variants with duplicated rsid in the bgen file (ukb_imp_chr1_v3.bgen ) @joellembatchou

**Comment by joellembatchou** [comment]
Yes that would be causing the issue. I've made an update in the latest release (v2.2.3) to allow for variants with duplicate IDs (Regenie will only keep the first occurrence in the genotype file).

**Comment by QinFinnUK** [comment]
Thank you so much Joelle, --extract works perfectly now! 😃  @joellembatchou
