### ISSUE TITLE
!! Uh-oh, SNP with low variance

### ISSUE THREAD

**Issue by Ningus1** [rgcgithub/regenie#16]
Hi There,

I'm using Regenie with UK Biobank data. When I run Regenie step 1 it stops when it gets to block 45 with the following message in the output log file:

> block [45] : 1000 snps  (41126ms) 
>    -residualizing and scaling genotypes...!! Uh-oh, SNP with low variance.

what does this mean, does it mean there is troublesome SNP with a low minor allele frequency? The GRM file I am using has been filtered to a minor allele frequency of 1%. I had a quick look in the Data.cpp and found 

>  // only done in step 1
  if(scale_G.array().minCoeff() < params.numtol) {
    if(!params.test_mode) {
      sout << "!! Uh-oh, SNP with low variance.\n" ;
      exit(1);

There is nothing in the error log file detailing which SNP specifically is causing the issue, is there a flag to tell Regenie to ignore low variance SNPs, or a flag to set a minMAF?

At the moment I have just increased the --minMAC flag to 1000 in the hope that it catches that low variance SNP

Regards

Nathan

**Comment by joellembatchou** [comment]
Hi Nathan,

Yes this error appears if the variance of the SNP after projecting out covariates is lower than threshold of 1e-6. As you have applied a MAF filter already, it seems this might be happening because the SNP is highly correlated with some of the covariates so that the variance gets very close to 0 after projecting these out.

The `--minMAC` option only works in step 2. I've edited the code to print out the ID of the problematic SNP (so it can be among the excluded variants using `--exclude/--extract`) -> Regenie version 1.0.5.31

**Comment by saifulislampharma** [comment]
Hi, 
I have also faced the same problem, initially i tried to put the problematic SNPs in a file and include the --exclude . But new SNPs with low variance appears again. so it would be very tedious to pick those SNP manually.
Is there any way to exclude the problematic one before using command?

**Comment by joellembatchou** [comment]
Are you applying a MAF/MAC filter prior to running step 1? 
Also, what covariates are being used in the step 1 run? 

Regenie keeps the memory usage low by avoiding to read the whole genotype data at once (and so only reads it in blocks). Hence, it will not know of problematic SNPs with low variance post projection of covariates only after they are processed in memory.  

In the current version there is no option to identify these SNPS in the whole genotype data within the Regenie run. I will keep it as an enhancement feature to add. In the meanwhile, I'd suggest looking closely at what covariates are going into the model and their correlations with SNPs going into step 1. (For example, if a subset of these covariates are PCs computing from the SNPs, then you'd want to look at the PC loadings)

**Comment by saifulislampharma** [comment]
thanks. Yes, after applying MAF at 0.05, it excludes the low variance SNP, at after that, step 1 was performed. Thank you.

**Comment by JaehyunParkBiostat** [comment]
Hello, I would like to ask about a similar issue while running the first step.

I tried running the first step with about 248K samples and 375K variants.
I faced a similar error (`ERROR: !! Uh-oh, SNP chr17:21297466:C:T has low variance (=0.000000).`), specifically with those on chromosome 17.

I investigated the allele frequencies of those variants, but I found that they had quite high MAFs.
For example, chr17:21297466:C:T had an allele frequency of 0.500002.

I also found that the problematic variants had similar MAFs around 0.500, which seemed to be high enough to prevent the low variance problem.
I performed MAF filtering (> 0.05) and LD pruning with Plink2 once again, but it did not solve the issue.

I would appreciate it if you could let me know the possible reason for this issue.

Thank you.

**Comment by joellembatchou** [comment]
Hi Jaehyun,

Similar to #664 where MAF was 0.5, try applying a HWE filter which should take care of these variants.

Cheers,
Joelle

**Comment by JaehyunParkBiostat** [comment]
Hello,

I apologize for the late report; I found that applying HWE filter solved the problem.

Thank you!
