### ISSUE TITLE
Step 1 slow - multithreading problem

### ISSUE THREAD

**Issue by psnavais** [rgcgithub/regenie#168]
Hi,

I am having some troubles to get decent speeds with REGENIE. This is our current set-up: Ubuntu 18.04, 48 threads, 96G RAM, 25K samples, 2 binary traits, 15 covariates - none categorical and the latest version of REGENIE. Genotype data is a ~450K SNPs .bed file.

Full step 1 took almost 3 days using 36 threads and a block size of 100, with level 0 taking most of the time. Decreasing the number of threads to 10 (not to 20 or 15) reduces the time of level 0 to 10 minutes (as noticed in a [previous solved issue](https://github.com/rgcgithub/regenie/issues/95)). Now level 1 is already at >2 day (with 10 threads and blocks of 100), and hasn't finished the first trait. Increasing the number of blocks increases the time of level 0 to >3 hours, no matter the number of threads. The problem might be related to multi-threading not working for level 1, which appears to use only one thread (though I am not sure level 1 runs with multiple threads). Is this an expected behavior?

Edit: After 2 days running level 1 of step 1, I interrupted regenie, and tried it with 36 threads and 1000 block size. This is a picture of the screen, where one can see threads is preceded by '#'. Despite this potential commented line, now the level 1 of step 1 appears to use the 36 threads.

![Screenshot from 2021-08-16 09-55-19](https://user-images.githubusercontent.com/26716229/129530510-2fd27626-26e4-431a-9132-277fced8c3f4.png)

 I'd appreciate any hints on why this might be happening, and potential solutions. 

Pol

**Comment by joellembatchou** [comment]
Hi Pol,

Using too small block sizes at level 0 will cause level 1 to have a very large number of predictors (in your case ~25K) which will make level 1 very slow; hence we recommend to use block sizes of 1000 (in `--bsize`). 

From the log output you attached above, level 0 would take about 2h; given the number of samples you have, I'd presume overhead might be an issue here where your data is quite small that using too many threads would end up costing you more. Would recommend using 4-8 threads instead. Also, you can use 'htop' to check how many threads how many threads are being used during the run.

**Comment by psnavais** [comment]
Sorry, I should have said that running step 1 level 0 with 10 threads only uses one thread (using htop). With 36 threads now step 1 rocketed, and step 2 is running for one day - which is reasonable. 

Thanks!
