### ISSUE TITLE
Meaning of the EXTRA column regenie burden

### ISSUE THREAD

**Issue by dianacornejo** [rgcgithub/regenie#179]
Dear @joellembatchou I was wondering if you could explain to me what the EXTRA column is referring to in the output of regenie burden
```
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P EXTRA
22 16962634 GAB4.Mask3.singleton ref Mask3.singleton 0.0125 200 ADD 0.418698 0.98109 0.182131 0.174218
22 15528096 OR11H1.Mask3.singleton ref Mask3.singleton 0.02 200 ADD 0.303158 0.840239 0.130176 0.143725
```
Thanks a lot,

**Comment by Shicheng-Guo** [comment]
check here: https://github.com/rgcgithub/regenie/issues/152
burden test only have 12 columns and Extra can be ignored, I think.
