### ISSUE TITLE
Cannot convert the value to double

### ISSUE THREAD

**Issue by saifulislampharma** [rgcgithub/regenie#18]
Hi,
Currently i am trying to use regenie in our project. i have been struck in the step 1. it cannot read the phenotype file. 
Could u please help?

../regenie/regenie --bed ./beds_files/merge_bed12 --step 1  --keep keep_ids --phenoFile  v1british_21015_pheno --bsize  1000 --lowmem ./temp/test/ --out ./temp/ test/  -o step_1

the output is the following:
Fitting null model
 * bim              : [./beds_files/merge_bed12.bim] n_snps = 105891
 * fam              : [./beds_files/merge_bed12.fam] n_samples = 105
   -keeping only individuals specified in [keep_ids]
     +number of genotyped individuals to keep in the analysis = 105
 * bed              : [./beds_files/merge_bed12.bed]
 * phenotypes       : [v1british_21015_pheno] n_pheno = 51
   -keeping and mean-imputing missing observations (done for each trait)
ERROR: Could not convert value to double:

i am using the version 1.0.5.4.

my phenofile is like this:

FID IID QT0 QT1 QT2 QT3 QT4 QT5 QT6 QT7 QT8 QT9 QT10 QT11 QT12 QT13 QT14 QT15 QT16 QT17 QT18 QT19 QT20 QT21 QT22 QT23 QT24 QT25 QT26 QT27 QT28 QT29 QT30 QT31 QT32 QT33 QT34 QT35 QT36 QT37 QT38 QT39 QT40 QT41 QT42 QT43 QT44 QT45 QT46 QT47 QT48 QT49
1011486 1011486 0.08650624752044678 0.04119496047496796 -0.06235448643565178 0.04407983273267746 0.01393863931298256 0.17115741968154907 0.11086756736040115 -0.07657979428768158 -0.037114616483449936 -0.1766708493232727 0.0165364071726799 -0.09792745113372803 -0.01345844566822052 -0.07929056137800217 0.0025563156232237816 0.06541378796100616 -0.04848047345876694 -0.028847645968198776 -0.036511074751615524 -0.14107286930084229 -0.011658050119876862 0.16865745186805725 0.055380549281835556 0.05419118329882622 -0.2434837520122528 -0.07224298268556595 -0.07210621237754822 -0.0017865076661109924 0.25805607438087463 -0.004425885155797005 -0.023521680384874344 -0.03987765312194824 0.1299472451210022 0.10304250568151474 0.0120860505849123 0.07672308385372162 0.015035469084978104 0.05200103297829628 -0.08022595196962357 -0.011165479198098183 -0.06150960549712181 0.218735933303833 -0.07328888028860092 -0.10803087800741196 0.018650751560926437 0.00676332600414753 0.13026218116283417 0.049227744340896606 0.025693099945783615 0.0573546439409256

**Comment by joellembatchou** [comment]
Hi,

What is printed out for  <STRING> in "ERROR: Could not convert value to double: **STRING**". It should show what value caused the error.

Also, note that to specify where to store the temporary files from step 1, you need to use `--lowmem-prefix` (so in your case `--lowmem --lowmem-prefix /temp/test/)

**Comment by saifulislampharma** [comment]
Yes. There was extra whitespace in the end of each line. After removing it, step 1 was performed. Thank you.
