### ISSUE TITLE
Extending chrStrToInt to recognize X, Y coded as 23, 24

### ISSUE THREAD

**Issue by demodw** [rgcgithub/regenie#187]
Hi,

Currently regenie only recognizes the sex chromosomes coded as X, Y, PAR1, PAR. Would it possible to extend chrStrToInt (https://github.com/rgcgithub/regenie/blob/e37f028dcf421e4fc40955fc97439c5171a78ee3/src/Regenie.cpp#L10979) to also recognize 23, 24?

This is currently an error that occurs for me in Step1 of regenie, despite providing a list of SNPs to extract (which only contains autosomal SNPs). An alternative could also be to only validate the SNPs being extracted?

Thanks in advice

Br,
David

**Comment by joellembatchou** [comment]
Hi David,

Regenie recognizes chr 23 (it assumes there are 22 autosomal chrs and collapses the sex chr as chr23). So ways around would be to replace 24 with 23 in the variant information file (i.e. BIM, PVAR) or use --nauto 23 so that chr=24 would be allowed.
