### ISSUE TITLE
P-values far too high for quantitative phenotype

### ISSUE THREAD

**Issue by DDochtermann** [rgcgithub/regenie#189]
I'm having some trouble running regenie (v2.2.4) on a quantitative phenotype for a large cohort. I'm testing a standard height GWAS with heights rounded to the nearest integer. I've tried a few different tests to see where the issue lies.

Converting the phenotype to binary and modifying regenie options to match returns reasonable results, as does running the quantitative cohort with plink.

I've tried running without the covariate file, using older regenie versions (v2.0.2 and v2.2), and some experiments with flag options, all to no avail. The median log10 P-value returned on these regenie runs is around 700, with a maximum of 90000, far too high. (in plink, median 0.3, max 90)

Options used for the no covariate run, filenames/paths removed: 
--step 1 \
--bed (...) \ 
--phenoFile (...) \ 
--keep (...) \ 
--extract (...) \ 
--bsize 1000 \ 
--threads 8 \ 
--out (...)

--step2 \ 
--bgen (...) \ 
--sample (...) \ 
--phenoFile (...) \ 
--pred (...) \ 
--keep (...) \ 
--gz \ 
-pThresh 0.01 \ 
-bsize 1000 \ 
--threads 8 \ 
--verbose \ 
--out (...)

Any ideas on what might be going wrong?

**Comment by DDochtermann** [comment]
I think I've narrowed it down. The initial runs that returned high p-values were on multiple concurrent phenotypes (EUR/AFR/HIS). I trimmed my phenotype file to a single cohort (EUR) and now have normal p-values again. So for example, my initial phenotype file looked something like:

```
FID	IID	Height_EUR 	Height_AFR 	Height_HIS
001	001	68		NA		NA
002	002	70		NA		NA
003	003	NA		71		NA
004	004	NA		NA		70
005	005	67		NA		NA
```

Which was problematic. Changing it to 

```
FID	IID	Height_EUR 
001	001	68			
002	002	70			
005	005	67		
```	

Fixed the issue. I'd assume this is a bug?

**Comment by joellembatchou** [comment]
As step1. of Regenie imputes missing values for the phenotypes, it is best used when the phenotypes have similar missingness patterns. The phenotypes you are running here are all mutually exclusive (so there are 2 NAs in each row as a sample can only be in 1 of the ancestries) so these traits should not be run together but rather separately. Note that in our multi-trait analyses in the Regenie paper, we had at most ~15% missingness in our phenotypes.

**Comment by DDochtermann** [comment]
Interesting. I possibly missed some details or misinterpreted something from the paper regarding parallel phenotypes then. 

I have been setting up mutually exclusive phenotypes this way in my phenotype files to run them in parallel. I ran a test and formatting multiple phenotypes this way vs independent runs doesn't seem to affect the outcome on binary phenotypes, just quantitative. Is that expected behavior?

**Comment by joellembatchou** [comment]
For BTs, the logistic regressions are run separately for each trait hence why the multi-trait runs give similar results as single trait run.

**Comment by nm15336** [comment]
Hi, I have the exact same issue - with the p values being the same range as what @DDochtermann described. I am only running one continuous phenotype 'age' in European population. Are there any suggestions for why, when I'm only running one singular phenotype? Thanks!

**Comment by joellembatchou** [comment]
Hi,

Could you give more information as to how you are running REGENIE (eg include logs) as well as the structure of your dataset?

Thanks,
Joelle
