### ISSUE TITLE
Syntax of --chrList

### ISSUE THREAD

**Issue by came203** [rgcgithub/regenie#19]
Dear Joelle and team,

thanks for providing the software.
I'm not so sure about the syntax of --chrList when running step2. If I provide a comma-separated list of chromosomes, would it be "1,2,3,..." or "chr1,chr2,chr3...". In addition, which arguments does the --bgen switch need? 

Best wishes
Rainer

**Comment by joellembatchou** [comment]
Hi Rainer,

For the `--chrList` argument, you can specify it as `--chrList 1,2,X,XY,5,6,8` for example. It also accepts the chromosomes have the prefix 'car' (lowercase) so you can also use `--chrList chr1,chr2,chrX,chrXY,chr5,chr6,chr8` as well.

For the `--bgen` argument it takes in the path to the BGEN formatted genotype file. So if the files is in `./genotype_data/test.bgen` then you would use `--bgen ./genotype_data/test.bgen`.
If there is also an accompanying sample file, you can use `--sample ./genotype_data/test.sample`

**Comment by Yemch** [comment]
Hi Joelle,

I have the same question here. If I want to specify `--chrList` as `1,2,3,4,5`, would the corresponding `--bgen` argument be `--bgen ukb_imp_chr{1:5}_v3.bgen`? 

And also for the output, would I get separate output files for each chromosome? How do I specify `--out` if so?

Thanks,
Mingchen

**Comment by joellembatchou** [comment]
Regenie only accepts a single genotype file as input so you would have to analyze each of the genotype files (which are split by chromosome) in separate calls to regenie (e.g. using bash for loop). 

You can use the argument `--out` to specify different output prefix based on the chromosome number. So for example it would look something like

```
for chromosome in {1..22}
do
  ./regenie \
  --bgen ukb_imp_chr${chr}_v3.bgen \
  ...   \  # <- pass other arguments to regenie like phenotype/covariate files, etc...
  --out regenie_out_chr$chr
done
```
