### ISSUE TITLE
ERROR: could not convert value to double: NA

### ISSUE THREAD

**Issue by emily86111816** [rgcgithub/regenie#190]
Hi,
I'm currently using regenie version 2.2.4 to analyze my data. However, it came up an error in step 1. It can't read my phenotype file. I've read past post for this kind of error, then I checked for my phenotype file. However, I didn't find any reason to cause this error yet.
Could you help me to solve this problem?

This is my code for analysis:
./regenie \
  --step 1 \
  --bed /home/emilychen/HLA/regenie/hla \
  --covarFile /home/emilychen/HLA/regenie/covariate_f.txt \
  --phenoFile /home/emilychen/HLA/regenie/pheno_b_female.txt \
  --bsize 100 \
  --bt --lowmem \
  --lowmem-prefix tmp_rg \
  --out fit_bin_f_out

output:
Fitting null model
 * bim              : [/home/emilychen/HLA/regenie/hla.bim] n_snps = 29985
WARNING: Total number of snps out-of-order in bim file : 3
 * fam              : [/home/emilychen/HLA/regenie/hla.fam] n_samples = 59448
 * bed              : [/home/emilychen/HLA/regenie/hla.bed]
 * phenotypes       : [/home/emilychen/HLA/regenie/pheno_b_female.txt] n_pheno = 5
ERROR: could not convert value to double: NA

The following file is my phenotype format:

FID IID POSTPARTUM_DEPRESSION MYOMA OVARIAN_CYST ENDOMETRIOSIS CERVICAL_POLYP
TV21_20180408D TV21_20180408D 0 1 1 0 0
TV21_20180211H TV21_20180211H 0 0 0 0 0
TV21_20180410D TV21_20180410D 0 0 0 0 0
TV21_20180409D TV21_20180409D 0 1 1 0 1
TV21_20180512E TV21_20180512E 0 0 0 0 0
TV21_20180205D TV21_20180205D 0 0 0 0 0
TV21_20180402D TV21_20180402D 0 NA NA NA NA

**Comment by joellembatchou** [comment]
Are there special characters in your file? (as 'NA' should be recognized as corresponding to missing value) 

Also, if you run the regenie command using --phenoCol to analyze each phenotype separately, does the command run for all phenotypes or fail for one/all phenotypes?

To check the unique values in each column, you could run the following bash script
```
for col in 3..7; do
cut -d ' ' -f$col /home/emilychen/HLA/regenie/pheno_b_female.txt | sort | uniq -c
echo "---"
done
```
It should output at most 4 values for each trait (phenotype name, 0, 1 or NA)

**Comment by dvh13** [comment]
I was getting this error too. "ERROR: could not convert value to double: NA". Found a funny character in the phenotype fields. using the sort | uniq as above. regards, david van heel

**Comment by dvh13** [comment]
but I still cant solve it. have tried removing non-UTF8 characters, weird non binary characters. mac2unix. adding extra line feed to last line. but I still get 5 values for one trait with two lines for NA. the file worked fine in SAIGE


[hmw208@ddy79 regenie]$ awk </data/Blizard-VanHeelLab/GenesandHealth/analysis_hmw208/2021_10_covid19hgi/GNH.44190.noEthnicOutliers.covariates.20PCs.withS1QST_diabetes_v07_justPHENOSregenie_v6.txt '{print $6}' | sort | uniq
0
1
NA
NA
S1QST_Diabetes
[hmw208@ddy79 regenie]$

**Comment by emily86111816** [comment]
I have solved my problem by changing other ways to output my data. I use R language to output my data for analyzing. I found when I used write.table() to output my data, it would endup resulting this error. However, when when I used write_delim() from tidyverse package to output my data, it could work. We thought that Regenie is a c++ based software, so it treated different types of value differently.

**Comment by dvh13** [comment]
I have solved my problem with the phenotype file. Regenie does not like CRLF at the end of lines. Converting the file with dos2unix has made it work. Debugging the files with cat -T    cat -v  and  file  helped me sort this out.

**Comment by AlisaBIG** [comment]
Hello, I have same error too. My input command had no problems. But return error like 
`could not convert value to double: 'A'`
And  my covariates file looks like as below:

FID      IID      dummy  Gender  Age  PC1       PC2      PC3        PC4       PC5        PC6         PC7         PC8        PC9         PC10
1000017  1000017  A      1       56   -11.369   3.56718  -1.97553   0.213937  -12.4342   -1.69838    -0.0906869  -3.49819   4.7626      3.15321
1000025  1000025  A      1       62   -12.162   2.7747   0.175048   2.55493   8.75958    -0.0441244  -1.4973     0.0526797  0.276735    2.1188
1000056  1000056  A      0       65   -10.7174  5.77507  0.620341   0.505251  -2.4916    1.05286     0.290698    1.67283    -1.92845    -0.712658
1000061  1000061  A      1       53   -13.4111  2.89177  -1.07691   -3.57815  -8.12579   -2.20137    -0.981899   0.799105   -0.0608819  -0.63695
1000108  1000108  C      1       53   -10.4621  5.78141  -2.22363   0.842825  -4.63634   -3.67493    0.619508    -1.68951   -1.27303    3.13426
1000115  1000115  A      0       54   68.3988   -112.19  -20.2611   5.51176   -6.44779   -4.70192    -3.70831    -1.26685   1.56186     -4.09177
1000194  1000194  A      0       48   -15.2167  4.29171  -1.78487   2.19157   7.01079    -1.14637    0.184547    -1.85365   -1.07361    0.738687
1000201  1000201  A      1       64   -12.5441  4.10342  -0.268869  1.19907   -0.541329  1.49072     -0.612991   0.45567    4.25544     -2.67295
1000213  1000213  B      0       61   -11.494   3.43141  -3.58956   -3.48781  -2.01124   -0.34383    -1.47756    -0.256353  -3.89165    -3.97156

So I woder if it is Regenie failed to deal with column dummy whose characters are "A B C" . It should be digits or NA? But my covariates do need this column. How can I solve this problem?

**Comment by joellembatchou** [comment]
Hi @AlisaBIG, you need to specify categorical covariates using `--catCovarList`.

**Comment by AlisaBIG** [comment]
> Hi @AlisaBIG, you need to specify categorical covariates using `--catCovarList`.

Hi, I have done as you said. And returned error:
`ERROR: Option ‘catCovarList’ does not exist`

And my command as follow:
`./regenie --step 1 --bed $g  --covarFile $covar_file  --catCovarList dummy --phenoFile $phe_file --keep $qc_pass_id --extract $snps_pass_snplist --bsize 1000 --qt --lowmem --lowmem-prefix tmp --out $out_prefix`

When I search for help, It seems that there is no option  called `--catCovarList`
`regenie --helpFull | grep catCovarList`
I am just a new beginner, so I wonder if option `--catCovarList`  has been removed from your script by mistake? 
Thanks in advanced!

**Comment by joellembatchou** [comment]
Which REGENIE version are you using? Please make sure to use the most recent version (v3.2.1).

**Comment by AlisaBIG** [comment]
> Which REGENIE version are you using (`regenie --version`)? Please make sure to use the most recent version (v3.2.1).

When I updated my regenie to the most recent version, problem solved. Thank you very much!

**Comment by AlisaBIG** [comment]
Hi, @joellembatchou . Sorry to disturb you again. I am learning how to parallelize Step 1  using the example data from [https://github.com/rgcgithub/regenie/tree/master/example].  In the stage1, I can't find input file /src/test/fit_bin_parallel, how can I get it? Thanks in advance!

**Comment by chirrie** [comment]
I am also getting same error ..and my files look fine

Fitting null model
 * bim              : [awigen-qc.bim] n_snps = 698876
 * fam              : [awigen-qc.fam] n_samples = 10776
 * bed              : [awigen-qc.bed]
 * phenotypes       : [FG_phenotype-reg.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 9617
 * covariates       : [FG_phenotype-reg.txt] n_cov = 11
ERROR: could not convert value to double: '-'
Start time: Fri Mar 15 10:25:20 2024

Commans is a below using (v3.4.1.gz)

regenie --threads 16 --step 1 --bed awigen-qc --phenoFile FG_phenotype-reg.txt --phenoCol glucose_qc --covarFile FG_phenotype-reg.txt --covarCol sex --catCovarList sex --covarCol age --covarCol bmi_c_qc --covarCol PC{1:8} --strict --bsize 2000 --qt --lowmem --out FG-reg-bm1

**Comment by joellembatchou** [comment]
Hi,

Are you using `-` to code for missing values? If you run `grep -m 1 -w "-" FG_phenotype-reg.txt` does anything come up?

Cheers,
Joelle
