### ISSUE TITLE
ERROR: one of the folds has only cases/controls for phenotype '...'

### ISSUE THREAD

**Issue by freeseek** [rgcgithub/regenie#191]
I am trying to write a pipeline for testing multiple users input phenotypes at once. Is there a way to tell REGENIE to automatically skip phenotypes that turn out with an insufficient number of cases and controls for step1 to work?

**Comment by joellembatchou** [comment]
Hi,

There is an option `--minCaseCount X` which ignores traits who have fewer than X cases (default is X=10).

**Comment by freeseek** [comment]
My bad I had missed that. My only suggestion then is to include both of those options as suggestions in the error message. :-)
