### ISSUE TITLE
Regenie step2 chromosome X

### ISSUE THREAD

**Issue by IoannaTach** [rgcgithub/regenie#195]
Hello,

I wish to run single-point analysis for chromosome X using plink data. I am getting this error:
regenie: src/Geno.cpp:1447: void check_bgen(std::string, param*): Assertion `minploidy == 2' failed.

According to Regenie's instructions:
"To include X chromosome genotypes in step 1 and/or step 2, males should be coded as diploid so that their genotypes are 0/2. This can be done in PLINK by setting the sex of all individuals to female before generating the genotype file. Chromosome values of 23 (for human analyses), X, XY, PAR1 and PAR2 are all acceptable and will be collapsed into a single chromosome."

I tried to correctthe plink files using the plink flag "split-par", but I am still getting the same error. I also tried the plink flag "set-hh-missing", but that did not fix the error Regenie gives me either.

Could you please give the plink command you mentin in the instructions that codes males as diploid? Many thanks!

Best,
Ioanna

**Comment by joellembatchou** [comment]
Hi Ioanna,

The 0/2 coding is [automatically done in BED/PGEN formats for haploid genotypes](https://groups.google.com/g/plink2-users/c/hPCgYtpCy0M/m/xwZifVK5AQAJ) so if the genotype file is in these formats then no additional modification needed.

**Comment by IoannaTach** [comment]
Thank you, it worked.

**Comment by skatta20** [comment]
Hi. How do you verify/test the genotypes coding in pen file to make sure that the males are coded as 0/2

**Comment by joellembatchou** [comment]
Hi,

REGENIE v3.2+ will output warning message if there are males not coded as 0/2 in non-PAR chrX.

**Comment by kauralasoo** [comment]
What would be the easiest way to recode males in non-PAR chrX from 0/1 to 0/2 if the genotypes are originally in VCF format? This seems like a standard step and I cannot imaging that everybody writes their own custom scripts for it.
