### ISSUE TITLE
Undocumented GxE and GxG interactions 

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#197]
Hi,

I realized this has been discussed in [#194](https://github.com/rgcgithub/regenie/issues/194), but `--interaction`  is already implemented in REGENIE though not documented. Does this mean the option is not yet tested or just undocumented (but works fine)?

Thanks!
OJ

**Comment by Shicheng-Guo** [comment]
Interesting. have you tried to use it or test it? Thanks Ojami!

**Comment by Ojami** [comment]
I didn't delve into all details, but I gave it a quick try for GxE interaction. By default 4 different tests are performed, first is conditional (no interaction included --> typical GWAS), and the remaining 3 are for SNP, SNPxE and joint (2 df in case on 1 interaction term). But since it's not yet documented I'm not sure if the implementation needs more polishing/fine-tuning!

**Comment by joellembatchou** [comment]
Hi,

Yes, this is still ongoing work and we will announce when it will be available in Regenie for use.

Cheers,
Joelle

**Comment by Shicheng-Guo** [comment]
Looking forward to the release of interaction which will be quite interesting for UKB-WES analysis.

**Comment by UxxUnet** [comment]
Here's the repost of [issue](https://github.com/rgcgithub/regenie/issues/221#issue-1087241296) #221 . I also have questions related to the interaction model. Could anyone help me with this?
