### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by Yemch** [rgcgithub/regenie#20]
Hi,

I am using REGENIE v1.0.5.2, and I came across an unexpected error when I tried to run the example files. 

Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
phenotype 1 (Y1) : Aborted (core dumped)

Below are part of the log:

./regenie \
   --step 1 \
   --bed example/example \
   --exclude example/snplist_rm.txt \
   --c example/covariates.txt \
   --p example/phenotype_bin.txt \
   --remove example/fid_iid_to_remove.txt \
   --b 100 \
   --bt --lowmem \
   --lowmem-prefix tmp_rg \
   --o /mye/results/fit_bin_out

....

Chromosome 1
 block [1] : 100 snps  (2ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (11ms) 
   -calc level 0 ridge...done (5ms) 
 block [2] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (3ms) 
   -calc level 0 ridge...done (2ms) 
 block [3] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (22ms) 
   -calc level 0 ridge...done (2ms) 
 block [4] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (10ms) 
   -calc level 0 ridge...done (2ms) 
 block [5] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (10ms) 
   -calc level 0 ridge...done (2ms) 
 block [6] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (8ms) 
   -calc level 0 ridge...done (2ms) 
 block [7] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (10ms) 
   -calc level 0 ridge...done (2ms) 
 block [8] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (10ms) 
   -calc level 0 ridge...done (2ms) 
 block [9] : 100 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (8ms) 
   -calc level 0 ridge...done (2ms) 
 block [10] : 94 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (7ms) 
   -calc level 0 ridge...done (2ms) 

 Level 1 ridge with logistic regression...
   -on phenotype 1 (Y1)...done (6ms) 
   -on phenotype 2 (Y2)...done (6ms) 

Output

terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
phenotype 1 (Y1) : Aborted (core dumped)
`

Do you have any suggestions about that?

Thanks,
Mingchen

**Comment by joellembatchou** [comment]
Which boost version do you have? It seems that Boost versions < 1.56 lead to this error


-> see here 


https://svn.boost.org/trac10/ticket/5289


-> also here


https://stackoverflow.com/questions/19405272/c-issues-with-boostfilesystem-on-server-localefacet-s-create-c-locale


I would suggest getting the most recent version of the BGEN library and installing it (since it links to boost library).


Cheers,
Joelle

On Jul 30, 2020, at 3:26 PM, Mingchen Ye <notifications@github.com> wrote:





terminate called after throwing an instance of 'std::runtime_error'
what(): locale::facet::_S_create_c_locale name not valid
phenotype 1 (Y1) : Aborted (core dumped)
`
Do you have any suggestions about that?
Thanks,
Mingchen

**Comment by Yemch** [comment]
Dear Joelle,

Thanks for your reply. 

I am using the latest version of BGEN v1.1.7 but with an old version of boost v 1.55. It seems that the developers hardcoded the compilation files to lookup for the boost library. I've tried to replace the old boost with boost v.1.73 but failed. 

Would any other BGEN library work?

Thanks,
Mingchen

**Comment by joellembatchou** [comment]
Hi Mingchen,

I am not able to replicate the error message after installing BGEN v1.1.7 (I think this only occurs on select machines). Anew version was released (v1.0.5.5) where there is an alternative function used outside of boost::filesystem library in the case that this error occurs. Let me know if that doesn't fix the issue.

Cheers,
Joelle

**Comment by Yemch** [comment]
Hi Joelle,

The new version regenie works! Many thanks for that!

Best,
Mingchen
