### ISSUE TITLE
ERROR: all individuals have missing/invalid values for all traits.

### ISSUE THREAD

**Issue by csalvoro** [rgcgithub/regenie#209]
Hello,

I'm running regenie v2.2.4 using the Docker image, but I get the above error in step 2.
Here is the list of options I'm using:

regenie --step 2 \
--bt \
--bsize 1000 \
--bgen my_path/file.bgen \
--phenoFile my_path/pheno.sample \
--covarFile my_path/cov.sample \
--covarColList PC1,PC2,PC3,PC4,AGE \ 
--firth \
--approx \ 
--pThresh 0.01 \ 
--pred my_path/output/out_pred.list \
--out my_path/out_assoc

My Phenotype file contains just a single, binary phenotype, with a 0/1/NA annotation. The FID/IID labels match exactly those in the .loco file, as the exact same phenotype file was used in step1. I can't figure out where the mistake is, could you provide any suggestions?

Thanks!
Cecilia

**Comment by joellembatchou** [comment]
Hi Cecilia,

You may need to pass a .sample file with the input BGEN file (using --sample) as it seems the sample IDs in the BGEN file may not match those in the phenotype/covariate files.

Cheers,
Joelle

**Comment by csalvoro** [comment]
Hi Joelle,

thanks so much for your quick reply.
You're absolutely right, that did the trick.

Thanks!
Cecilia

**Comment by joellembatchou** [comment]
You can use `-os` option to generate the .sample file in QCTOOL and pass that to Regenie (IDs should match phenotype/covariate files). Also, note that Step 2 was optimized for BGEN format with 8-bit encoding (so also use `-bgen-bits 8` in QCTOOL).

Cheers,
Joelle

**Comment by brettva** [comment]
@joellembatchou I appreciate the response!
