### ISSUE TITLE
Does running step2 with --firth flag but not the --approx flag run regular old non-approximated firth?

### ISSUE THREAD

**Issue by brettva** [rgcgithub/regenie#210]
Assuming p val is below the threshed given by `--pThresh` that is.

by contrast wondering if running step2 using `--firth` and `--approx` flag runs the ~60x faster "fast Firth" described in the [paper](https://www.nature.com/articles/s41588-021-00870-7.pdf).

Just trying to understand `--approx`

toggling this `--approx` flag changes my step2 runtime from  2.14416s to 3.98446s for a handful of variants, so def seems slower w/o `--approx` 

Thanks!

**Comment by joellembatchou** [comment]
Hi,

Yes, `--firth --approx` activates the approximate Firth method which is much faster than exact Firth (ie using only `--firth`)

Cheers,
Joelle
