### ISSUE TITLE
Flag for getting BLUP effect estimates

### ISSUE THREAD

**Issue by hrushikeshloya** [rgcgithub/regenie#211]
Was wondering if there is a flag in step 1 to get the effective BLUP effect estimates learned from the prediction ?

**Comment by joellembatchou** [comment]
Hi,

No there is no such option available (note that the predictors used in the final model in Step 1 are block predictions combining effects of multiple variants so the effect estimates from the model are not directly interpretable).

**Comment by hrushikeshloya** [comment]
Yes, was wondering if we could get effect estimates for step 0 and step 1. My use case is evaluating the R2 between true phenotype and predicted phenotype on a completely held-out dataset. Thanks!
