### ISSUE TITLE
Regenie 2.0.2 - ERROR: Phenotype 'X' has sd=0.

### ISSUE THREAD

**Issue by linxin1husky** [rgcgithub/regenie#218]
Hey everyone, 

I've been struggling with this issue for a while. I'm not sure why I kept receiving such ERROR messages.

### I have checked the following things:
1. IID/FID has a crossing-over between phenotype and covariate file.
2. both phenotype and covariate files are space-separated.
3. input bed/bim/fam passed a '--mac 50' filter.
3. I implemented the '--strict' option.
4. I calculated the sd of phenotype X separately. It's around 0.07. Is that a very low number to Regenie?
5. I checked all spelling and all spelling is correct. But I have a "/" in the covariate column name. Will that be an issue?
6. I tested the same phenotype file and a different version of covariates (fewer covariates compared to desired one). The program ran without an error message.
7. I guess updating to the latest Regenie might solve the problem. But I'm calculating on a shared server and I'm not admin so I can't update ASAP. 

>
>
>               |============================|
>               |        REGENIE v2.0.2      |
>               |============================|
> 
> Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
> Distributed under the MIT License.
> 
> ...
>    -number of individuals remaining with non-missing phenotypes = 335679
> ...
>  * covariates       : [covariate.txt] n_cov = 25
>    -number of individuals with covariate data = 324601
>  * number of individuals used in analysis = 324601
>    -fitting null logistic regression on binary phenotypes...done (1694ms) 
>    -residualizing and scaling phenotypes...ERROR: Phenotype 'X' has sd=0.
>
>

I am not sure what else I can modify to overcome this error message. Please let me know if you have any suggestions. Thanks!

**Comment by joellembatchou** [comment]
Hi,

Have you checked the correlation of the phenotype with the covariates that you included in the analysis? The error indicates that after projecting out covariates, the phenotype has very low variance (numerically 0). For example in R, if you do 
```
sd( lm(X ~ covariates )$resid)
```
what do you get?

**Comment by linxin1husky** [comment]
Hey Joelle,

I got 4.653496e-16, which is extremely small. Any suggestions to improve? 

Also, what's the minimum variance that Regenie accepts?

Best,
Lin

**Comment by joellembatchou** [comment]
So one of the covariates (or a linear combination of multiple) explains all the variation in the trait. You can use `summary(lm(X ~ covariates ))` to identify which ones (they would have very small p-values). Alternatively, you can compute the correlation of your trait with the covariates and see which have very high correlations. Regenie uses a threshold of 1e-6 for the SD of the residuals.

**Comment by linxin1husky** [comment]
Thank you for the detailed explanation. I will dig into that. 

All the best,
Lin
