### ISSUE TITLE
Conditional  analysis

### ISSUE THREAD

**Issue by Cloufield** [rgcgithub/regenie#219]
Hi, 
I am wondering if REGENIE supports conditional analysis? 
By checking the source code, it seems that conditional analysis has already been implemented, but there are no descriptions on how to use it.  (condition_snps_list? condition_snps_names? )
Or is it needed to manually extract the dosage of snps and add to covariates for now?
Thanks!

**Comment by joellembatchou** [comment]
Hi,

This feature is in the development phase; we will announce when it is ready in a future release.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
This is now available in v3.0. Cheers
