### ISSUE TITLE
SNPs list in step2

### ISSUE THREAD

**Issue by fmurgia** [rgcgithub/regenie#22]
Hi,
I wonder if, a new command ‘--include’ ,could be implemented in step 2 to allow testing only a list of imputed variants and not all those present in the bgen file.
Best,

Federico

**Comment by joellembatchou** [comment]
Hi Federico,

I will add this to the list of enhancements to add to software. 

Thanks,
Joelle

**Comment by joellembatchou** [comment]
This has now been implemented in Regenie v1.0.6.5. (Options are `--extract/--exclude`)
