### ISSUE TITLE
'--write-mask-snplist' lost some SNPs in certain mask categories

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#222]
Hi Joelle, 

I am trying to use '--write-mask-snplist' to ouput all the mask related information including masked SNPs for each category. In my genotype data, we do have same SNPs in "M2.singleton" because we notice there are 4 heterozygotes for this category , however, --write-mask-snplist don't have any SNPs in this category as output.  I am wondering any other one meet such issue before? or can you give some suggestion? 

Thanks
Shicheng

![image](https://user-images.githubusercontent.com/6641283/149218616-11e6932a-720d-4d66-bdc0-b1fa52ddaf48.png)

**Comment by joellembatchou** [comment]
Are you using the default min MAC filter of 5 (can be changed using `--minMAC`)? It's most likely that the M2.singleton mask does not appear in the --write-mask-snplist file because the variant failed the minMAC filter (so it also should not be present in the summary stats result files).

**Comment by Shicheng-Guo** [comment]
Oh. Yeah. Great idea!! Let me check. Thanks Joelle!!

**Comment by Shicheng-Guo** [comment]
> --minMAC

Confirmed! Thanks Joelle!!
