### ISSUE TITLE
Is it possible to add N_CASES and N_CONTROLS to the output?

### ISSUE THREAD

**Issue by hou** [rgcgithub/regenie#227]
Is it possible to add N_CASES and N_CONTROLS to the output? Regenie reports no. cases and no. controls in the log. But given that each variant might have different number of missing genotypes, the final N_CASES and N_CONTROL might be very different with the no. cases and no. controls provided in the log.

**Comment by Wainberg** [comment]
Just wanted to second this - per-variant N/NCAS/NCON is really important! Right now regenie just outputs the same N for each variant regardless of missingness, and doesn't output NCAS or NCON. (Relatedly, it would also be great to include A1COUNT as well as A1FREQ, and A1COUNT_CASES and A1COUNT_CONTROLS with --af-cc.)

**Comment by joellembatchou** [comment]
Hi,

We have an option `--htp COHORT_NAME` which will output a more detail summary statistics format including the genotype counts in cases/controls.

Cheers,
Joelle

**Comment by Wainberg** [comment]
Awesome! Would be great to add that to the documentation at https://rgcgithub.github.io/regenie/options; there's a treasure trove of "Extra" options at https://github.com/rgcgithub/regenie/blob/master/src/Regenie.cpp#L275 that don't seem to be documented anywhere. Some of the "Main" and "Additional" options are also missing documentation: --qt, --l0, --l1, --compute-all, --condition-file-sample, --anno-labels, --version, --iid-only (mentioned in passing but not included in one of the tables of options), --setl0, --setl1, --skato-rho (the documentation calls it --skat-rho), --joint-only, --force-ltco, --compute-corr, --output-corr-text, --forcein-vars, and --print-vcov. (I can open a separate issue if you'd like.)
