### ISSUE TITLE
--sex-specific option not working in version 2.2.4

### ISSUE THREAD

**Issue by qw57** [rgcgithub/regenie#228]
Hi,

I am using regenie 2.2.4 to run sex stratified GWAS. In a test run and running on my own data, the package appeared not being able to extract the correct sex specific samples from the sample file (suffix changed to .txt for ease of uploading on here, and randomly allocated sex to the 500 samples in the example for demonstration) [example_3chr_withSex.txt](https://github.com/rgcgithub/regenie/files/7950507/example_3chr_withSex.txt). 

My script looks like below. Log file is pasted below the script. 

#------- **Scripts** --------
**Step1:**
`regenie \
  --step 1 \
  --bed ~/bin/regenie-2.2.4/example/example \
  --exclude ~/bin/regenie-2.2.4/example/snplist_rm.txt \
  --covarFile ~/bin/regenie-2.2.4/example/covariates.txt \
  --phenoFile ~/bin/regenie-2.2.4/example/phenotype_bin.txt \
  --bsize 200 \
  --bt --lowmem \
  --lowmem-prefix tmp_rg \
  --out fit_bin_out`

**Step 2: male specific analyses**
`regenie \
  --step 2 \
  --bgen ~/bin/regenie-2.2.4/example/example.bgen \
  --sample ~/bin/regenie-2.2.4/example/example_3chr_withSex.sample \
  --covarFile ~/bin/regenie-2.2.4/example/covariates.txt \
  --phenoFile ~/bin/regenie-2.2.4/example/phenotype_bin.txt \
  --bsize 200 \
  --bt \
  --pThresh 0.01 \
  --pred fit_bin_out_pred.list \
  --write-samples \
  --gz \
  --out test_bin_out `
#----------------------- **Log see below** ----------------------------
Association testing mode with fast multithreading using OpenMP
 * bgen             : [/home/q/qw84/bin/regenie-2.2.4/example/example.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with 500 named samples and 1000 variants with 8-bit encoding.
   -index bgi file [/home/q/qw84/bin/regenie-2.2.4/example/example.bgen.bgi]
   -sample file: /home/q/qw84/bin/regenie-2.2.4/example/example_3chr_withSex.sample
   -keeping only male individuals in the analysis
**ERROR**: no samples remaining in the analysis.

#-------------**Please note :**
If I specify 'female' for the --sex-specific option, The output generated is identical to a non-sex specific analysis -- almost as if the --sex-specific option is not able to discern the sex information in the sample file. The log file for a 'female' specific analysis looks like below when running on the example data.

Association testing mode with fast multithreading using OpenMP
 * bgen             : [/home/q/qw84/bin/regenie-2.2.4/example/example.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with 500 named samples and 1000 variants with 8-bit encoding.
   -index bgi file [/home/q/qw84/bin/regenie-2.2.4/example/example.bgen.bgi]
   -sample file: /home/q/qw84/bin/regenie-2.2.4/example/example_3chr_withSex.sample
   -keeping only female individuals in the analysis
 * phenotypes       : [/home/q/qw84/bin/regenie-2.2.4/example/phenotype_bin.txt] n_pheno = 2
   -number of phenotyped individuals  = 500
 * covariates       : [/home/q/qw84/bin/regenie-2.2.4/example/covariates.txt] n_cov = 3
   -number of individuals with covariate data = 500
 * number of individuals used in analysis = 500
 * case-control counts for each trait:
   - 'Y1': 121 cases and 379 controls
   - 'Y2': 115 cases and 385 controls
 * LOCO predictions : [fit_bin_out_pred.list] n_files = 2
   -file [/lustre/ahome3/q/qw84/bin/regenie-2.2.4/testrun/fit_bin_out_1.loco] for phenotype 'Y1'
   -file [/lustre/ahome3/q/qw84/bin/regenie-2.2.4/testrun/fit_bin_out_2.loco] for phenotype 'Y2'
 * user specified to write sample IDs for each trait
 *  threads : [27]
 * block size : [200]
 *  blocks : [5]
 * approximate memory usage : 2MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)
Chromosome 1 [5 blocks in total]
   -reading loco predictions for the chromosome...done (1ms) 
   -fitting null logistic regression on binary phenotypes...done (0ms) 
 block [1/5] : done (7ms) 
 block [2/5] : done (3ms) 
 block [3/5] : done (3ms) 
 block [4/5] : done (3ms) 
 block [5/5] : done (4ms) 
Association results stored separately for each trait in files : 
* [test_bin_female_out_Y1.regenie.gz]
* [test_bin_female_out_Y2.regenie.gz]
Number of ignored tests due
 to low MAC : 0

**Comment by joellembatchou** [comment]
Hi, 

Regenie assumes that males are coded as 1 in the Sex column of the sample file so if that is not the case, it will assume samples are female. I will change it to throw out an error if the Sex does not have 0/1/2 [0=unknown, 1=male, 2=female].

Cheers,
Joelle

**Comment by qw57** [comment]
Hi Joelle!
Thanks for the reply. I have recoded sex in 1/2 and Regenie is behaving as expected now. Thanks!
