### ISSUE TITLE
Example does not match documentation

### ISSUE THREAD

**Issue by VChapdelaineT** [rgcgithub/regenie#229]
Hi,  

the output of a correct execution of the wiki's example (https://rgcgithub.github.io/regenie/options/) doesn't match the provided solution. (due to the --exclude option and some version tweaks I suspect). 

P.S. On an other note, great job on a great program.

Thank you.

**Comment by joellembatchou** [comment]
Hi,

Yes the example sum stats file is outdated; thanks for pointing that out. I will edit the test script in the next release.

Cheers,
Joelle
