### ISSUE TITLE
Regenie Docker image

### ISSUE THREAD

**Issue by akotlar** [rgcgithub/regenie#23]
Hey all, would it be possible add building and pushing a version-tagged regenie docker image. We (Hail team), are building a regenie module, and would like to rely on an official image. Happy to PR a Makefile change if that would help (just need the repo to push to).

Also, would you accept a PR that modified the Dockerfile to exclude ENTRYPOINT? This would make our lives slightly easier, and would make regenie invocation via docker container a bit more uniform with that in a normal shell environment (could copy paste the regenie examples, and when running from docker would make it possible to use environment variables within the regenie command)

**Comment by joellembatchou** [comment]
Hi,

Docker images are available in [here](https://github.com/rgcgithub/regenie/packages/348948/versions). Thank you for suggesting the removal of ENTRYPOINT; the Dockerfile has been changed appropriately.

The Makefile has been edited so running `make docker-build` will build the docker image and `make docker-test` will run a test script (using the exemplar commands from the Regenie webpage) to check the image build.

Cheers,
Joelle

**Comment by akotlar** [comment]
Awesome thanks Joelle!

**Comment by akotlar** [comment]
Sorry, to be clear about the image: you aren't actually publishing it to Docker Hub. Would it be possible to do so? This has some implications on integrating the project into an existing build system, and the licensing issues that may entail, even with a compatible license (namely we need to get approval from our legal department to do so), but referencing a built docker image (published to Docker Hub or some other repository like gcr.io), carries no such complexities.

**Comment by joellembatchou** [comment]
Hi,

We are currently only planning on publishing Docker images through Github.

Cheers,
Joelle

**Comment by akotlar** [comment]
Ah, I had checked your link on mobile, and the GitHub app just redirected me to the repo, so I though you were pointing out that you make the Dockerfile available Didn't know GitHub had this feature, cool. Thanks!

**Comment by akotlar** [comment]
This looks like it has a fairly important restriction. One needs to authenticate with Github before pulling the image. This makes `docker pull ...` break. Same issue is present when using as base image (`FROM:`)

**Comment by saphir746** [comment]
It's also not very compatible for use via Singularity

**Comment by matuskosut** [comment]
Hi @akotlar 

I was working a little on publishing regenie in bioconda, which also includes docker images published to Biocontainers (https://biocontainers.pro/tools/regenie). It is an open community, so anyone can help out.

@saphir746 would Biocontainers work better with singularity?

**Comment by Shicheng-Guo** [comment]
Dear Joelle, any plan to update docker image to 3.0.3 ？

**Comment by joellembatchou** [comment]
You mean here:
https://github.com/rgcgithub/regenie/pkgs/container/regenie%2Fregenie/18094304?tag=v3.0.3.gz

**Comment by nathanweeks** [comment]
> Hi @akotlar
> 
> I was working a little on publishing regenie in bioconda, which also includes docker images published to Biocontainers (https://biocontainers.pro/tools/regenie). It is an open community, so anyone can help out.
> 
> @saphir746 would Biocontainers work better with singularity?

@matuskosut @saphir746 A Singularity image created from the regenie Biocontainers image seems to work OK (https://github.com/rgcgithub/regenie/pull/292)
