### ISSUE TITLE
regenie2fuma or '--fuma'

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#230]
Dear regenie team, 

I will be nice to have an option '--fuma' to generate fuma input format for regenie output. 

Thanks.

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

As this can be easily done as a post-Regenie step (using the appropriate columns in the Regenie sum stats file), we don't plan to implement additional format output for FUMA.

Cheers,
Joelle
