### ISSUE TITLE
Include rare variants in step 1

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#231]
Dear Joelle, 

I am wondering do we have any test to check how rare variants affect step 1 and further step 2 association? 

Thanks.

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

We have not studied the impact of including rare variants in Step 1 as we recommend for Step 1 to use variants on array with appropriate QC to exclude for example rare variants or with high missingness.

Cheers,
Joelle

**Comment by Shicheng-Guo** [comment]
Thank you Joelle! You are always so helpful!! Shicheng
