### ISSUE TITLE
SKAT/SKAT-O gene level testing implementation?

### ISSUE THREAD

**Issue by ggstatgen** [rgcgithub/regenie#234]
Hi

Are you still planning on implementing gene-level tests which account for effect directionality across the tested SNPs? Something along the lines of what SKAT/SKAT-O do. 

These would be immensely useful as they would allow us to use Regenie for pretty much all our genome-wide variant- and gene-level testing needs.

**Comment by joellembatchou** [comment]
Hi,

Yes, we are actively working on adding other gene-based tests for Step 2 (like SKAT/SKATO). We will announce on the main page when they are available.

Cheers,
Joelle

**Comment by ggstatgen** [comment]
Many thanks Joelle!
