### ISSUE TITLE
ERROR: none of the individuals remaining in the analysis are in the LOCO predictions file from step 1.

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#235]
Hi Joelle, 

After filtering, it looks for some phenotypes, all the individuals are lost, and then REGENIE will report above error mentioned as title. I am wondering can we indicate which phenotype have this issue, so that we can remove it from the phenotype matrix?  

```
   -file [/expanse/projects/janssen4/dsci-csb/user/sguo2/regenie/2021Q4/q2tStep1/ukb_step1.qt.52_4.loco] for phenotype 'X27837'
    + 82151 individuals with missing LOCO predictions will be ignored for the trait
   -file [/expanse/projects/janssen4/dsci-csb/user/sguo2/regenie/2021Q4/q2tStep1/ukb_step1.qt.52_5.loco] for phenotype 'X27838'
    + 61 individuals with missing LOCO predictions will be ignored for the trait
ERROR: none of the individuals remaining in the analysis are in the LOCO predictions file from step 1.
Either re-run step 1 including individuals in current genotype file or use option '--ignore-pred'.

```
Best, 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

I see, I will make note of this so that it will first go through all the loco files and if this occurs, write a file with all the problematic phenotypes (so you don't have to do it one-at-a-time).

Cheers,
Joelle
