### ISSUE TITLE
installation issue "cannot find -lboost-iostreams"

### ISSUE THREAD

**Issue by bicyclic** [rgcgithub/regenie#236]
Hi, I'm trying to compile regenie.

When I run `make HAS_BOOST_IOSTREAM=1`, I get the error message in the title. 

If I just run `make`, I get several messages indicating that `boost::iostreams` cannot be accessed -- a few are copied below:
`Files.cpp:(.text+0x1b87): undefined reference to boost::iostreams::zlib::deflated`
`Files.cpp:(.text+0x1b8e): undefined reference to boost::iostreams::zlib::default_strategy`
`Files.cpp:(.text+0x1b9d): undefined reference to boost::iostreams::zlib::default_compression`

I provided reference to `/usr/bgen` as indicated and indeed in the console output, I can see `-L/usr/bgen/build/3rd_party/boost_1_55_0` being called. 

For reference, I am using .gcc-7.3.0 to compile. Please let me know if I can provide any other info and thanks for your time!

**Comment by joellembatchou** [comment]
Hi,

Is the Boost Iostreams library installed on your system? (you can install it using `sudo apt update && sudo apt install libboost-iostreams-dev`).

**Comment by bicyclic** [comment]
Ah, I installed this and it solved my issue -- thank you!
