### ISSUE TITLE
Covariates

### ISSUE THREAD

**Issue by mjbeyeler** [rgcgithub/regenie#238]
Hi,

I have a question regarding the covariates.

Does regenie require the covariates like age and genotypic PCs to be regularized, before being put as input? for example through rank-based inverse normal transformation?

If not, would you still recommend it?

(Same question for bgenie)

**Comment by joellembatchou** [comment]
Hi,

Regenie does not require regularization of covariates. It is not usually done to apply transformations like RINTing to covariates (it is actually more done for the phenotype). We do internally check for multicollinearity of the covariate variables and, if present, handle it accordingly.
