### ISSUE TITLE
--SPA and --Frith: computational time

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#242]
Dear Joelle, 

I am wondering is there any computational time has been tested for the difference between --SPA and --Firth? 

Is there any big difference between --SPA and --Firth on computational time? 

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

We have found approximate Firth test to roughly be about 25-40% slower than SPA (big advantage with Firth is in the more accurate parameter estimates with rarer variants or high case-control imbalance).

Cheers,
Joelle
