### ISSUE TITLE
WARNING: Fitted probabilities numerically 0/1 occured (phenotype #X368.3).done (6652ms)

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#245]
Dear Joelle, 

I am wondering is there any way to track which SNPs have Fitted probabilities numerically 0/1 scenario. I'd like to export these SNPs for some further analysis. 

Thanks.

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng

Is this error referring to the null logistic regression step? If so, the model does not include SNPs (unless you have added some as covariates). It is more likely the case that a covariate (or a set of covariates) is able to quite well separate cases from controls (is the trait highly imbalanced, e.g. low number of cases?)
