### ISSUE TITLE
Performing gene-based burden analysis using WES data

### ISSUE THREAD

**Issue by git-jemiller** [rgcgithub/regenie#248]
Hi, 

I was wondering if it's possible to perform gene-based association testing using WES with regenie? 
And if so, would I just need to run step2? 

If this is possible are there any unique settings/flags I would need to use?

Thanks,
Jason

**Comment by joellembatchou** [comment]
Hi Jason,

Yes it is possible, REGENIE itself is not aware of the data type input (ie imputed, exome, array,...), you just need to pass the genetic data in either PLINK BED, PLINK2 PGEN or BGEN formats. An example application of REGENIE on WES data is this paper: [https://doi.org/10.1038/s41586-021-04103-z](https://doi.org/10.1038/s41586-021-04103-z). There are no special settings/flags for WES data.

Depending on the structure on your data (are there related individuals present or high amounts of population structure), you may need to run Step 1 as well. 

Cheers,
Joelle
