### ISSUE TITLE
Cannot open phenotype file : NULL

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#25]
ERROR: Cannot open phenotype file : NULL
I've added for regenie -- step 1**--phenoFile xx.txt** 
which is a text file, first column FID, second column IID, followed by 1 column for each Phenotype (PheCodes as headers) with columns numbered as binary, 0s or 1s with NAs indicated. What's the reason for this error?..
Covariate File is being read OK...

**Comment by joellembatchou** [comment]
The error means that the phenotype file name stored inside the software is "NULL"

Which version of Regenie are you running? As mentioned in the README, some of the  option names were changed and option `--phenoFile` was introduced in Regenie v1.0.5.3 so it will not be recognized in previous versions. 

I would suggest updating to the most recent version (v1.0.5.6) and re-running the command.

Best,
Joelle
