### ISSUE TITLE
Burden-Testing: Recommended way to obtain the variants tested in each mask?

### ISSUE THREAD

**Issue by ggstatgen** [rgcgithub/regenie#250]
Dear Joelle

I would really appreciate a simple way to see exactly, for each gene which variants where tested for the given mask.

Of course, the full set of variants is in the .annotations input file, but I'm interested in the subset of those effectively used when filtering for  MAF threshold and specific mask (eg only LOFs; LOFS+missense).

What is the recommended way to get this at the moment?

**Comment by joellembatchou** [comment]
Hi,

Use `--write-mask-snplist` : to write list of variants that went into each mask to file
