### ISSUE TITLE
Advice on analysis of imbalanced BTs

### ISSUE THREAD

**Issue by mpx353** [rgcgithub/regenie#251]
Hi,

I just wondered whether there are any guidelines re analysis of very imbalanced BTs? I am currently trying to complete Step 1. with a case:control ratio of ~2500:50k (no covariates considered) in --loocv mode. 
When attempting Step 1 regression, I am receiving a non-converging warning. 

Following other posts here and the FAQ I tried to play with --niter, increasing it to 1000 without luck. 

I just wondered whether there are some further things I could try in order to be able to run step 2? At the moment I am using ~150k HQ SNPs in the model, should I try to add more (lower quality) SNPs? Happy to hear any thoughts.

Many thanks,
Stefan

**Comment by joellembatchou** [comment]
Hi Stefan,

We are working on improving the algorithm for the level 1 logistic regression to reduce convergence issues like yours. It seems you have already tried with no covariates and are already using LOOCV & also tried increasing the number of iterations. I don't have an obvious suggestion but will be looking into solutions to reduce convergence issues.

Cheers,
Joelle

**Comment by mpx353** [comment]
Fabulous, I am re-compiling now and will let you know if the issue has been resolved.

Best,
Stefan

**Comment by mpx353** [comment]
Just to let you know that the convergence issues have disappeared now. Many thanks for your help. 
I will proceed to Step 2 now and will be back in contact in case I encounter related issues.

Best,
Stefan
