### ISSUE TITLE
Regenie v3.0: gcc/7.5.0 or gcc/10.2.0 or gfortran 11.2.0

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#253]
Hi Joelle, 

I am wondering is there any specific requirement for the version of gfortran ? 

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

In the [Dockerfile](https://github.com/rgcgithub/regenie/blob/master/Dockerfile) which uses Ubuntu 18.04,  `sudo apt-get install g++ gfortran` will install GCC & Gfortran. GCC does needs to be version >= 5.1 so choosing v7.5 vs v10.2 should not impact successful compilation of the software.

Cheers,
Joelle

**Comment by Shicheng-Guo** [comment]
Thank you Joelle, confirmed gcc/7.5.0 works well!! Shicheng
