### ISSUE TITLE
Version 3 enhance the ability to decease false positive 

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#257]
Dear Joelle, 

I notice version 3.0 have some ability to remove some false positive result in 2.2.4. Here is an example, I received a false positive in 2.2.4 with beta=82 and LOG10P=173 while in version 3.0, beta and p are not significant which is what we expected. I find the sample size (from 185K to 406K) used in the analysis are changed in version 2.2.4 and version 3.0. I am wondering is there something changed underlying the code so that more samples are used (N>50 phenotypes are existed in phenotype matrix so that multiple traits analysis could be performed). [I used exact same parameters between 2.2.4 and 3.0]

```
UKB.phecode.v2021Q4.IMP38.chr1.SLC45A3.additive.SNV_X071.R3.regenie: 1 204657924 chr1_204657924_C_T C T 0.967188 **406223** ADD 0.0917324 0.345056 0.0706751 0.102177 NA

UKB.phecode.v2021Q4.IMP38.chr1.SLC45A3.additive.SNV_X071.R2.regenie: 1 204657924 chr1_204657924_C_T C T 0.967304 **185865** ADD 82.2572 2.92028 793.415 173.836 NA
```

Here is to confirm sample size increasing is common in version 3.0

Thanks. 
Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

Could you include the logs from both runs?
