### ISSUE TITLE
How does REGENIE handle genotype missingness with burden/SKAT family tests?

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#259]
Hi,

I couldn't find this within the docs, so, I was wondering how does REGENIE generate burden masks? Does it exclude _any sample_ with a missing genotype call in _either of markers_? Please consider this example:
| snp1,snp2,snp3 | MAX_1 | MAX_2 |
| --- | --- | --- |
| 1,NA,0 | NA | 1 |
| 0,1,0 | 1 | 1 |
| NA,0,0 | NA | 0 |
| 1,0,1 | 1 | 1 |

Based on what I found in #226, seems REGENIE uses `MAX_1`; however imputation in this case can improve the power (`MAX_2`), especially in case of ultra rare variants where we don't expect any ALT hom. (2s) within the matrix (so even without imputation `MAX_2` is most probably accurate for sample 1). 
Also, in case of SKAT family, it's possible to (e.g. mean) impute the genotype matrix (SKAT R implementation). Do you think it's possibe to implement genotype imputation for gene-based tests? Maybe a filter for missingness rate (e.g. to remove all markers with a missingness > filter cutoff prior to imputation) can be of help as well.

Thanks
Best/Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

In REGENIE, variants with missing data are imputed with per-SNP averages so your scenario in MAX_1 would not occur (the NA would be replaced by the SNP average). 

Cheers,
Joelle

**Comment by Ojami** [comment]
I see, this is perfect then! 
Thanks Joelle!
