### ISSUE TITLE
Bug in new burden tests

### ISSUE THREAD

**Issue by came203** [rgcgithub/regenie#260]
Dear Joelle,

magnificent work on v3, however I came across a crash when using the `--vc-tests skato,acato-full` for some of my quantitative phenotypes.

Without the `--vc-tests skato,acato-full` , the run is completed normally. When I turn on the option, I get crashes at each chromosome with following message:
```

set [14/299] : 5 variants...
     -reading in genotypes, computing gene-based tests and building masks...done (112ms)
     -computing joint association tests...done (0ms)
 set [15/299] : 5 variants...
     -reading in genotypes, computing gene-based tests and building masks...regenie: ./external_libs/eigen3/Eigen/src/Core/PlainObjectBase.h:312: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::Index = long int]: Assertion `((SizeAtCompileTime == Dynamic && (MaxSizeAtCompileTime==Dynamic || size<=MaxSizeAtCompileTime)) || SizeAtCompileTime == size) && size>=0' failed.
/var/lib/slurm-llnl/slurmd/job288620/slurm_script: line 36: 167775 Aborted                 (core dumped)
```

Interestingly, this only happens for specific phenotypes without an apparent logic. 

Best
Rainer

**Comment by came203** [comment]
By the way, the exact same command work for a binary trait, but not for a continuous trait

**Comment by joellembatchou** [comment]
Hi Rainer,

It could be related to this issue #252. Could you recompile from the most recent edit which was made to address that issue (bec102fa8b66e4a8ad1116061bfadd3377055838) and see if that solves your problem?

Cheers,
Joelle

**Comment by came203** [comment]
Dear Joelle,

yes that has done the trick, thanks a lot

Rainer
