### ISSUE TITLE
Step 2 Failing immediately with "void check_bgen" and core dumped Error

### ISSUE THREAD

**Issue by hannahpky** [rgcgithub/regenie#261]
Hi - I'm trying to run regenie and receive the following error during part 2:
`regenie: src/Geno.cpp:1770: void check_bgen(const string&, const string&, bool&, bool&, uint&, const int&): Assertion 'phasing == 0' failed. ./regenie_step2.sh: line 20: 2757072 Aborted                 (core dumped)`

These are the parameters I used as my input: 
```
 --step 2 \  
 --bgen myfile.bgen \
 --covarFile regenie_covarfile.txt \
 --phenoFile regenie_phenofile.txt \
 --chrList 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22 \
 --bsize 200 \
 --bt \
 --spa \
 --pThresh 0.01 \
 --pred regenie_stut_fit_out_pred.list \
 --out myfile_out_spa`
```
I'm wondering if the issue could possibly be with my bgen file? I'm new to using bgen formatted files and typically begin with imputed vcf.gz files as my input (from TOPMed imputation server, which uses minimac4 for imputation and Eagle for phasing). I created my bgen file starting from my vcf.gz file using the following commands:
` plink2 --vcf myvcffile.gz --export bgen-1.2 'bits=8' 'dosage=HDS' 'id-delim= ' --out myfilename` and then used `bgenix -g myfilename -index` to created the indexed bgen file (bgen.bgi).  

Help would be greatly appreciated! Our lab is considering switching from primarily using saige to using regenie and we'd like to perform some benchmarking analyses, thanks!
-Hannah

**Comment by joellembatchou** [comment]
Hi Hannah,

The error indicates that the genotype file you are passing in has phased data present (REGENIE does not handle phased data). I think in the PLINK command you are using,  you can directly [export to PGEN format](https://www.cog-genomics.org/plink/2.0/data#make_pgen) (which REGENIE can handle) and use `erase-phase`.

**Comment by hannahpky** [comment]
Hi @joellembatchou thank you very much! That was indeed the issue, my bgen file did have phased data present (I did not realize phased data were incompatible with regenie). Exporting my vcf to pgen format resolved the issue and I was able to successful execute step 2, thanks!

Best,
Hannah
