### ISSUE TITLE
--chrList Usecase

### ISSUE THREAD

**Issue by jatin-sandhuria** [rgcgithub/regenie#264]
Hi Regenie Developers

I am planning to use --chrList option Regenie has. 

Since --bgen does not accept multiple bgen files, would it be fair to use one big BGEN file which contains all the chromosomes and then use it with --chrList ? If so, would regenie internally use only those variants in the BGEN file for respective chromosome present in the --chrList option ?

Thank You
Jatin

**Comment by joellembatchou** [comment]
Hi Jatin,

Yes, using `--chrList`, only the chromosomes specified in the option argument will be analyzed. Alternatively, if you have BGEN files split by chromosomes, you could run the chromosomes in separate Regenie runs.

Cheers,
Joelle

**Comment by jatin-sandhuria** [comment]
Perfect. Another question regarding --chrList, if I have values 22,12,5,8 for --chrList option, will Regenie processed the chromosomes parallelly or serially ?

**Comment by joellembatchou** [comment]
Serially

**Comment by jatin-sandhuria** [comment]
Makes sense. Many thanks for the information.
