### ISSUE TITLE
Output columns for ADD-BURDEN-ACAT

### ISSUE THREAD

**Issue by rnbeaumont** [rgcgithub/regenie#266]
In the output files I've noticed that when running the new tests, rows relating to the ADD-BURDEN-ACAT test contain an extra field (there seem to be 5 "NA" fields output between the ID column and the the TEST column where the header states there should be 4 fields here. This is causing parsing issues for such lines. Is it possible to remove these extra fields from the output?

**Comment by joellembatchou** [comment]
Hi,

Can you include an example of what you mean?

**Comment by rnbeaumont** [comment]
The header and some example lines from the output look like

CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P EXTRA
22 44679702 PRR5_ENST00000006251.synonymous.singleton ref synonymous.singleton 0.000124304 148829 ADD 0.101439 0.0764498 1.76059 0.733882 DF=1
22 44679702 PRR5_ENST00000006251 NA NA NA NA NA ADD-BURDEN-ACAT NA NA 0.0953812 0.120649  DF=54
