### ISSUE TITLE
Allele0 and Allele1 swapped in step 2 output

### ISSUE THREAD

**Issue by DDochtermann** [rgcgithub/regenie#268]
I've been noticing this in my output files, it seems like the ID column has one format while Allele1 and Allele0 are swapped (giving ~0.99 for A1Freq)

```
CHROM   GENPOS      ID                   ALLELE0    ALLELE1   A1FREQ 
1       957415      chr1:957415:C:T      T          C         0.99991
1       1201444     chr1:1201444:G:A     A          G         0.999838
```

Any idea why this may be happening?

**Comment by joellembatchou** [comment]
Hi,

Are you using BGEN or PLINK BED input format? If so, you can use `--ref-first` to specify to use the first allele as the reference allele.
