### ISSUE TITLE
"No missing values are allowed incovariate matrix" in 3.0.1 version? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#269]
Dear Joelle, 

"No missing values are allowed in covariate matrix", is this still true for 3.01 version? or imputation will be performed if missing is detected? 

https://rgcgithub.github.io/regenie/options/#covariate-file-format

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

Individuals with missing covariate data will be excluded from the analysis (will edit the documentation accordingly).

Cheers,
Joelle
