### ISSUE TITLE
Step2 ERROR: Header of blup file must start with FID_IID.

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#27]
Please advise: Which file is not formatted correctly here? Step 1 worked fine...Step 2 ERROR See below...

Association testing mode with multithreading using OpenMP
 * bim              : [RECODE.bim] n_snps = xx
 * fam              : [RECODE.fam] n_samples = yy
 * bed              : [RECODE.bed]
 * phenotypes       : [STRs_PhenoFile_F.txt] n_pheno = xyz
   -number of phenotyped individuals =xyz
 * covariates       : [Cov_STRs_F] n_cov = xx
   -number of individuals with covariate data = zz
 * number of individuals used in analysis = zz
 * loco predictions : [fit_bin_out_pred.list] n_files = yy
 -file [fit_bin_out_1037.loco] for phenotype (LISTED FOR EACH PHENOTYPE)
-reading loco predictions for the chromosome...ERROR: Header of blup file must start with FID_IID.

head fit_bin_out_pred.list (First column is PheCode)
008.6 fit_bin_out_1.loco
008.7 fit_bin_out_2.loco

head fit_bin_out_1.loco (First column is FID_IDD)
FID_IID
1
2
3
4
5
6
7
8
9

**Comment by joellembatchou** [comment]
Are you using the same Regenie version to run step 1 and step 2 ? If yes, which version is it? (It seems to be an older version from 1.0.5.3 (at least for step 1) as the paths in `fit_bin_out_pred.list` from step 1 of Regenie should all be absolute).

It is unclear from the output you have but does the `fit_bin_out_1.loco` contain 24 rows and XX columns (where XX is the number of individuals used in the step 1 run)?
