### ISSUE TITLE
Error when running Regenie

### ISSUE THREAD

**Issue by rnbeaumont** [rgcgithub/regenie#272]
Hi,

I'm trying to run Regenie using the new ACAT tests and while most chromosomes finish, I'm getting an error on chr 7

regenie_v3.0.gz_x86_64_Linux: ./external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Array<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.

Given that the other 21 chromosomes complete OK I'm assuming it's not an issue with any of the inputs I'm using. Are you able to help with this error?

**Comment by joellembatchou** [comment]
Hi,

Which REGENIE version are you using?

**Comment by rnbeaumont** [comment]
Thanks very much for the reply. I am using v3.0.1 already

**Comment by joellembatchou** [comment]
Hi,

Ok the error message you added indicated the binary was for v3.0 (**regenie_v3.0.gz_x86_64_Linux**). Can you re-run for the set which is causing the issue (using `--starting-block`) using the option `--debug`? This will output more information which may help pinpoint where the issue is coming from.

Thanks,
Joelle

**Comment by rnbeaumont** [comment]
Apologies, I'd thought I was using that version. I've tried with v3.0.1 and I get the same error. The output with --debug in is

Chromosome 7 [2003 sets in total]
   -reading loco predictions for the chromosome...done (10ms)
 set [353/2003] : 385 variants...1 chunks
     -reading in genotypes, computing gene-based tests and building masks...WARNING: 30/57 masks fail MAC filter...set #18; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
set #21; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
Q_SKAT for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 20976.4       0       0 20976.4       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
0       0       0       0       0       0       0       0       0       0
Q_BURDEN for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 19512.2       0       0 19512.2       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
0       0       0       0       0       0       0       0       0       0
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
done (1182ms)
     -computing association tests...done (43ms)
     -computing joint association tests...regenie_v3.0.1.gz_x86_64_Linux: /home/s.joelle.mbatchou/software/regenie/external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Array<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffRet
urnType = const double&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.

**Comment by joellembatchou** [comment]
Hi,

Thank you that is very helpful. Which of the joint tests are you using?

**Comment by joellembatchou** [comment]
Sorry I meant for the `--joint` option (eg acat/nnls/minp)

**Comment by rnbeaumont** [comment]
Thanks for pushing the update. I've recompiled and rerun; the output is below

Chromosome 7 [2003 sets in total]
   -reading loco predictions for the chromosome...done (10ms)
 set [353/2003] : 385 variants...1 chunks
     -reading in genotypes, computing gene-based tests and building masks...WARNING: 30/57 masks fail MAC filter...set #18; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
set #21; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
Q_SKAT for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 20976.4       0       0 20976.4       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
Q_BURDEN for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 19512.2       0       0 19512.2       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
done (1169ms)
     -computing association tests...done (44ms)
     -computing joint association tests...regenie: ./external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Array<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted

**Comment by joellembatchou** [comment]
Ok that's strange that nothing was printed out. If you instead run with `--joint minp`, does the error still occur?

**Comment by rnbeaumont** [comment]
Yes, I get the same error. Here's the output with minp

Chromosome 7 [2003 sets in total]
   -reading loco predictions for the chromosome...done (11ms)
 set [353/2003] : 385 variants...1 chunks
     -reading in genotypes, computing gene-based tests and building masks...WARNING: 30/57 masks fail MAC filter...set #18; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
set #21; rare_mask [mu,nZ,w,w_a] = [0.00494418,31,23.5582,1.36859]
Q_SKAT for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 20976.4       0       0 20976.4       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
Q_BURDEN for all masks:
      0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0 19512.2       0       0 19512.2       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
#in mask=2
SV log10p:
0.0221982  0.586584
Wsq:
0.52517 1.36859

L:
9396.49
[muQ, scFac]=9396.49 0.829134
tau=13602.6 13695.9 13975.8 14442.3 15095.5 15935.3 18267.9   22924
Q:
20976.4 20961.8 20917.8 20844.6 20742.1 20610.4 20244.3 19513.7
acato logp=0.118381 0.416434 0.416173 0.415498 0.414734 0.414424 0.424808 0.433604 0.447255
done (1410ms)
     -computing association tests...done (34ms)
     -computing joint association tests...regenie: ./external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Array<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted

**Comment by joellembatchou** [comment]
Hi,

Can you check if this addresses your issue (cca6d9f6254bc5673a361d7e5cccce620b329676)?
