### ISSUE TITLE
Concern about co-analyzing phenotypes with missingness

### ISSUE THREAD

**Issue by apoliakov** [rgcgithub/regenie#273]
Hello! Thanks for the tool!

This is a general question about the risks of co-analyzing phenotypes with variable missingness percentages. If we have a "bag" of say 100 categorical phenotypes where the per-trait missing percentage varies from "almost none" to "50%" - is there a risk in running those traits together in Regenie v3? 

Anecdotally I had heard there are issues with phenotype matrices being subset to only individuals for which none of the phenotypes are missing in certain steps- and that sounds like something that might reduce our statistical power.

I was trying to parse this paragraph:
https://rgcgithub.github.io/regenie/overview/#missing-phenotype-data
But it's not 100% clear on which steps "group phenotypes together" and which consider each phenotype separately. Could you provide some more specific guidance?

Thank you very much!!

**Comment by joellembatchou** [comment]
Hi,

We do not recommend running Regenie multi-trait runs where traits have above 20% missingness (which is the threshold we used in the runs for the Regenie paper). This is quite important for Step 1 where we use mean-imputation for missing values.

Phenotypes are analyzed together in Step 1 (so mean-imputation is used for missing values):
* both in the level 0 and level 1 ridge regression models for QTs
* only at level 0 for BTs

Cheers,
Joelle
