### ISSUE TITLE
Error in step 2 when running burden analysis

### ISSUE THREAD

**Issue by git-jemiller** [rgcgithub/regenie#274]
Hi,

I'm trying to perform a burden based analysis using regenie v2.2.4 using a binary trait. I have been able to run a GWAS using my data previously. I have been getting the following error message but have been unable to debug so was curious if I could get some insights as to what might be the issue.

```
* set file        : [/cromwell_root/sandbox/regenie/burden_files/setlistfile.txt] ERROR: unknown chromosome code in set list file.
ln: failed to access. '/cromwell_root/*.regenie.gz': no such file or directory
```
Here is a sample of my step 2 setup

```
regenie \
--step 2 \
--bgen ${bgen} \
--covarFile ${cov_pheno} \
--covarColList ${covariates} \
--phenoFile ${cov_pheno} \
--phenoColList ${sep="," phenolist} \
--anno-file ${annofile} \
--set-list ${setlist} \
--sample ${sample} \
--mask-def ${maskdef} \
--pred ${pred} \
--bsize ${bsize} \
--threads $n_cpu \
--out ${prefix} \
${options}

```

FYI, options = "--bt --firth --approx --aaf-bins 0.1,0.5 --write-mask --check-burden-files"

For my annotation file and set list file I've tried changing the formatting of the chromosome, and have removed sex chromosomes to avoid any complications there, but still run into this issue. 

A line of my setlist file looks like this (I wasn't able to copy the exact file due to the env I was running the analysis, so assume tab-separated):

`gene1:(ENSG001,ENST0001)      1     1000     chr1_1000_C_A`

And this is similar to what the annotation file would look like (also tab-delimited):
`chr1_1000_C_A     gene1:(ENSG001,ENST0001)     lofs`

Any help would be greatly appreciated, thanks!

**Comment by joellembatchou** [comment]
Hi,

The "," in the first column is throwing off the file parsing so I'd recommend converting that to `gene1:(ENSG001_ENST0001)`. Note that you should also do the same for the annotation file.

Cheers,
Joelle

**Comment by git-jemiller** [comment]
Hi Joelle, 

Thank you for your quick and helpful response! Regenie was able to run after I replaced the commas with underscores, however I ran into the following warning:

```

set file: : [/cromwell/pathtosetlistfile/setlistfile.txt] n_sets = 6
WARNING: Detected 2285 sets with only unknown variants (these are ignored).
       +reports on burden input files written to [pred.list.file.bgen._masks_report.txt]

```

Further down in the output log file it says...

```
Number of tests with Firth correction: 0
Number of failed tests : (0/0)
Number of ignored tests due to low MAC: 0
```

The output only contains the header but without any results. 

I also tried using --build-mask 'sum' and ''comphet' but ran into the same error. Do you have any advice on how to proceed? 

Thanks!

**Comment by joellembatchou** [comment]
Can you include the full log as I can't determine from this information why no masks are built? 

Also, are you expecting for only 6 sets out of all those in the set-list file to be analyzed? If not, checking `pred.list.file.bgen._masks_report.txt` should give more insights.

**Comment by git-jemiller** [comment]
Hi Joelle, 

I tested out my analysis using the most recent version of regenie but it still resulted in a similar warning and no results in the output file  (i.e., cohort.pred.list.cohort_ref_1.0.bgen_phenotype_column.regenie.gz), however it does have the name of the mask and the header with CHROM, GENPOS, etc.

I also don't see the cohort.pred.list.cohort_ref_1.0.bgen_masks_report.txt file anywhere even though the log suggests it should have been made. 

I'm able to provide the log file, but I had to remove all of the path names and change the file names to something generic. I also rounded sample sizes so they aren't exactly the same as what I'm actually seeing.

Any suggestions on how to proceed would be greatly appreciated! 

Best,
Jason

```

Start time: Fri Apr 22 16:07:17 2022

              |=============================|
              |      REGENIE v3.0.3.gz      |
              |=============================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : cohort.bgen.log

Options in effect:
  --step 2 \
  --bgen /pathtofile/cohort.bgen
  --covarFile /pathtofile/cohort_covariats_phenos.txt.gz \
  --covarColList {list of strings} \
  --phenoFile /pathtofile/cohort_covariates_phenos.txt.gz \
  --phenoColList phenotype_column \
  --anno-file /pathtofile/cohort_genotype_vep_all_lof_nofs_canon_annofile_v4.txt \
  --set-list /pathtofile/cohort_genotype_vep_all_lof_nofs_canon_annofile_v2.txt_setlistfile_v6.txt \
  --sample /pathtofile/cohort.sample \
  --mask-def /pathtofile/regenie_all_lof_nofs_canon_mask_definition.txt \
  --pred /pathtofile/cohort_step1.pred.list \
  --bsize 400 \
  --threads 1 \
  --gz \
  --out cohort_pred.list.cohort.bgen
  --bt \
  --firth \
  --approx \
  --aaf-bins 0.1,0.05 \
  --check-burden-files \
  --build-mask sum

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bgen             : [/pathtofile/cohort_ref_1.0.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with 350000 anonymous samples and 20000 variants with 8-bit encoding.
   -index bgi file [/pathtofile/cohort_ref_1.0.bgen.bgi]
   -sample file: /pathtofile/cohort_ref_1.0.bgen.sample
 * phenotypes       : [/pathtofile/cohort_covariates_phenos.txt.gz] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 340000
 * covariates       : [/pathtofile/cohort_covariates_phenos.txt.gz] n_cov = 40
   -number of individuals with covariate data = 340000
 * number of individuals used in analysis = 340000
 * case-control counts for each trait:
   - 'phenotype_column': 10000 cases and 300000 controls
 * LOCO predictions : [/pathtofile/cohort.pred.list]
   -file [/pathtofile/cohort.phenotype_column.loco.gz] for phenotype 'phenotype_column'
 * annotations      : [/pathtofile/cohort_genotype_vep_all_lof_nofs_canon_annofile_v4.txt] 
   +number of annotations categories = 2
 * masks            : [/pathtofile/regenie_all_lof_nofs_canon_mask_definition.txt] n_masks = 1
 * aaf cutoffs      : [ 2 : 0.05 0.1 ] + singletons
 * set file         : [/pathtofile/cohort_genotype_vep_all_lof_nofs_canon_annofile_v2.txt_setlistfile_v6.txt] n_sets = 6
WARNING: Detected 2285 sets with only unknown variants (these are ignored).
     +report on burden input files written to [cohort.pred.list.cohort_ref_1.0.bgen_masks_report.txt]
 * # threads        : [1]
 * # tested sets    : [6]
 * max block size   : [400]
 * rule used to build masks : sum
 * approximate memory usage : 3GB
 * using minimum MAC of 5 (masks with lower MAC are ignored)
 * using fast Firth correction for logistic regression p-values less than 0.05

Chromosome 1 [6 sets in total]
   -reading loco predictions for the chromosome...done (401ms) 
   -fitting null logistic regression on binary phenotypes...done (1624ms) 
   -fitting null Firth logistic regression on binary phenotypes...done (8124ms) 
 set [1/6] : 1 variants...
     -reading in genotypes and building masks...done (10ms) 
 set [2/6] : 1 variants...
     -reading in genotypes and building masks...done (24ms) 
 set [3/6] : 1 variants...
     -reading in genotypes and building masks...done (8ms) 
 set [4/6] : 1 variants...
     -reading in genotypes and building masks...done (36ms) 
 set [5/6] : 1 variants...
     -reading in genotypes and building masks...done (18ms) 
 set [6/6] : 1 variants...
     -reading in genotypes and building masks...done (23ms) 

Association results stored separately for each trait in files : 
* [cohort.pred.list.cohort_ref_1.0.bgen_phenotype_column.regenie.gz]

Number of tests with Firth correction : 0
Number of failed tests : (0/0)
Number of ignored tests due to low MAC : 0

Elapsed time : 84.2598s
End time: Fri Apr 22 16:08:42 2022

```

**Comment by git-jemiller** [comment]
Hi Joelle,

I ended up getting regenie to work, thanks for your help! I'm using v3.0.1 though at the moment. I think the main issue ended up being more related to how I was submitting it as a job rather than anything with regenie itself. I believe the results from step 1, specifically the pred.list file was not being recognized and I switched from bgen chunk to a full genome bgen file. I'm not sure why the latter made a difference, but I'm still doing some tests.   

Best,
Jason

**Comment by joellembatchou** [comment]
Hi Jason,

Gld to know you were able to get it to work. I do wonder if this is a similar issue as #287; is the BGEN chunk file you were using in "ref-first" format? (i.e. if you do `bgenix -g bgen_file -list | head`, is allele1 REF or ALT?)

Cheers,
Joelle

**Comment by git-jemiller** [comment]
Hi Joelle,

Sorry, I was mistaken, it actually runs fine on individual bgen chunks when I point directly to the bgen chunked files rather than a list of files linked to google cloud storage. This is only for step2 btw when I'm using these gs chunked files. So it might be an issue with where the files are stored, but I can report back if I figure out the issue. 

Also, I looked into the ref-first  format, the columns are as follows: 

"alternate_ids rsids chromosome position number_of_alleles first_allele alternative_allele" . 

So does that mean I should specify ref-first? 

Best,
Jason

**Comment by joellembatchou** [comment]
Hi Jason,

You should check whether the allele specified in "first_allele" column is the one you want as REF in REGENIE (if that is the case, then you should use `--ref-first`).

Cheers,
Joelle
