### ISSUE TITLE
PgrGet1D() error 6

### ISSUE THREAD

**Issue by Mathias0077** [rgcgithub/regenie#276]
I converted the HRC-imputed vcf files of our study by chr to pgen format with PLINK v2.00a3LM AVX2 Intel (23 Jan 2021):

`plink2 --vcf $infile --make-pgen --id-delim '_' --out $outfilename`
then the association in step2 runs through. Good.

Then I noticed that with the command above I do not export the dosages, which was the intention, so I exported with this command:
`plink2 --vcf $infile dosage=DS --make-pgen --id-delim '_' --out $outfilename`

Then I, again, perform step 2 as above (psam, pvar, step1.loco are identical). The novel pgen file is now much bigger of course. For all tested chromosomes I always get this error (example chr17),:

```
* # threads        : [16]
 * block size       : [1000]
 * # blocks         : [1091]
 * approximate memory usage : 211MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)

Chromosome 17 [1091 blocks in total]
   -reading loco predictions for the chromosome...done (95ms)
 block [1/1091] : PgrGet1D() error 6
PgrGet1D() error 6
PgrGet1D() error 6
PgrGet1D() error 6
```

Our linux server has >500 GB RAM, so RAM should be sufficient.
I varied the used blocks and number of threads -> always the same problem
I could not locate the PgrGet1D() method in the cpp files. 
I am using REGENIE v3.0.3.

Do you have any advice, what might cause this problem?

Thank you very much.
Mathias

**Comment by joellembatchou** [comment]
Hi Mathias,

Indeed this is an error from the PGEN library we are using; I haven't synced it to the most recent updates from the original library so that could be the issue. Alternatively, you could try
* getting the PGEN files using a more recent PLINK2 binary
* converting to BGEN instead which is a supported REGENIE input format

**Comment by Mathias0077** [comment]
Hi Joelle,

thanks for looking at my problem.

Indeed, converting to bgen v1.2, 8-bit encoding finally worked (bgen 1.3 did not work and also bgen v1.2 16-bit did not work).

I am working with REGENIE v3.0.3 and PLINK v2.00a3LM AVX2 Intel (28 Mar 2022) 

Best,
Mathias
