### ISSUE TITLE
ERROR: number of variants/blocks in file don't match with that in master file.

### ISSUE THREAD

**Issue by dtaliun** [rgcgithub/regenie#277]
Hi, 

I am getting an error "ERROR: number of variants/blocks in file don't match with that in master file." when running some of the *.snplist files in parallel in Step 1. I noticed, that the error happens only for some of the *.snplist files and only when the "*.bgi" index file is present (as input I am using bgen v1.2, 8-bit encoding, zlib compressed). The error occurs for the regenie versions >2.0.2 .

The input bgen file has 360,252 variants (SNPs only, ld-pruned). The block size is 1000 and the number of parallel jobs is 10 (K=10). Changing K didn't resolve the issue. The only solution is not to have the *.bgi index file in the working directory.

Many thanks!

**Comment by joellembatchou** [comment]
Hi,

Can you try with [v3.1](https://github.com/rgcgithub/regenie/releases/tag/v3.1)? (it has more verbose output for the error which may indicate why it is happening)

**Comment by mariamaitoumelloul** [comment]
Hello, Im having the same issue with v3.2.5.3, do we know how to fix it please?

**Comment by joellembatchou** [comment]
Hi,

Can you include the full REGENIE log?

Thanks,
Joelle
