### ISSUE TITLE
A question on RINT with missingness in genotypes/covariates

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#278]
Hi Joelle,

I have some doubts on RIN transformation (`apply_rint` func) when missingness exists in covariates or genotypes (or small sample). Does REGENIE apply RINT after excluding missing covariates (and after applying `exlude` filter)? Because in case of high missingness, distribution of RINT trait can change (even may be non-normal) when RINT is applied before removal of missing samples, and therefore, effect sizes can be different (i.e. RINT_before_ex vs RINT_after_ex). 
The same can happen when missingness rate of some of interest variants is high (nonsensical in terms of GWAS but rather can be an issue when few variants are of interest), or when sample size is small. 

[PS]: I understand that as mentioned in #70, REGENIE mean imputes genotype missingness, so, genotpye missingness cannot be an issue with REGENIE (though still a general issue).

Thanks for yout inputs!
Best/Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

Individuals with missing covariates are removed from the analysis prior to RINTing. Genotypes are not used when RINTing so missingness in genotypes does not affect RINTing.

Cheers
Joelle
