### ISSUE TITLE
runtime error with recent v3.0.3 build

### ISSUE THREAD

**Issue by yujin2011** [rgcgithub/regenie#279]
Hi,

I just want to report I caught a hard runtime error in the recent build (v3.0.3) for a linear regression in UKBB data. There is no problem with the same job for v3.0.

regenie_v3.0.3.gz_x86_64_Linux_mkl: /home/s.joelle.mbatchou/software/regenie/external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::opera
tor()(Eigen::Index) const [with Derived = Eigen::Array<bool, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const bool&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
run_variant_quant.sh: line 31:  6213 Aborted                 (core dumped) 

Best,
Jin

**Comment by joellembatchou** [comment]
Hi Jin,

Can you try with [v3.1](https://github.com/rgcgithub/regenie/releases/tag/v3.1)? (I assume you are using `--apply-rint` which is why the error occurred as this bug was introduced in v3.0.3)

**Comment by yujin2011** [comment]
yes, and it produced exact results of previous version. congs!
