### ISSUE TITLE
new issue...ERROR: Zeros occured in Var(Y) during logistic regression! (Check covariates)

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#28]
I've updated REGENIE version and am now running an updated dataset...
Is the error below definitively due to lack of variance in covariates? I've tried applying differing filter parameters to phenotype and genotype data but still get the below...Is there a way to hone in on which variable is causing this, as not evident to me on my review of dataset including covariates...?

ERROR:
-fitting null logistic regression on binary phenotypes...ERROR: Zeros occured in Var(Y) during logistic regression! (Check covariates)

**Comment by psychrb** [comment]
Note: I am working with variants of relatively rare frequency, so some phenotype-variant pairs may be accounting for this...

**Comment by joellembatchou** [comment]
This error could occur because the sample size is too small, the number of cases for the phenotype is too small or a set of  covariates  (nearly) perfectly predicts the trait. This occurs when fitting the null logistic model so variants in the genotype file being low would not be a factor here. 

A quick check would be to see if it runs without specifying any covariates. If it still doesn't run, what is the number of cases and the sample size?

**Comment by psychrb** [comment]
I am working with a dataset of n=8,613 individuals, with several hundred phenotypes (phecodes)...I have filtered the phenotypes for inclusion, of at least n=50 cases and n=50 controls.

- When I include the full covariate File (Age, Sex, Race, PCs1-10), Step 1 doesn't run and is immediately stopped with ERROR **fitting null logistic regression on binary phenotypes...ERROR: Zeros occured in Var(Y) during logistic regression! (Check covariates)**
However, if I include a limited set of covariates, i.e. Age, Sex, Race, PCs1-3, Step 1 does then proceed…
QUESTION (1): Comments/input to resolve…? Unlikely that the latter PCs are predicting each trait, as many phenotypes input?

-If I run Step 1 with limited covariates (Age, Sex, Race, PCs1-3)... Step 1 runs to completion but…for several phenotypes, either of 2 main errors are thrown:
-on phenotype xyz...WARNING: Ridge logistic regression did not converge! (Increase --niter)
-on phenotype yyy...ERROR: Zeros occured in Var(Y) during ridge logistic regression! (Try with more common SNPs)

THEN in LOCO predictions:
phenotype xxx : Level 1 logistic did not converge. LOCO predictions calculations are skipped.
phenotype yyy : Level 1 logistic did not converge. LOCO predictions calculations are skipped.

QUESTION (2): Pls advise if specific suggestions/modifications/work-around?
Or if I just need to use more stringent thresholds for genotype freq and phenotype inclusion....

-Next, if I proceed with Step 2 with --ignore-pred, an output file.regenie is generated, anyway…
If I don’t add the –ignore-pred file, ERROR: ERROR : Number of files (489)  is not equal to the number of phenotypes.
QUESTION (3): What is effect of –ignore-pred on output here…??

QUESTION (4): Please confirm the column labels, on file.regenie definitively match the order of the --phenoFile column labels??

**Comment by psychrb** [comment]
Thank You. I am working with a dataset of ~8,600 individuals, a few hundred phenotypes (phecodes)...I have filtered the phenotypes for inclusion, of at least n=50 cases and n=50 controls.

-When I include full covariates (Age, Sex, Race, PCs1-10), Step 1 doesn't run and is immediately stopped with ERROR **fitting null logistic regression on binary phenotypes...ERROR: Zeros occured in Var(Y) during logistic regression! (Check covariates)**
However, if I include a limited set of covariates (i.e. Age, Sex, Race, PCs1-3,) Step 1 does then proceed…
QUESTION (1): Comments/input on this error message …? Unlikely that the latter PCs are predicting trait..and multiple phenotypes input?

-If I run Step 1 with limited covariates (Age, Sex, Race, PCs1-3)... Step 1 runs to completion but…for some phenotypes, either of 2 main errors are then thrown:
-on phenotype xyz...WARNING: Ridge logistic regression did not converge! (Increase --niter)
-on phenotype yyy...ERROR: Zeros occured in Var(Y) during ridge logistic regression! (Try with more common SNPs)

THEN in LOCO predictions:
phenotype xxx : Level 1 logistic did not converge. LOCO predictions calculations are skipped.
phenotype yyy : Level 1 logistic did not converge. LOCO predictions calculations are skipped.

QUESTION (2): Comments/suggestions/modifications/work-around, given these few phenotypes that are skipped?
(Or as is likely, I need to use more stringent thresholds for genotype freq/phenotype inclusion....)

-If I add --ignore-pred flag and proceed with Step 2, an output file.regenie is successfully generated …But, if I don’t add the –ignore-pred file, ERROR: ERROR : Number of files is not equal to the number of phenotypes.
QUESTION (3): WIth –ignore-pred is Step 1 output then entirely ignored?

-Lastly, format:
QUESTION (4): Please confirm the column labels, on Step 2 output file.regenie definitively match the order of the --phenoFile column labels??

Please respond to what might pertain to the code/program...
THANK YOU!!

**Comment by psychrb** [comment]
Thank You. 

To answer your question: I am working with a dataset of ~8,600 individuals, a few hundred phenotypes (phecodes)...I have filtered phenotypes for inclusion, of at least n=50 cases and n=50 controls.
-When I include full covariates (i.e. Age, Sex, Race, PCs1-10), Step 1 doesn't run and is immediately stopped. 
ERROR fitting null logistic regression on binary phenotypes...ERROR: Zeros occured in Var(Y) during logistic regression! (Check covariates)
However, if I include a limited set of covariates (i.e. Age, Sex, Race, PCs1-3,) Step 1 does then proceed…

QUESTION: Comments/input on this error message …? Unlikely that the latter PCs are predicting trait..and multiple phenotypes input?

If I run Step 1 with limited covariates (Age, Sex, Race, PCs1-3)... Step 1 runs to completion but…for a few phenotypes, either of 2 main errors are then thrown:
-on phenotype xyz...WARNING: Ridge logistic regression did not converge! (Increase --niter)
-on phenotype yyy...ERROR: Zeros occured in Var(Y) during ridge logistic regression! (Try with more common SNPs)
THEN in LOCO predictions:
phenotype xxx : Level 1 logistic did not converge. LOCO predictions calculations are skipped.
phenotype yyy : Level 1 logistic did not converge. LOCO predictions calculations are skipped.

QUESTION: Comments/suggestions/modifications/work-around, given these few phenotypes that are skipped? Step 2 unable to run with missing LOCO predictions (unless --ignore-pred)..
(Or as is likely, I need to use more stringent thresholds for genotype freq/phenotype inclusion....)

**Comment by psychrb** [comment]
I am working with a dataset of n=8,613 individuals, with several hundred phenotypes (phecodes)...I have filtered the phenotypes for inclusion, of at least n=50 cases and n=50 controls. I am able to use full covariate model...

-If I run Step 1, Step 1 runs to completion but…for some phenotypes, either of 2 main errors are thrown:
-on phenotype xyz...WARNING: Ridge logistic regression did not converge! (Increase --niter)
-on phenotype yyy...ERROR: Zeros occured in Var(Y) during ridge logistic regression! (Try with more common SNPs)

THEN in LOCO predictions:
phenotype xxx : Level 1 logistic did not converge. LOCO predictions calculations are skipped.
phenotype yyy : Level 1 logistic did not converge. LOCO predictions calculations are skipped.

Pls advise if specific suggestions/modifications/work-around…?
Or if I just need to use more stringent thresholds for genotype freq and phenotype inclusion....
(The only way I can proceed with Step 2 with LOC) predictions skipped is --ignore-pred..)

**Comment by joellembatchou** [comment]
You can check here for some guidelines [dealing with small sample sizes](https://rgcgithub.github.io/regenie/faq/)

Note that Regenie should be ran on traits with similar missingness patterns (in the [BioRxiv pre-print](https://www.biorxiv.org/content/10.1101/2020.06.19.162354v1) we looked at data with up to ~7% missing for binary phenotypes). It sounds like you are jointly running phenotypes with some having up to 99% of the data missing [i.e. 1-100/8613]). You should break down you set of traits into smaller sets that have similar missing data patterns and run Regenie separately on these sets.

**Comment by psychrb** [comment]
Oh, maybe I wasn't clear: the rate of missingness is not that high in my dataset... threshold of 50 was a minimum, so for example a phenotype would indeed be included for n=160 cases and n=9212 controls (as it's greater than threshold of n=50 cases).
The rate of phenotype missingness of 7% overall, is indeed helpful however...I will consider rate of missingness in phenotype inclusion and re-run analyses...Thanks!

**Comment by linnabrown** [comment]
Hi author, I also have the same bug as psychrb. But when I remove `--covarFile` it can run successfully. Do you have any idea about it?
