### ISSUE TITLE
Error when using "--apply-rint" option

### ISSUE THREAD

**Issue by daniel-hui** [rgcgithub/regenie#280]
I am running `regenie_v3.0.3.gz_x86_64_Centos7_mkl` on an HPC cluster running `CentOS Linux release 7.8.2003 (Core)`. If I try to run step2 using the "--apply-rint" option I get the following error:

```
regenie_v3.0.3.gz_x86_64_Centos7_mkl: /src/regenie/external_libs/eigen3/Eigen/src/Core/DenseCoeffsBase.h:180: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Array<bool, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const bool&; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted (core dumped)
```

I can run step2 successfully without it. I'm curious if I can just RINT the phenotypes myself before step2, or do I need to re-run step1 again with RINT'd phenotypes?

 Somewhat unrelated, but just curious if regenie is capable of outputting raw instead of -log10 p-values? I looked through the docs and didn't see an option to. Thanks.

Daniel

**Comment by GHawkes93** [comment]
Hi Daniel, Joelle,

I've found this issue too. Raw continuous phenotypes, and binary seem to be working fine. This was not an issue for me with the initial 3.0 release - seems to be something new.

Cheers,
Gareth

**Comment by joellembatchou** [comment]
Hi,

Sorry about that, it is a bug that was introduced in v3.0.3 and only occurs with `--apply-rint`. It will be fixed in the next release (should be for this week).

Cheers,
Joelle
