### ISSUE TITLE
Question about singleton

### ISSUE THREAD

**Issue by yuhancui** [rgcgithub/regenie#283]
Dear Joelle,

I have a confusion about "singleton" in step2 burden test for rare variant analysis ("AAF cutoffs" part says "By default, a mask based on singleton sites are always included."). 
To my understanding, "singleton" means a variant which is super rare that only appears once in the sample data. Then this variant should have MAC=1 and will be filtered out ( step2 has default filter of MAC=5) in step2? Something seems not correct here.
Could you please explain the meaning for "singleton" ?

Thanks,
Yuhan

**Comment by joellembatchou** [comment]
Hi Yuhan,

For the burden tests, REGENIE applies MAC filter to the resulting burden masks (so no MAC filter is applied to the input single variants going into each mask).

Cheers,
Joelle

**Comment by yuhancui** [comment]
Thanks Joelle! To be specific, "REGENIE applies MAC filter to the resulting burden masks" means the MAC filter is applied on those gene sets included in the burden masks, correct?

**Comment by yuhancui** [comment]
Got it. Thanks very much!
