### ISSUE TITLE
EXTRA column and number of covariates in log 

### ISSUE THREAD

**Issue by mtalaei** [rgcgithub/regenie#288]
Hi Joelle,

I have two issues that could not find any explanation for:
 
1. In the output of my step 2 Regenie analysis, there is an EXTRA column that contains nothing but NA. I have seen in other documents that it could be a sign of some errors (checked, and that was not the case). Can I just ignore it as it only contains NA?
2. While I have 14 covariates, the log file says "n_cov = 2" and only shows the first items in the list of my covariates (the first continuous one after --covarColList, and the first categorical one after --catCovarList). Is that OK?

Thanks 
Mohammad

**Comment by joellembatchou** [comment]
Hi Mohammad,

(1) The extra column is there to potentially indicate if SPA/Firth correction failed (`TEST_FAIL`) or for the joint tests on burden masks (eg NNLS, ACAT) it will print out the number of burden masks included in the joint test (DF=xx). If these don't apply, it will just have a "NA" in that column.

(2) When specifying `--covarColList/--catCovarList`, did you ensure the covariate specified were comma-separated? If the log file does not show all the covariates you specified in the command option list, then they were not properly passed to the software (such error would be catched starting from version 3.0.3).

Cheers,
Joelle

**Comment by mtalaei** [comment]
Thank you very much, Joelle
The covariates were comma-separated, but I had a space after each comma, and that was the problem. The issue was resolved when I just changed "--catCovarList centre, array" to "--catCovarList centre,array". 

Cheers
Mohammad
