### ISSUE TITLE
Regression taking 26 hours to complete

### ISSUE THREAD

**Issue by jatin-sandhuria** [rgcgithub/regenie#289]
Hi - I am running a regression on 1 phenotype, 38 covariates, ~34k samples, 4.7 million chromosome 6 variants. It is taking ~25 hours to complete chromosome 6 on step 2. Does Regenie take that long time to run one chromosome ? I am also seeing this with other chromosomes where chromosome 22 is taking ~10 hours and chromosome 2 is taking more than 30 hours to run.  

Can you suggest if this is expected for Regenie to take ~25 hours to complete a regression ? 

Resources provided to the job: --mem=75GB --cpus-per-task=50

Logs:
              |===========================|
              |      REGENIE v3.0.gz      |
              |===========================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : /{path}/output_dir/regression/session_10_missingness_10//chr6.log

Options in effect:
  --step 2 \
  --chr 6 \
  --phenoFile {path}/phenotype_file_for_session_id_10_missingness_10.txt \
  --covarFile {path}/covariates_file_for_session_id_10_missingness_10.txt \
  --phenoColList phenotype_1 \
  --covarColList cov_1, cov_2, cov_3, cov_4, cov_5, cov_6, cov_7, cov_8, cov_9, cov_10, cov_11, cov_12, cov_13, cov_14, cov_15, cov_16, cov_17, cov_18, cov_19, cov_20, cov_21, cov_22, cov_23, cov_24, cov_25, cov_26, cov_27, cov_28, cov_29, cov_30, cov_31, cov_32, cov_33, cov_34, cov_35, cov_36, cov_37, cov_38 \
  --catCovarList cov_35, cov_36, cov_37, cov_38 \
  --pred {path}/output_dir/pheno_prediction/session_10_missingness_10//_pred.list \
  --gz \
  --out {path}/output_dir/regression/session_10_missingness_10//chr6 \
  --minMAC 25 \
  --minINFO 0.3 \
  --extract {path}/incl_variants.txt \
  --sample {path_sample_bgen}.sample \
  --maxCatLevels 30 \
  --ref-first \
  --bsize 7000 \
  --bgen {path}.bgen

Association testing mode with fast multithreading using OpenMP
 *bgen             : [{path}.bgen]
   -summary : bgen file (v1.2 layout, zlib compressed) with 487409 anonymous samples and 5751712 variants with 8-bit encoding.
   -index bgi file [{path}.bgen.bgi]
   -keeping variants specified by --extract
   -number of variants remaining in the analysis = 4789537
   -sample file: {path_sample_bgen}.sample
 *phenotypes       : [{path}/phenotype_file_for_session_id_10_missingness_10.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 34023
 *covariates       : [{path}/covariates_file_for_session_id_10_missingness_10.txt] n_cov = 38
   -number of individuals with covariate data = 34023
 *number of individuals used in analysis = 34023
 *LOCO predictions : [{path}/output_dir/pheno_prediction/session_10_missingness_10//_pred.list]
   -file [{path}/output_dir/pheno_prediction/session_10_missingness_10/_1.loco.gz] for phenotype 'phenotype_1'
   -residualizing and scaling phenotypes...done (12ms) 
 *# threads        : [95]
 *block size       : [7000]
 *#blocks         : [685]
 *approximate memory usage : 27GB
 *using minimum MAC of 25 (variants with lower MAC are ignored)
 *using minimum imputation info score of 0.3 (variants with lower info score are ignored)
 *user specified to test only on select chromosomes

Regression job took across a batch of Chromosome: 6 in (hours: minutes: seconds): 25:30:44

**Comment by jatin-sandhuria** [comment]
Also, the bgen files which are used for step2 is non-phased, is of v1.2 format and is of 8-bit encoding

**Comment by joellembatchou** [comment]
Hi,

It may be a overhead issue; can you try instead splitting the run into multiple jobs (eg groups of variants) and running these jobs in parallel specifying e.g. 4 threads per job (so ~20-25 jobs overall since you seem to have 95 cores available)? Also, you can reduce the block size, since Step 2 is purely parallel in nature, e.g. `--bsize 200` to limit memory usage across all the jobs.

Cheers,
Joelle

**Comment by jatin-sandhuria** [comment]
Thanks Joelle!
