### ISSUE TITLE
Testing binary and quantitative phenotypes together?

### ISSUE THREAD

**Issue by Apb58** [rgcgithub/regenie#29]
Hello! I was wondering if there is currently a way to be able to include both binary and quantitative traits together in the same phenotype file. I can run step 1 using a 'mixed' phenotype file by not setting the `--bt` flag, but then the binary traits are treated continuos. 

I realize this is likely not possible because the regression modeling strategy (linear v. logistic) used in step 2 depends on the phenotypes following one or the other format, but I thought I'd just make sure I wasn't missing anything...

**Comment by joellembatchou** [comment]
Hi,

Currently, quantitative and binary phenotypes need to be run separately as the model fit in level 1 as you mentioned uses a linear/logistic model for QTs/BTs, respectively. 
You can still use a file that has all traits together by using option `--phenoColList` to specify the phenotype columns to include in each run.

Cheers,
Joelle

**Comment by ajlee21** [comment]
Are there plans to add this feature to the REGENIE app - i.e. allow users to run both quantitative and binary phenotypes in parallel runs of the same job?

**Comment by joellembatchou** [comment]
Hi, 

No, we do not have plans to add this feature at this time.

Cheers,
Joelle
