### ISSUE TITLE
A question on `condition-list` argument with gene-based tests

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#297]
Hi Joelle,

When performing gene-based tests, one may adjust (conditionin on) for some genes with `condition-list` option. This essentially means, one would include all list of variants on those conditioning genes in `condition-list` file. This is extremely slow especially for BTs , since the number of variants on genes tend to be large, and thus, the covariate matrix will be a huge sparse matrix with hundreds of rare variants (as opposed to single-variant analyses). Doesn't it make more sense to first collapse those variants into a burden mask and then include it into the list of covariates (after all, that's the main rationale behind burden test!). So technically instead of testing:
```
y ~ mask_gene1 + X + conditioning_variants_on_gene2 [e.g. 100 rare variants]
```
this test is performed:
```
y ~ mask_gene1 + X + mask_gene2
```
or for more than 1 conditioning genes:
```
y ~ mask_gene1 + X + mask_gene2 + mask_gene3
```

Appreciate your thoughts on this!

Best/Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

I think the reasoning we had when implementing these was to address the question of "is this rare variant signal driven by a nearby GWAS hit" which would often be a more common variant hence we did not consider the approach of collapsing the conditioning variants into a burden mask. If for your specific usage you would like to do that, you could first run Regenie for your conditioning gene (eg `mask_gene2`), building and writing to BED file the resulting mask and then specify it in a second Regenie run (using `--condition-list/--condition-file`).

Cheers,
Joelle

**Comment by Ojami** [comment]
Yes, that's certainly of more practical use!

Best/Oveis
