### ISSUE TITLE
Raitonale for pruning step 1 variants

### ISSUE THREAD

**Issue by tom-a-bond** [rgcgithub/regenie#299]
Hi,

Is the aim of LD pruning the variants used for step 1 just to get ~500k variants, or would you recommend light pruning (e.g. R2 threshold 0.9, window size 1,000 markers, step size 100 markers as per https://www.nature.com/articles/s41588-021-00870-7) in general? (i.e. does pruning serve some purpose other than altering the number of variants?)

Thanks
Tom

**Comment by joellembatchou** [comment]
Hi Ton,

The penalized regressions used in Regenie can handle having highly correlated variants; indeed, pruning is recommended to reduce the number of variants to ~500k.

Cheers,
Joelle

**Comment by tom-a-bond** [comment]
Great, thanks for confirming
Best wishes,
Tom
