### ISSUE TITLE
error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by freeseek** [rgcgithub/regenie#303]
The latest published Linux binaries, starting from version 3.0, depend upon the libgfortran.so.4 binary from the libgfortran4 package. However, new systems come with the libgfortran.so.5 binary from the libgfortran5 package and typically the older binary cannot be easily installed. Is there an easy workaround?

**Comment by joellembatchou** [comment]
Hi,

Sorry about that oversight; in future releases, we will make sure to statically compile the GFortran library so this issue can be avoided. For now, I've added a Ubuntu binary (https://regenie_v3.1.1.gz_x86_64_linux_mkl_static_gfortran.zip)  for the newest version [here](https://github.com/rgcgithub/regenie/releases/tag/v3.1.1).

Cheers,
Joelle
