### ISSUE TITLE
Encoding non-numerical variables in covariates

### ISSUE THREAD

**Issue by syaffers** [rgcgithub/regenie#304]
Hi, I came across your paper in Nature, and it was stated that the covariates used for one of your analysis were

> ... age, age^2, sex, age × sex ...

How do you encode sex as a numerical value in the covariates file? Also, in extension, how do you encode categorical variables if you wanted to include them as covariates?

What about the sex in the FAM file (if I were using PLINK's bfile)? Is this automatically included as part of a covariate, or should I pass a flag to use the FAM-bound sex value as a covariate?

**Comment by joellembatchou** [comment]
Hi,

Sex was numerically coded as 1/2 in the covariate file for the paper (1=male,2=female). You can have categories listed in the covariate file for the categorical variables (e.g. male/female for sex) and then pass them through `--catCovarList`.
The sex information in the FAM file is not included as a covariate; you would need to add it to the covariate file.

Cheers,
Joelle
