### ISSUE TITLE
Analyses in small cohorts - correlation between p-values from regenie and plink2 low

### ISSUE THREAD

**Issue by Ax-Sch** [rgcgithub/regenie#305]
Dear Joelle,

first of all - thank you for your great and easy to use software! 

I have an issue regarding regenie’s behaviour in small cohorts. I conducted a GWAS in two cohorts with small sample sizes within the Long COVID working group of the COVID-19 Host Genetics Initiative. 
The first GWAS conducted was on a cohort of 90 cases and 84 controls (after QC, binary phenotype). Data was from an Illumina GSA array. QC was done as recommended by the Long COVID working group (standard procedures). Then European individuals were selected by PCA and related individuals were removed (KING). This data was then imputed using TopMed (for this, data was lifted from hg19 to hg38). I then pruned the unimputed data and conducted regenie step 1 (10 PCs, Age, Sex and combination thereof were used as covariates). Regenie step 2 was subsequently conducted with varying parameters. Additionally, I conducted the GWAS on the imputed data using plink2’s –glm command (covariates were used). 
The issue is that the correlation of p-values between methods using regenie step1 (step2 with SPA, step2 with Firth’s, step2 with no correction) and methods not using regenie step1 (regenie step2 with SPA with ignore-pred-option, regenie step2 with Firth’s with ignore-pred-option, regenie step2 with no correction with ignore-pred-option, plink2) is low. Within these groups of methods the correlation of p-values is high, however (you can see pairwise correlation coefficients at the bottom).

With a different phenotype definition I have 90 cases and 988 controls (same overall data set). There this behaviour seems to be milder (see below). I would be very interested in your opinion on this behaviour. My thoughts were that regenie with step 1 might be too complex for the first, very small cohort. The next question would be if there are recommendations on the method for such small cohorts?

**90 cases, 84 controls**
Pearson’s correlation coefficients of -log10(P) values
Method1 Method2	cor
Regenie SPA	vs. Regenie no corr.	0.9952827
Regenie SPA	vs. Plink2 glm	0.4553663
Regenie no corr.	vs. Plink2 glm	0.4521635
Regnie ignore-pred, no corr.	vs. Plink2 glm	0.9978776
Regnie ignore-pred, no cor	vs. Regenie no corr.	0.4538803
Regnie ignore-pred, SPA	vs. Plink2 glm	0.9966445
Regnie ignore-pred, SPA	vs. Regenie SPA	0.4578595

**90 cases, 988 controls**
Pearson’s correlation coefficients of -log10(P) values
Method1	Method2	cor
Regenie SPA	vs. Regenie no corr.	0.9954188
Regenie SPA	vs. Plink2 glm	0.9016621
Regenie no corr.	vs. Plink2 glm	0.908035
Regnie ignore-pred, no corr.	vs. Plink2 glm	0.9844786
Regnie ignore-pred, no cor	vs. Regenie no corr.	0.9212221
Regnie ignore-pred, SPA	vs. Plink2 glm	0.9775768
Regnie ignore-pred, SPA	vs. Regenie SPA	0.9256606

![image](https://user-images.githubusercontent.com/56272646/169308153-858af0d2-f1f0-435e-8f7c-c0609c16be75.png)
-Log10(p-value) of Regenie with step 1 and --spa (y-axis) vs. plink2 (x-axis) in the cohort with 90 cases and 84 controls. Note that filters were applied (-log10(p)>2) to not overwhelm ggplot, which explains the square with no data points in the lower left of the plot.

![image](https://user-images.githubusercontent.com/56272646/169309038-aaffd5a3-1c1e-4131-8036-c355a4867c7d.png)
-Log10(p-value) of Regenie without step 1 (--ignore-pred option) and --spa (y-axis) vs. plink2 (x-axis) in the cohort with 90 cases and 84 controls.

**Comment by joellembatchou** [comment]
Hi,

With very small sample sizes, the step 1 genetic predictions will be quite noisy (would decrease with N) and so would lead to lower correlation between including them vs excluding them (e.g. Regnie ignore-pred, no cor vs. Regenie no corr.). And your experiments supports that in the larger sample size case, the correlation is much higher. We have done testing on sample sizes as low as 1000 individuals where we found the step 1 predictions worked well at capturing pop. structure & relatedness but did not consider lower sample sizes.

Cheers,
Joelle

**Comment by guhanrv** [comment]
Hi @Ax-Sch - 

Do you mind sharing your command for running Regenie with ignore-pred and no correction (no step 1) that got good concordance with plink2 glm? I am getting bad concordance (0.42) even in this setting with a similarly small dataset.

My command is:

```
regenie \
    --threads 32 \
    --step 2 \
    --ignore-pred \
    --bsize 200 \
    --apply-rint \
    --bed ${geno} \
    --phenoFile ${pheno_file} \
    --phenoCol ${pheno_col} \
    --covarFile ${pheno_file} \
    --covarCol Sex --covarCol Age --covarCol PC{1:10} \
    --out results/regenie/${pheno_col} \
    --remove to_remove \
    --minMAC 0.5
```
