### ISSUE TITLE
A clarification on two-step ridge regression 

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#306]
Hi Joelle,

In REGENIE, final shrinkage parameter (i.e. in level 1) is selected via k-fold CV. So, out-of-sample predictions from level 0, are used in level 1 to find the ω corresponding to min MSE (eqs 20-24 in supp material of REGENIE paper). My question is: does REGENIE fit two separate ridge models in level 0, one using full dataset (eq. 14), and one in eq 21 for all k folds? so W* is only used for finding optimal ω, and W is used for predictions. Is this correct?
If so, why not constructing W* from W in level 1? I mean instead of CV in each genotype block in level 0, CV can be applied to W matrix in level 1 to save some time and memory. Based on description given [here](https://rgcgithub.github.io/regenie/overview/#step-1-whole-genome-model), it seems to me that k-fold CV is done in level 1 and no W* is not involved (no CV in level 0?).

Thanks 
Best/Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

At level 0, out-of-sample predictions are obtained separately for each fold and these are used as input predictors for the level 1 models. So we only apply Eqn. 21 to get the predictions at level 0 (this is done to reduce overfitting). At level 1, we apply the ridge regressions within each fold & compute again out-of-sample predictions to obtain the optimal parameter. 

Cheers,
Joelle

**Comment by Ojami** [comment]
Hi Joelle,

Thanks for the clarification. To me, eq 14 is a bit confusing (W* is constructed in level 0 and not W).

One could also fit (CV per each block) a separate ridge to find an optimal lambda for each block, so output of each block at level 0 is a vector instead of matrix. I guess the approach of REGENIE outperforms (better fit) this potential approach. I was wondering if you have also tested this in the development of REGENIE? 

Best
Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

Right, we used a stacking approach inspired by previous work (e.g. Stacked regressions, Breiman 1996) which showed it can give better performance compared to directly choosing the optimal lambda for each block in level 0.

Cheers,
Joelle

**Comment by Ojami** [comment]
Thanks Joelle,
Precise and clear as always!
