### ISSUE TITLE
GxE interaction

### ISSUE THREAD

**Issue by DelnazRoshandel** [rgcgithub/regenie#309]
I want to run a GWAS for a quantitative trait in UKBB on RAP and test for GxSex interaction. So in step 1, I included Sex as a covariate in the model with a bunch of other covariates. I realize that --interaction can only be used in Step 2. So My code looks like this:

regenie --step 1 \
 --lowmem --out Output_File_Name --bed ukb22418_c1_22_v2_merged \
 --phenoFile Phenotype_File.txt --covarFile Covariates_File.txt \
 --phenoCol PhenotypeName \
 --covarColList Sex,Covar1,Covar2,... \
 --catCovarList Sex \
 --bsize 1000 --threads 16

Which worked fine. However, when I run Step 2 like this:

regenie --step 2 \
    --bgen ukb22828_c1_b0_v3.bgen \
    --sample ukb22828_c1_b0_v3.sample \
    --phenoFile Phenotype_File.txt --covarFile Covariates_File.txt \
    --phenoCol PhenotypeName \
    --covarColList Sex,Covar1,Covar2,... \
    --catCovarList Sex \
    --interaction Sex \
    --minMAC 80 --minINFO 0.5 \
    --bsize 1000 \
    --pred Output_File_Name.list \
    --threads 16 --out Output_File_Name_Chr1

I get this error message:
ERROR: There are unmatched arguments:
'--covarColList'
(Make sure there are no spaces in the options arguments)

There is no space between the covariate names. They are separated by ","

I am wondering what is causing the problem.

**Comment by joellembatchou** [comment]
Hi,

Have you trying printing your command and piping through `cat -A` to see if there are any special characters?

Cheers,
Joelle
