### ISSUE TITLE
Issue identifying group files when running regenie gene burden test - v2.2.4

### ISSUE THREAD

**Issue by akhilpampana** [rgcgithub/regenie#311]
Hello, 

I am trying to run a gene burden test using regenie 2.2.4. I am getting the issue of "incorrectly formatted file at line 1". I used the same format the files were generated as suggested in the documentation.  Please do let me know how to fix it. 

I even tried to upgrade to the latest version of regenie to test the group. There also I am getting issues as suggested in the photo below. 

Please do let me know how to get through the issue. 
Grp format: ![grp_format](https://user-images.githubusercontent.com/19439352/171908294-92ffbcd5-a2cb-4f0f-ade6-ecc235e7f576.PNG)
Code issue: ![Code_issue](https://user-images.githubusercontent.com/19439352/171908282-4ff93ff8-049c-447e-86a3-217335eae7ae.PNG)
Issue when updating to latest version of regenie: ![Issue_when_updateing_to_lates](https://user-images.githubusercontent.com/19439352/171908453-073b1cb4-3ee4-442f-9de8-49afb759d9a0.PNG)

Regards
Akhil

**Comment by joellembatchou** [comment]
Hi Akhil,

I am not sure why you are getting the error as from the snapshot you included, the format of the setlist file looks good (perhaps try `head plof.grp | cat -A` to see if there are any special characters). 

There are pre-compiled Regenie binaries available for the newest version: https://github.com/rgcgithub/regenie/releases/tag/v3.1.1

For the error you got, did you pull from the latest commit in the Github repository?

Cheers,
Joelle

**Comment by akhilpampana** [comment]
Hello, 
![image](https://user-images.githubusercontent.com/19439352/172741700-94ad6a08-bcd9-4689-8438-eac6a3c1a391.png)

I did run with the latest build and still got the same error. Not sure how to fix it.

Regards
Akhil

**Comment by akhilpampana** [comment]
I tried as suggested above it dint worked however when I break the group files by chromosomes, it worked fine. Not sure what the issue is with the combined file.

**Comment by joellembatchou** [comment]
Great, happy to hear you found a solution.

Cheers,
Joelle
