### ISSUE TITLE
Seemingly deflated p-value problem

### ISSUE THREAD

**Issue by maxwell2732** [rgcgithub/regenie#312]
Hello,

I'm analyzing a binary trait with two covariates, the qq plot looks to be deflated at the upper tail. Is there any suggestion on the options that may correct the bias? Thanks!! 

![qq1](https://user-images.githubusercontent.com/52115330/173377996-1eb05076-9d03-427a-8f95-3db8d6ca8f27.png)

The codes I used were:

# Step 1:
regenie --step 1 
--bed c1_22_merged 
--phenoFile phe2.phe 
--extract 220610_array_snps_qc_pass.snplist 
--phenoCol phe_cc 
--covarFile phe2.phe 
--covarCol age 
--covarCol sex 
--bsize 1000 
--lowmem 
--out 220610_results
 --bt 
--loocv 
--threads 16 
--gz

# Step 2:
regenie --step 2 
--bed c1 
--out assoc_c1 
--phenoFile phe2.phe
--covarFile phe2.phe 
--bt 
--approx 
--firth-se 
--firth 
--extract c1_snps_qc_pass.snplist 
--phenoCol phe_cc 
--covarCol age 
--covarCol sex 
--pred 220610_results_pred.list 
--bsize 200
 --pThresh 0.05 
--minMAC 3 
--threads 16 
--gz

**Comment by joellembatchou** [comment]
Hi, 

Is your BT highly imbalanced?

**Comment by maxwell2732** [comment]
Yes, the numbers of cases and controls are 9,273 and 169,703, respectively.

So cases:controls is about 1:18.3. 

Is this the reason?

**Comment by joellembatchou** [comment]
Possibly, Firth/SPA can be more conservative in the presence of high case-control imbalance.
