### ISSUE TITLE
v3.1.2    --phenoFile has to be tab delimited

### ISSUE THREAD

**Issue by dvh13** [rgcgithub/regenie#315]
Minor issue. Documentation says --phenoFile can either be tab or space delimited. But only tab delimted works. Space delimited gives "ERROR: incorrectly formatted phenotype file."
regards, david

**Comment by joellembatchou** [comment]
Hi David,

Have you tried running the test script in the source directory? i.e. `bash test/test_bash.sh` 
It runs a few test commands, some of which use the phenotype file in `example/phenotype_bin.txt` which is space-separated.

Have you checked there are no extra spaces or special characters in your input phenotype file? The error indicates that there is a row where the number of columns is not the same as that in the header. Perhaps using `awk '{print NF}' pheno_file | sort | uniq` may help?

Cheers,
Joelle

**Comment by dvh13** [comment]
Hi Joelle,

No to test scripts, but have run regenie lots. Was just pointing out it is a bit sensitive to absolutely perfect input phenotype files. I sorted this one and it runs fine.

Close the ticket.

thanks, david



On 1 Jul 2022, at 17:56, Joelle Mbatchou ***@***.******@***.***>> wrote:



Hi David,

Have you tried running the test script in the source directory? i.e. bash test/test_bash.sh
It runs a few test commands, some of which use the phenotype file in example/phenotype_bin.txt which is space-separated.

Have you checked there are no extra spaces or special characters in your input phenotype file? The error indicates that there is a row where the number of columns is not the same as that in the header. Perhaps using awk '{print NF}' pheno_file | sort | uniq may help?

Cheers,
Joelle
