### ISSUE TITLE
Informtion on allele frequency and N for binary traits

### ISSUE THREAD

**Issue by Mathias0077** [rgcgithub/regenie#317]
Dear Joëlle,

would it be possible in analyses of binary outcomes to report the allele frequency A1FREQ and the N separately for cases and controls?

So f. e. reporting A1FREQ_CASE, A1FREQ_CTRL, N_CASE and N_CTRL?

Best,
Mathias

**Comment by joellembatchou** [comment]
Hi Mathias,

Please check #227 for the `--htp` option which outputs more detailed summary stats.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Hi Mathias,

These columns are now all present in sumstats file when using `--af-cc` (see [v3.2.2 release](https://github.com/rgcgithub/regenie/releases/tag/v3.2.2)).

Cheers,
Joelle
