### ISSUE TITLE
Questions about "BETA" and "SE" in the gene-based test

### ISSUE THREAD

**Issue by Jia21** [rgcgithub/regenie#319]
Hi,

I am using regenie 2.2.4 to perform gene-based test, the command of step 2 is listed below, this command should use SKAT to perform gene-based test, but there are "BETA" and "SE" columns in the output, I am wondering what's the meaning of "BETA" and "SE" if it uses SKAT. 
regenie --step 2 \
                --pgen chr7_rare \
                --sample chr7_rare.sample \
                --phenoFile srcR_phe.txt  \
                --bsize 500 \
                --threads 20 \
                --anno-file chr7_anno.file \
                --set-list chr7_set.file \
                --mask-def chr7_mask.file \
                --approx \
                --write-mask-snplist \
                --write-mask \
                --pred fit_phe_genotyped_chrs_out_pred.list \
                --out final_phe_chr7

The second question is whether regenie can perform the classic burden test accounting for the total alternative allele counts within a specific region in the gene-based test. 

Thank you so much! 

Cheers,
Elaine

**Comment by joellembatchou** [comment]
Hi Elaine,

SKAT/SKATO tests are only available in v3.0+ (I recommend using latest available version); to specify those, use for example `--vc-tests skat` (see [documentation](https://rgcgithub.github.io/regenie/options/#skatacat-tests) for more details). These will have `NA` for BETA/SE columns.

If you want the [sum of ALT alleles as the rule to build masks,](https://rgcgithub.github.io/regenie/options/#options_1) you can use `--build-mask sum` (note this does not work with `--write-mask` which requires the mask taking values in {0,1,2}).

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Hi Elaine,

Which values are you referring to in your first question? 

The default rule when building burden mask is to take the maximum number of ALT alleles across sites. If you want to take the total number of ALT alleles, use `--build-mask sum`. This figure [here](https://rgcgithub.github.io/regenie/options/#options_1) shows the current set of aggregation rules available for the burden test. (Note this does not apply to the SKAT/ACAT test which combine single variant summary stats).

Cheers,
Joelle

**Comment by ggstatgen** [comment]
> Hi Elaine,
> 
> SKAT/SKATO tests are only available in v3.0+ (I recommend using latest available version); to specify those, use for example `--vc-tests skat` (see [documentation](https://rgcgithub.github.io/regenie/options/#skatacat-tests) for more details). These will have `NA` for BETA/SE columns.
> 
> If you want the [sum of ALT alleles as the rule to build masks,](https://rgcgithub.github.io/regenie/options/#options_1) you can use `--build-mask sum` (note this does not work with `--write-mask` which requires the mask taking values in {0,1,2}).
> 
> Cheers, Joelle

Hi Joelle. Apologies for reopening an old thread. I've just completed a --vc-tests skat run on multiple quantitative phenotypes and I'm getting NAs in the summary stats. What is the reason for this? Also, it seems that the results include standard LR model -based results as well as skat? Is there some decision taken at run time for when a skat test can actually be performed and, if not, does regenie scale down to a standard burden test, perhaps? Many thanks!

**Comment by joellembatchou** [comment]
Hi,

For the gene-based test run, REGENIE will run SKAT/ACATV as well as build the mask rollup aggregating the all variants included in the set and test the resulting burden mask for association (corresponding to LR test in summary stats). If you run both SKAT and ACATV (i.e. `--vc-tests skat,acatv`, do you get "NA" also for ACATV? SKAT can fail if the p-value calculation (which relies on numerical integration/SPA) fails.

**Comment by ggstatgen** [comment]
Hi Joelle thanks. I will try running -acatv and let you know.

For pure `--vc-tests skat` tests, though, I'm not clear on whether those 'NA' are expected behaviour, or the results of a failure. 

I do get p-values, but (for quantitative phenotype tests)  I get  something as follows

`alanine_aminotransferase_log	A3GALT2.Mask1.0.1	1	33306776	ref	Mask1.0.1	alanine_aminotransferase_log	TEST_NAME	ADD-WGR-LR	-0.00732777	-0.0854309	0.0707754	0.854102	0.000152952	382473	382357	115	1	NA	NA	NA	NA	REGENIE_SE=0.039849;MAC=117.000000`

So NAs for `Effect, LCI_Effect, UCI_Effect, AAF, Num cases, CASES_REF, CASES_HET, CASES_ALT`

Is this expected behaviour for this test?

**Comment by joellembatchou** [comment]
In the output you included, the p-value is 0.947019 (the rest of the columns being NA is fine as the SKAT test is a joint test on multiple variants [so there will not be genotype counts/AAF).
