### ISSUE TITLE
Difference in association results of regenie with/without dosoges 

### ISSUE THREAD

**Issue by SHIYX42** [rgcgithub/regenie#320]
Hi developers,

I converted my imputed VCF data from the Topmed Imputation Server to the plink2 pgen format. I took help from issue at [#113](https://github.com/rgcgithub/regenie/issues/113). 

I create bgen file with two methods then convert into pgen file as:
`plink2 --vcf chr1.dose.vcf.gz -export bgen-1.2 'bits=8' --out chr1_forPGEN`

`plink2 --vcf chr1.dose.vcf.gz 'dosage=DS' --export bgen-1.2 'bits=8' --out chr1_doseforPGEN`

Then convert into pgen file:
`plink2 --bgen chr1_forPGEN.bgen ref-last 
--sample chr1_checkforPGEN.sample --make-pgen erase-phase --out chr1_hg19`

`plink2 --bgen chr1_doseforPGEN.bgen ref-last 
--sample chr1_checkforPGEN.sample --make-pgen erase-phase --out chr1_hg19.dose`

I finished my association analysis through regenie v3.1.3 successfully, but I found that the results without dosages in pgen files have a big difference compared to Allele1freq info from the *.pvar file. Besides, the -log10P and CHISQ also have a huge difference between *.regenie and *.dose.regenie. 

e.g.
**rs28769581     A1FREQ 0.82594     ——*.pvar**
**rs28769581     A1FREQ 0.90211     ——*.regenie**

**rs2736100      -log10P 18.2129    CHISQ 79.02760——*.regenie**
**rs2736100      -log10P 0.93971    CHISQ 2.48562——*.dose.regenie**

Here I've pasted the main codes I used below:
`regenie --step 1 --bed Allautosome.genotyped.hg19.final --phenoFile Allautosome_phenotyped_forregenie.txt --covarFile PCA10final.eigenvec --bt --threads 18 --bsize 1000 --lowmem --out Allautosome.genotyped.hg19.step1`

`for i in `seq 22`;
do regenie 
     --step 2 
     --pgen chr${i}.dose.filtered.hg19.final 
     --phenoFile Allautosome_phenotyped_forregenie.txt 
     --covarFile EASPCA10final.eigenvec 
     --threads 18 
     --bt 
     --firth --approx --pThresh 0.01 
     --pred Allautosome.genotyped.hg19.step1_pred.list 
     --bsize 1000 
     --out chr${i}.pgenhg19.step2;
done`

Based on my phenotype, I prefer to use *.regenie (association without dosage) for subsequent analysis. However, I'm confused about the results difference situation. 

Additionally, the sample size of my dataset is 8586 (4853 cases：3733 controls), do you think the -pThresh 0.01 is reliable for my dataset. I also want to calculate OR value from beta and SE, Do their mathematic relations look like this: (log OR = β / (μ * (1 - μ)), where μ = case fraction)? 

Could you give me your advice, please? 

Thanks!
Yixin

**Comment by joellembatchou** [comment]
Hi Yixin,

For your example with variant rs2736100, can you check difference between hard-called and dosage version? Are you applying MAC/INFO filters?

BETA/SE is estimated from a logistic model so you can take exp(BETA) to get the OR.

Cheers,
Joelle

**Comment by SHIYX42** [comment]
Hi Joelle,

Thanks for your reply! 

I've checked rs2736100 in my vcf file, actually rs2736100 is a directly genotyped snp, but after imputation through TOPMed imputation server, it was marked as 'TYPED', which means this marker was genotyped and imputed. I have checked and found all the hard-call genotypes were matched with dosage information, but some dosages directly showed 0.000, 1.000 or 2.000.
Does this 'TYPED' marker cause the huge differences between the two association results?

For MAC/INFO filters, I didn't apply '--minMAC' and '--minINFO' in my commands, and I had already filtered the SNPs with INFO threshold 0.3 and MAF threshold 0.01 before the regenie association analysis.

Cheers,
Yixin

**Comment by SHIYX42** [comment]
Hi Joelle,

I also have a question about the effect of dosages in association analysis.

I found such a statement 'once loaded into a project there is no distinction between "imputed" genotype data and any other type of genotype data' from [PSEQ](https://zzz.bwh.harvard.edu/plinkseq/dosage.shtml). Does this mean that the role of dosage is reflected in the INFO column in the association analysis results? I have been guessing for the past two days. Is the difference in allele frequencies in *.pvar and *.regenie due to the missing hard-call genotype when converting to *.pgen files? Is the difference in the results of beta, se and p-value in *.regenie and *.dose.regenie also caused by this? If my thoughts are correct, could you please suggest a solution?

I sincerely look forward to your reply.

Cheers,
Yixin

**Comment by joellembatchou** [comment]
Hi Yixin, 

I meant for example with "rs2736100" comparing the actual genotypes stored in the files with/without dosages (you can do that easily using the [pgenlib](https://github.com/chrchang/plink-ng/tree/master/2.0/pgenlibr) R library for example - I found [this website](https://yosuketanigawa.com/posts/2020/09/PLINK2) useful to figure out how to install it). It is quite strange that you get such large difference in -log10P (79 vs 2) when the variant was directly typed.

For your other question, I don't quite know what PLINK2 does when you don't specify 'dosage=DS' at the imputed sites as the documentation indicates that without that flag dosages would not be imported. Either way, since you do have imputed data present, I would recommend using this flag to properly retain the dosages when converting file formats.

Cheers,
Joelle

**Comment by SHIYX42** [comment]
Hi Joelle,

Thanks for your reply! I checked the actual genotypes of "rs2736100"  stored in the files with/without dosages. I found that the actual genotypes stored in the file without dosages are consistent with the original vcf, but are pretty different from the file with dosages. 403 missing genotypes "./." (of 8586) appeared in the file with dosages. Is the huge difference in -logP due to this? 

Then I found the bfiles I used for step1 which converted from directly genotyped vcf still have a big difference in actual genotypes. 2062 "1|0" genotypes in the original vcf were replaced by "0|1" in bfiles, I cannot sure if this would cause any problem. 

Besides, I found something useful in [PLINK2](https://groups.google.com/g/plink2-users/c/PdLBjHTGYwM). If you just use --vcf without either dosage=DS or dosage=HDS, a .pgen with the original GT values would be generated. That's why the actual genotypes stored in *.pgen file without dosages are consistent with the original vcf.

Cheers,
Yixin

**Comment by SHIYX42** [comment]
Hi Joelle,

I took help from this [plink2 conversation](https://groups.google.com/g/plink2-users/c/PdLBjHTGYwM), and converted one new *.pgen file of "rs2736100" from the original vcf:
`plink2 --vcf rs2736100final.vcf dosage=DS --hard-call-threshold 0.499999 --make-pgen erase-phase fill-missing-from-dosage --out rs2736100withdose.newmake`

Then I compared the actual genotypes stored in this new pgen file with the original vcf and the bfiles I used for step1. This time the actual genotypes stored in the new pgen file didn't appear the missing genotype './.', and the actual genotypes in the new pgen file and bfile are consistent.  But the new pgen file also has '0|1' replacing '1|0'. 

However, the association results of this new pgen file and bfile after step 2 are completely different. The association results shows below:

**bfile:**
**CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P EXTRA**
**5 1286516 rs2736100 C A 0.556546 8586 ADD 0.299117 0.0338273 79.0276 18.2129 NA**

**fixed pgen:** 
**CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ INFO N TEST BETA SE CHISQ LOG10P EXTRA**
**5 1286516 rs2736100 C A 0.55844 0.957779 8586 ADD -0.0536215 0.0339841 2.48958 0.940806 NA**

I'm really confused about this strange situation, any ideas for this?

Cheers,
Yixin

**Comment by SHIYX42** [comment]
Hi Joelle,

New pgen file log(only one snp rs2736100):

Log of output saved in file : rs2736100.hg19.step2.log

Options in effect:
  --step 2 \
  --pgen rs2736100withdose.newmake \
  --phenoFile Allautosome_phenotyped_forregenie.txt \
  --covarFile EASPCA10final.eigenvec \
  --threads 12 \
  --bt \
  --firth \
  --approx \
  --pThresh 0.05 \
  --pred Allautosome.genotyped.hg19.step1_pred.list \
  --bsize 1000 \
  --out rs2736100.hg19.step2

Association testing mode with fast multithreading using OpenMP
  pvar             : [rs2736100withdose.newmake.pvar] n_snps = 1
  psam             : [rs2736100withdose.newmake.psam] n_samples = 8586
  pgen             : [rs2736100withdose.newmake.pgen]
  phenotypes       : [Allautosome_phenotyped_forregenie.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 8586
  covariates       : [EASPCA10final.eigenvec] n_cov = 10
   -number of individuals with covariate data = 8586
  number of individuals used in analysis = 8586
  case-control counts for each trait:
   -- 'Y1': 4853 cases and 3733 controls
 LOCO predictions : [Allautosome.genotyped.hg19.step1_pred.list]
   --file [/asnas/fangxd_group/shiyixin/TOPMed_imputationresults/dose_genotyped_hg19/Allautosome.genotyped.hg19.step1_1.loco] for
   threads        : [12]
  block size       : [1000]
   blocks         : [1]
  approximate memory usage : 133MB
  using minimum MAC of 5 (variants with lower MAC are ignored)
  using fast Firth correction for logistic regression p-values less than 0.05

Chromosome 5 [1 blocks in total]
   --reading loco predictions for the chromosome...done (20ms)
   --fitting null logistic regression on binary phenotypes...done (17ms)
   --fitting null Firth logistic regression on binary phenotypes...done (60ms)
 block [1/1] : done (1ms)

Association results stored separately for each trait in files :
 [rs2736100.hg19.step2_Y1.regenie]

Number of tests with Firth correction : 0
Number of failed tests : (0/0)
Number of ignored tests due to low MAC : 0

Elapsed time : 3.36395s
End time: Fri Jul 29 10:33:52 2022

Here shows log of bfile:

Log of output saved in file : Allautosome.genotyped.hg19.step2.log

Options in effect:
  --step 2 \
  --bed Allautosome.genotyped.hg19.final \
  --phenoFile Allautosome_phenotyped_forregenie.txt \
  --covarFile EASPCA10final.eigenvec \
  --threads 18 \
  --bt \
  --firth \
  --approx \
  --pThresh 0.01 \
  --pred Allautosome.genotyped.hg19.step1_pred.list \
  --bsize 1000 \
  --out Allautosome.genotyped.hg19.step2

Association testing mode with fast multithreading using OpenMP
  bim              : [Allautosome.genotyped.hg19.final.bim] n_snps = 460095
  fam              : [Allautosome.genotyped.hg19.final.fam] n_samples = 8586
  bed              : [Allautosome.genotyped.hg19.final.bed]
  phenotypes       : [Allautosome_phenotyped_forregenie.txt] n_pheno = 1
   --dropping observations with missing values at any of the phenotypes
   --number of phenotyped individuals with no missing data = 8586
  covariates       : [EASPCA10final.eigenvec] n_cov = 10
   --number of individuals with covariate data = 8586
  number of individuals used in analysis = 8586
  case-control counts for each trait:
   -- 'Y1': 4853 cases and 3733 controls
  LOCO predictions : [Allautosome.genotyped.hg19.step1_pred.list]
   --file [/asnas/fangxd_group/shiyixin/TOPMed_imputationresults/dose_genotyped_hg19/Allautosome.genotyped.hg19.step1_1.loco] for
   threads        : [18]
  block size       : [1000]
   blocks         : [471]
  approximate memory usage : 216MB
  using minimum MAC of 5 (variants with lower MAC are ignored)
  using fast Firth correction for logistic regression p-values less than 0.01
######## Here I ingored the blocks infomation of all chromosomes but I have made sure every block done ###########
Association results stored separately for each trait in files :
[Allautosome.genotyped.hg19.step2_Y1.regenie]

Number of tests with Firth correction : 7757
Number of failed tests : (0/7757)
Number of ignored tests due to low MAC : 0

Elapsed time : 19.2319s
End time: Wed Jul 20 15:58:11 2022

Hope this information is helpful to you!

**Comment by joellembatchou** [comment]
Hi,

" But the new pgen file also has '0|1' replacing '1|0'. " -> should the new PGEN file not have phasing information (since you specified `erase-phase`?
Just to be clear, did you check the actual dosages in `rs2736100withdose.newmake.pgen` vs the genotypes in `Allautosome.genotyped.hg19.final.bed` for SNP rs2736100? (e.g. making a scatterplot of the values)

**Comment by SHIYX42** [comment]
Hi Joelle,

So sorry for the misunderstanding due to my mistake, the fact is that the new pgen file also has '0/1' replacing all '1|0' in the original vcf file. 

I have checked the actual dosages in `rs2736100withdose.newmake.pgen` vs the genotypes in `Allautosome.genotyped.hg19.final.bed` for SNP rs2736100, I didn't find any differences. All actual dosages were matched to the genotypes.
