### ISSUE TITLE
Try to use cmake to generate makefile but I got this issue.

### ISSUE THREAD

**Issue by linnabrown** [rgcgithub/regenie#321]
cmake ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:38 (message):
  Must specify path to BGEN library in 'BGEN_PATH'

**Comment by joellembatchou** [comment]
Hi,

As the error states, you need to specify the path to the BGEN library, e.g. from the Regenie source directory
```
BGEN_PATH=<bgen_lib_path> cmake -S . -B build/
make -C build/
```
The REGENIE binary will be located in the build subfolder.

**Comment by linnabrown** [comment]
Thanks! I would like to know what is BGEN_PATH?

**Comment by joellembatchou** [comment]
Please check the [install page](https://rgcgithub.github.io/regenie/install/) for more info.

**Comment by linnabrown** [comment]
Got you. Thanks a lot!
