### ISSUE TITLE
List of variants with respective contributions

### ISSUE THREAD

**Issue by isabelrem** [rgcgithub/regenie#323]
Dear Joelle,

Is there a way with REGENIE to get a list of variants with their respective contributions into the cumulative association analysis? I would like to perform conditional analysis but am not sure if REGENIE has a built in way to assess which variants contribute the most to a gene-based result.

I hope that makes sense?

Thanks in advance!

**Comment by joellembatchou** [comment]
Hi,

You could look into the [LOVO scheme](https://rgcgithub.github.io/regenie/options/#lovolodo-schemes) (for leave-one-variant-out) which aims to identify variants contributing most to a gene-based test (i.e. once they are excluded you would have a large increase in the gene test p-value).

Cheers,
Joelle
