### ISSUE TITLE
--ref-first

### ISSUE THREAD

**Issue by isabelrem** [rgcgithub/regenie#324]
Dear Joelle,

The documentation says that --ref-first is used to 'Specify to use the first allele as the reference allele for BGEN or PLINK bed/bim/fam file input [default is to use the last allele as the reference]'.

My question is, how does REGENIE determine the first and last allele? Does this refer to the order of the alleles in the variant identifier (e.g., 10:110644356:G:A), or does it refer to the order of the two variant columns in the .bim file?

10      10:46961:G:A    0       46961   **A       G**
10      10:46981:G:A    0       46981   **A       G**
10      10:46982:T:C    0       46982   **C       T**
10      10:46983:D:14   0       46983   **A       ATAGTGACACATGGC**
10      10:46995:G:A    0       46995   **A       G**
10      10:47001:I:12   0       47001   **CAGAACACAGTAA   C**
10      10:47001:C:G    0       47001   **G       C**
10      10:47006:C:T    0       47006   **T       C**
10      10:47007:A:G    0       47007   **G       A**
10      10:47009:A:G    0       47009   **G       A**

Many thanks!

**Comment by joellembatchou** [comment]
Hi,

Yes, this refers to the order of alleles in the last 2 columns of the BIM file.

Cheers,
Joelle

**Comment by isabelrem** [comment]
Thank you !

**Comment by uelandte** [comment]
Hello!

Hoping to follow up with a clarifying question on this topic. How does --ref-first interpret plink2 pgen/pvar/psam files?

The documentation mentions only bed/bim/fam files and bgen files, in that it will "Specify to use the first allele as the reference allele for BGEN or PLINK bed/bim/fam file input [default is to use the last allele as the reference]"

The default .pvar column order for the first four columns is POS   ID   REF   ALT  

Should --ref-first be applied to all regenie runs that take pgen/pvar/psam files as inputs? In other words, will it function similarly to the BIM file mentioned above where it looks at the last two columns?
