### ISSUE TITLE
Cannot use --interaction with Firth or SPA?

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#325]
Hi Joelle,

Generally, when both `spa` and `firth` are used, REGENIE by default overrides `spa` and applies `firth`, and generates a harmless warning. Although when `interaction` is used, REGENIE throws an error:
https://github.com/rgcgithub/regenie/blob/aee5b0db75224b722db6bd044c90e32324b56756/src/Regenie.cpp#L972-L973

The error implicates that `firth` cannot be used with `interaction`, though it seems the problem is not `firth` but only `spa`. So If I'm not wrong:
1- error message is not informative (only SPA)
2- Why not ignoring `spa` when `firth` is also used, just like without `interaction`?

Thanks
Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

Thanks for pointing that out, it was a typo in the error message. Firth can be used in interaction test but SPA cannot. In the next release, `--spa` will be ignored when `--firth` is also specified for interaction testing.

Cheers,
Joelle
