### ISSUE TITLE
How to create masks with multiple annotations included?

### ISSUE THREAD

**Issue by isabelrem** [rgcgithub/regenie#326]
Dear Joelle,

I'm trying to make a mask file with one mask for PTV variants, one mask for missense variants, and one mask that includes both. My mask file is currently set out like this:

Mask1 missense
Mask2 PTV
Mask3 missense,PTV

When I run step 2 of regenie, I get this message:

WARNING: Detected 1 masks with unknown annotations.

As far as I can tell my mask file mirrors the mask file example on the documentation page. Is there some formatting step I've missed?

Thanks!

Isabel

**Comment by joellembatchou** [comment]
Hi Isabel,

Are both annotations present in the 3rd column of the annotation file (ie what you pass to `--anno-file`?

**Comment by johsr** [comment]
Hi everyone,
If I may barge in: I had the same problem and then realized that some masks where not correctly detected because I had CRLF line breaks (Windows) in my file. As soon as I changed to LF line breaks (Unix) the problem disappeared. The same holds true for the set list file.
