### ISSUE TITLE
No results for Beta or SE for SKATO tests

### ISSUE THREAD

**Issue by isabelrem** [rgcgithub/regenie#327]
Hiya,

In my SKATO test output, the Beta and SE columns are always blank. Is this intended or has something gone wrong?

Thanks!

Isabel

**Comment by joellembatchou** [comment]
Hi Isabel,

Yes, SKATO is a joint test on multiple single variants and does not output effect size estimate. You can read more on the gene-based tests in the [documentation](https://rgcgithub.github.io/regenie/overview/#variance-component-tests).

Cheers,
Joelle
