### ISSUE TITLE
Questions about base level in the  Interaction testing

### ISSUE THREAD

**Issue by WZo0o** [rgcgithub/regenie#330]
Hello，
I noticed that in your official document said that If the interacting variable is categorical, you will have separate lines for each level aside from the baseline level.

My interacting variable named TD only have 3 level including 0,1, and 2 ,then I specified 0 as the baseline to do the interaction testing. But I still get a line including ADD-INT_SNPxTD, is this line mean baseline level ?

In addition, I should have 2 covariates including TD and PS_SCORE  in my analysis, but I only get a line named ADD-CONDTL.

Could you help me to solve these questions?

This is my script
regenie  --step 2 \
              --interaction TD[0]  \
              --covarColList TD,PS_SCORE  \
              --catCovarList TD  \
              --pgen UKB_auto_merge  \
              --keep qc_pass.id  \
              --extract qc_pass.snplist  \
              --ref-first  --phenoFile phe.txt  \
              --covarFile cov.txt  \
              --bt  --firth --approx --pThresh 0.01  \
              --pred ukb_step1_BT_pred.list  \
              --bsize 400  --threads 8  --chr 21  --out ukb_step2_BT_chr21

This is my outcome
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ INFO N TEST BETA SE CHISQ LOG10P EXTRA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-CONDTL -0.434759 0.23297 3.48255 1.20748 NA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-INT_SNP -0.494672 0.310922 2.53124 0.952286 NA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-INT_SNPxTD=2 -0.501612 0.860496 0.339812 0.25186 NA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-INT_SNPxTD=1 -12.9373 52.3614 0.0610474 0.0942861 NA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-INT_SNPxTD NA NA 0.400329 0.0869302 NA
21 9413985 21:9413985_A_T A T 0.00540667 0.775698 323697 ADD-INT_3DF NA NA 4.13859 0.607509 NA

**Comment by joellembatchou** [comment]
Hi,

The `ADD-INT_SNPxTD` correspond to a joint test for the two interaction parameters (ie `ADD-INT_SNPxTD=1` = `ADD-INT_SNPxTD=2` = 0). For the covariates effects, these are not included in the sumstats file.

Cheers,
Joelle

**Comment by WZo0o** [comment]
Hi，

Thanks for your reply

Sincerely，
WangZheng
