### ISSUE TITLE
--htp flag not working with --build-mask sum

### ISSUE THREAD

**Issue by TGDrivas** [rgcgithub/regenie#336]
Hello,

We noticed a discrepancy in regenie's behavior when using the --htp flag. When conducting gene-based testing and supplying 'comphet' to --build-mask, the output of step 2 is as expected for --htp. However, when changing only 'comphet' to 'sum' the output of step 2 appears to ignore the --htp flag and reverts to the standard output format. Is there any possibility that this could be looked into? Thank you!

**Comment by joellembatchou** [comment]
Hi,

Yes the `--htp` option is not compatible with `--build-mask sum` as there will not be "genotype counts" available (which is the key info added when using `--htp`). 

Cheers,
Joelle
