### ISSUE TITLE
Extreme inflation of SKATO p-values with SPA correction in v3.2.1

### ISSUE THREAD

**Issue by discs89** [rgcgithub/regenie#341]
Hello,

We are using regenie v3.2.1 to run a SKATO gene-based analysis with rare variant data (max AAF < 0.01) on a binary trait. The total sample size is > 300,000 individuals and the case-control ratio of the phenotype is (slightly) unbalanced – around 1 case per 9 controls – and we therefore use SPA correction. Furthermore, we do not collapse ultra-rare variants into a burden mask. We found strong inflation of gene p-values for this analysis and then ran the same analysis with Firth correction.

Settings for the SPA-corrected analysis (for chromosome 5 in this example):
```
--step 2 \
--bed genetic_data_c5_filtered \
--pred regenie_step1_pred.list \
--covarFile covar_regenie.txt \
--catCovarList covar1,covar2,covar3,covar4 \
--phenoFile pheno_regenie.txt \
--phenoCol pheno1 \
--bt \
--spa \
--vc-tests skato \
--vc-maxAAF 0.01 \
--vc-MACthr 0 \
--minMAC 1 \
--anno-file c5_annotation_file.txt \
--set-list c5_set_list.txt \
--mask-def mask_definitions.txt \
--out skato_c5
```

Settings for the same analysis with Firth correction:
```
--step 2 \
--bed genetic_data_c5_filtered \
--pred regenie_step1_pred.list \
--covarFile covar_regenie.txt \
--catCovarList covar1,covar2,covar3,covar4 \
--phenoFile pheno_regenie.txt \
--phenoCol pheno1 \
--bt \
--firth \
--approx \
--vc-tests skato \
--vc-maxAAF 0.01 \
--vc-MACthr 0 \
--minMAC 1 \
--anno-file c5_annotation_file.txt \
--set-list c5_set_list.txt \
--mask-def mask_definitions.txt \
--out skato_c5
```

Comparing the QQ plots (gene p-values derived from the ADD-SKATO model) for both analyses shows much stronger inflation of p-values in the SPA-corrected analysis compared to the Firth-corrected analysis. The SPA-corrected results look extremely inflated. These plots summarize p-values for all chromosomes:

![qq_comparison_spa_firth](https://user-images.githubusercontent.com/114227076/192470597-37f58f39-e157-48f7-8792-a105f834d8a2.png)

We further looked into this for chromosome 5, and additionally ran the analysis without any p-value correction. We used the following settings:
 ```
 --step 2 \
  --bed genetic_data_c5_filtered \
  --pred regenie_step1_pred.list \
  --covarFile covar_regenie.txt \
  --catCovarList covar1,covar2,covar3,covar4 \
  --phenoFile pheno_regenie.txt \
  --phenoCol pheno1 \
  --bt \
  --pThresh 0.0 \
  --vc-tests skato \
  --vc-maxAAF 0.01 \
  --vc-MACthr 0 \
  --minMAC 1 \
  --anno-file c5_annotation_file.txt \
  --set-list c5_set_list.txt \
  --mask-def mask_definitions.txt \
  --out skato_c5
```

Comparison of the association p-values between the three correction methods looks as follows, with two top-associated genes highlighted:

![p_comparison_correction_regenie](https://user-images.githubusercontent.com/114227076/192470828-187267a5-9840-4456-a1b4-9c216b57c380.png)

Association p-values from the ‘Firth’ and ‘no correction’ analyses correlate poorly with the p-values from the SPA analysis. P-values in the SPA analysis are remarkably low, which seems unexpected. The correlation between the ‘Firth’ and ‘no correction’ analyses is much better and reflects a subtle attenuation of test statistics when Firth correction is used compared to no correction.

We also compared SPA-corrected gene association p-values (for chr 5) between recent regenie versions:

![p_comparison_versions_regenie](https://user-images.githubusercontent.com/114227076/192470909-cb89122d-5aaf-4f36-a16f-14aa1b71f26e.png)

There have been various bug fixes regarding SPA correction in the past versions, but the increased inflation of test statistics in the most recent versions is remarkable. Is this due to fixed issues, or should this kind of increase in signal not be expected from recent bug fixes?

Thank you.

**Comment by joellembatchou** [comment]
Hi,

Thank you for the detailed overview of your analyses. Did you run the same steps above using the default MAC threshold of 10 for ultra-rare variants? (I am wondering if what you see is due to SPA being used with these ultra-rare variants included as single variants).

**Comment by discs89** [comment]
Hi,
Thank you for this suggestion. I repeated (in regenie v3.2.1) the SPA-corrected analysis with the same settings as above, except this time with `--vc-MACthr=10` (the default). The p-values in the SPA corrected analysis now look much more realistic.

![qq_comparison_spa_burdenmask](https://user-images.githubusercontent.com/114227076/192784391-ba6c4162-2a59-449f-89d4-9a58af1b7992.png)

I also applied this `--vc-MACthr=10` setting to the Firth-corrected and uncorrected analyses for chromosome 5, and then again compared the association p-values between the correction methods:

![p_comparison_correction_burdenmask_regenie](https://user-images.githubusercontent.com/114227076/192784472-e836b395-3fa8-49e3-8a43-11e8444586ec.png)

The correlation between p-values from the Firth-corrected or uncorrected analysis vs. the SPA-corrected analysis also looks much better now (although not as good as between the uncorrected and Firth-corrected analysis).

The reason why we do not want to collapse ultra-rare variants into a burden mask in our analysis is that we expect variants within genes can have opposing effect directions for our trait of interest (this is also the reason why we chose a SKATO analysis). As far as I understand, collapsing (ultra-rare) variants into a burden mask could (partly) level out such opposing effects.

Would you advise to use Firth correction instead of SPA if we do not want collapse ultra-rare variants into a burden mask using `--vc-MACthr`? Or do you have any other recommendations?

**Comment by joellembatchou** [comment]
Yes, if you plan to include ultra-rare variants as single variants then use Firth correction with binary traits.

Cheers,
Joelle
