### ISSUE TITLE
Methods to address relatedness

### ISSUE THREAD

**Issue by wanmengyao** [rgcgithub/regenie#343]
How does REGENIE acount for relatedness? The cohort for analysis has related individuals, but I don't want to exclude anyone for the originally small size. Do I need to add any code to address the related-ness, and what is the statistical mechanism?

**Comment by joellembatchou** [comment]
Hi, 

REGENIE uses a whole-genome regression framework to capture population structure, relatedness and polygenicity; you can refer to the [documentation](https://rgcgithub.github.io/regenie/overview/#overview) for a brief overview or to the [paper](https://doi.org/10.1038/s41588-021-00870-7) for more detailed information.

Cheers,
Joelle

**Comment by wanmengyao** [comment]
Thanks for your help!


| |
one_my0717
|
|
***@***.***
|
---- Replied Message ----
| From | Joelle ***@***.***> |
| Date | 10/12/2022 01:57 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [rgcgithub/regenie] Methods to address relatedness (Issue #343) |

Closed #343 as completed.
