### ISSUE TITLE
Does `--sample` correspond to the *optional* `Sample identifier block` in BGEN and is providing it always optional (even if `Sample identifier block` is missing from BGEN)?

### ISSUE THREAD

**Issue by etrh** [rgcgithub/regenie#344]
Hi @joellembatchou 

Sorry if this is an obvious question, but I've looked everywhere and haven't been able to find a conclusive answer.

I'm trying to understand the role of `--sample` and its structure and whether there are any scenarios where `regenie` might fail without providing a `--sample` file.

Does `--sample` actually refer to the *optional* `Sample identifier block` in `BGEN` files? 

That is to say, would `regenie` fail to run if the BGEN file in question has no `Sample identifier block` and at the same time the `--sample` argument isn't supplied to the `regenie` call?

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/29725715/194280313-dfeee97e-3e18-48c4-9cab-05793b721a5b.png">

**Comment by joellembatchou** [comment]
Hi,

The sample file specified by `--sample` accompanies a BGEN file and contains sample information (see file in `example/example.sample`). 

If the BGEN file already contains sample information then you don't need to specify the `--sample` file. If the BGEN file does not have your sample information, then you should get an error as the default sample IDs in the genotype data will not match those from the phenotype data. (Note that if the BGEN already has sample information, you can still specify a `--sample` file)

Cheers,
Joelle

**Comment by joellembatchou** [comment]
I believe [QCTOOL](https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/alphabetical_options.html) can be used to extract the sample IDs from a BGEN file (e.g. `qctool -g example.bgen -os example.sample`).

Cheers,
Joelle
