### ISSUE TITLE
Having trouble installing Regenie on Mac

### ISSUE THREAD

**Issue by shishirdube** [rgcgithub/regenie#347]
Hi,

I've tried installing via conda but it's not working.  Can someone please help?

Best,
S

**Comment by joellembatchou** [comment]
Hi,

What error message are you getting? (are you creating a new conda environment?)

Note that you can directly download pre-compiled binaries [here](https://github.com/rgcgithub/regenie/releases) or use the docker image [here](https://github.com/rgcgithub/regenie/pkgs/container/regenie%2Fregenie).

Cheers,
Joelle
