### ISSUE TITLE
spa (saddlepoint approximation) option in analysis 

### ISSUE THREAD

**Issue by hcso** [rgcgithub/regenie#35]
Thanks for providing such a wonderful program for large-scale GWAS. 
I just have a simple question. May I know if the spa option is implemented also for non-binary outcomes? 
Thank you very much.

**Comment by joellembatchou** [comment]
Hi,

Thank you for your interest in Regenie. The SPA option is only implemented for binary traits (i.e. when option `--bt` is used). [The reason why we implemented SPA for this case was to correct for inflation in the score test statistic when unbalanced binary traits are tested for association with rare variants.]

**Comment by hcso** [comment]
Thank you very much!
