### ISSUE TITLE
build-mask sum and --af-cc are not consistent

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#350]
Hi Joelle,

First, thanks for the new, yet faster version!
I've seen in #336 that since there is no allele counts with `sum` rule, `--htp` flag cannot be used ( `if(!take_max && !take_comphet) params.htp_out = false; // due to genocounts with sum rule`). But, how does REGENIE calculate `A1FREQ`, `A1FREQ_CASES`, and `A1FREQ_CONTROLS` with `sum` rule? When comparing with `max`, one would expect to see a larger `A1FREQ` for `sum`, but that's not the case. 
As an example, this is the output for `sum` (v3.2.1):

CHROM | GENPOS | ID | ALLELE0 | ALLELE1 | A1FREQ | A1FREQ_CASES | A1FREQ_CONTROLS | N | TEST | BETA | SE | CHISQ | LOG10P | EXTRA
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
2 | 1 | PLB1_ENSG00000163803.m1.0.01 | ref | m1.0.01 | 4.34963e-05 | 4.14603e-05 | 4.3512e-05 | 350362 | ADD | -0.0341793 | 0.0706051 | 0.234345 | 0.201818 | DF=1

And this is the same run with `max`:

CHROM | GENPOS | ID | ALLELE0 | ALLELE1 | A1FREQ | A1FREQ_CASES | A1FREQ_CONTROLS | N | TEST | BETA | SE | CHISQ | LOG10P | EXTRA
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
2 | 1 | PLB1_ENSG00000163803.m1.0.01 | ref | m1.0.01 | 0.0381463 | 0.0368362 | 0.0381563 | 350362 | ADD | -0.0221139 | 0.0736938 | 0.0900466 | 0.11684 | DF=1

Is it because REGENIE takes the average for `sum` rule?
```
  if(!take_max && !take_comphet) {
    snp_data->af1 /= nsites(isnp); // take average AAF across sites for sum rule
    snp_data->af /= nsites(isnp); 
    if(params->af_cc){
      snp_data->af_case /= nsites(isnp);;
      snp_data->af_control /= nsites(isnp);;
    }
  }
```
If that's the reason, is there any way to get minor allele count (MAC) for case/control?

Thanks!
Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

Yes when taking the sum rule, REGENIE will report the average AAF across the sites included in the mask. There is no MAC  reported with sum rule since there is no meaning to it  for the mask built with the sum rule.

**Comment by Ojami** [comment]
Thanks Joelle, makes sense.
