### ISSUE TITLE
How much time does it take to run burden test ?

### ISSUE THREAD

**Issue by xuqian007** [rgcgithub/regenie#351]
Hello !
I'm trying to perform a burden based analysis for a binary trait using regenie v3.2.1. And the sample size of the data is about 110,000, and the number of genes is more than 30,000, but I run about 4 days using regenie and still did not get the complete result. I want to know if there is any problem with my code. My input is as follows:
regenie \
--step 2 \
--bed burden \
--covarFile cov.txt \
--phenoFile phe.txt \
--bt \
--anno-file annotations \
--set-list setlist \
--mask-def mask \
--aaf-bins 0.1,0.05 \
--build-mask sum \
--write-mask \
--write-mask-snplist \
--bsize 200 \
--minMAC 2 \
--firth --approx \
--pred step1_out_pred.list \
--vc-tests skat,skato,acatv,acato \
--debug \
--out outcome_out_firth
In addition, why is the number of output so much more than the number of genes, which is about 6 million.
Any help would be greatly appreciated, thanks!

**Comment by joellembatchou** [comment]
Hi,

Could you include the REGENIE log file for your run? (the header portion before it starts going over each gene). As there are multiple burden masks that will be generated for each gene based on the mask definitions and AAF cutoffs used, as well as multiple gene-based tests (SKAT, SKATO, ACATV, ACATO), this will result in multiple sumstats line corresponding to each gene.

**Comment by xuqian007** [comment]
Hi!
Thank you for your prompt reply.And my REGENIE log file and input files as follows:
|=============================|
              |      REGENIE v3.2.1.gz      |
              |=============================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : exome_out_firth.log

Options in effect:
  --step 2 \
  --bed exome_buden \
  --covarFile /home/nijingjing/external_data/SO/cov.txt \
  --phenoFile /home/nijingjing/external_data/SO/phe.txt \
  --bt \
  --anno-file exome.annotations \
  --set-list exome.setlist \
  --mask-def exome.mask \
  --aaf-bins 0.1,0.05 \
  --build-mask sum \
  --write-mask-snplist \
  --bsize 200 \
  --minMAC 2 \
  --firth \
  --approx \
  --pred exome_step1_out_pred.list \
  --vc-tests skat,skato,acatv,acato \
  --debug \
  --out exome_out_firth

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [exome_buden.bim] n_snps = 1953046
 * fam              : [exome_buden.fam] n_samples = 117217
 * bed              : [exome_buden.bed]
 * phenotypes       : [phe.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 117217
 * covariates       : [cov.txt] n_cov = 14
   -number of individuals with covariate data = 117217
 * number of individuals used in analysis = 117217
 * case-control counts for each trait:
   - 'SO': 6572 cases and 110645 controls
 * LOCO predictions : [exome_step1_out_pred.list]
   -file [exome_step1_out_1.loco] for phenotype 'SO'

* annotations      : [exome.annotations] 
   +number of annotations categories = 3
 * masks            : [exome.mask] n_masks = 17596
WARNING: Detected 16166 masks with unknown annotations.
 * aaf cutoffs      : [ 3 : 0.05 0.1 1 ] + singletons
 * set file         : [exome.setlist] n_sets = 32187
WARNING: Detected 32187 sets with variants not in genetic data or annotation files.
WARNING: Detected 1575 sets with only unknown variants (these are ignored).
 * # threads        : [23]
 * # tested sets    : [32187]
 * max block size   : [200]
 * rule used to build masks : sum
 * computing gene-based tests for each set of variants included in a mask (rho=[0,0.01,0.04,0.09,0.16,0.25,0.5,1])
  -variants with MAC <= 10 are collapsed into a mask
  -weights are obtained from Beta(MAF,1,25)
  -list of gene-based tests run: ACATO,ACATV,SKAT,SKATO
 * approximate memory usage : 2GB
 * writing list of variants for each mask in file [exome_out_firth_masks.snplist]
 * using minimum MAC of 2 (masks with lower MAC are ignored)
 * using fast Firth correction for logistic regression p-values less than 0.05

Chromosome 1 [3513 sets in total]
   -reading loco predictions for the chromosome...done (95ms) 
   -fitting null logistic regression on binary phenotypes...done (133ms) 
   -fitting null Firth logistic regression on binary phenotypes...done (244ms) 
 set [1/32187] : TMEM69 - 28 variants...1 chunks
     -reading in genotypes, computing gene-based tests and building masks...(1)memory usage=945MB...(2)memory usage=84351MB...WARNING: 65300/70384 masks fail MAC filter and will be skipped...(3)memory usage=88938MB...(4)memory usage=76346MB...done (597365ms) 
     -computing association tests...done (811ms) 
 set [2/32187] : TMEM61 - 36 variants...1 chunks
--anno-file annotations file:
1:45693792:T:C  TMEM69  missense
1:45693861:A:T  TMEM69  missense
1:45693867:T:C  TMEM69  missense
1:45693462:D:2  TMEM69  LOF
----set-list setlist file:
TMEM69  1       45693486        1:45691075:C:T,1:45691076:G:A,1:45691085:A:C,1:45691094:C:T,1:45691096:C:G,1:45691099:G:C,1:45693253:T:C,1:45693274:T:C,1:45693309:C:T,1:45693360:T:G,1:45693367:G:A,1:45693408:C:A,1:45693438:A:G,1:45693441:C:G,1:45693486:G:A,1:45693490:C:T,1:45693498:C:A,1:45693498:C:G,1:45693501:G:T,1:45693519:A:G,1:45693533:A:G,1:45693585:G:C,1:45693592:G:C,1:45693636:T:C,1:45693723:A:G,1:45693740:G:A,1:45693792:T:C,1:45693861:A:T,1:45693867:T:C
TMEM69  1       45693665        1:45693462:D:2,1:45693570:D:2,1:45693800:D:2,1:45693903:T:C,Affx-89008192
--mask-def mask file:
TMEM69  missense,LOF

Also, if I only want to perform the analysis based on rare variants, can I set the AAF cutoff value to 0.01 or lower?  And how to set the parameters to make the run time shorter
Thank you very much.

**Comment by joellembatchou** [comment]
Hi,

The log indicates there are `n_masks = 17596` masks specified. From the snippet of the mask file, it seems that you are specifying a separate mask for each gene. The idea of the mask definition file is that you specify groups of annotation to aggregate variants across. For example, one mask definition file to analyze LoF variants as well as LoF+missense variants would be:
```
LoFs  LOF
LoFs_missense  missense,LOF
```

So for each gene, REGENIE will generate results based on these 2 mask categories. Let me know if that addresses your issue (or if I misunderstood your current setup).

Cheers,
Joelle

**Comment by xuqian007** [comment]
Hi,
I modified the mask file as follows : 
Mask1 LoF
Mask2 missense
Mask3 LoF,missense
but the mask file showed an error after running (WARNING: Detected 3 masks with only unknown annotations (these are ignored). ERROR: no masks are left to be included in the analysis), so I want to know how to modify the mask file.
Thank you very much for your help!

**Comment by joellembatchou** [comment]
What does your annotation file look like? Try re-running with `--check-burden-files` to see the cause of the error above.

**Comment by xuqian007** [comment]
My annotation file looks:
1:100038243:G:A MFSD14A missense
1:100038263:G:A MFSD14A missense
1:100038295:C:G MFSD14A missense
1:100049948:A:G MFSD14A missense
1:100049951:G:A MFSD14A LOF
1:100049951:G:C MFSD14A LOF
And I re-running with --check-burden-files , the masks_report.txt file looks:
## mask file: [input.mask]
## list of unknown annnotations in mask file
M1 Lof
M2 missense
M3 missense,LOF
->Detected 0 masks with unknown annotations.
->Detected 3 masks with only unknown annotations.
Thanks!

**Comment by joellembatchou** [comment]
Hi,

Please make sure whatever annotation name you use in 3rd column of the --anno-file matches with what is in the mask-file (case sensitive). For example, it seems you have both "Lof" and "LOF" which would be considered as 2 separate annotations.

Cheers,
Joelle
