### ISSUE TITLE
Step 1 qt phenotype all nan

### ISSUE THREAD

**Issue by mdelliot** [rgcgithub/regenie#352]
Hi, I'm trying to run a small test sample for a quantitative trait through step 1 and I cannot get any Output other than the one listed here.
Any ideas of what is going wrong?
Thank you

              |=============================|
              |      REGENIE v3.1.3.gz      |
              |=============================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : /Regenie/Step1New/MinMAF1pct/QT/regenieRes.log

WARNING: only variants which satisfy both extract/exclude options will be kept.
Options in effect:
  --step 1 \
  --bed /Regenie/allQCBAFilter/allQCBAFilter \
  --covarFile /Regenie/CovPheno/covariates.txt \
  --phenoFile /Regenie/CovPheno/phenotypesQT.txt \
  --qt \
  --lowmem \
  --apply-rint \
  --covarColList U1,U2,U3,U4,U5,U6,sex \
  --extract /Regenie/allQCBAFilter/snps.pruned.QT.snplist \
  --exclude /Regenie/allQCBAFilter/QT.exclude \
  --bsize 100 \
  --loocv \
  --lowmem-prefix /Regenie/Step1New/MinMAF1pct/QT/ \
  --out /Regenie/Step1New/MinMAF1pct/QT/regenieRes

Fitting null model
 * bim              : [/Regenie/allQCBAFilter/allQCBAFilter.bim] n_snps = 112312
   -keeping variants specified by --extract
   -removing variants specified by --exclude
   -number of variants remaining in the analysis = 35900
 * fam              : [/Regenie/allQCBAFilter/allQCBAFilter.fam] n_samples = 166
 * bed              : [/Regenie/allQCBAFilter/allQCBAFilter.bed]
 * phenotypes       : [/Regenie/CovPheno/phenotypesQT.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 121
 * covariates       : [Regenie/CovPheno/covariates.txt] n_cov = 7
   -number of individuals with covariate data = 166
 * number of individuals used in analysis = 121
   -applying RINT to all phenotypes
 * number of observations for each trait:
   - 'C3': 121 observations
   -residualizing and scaling phenotypes...done (0ms) 
 * # threads        : [47]
 * block size       : [100]
 * # blocks         : [373] for 35900 variants
 * # CV folds       : [121]
 * ridge data_l0    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * ridge data_l1    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * approximate memory usage : 960MB
 * writing level 0 predictions to disk
   -temporary files will have prefix [/Regenie/Step1New/MinMAF1pct/QT/_l0_Y]
   -approximate disk space needed : 3MB
 * setting memory...done

With the output of:

 Level 1 ridge...
   -on phenotype 1 (C3)...done (86ms) 

Output
------
phenotype 1 (C3) : 
  0.01  : Rsq = -nan, MSE = -nan<- min value
  0.25  : Rsq = -nan, MSE = -nan
  0.5   : Rsq = -nan, MSE = -nan
  0.75  : Rsq = -nan, MSE = -nan
  0.99  : Rsq = -nan, MSE = -nan
  * making predictions...writing LOCO predictions...done (60ms) 

and the pred.list file is all -nan

**Comment by joellembatchou** [comment]
Hi,

Have you checked the distribution of the phenotype for the 121 samples analyzed? Note that we recommend running Step 1 on a fairly large set of variants (eg 500K) to get good genome-wide coverage (here you only have 36K).
