### ISSUE TITLE
output of regenie step 1

### ISSUE THREAD

**Issue by VenZhang** [rgcgithub/regenie#353]
I combined only 1-22 chromesome  as the input of regenie step 1, but the output of step 1 has 23 lines. Is the output correct? Why is it possible when the input are 22 chromesomes?

**Comment by joellembatchou** [comment]
Hi,

The LOCO predictions for chrX are obtained from summing the polygenic predictions across autosomal chromosomes (so chrX does not need to be included in step 1 to get chrX step 1 predictions).

Cheers,
Joelle
