### ISSUE TITLE
interaction model

### ISSUE THREAD

**Issue by winkusch** [rgcgithub/regenie#354]
Dear Joelle, 

thanks for your fanatastic tool :) !

Quick question on interaction modelling that was not clear to me from the documentation: 

Do I have to add the interacting covariable to --covarColList or is it added automatically? 
If added and when running with --no-condtl, is the interacting covariable automatically being removed from --covarColList to obtain marginal effects? 

Specifically, I want to model GxBMI and at the same time fit a second model without BMI: 
E[Y] = a + b\*G + c\*BMI + d\*G\*BMI + othercov
E[Y] = a + b\*G + othercov

Which of the two calls is correct to obtain the results for these models: 
$ regenie  --covarColList BMI,othercov --interaction BMI --no-condtl
OR 
$ regenie  --covarColList othercov  --interaction BMI  --no-condtl
? 

Thank you in advance. 

Best wishes,
Thomas

**Comment by joellembatchou** [comment]
Hi Thomas,

The interacting variable is automatically added to the set of covariates so you don't need to specify it in `--covarCol/--covarColList`. 

To omit BMI from the set of covariates for the marginal GWAS (ie `E[Y] = a + b*G + othercov`), it is sufficient to use `--no-condtl` (both calls you included will give same result).

Cheers,
Joelle
