### ISSUE TITLE
ChrX

### ISSUE THREAD

**Issue by DelnazRoshandel** [rgcgithub/regenie#357]
I am wondering if you want to run Regenie on Chr X, can you run step 1 on only ChrX or you need to run it with autosomes genome-wide.

**Comment by joellembatchou** [comment]
Hi,

You can run step 1 including variants from autosomal chromosomes & REGENIE will output the required LOCO predictions needed for Step 2 with chrX.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
You want to have genome-wide coverage for the variants used in Step 1 so you should not run it on just chrX.

**Comment by DelnazRoshandel** [comment]
I already ran it on autosomes. So I am wondering if I need to repeat step 1 for autosomes + ChrX or I can just run step 1 separately for ChrX.

**Comment by joellembatchou** [comment]
No, the LOCO predictions needed for Step 2 with chrX are present in the .loco files from your autosome run (line starting with 23) so you can use that for step 2 with chrX.

Cheers,
Joelle

**Comment by DelnazRoshandel** [comment]
Thanks a lot Joelle, just to be clear you can't run step 1 for each chromosome separately, and you need to run it on all chromosomes together, right?

**Comment by joellembatchou** [comment]
No variants used in step 1 should have genome-wide coverage (you can omit chrX in step 1 and only use autosomes).
