### ISSUE TITLE
Interaction analysis results: interpretation and use of categorical variables

### ISSUE THREAD

**Issue by piganoemi** [rgcgithub/regenie#358]
Hi regenie team,

I run an interaction analysis with a categorical variables (coded 0/1). 

This is my command:
./regenie_v3/regenie_v3.2.1.gz_x86_64_Centos7_mkl \
    --step 2 \
    --bgen file.bgen \
    --ref-first \
    --sample file.sample \
    --keep file.id \
    --extract sentinels_snp \
    --phenoFile pheno_cov.txt \
    --phenoCol broad_pheno_1_5_ratio \
    --covarFile pheno_cov.txt \
    --covarColList age_at_recruitment,age2,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
    --interaction genetic_sex[0] \
    --bt \
    --gz \
    --threads 4 \
    --minMAC 10 \
    --minINFO 0.3 \
    --firth --approx --pThresh 0.01 \
    --pred broad_pheno_1_5_ratio.regenie.step1_pred.list \
    --bsize 1000 \
    --out chr4.regenie

This is what I obtained:
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ INFO N TEST BETA SE CHISQ LOG10P EXTRA
4 166495423 rs4320102 T C 0.665695 0.943805 46086 ADD-CONDTL -0.0721429 0.0196215 13.4543 3.61182 NA
4 166495423 rs4320102 T C 0.665695 0.943805 46086 ADD-INT_SNP -0.12454 0.0242991 26.0502 6.478 NA
4 166495423 rs4320102 T C 0.665695 0.943805 46086 ADD-INT_SNPxgenetic_sex 0.148952 0.0411729 13.1248 3.53548 NA
4 166495423 rs4320102 T C 0.665695 0.943805 46086 ADD-INT_2DF NA NA 26.5911 5.77419 NA

My question is: since the interaction variable is categorical, why does not show results for "ADD-INT_SNPxgenetic_sex=0" and "ADD-INT_SNPxgenetic_sex=1" ?

Best,
Noemi

**Comment by joellembatchou** [comment]
Hi Noemi,

You need to specify that the interaction variable is categorical using `--catCovarList genetic_sex`. Otherwise it will assume it is quantitative. Note that for binary variables the two give the same results.

Cheers,
Joelle

**Comment by piganoemi** [comment]
Hi Joelle,

Thanks for your answer !
Noemi
