### ISSUE TITLE
Step 1 don't output fit_bin_out_pred.list.  What's wrong with that?

### ISSUE THREAD

**Issue by danrans123** [rgcgithub/regenie#359]
**Here is the code for my step 1：**
regenie --step 1 --bed snp1519 \
  --covarFile regenie_covariates.txt \
  --phenoFile regenie_phenotype.txt \
  --remove remove.txt \
  --bsize 100 --force-step1 --out fit_bin_out

**Here is the result of my step 1：**
    CPU time :                                   24965.76 sec.
    Max Memory :                                 244547 MB
    Average Memory :                             174106.86 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   1256166 MB
    Max Processes :                              3
    Max Threads :                                30

The output (if any) follows:

Start time: Fri Nov 18 20:03:54 2022

              |=============================|
              |      REGENIE v3.2.2.gz      |
              |=============================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : fit_bin_out.log

Options in effect:
  --step 1 \
  --bed /gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/snp1519 \
  --covarFile /gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/regenie_covariates.txt \
  --phenoFile /gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/regenie_phenotype.txt \
  --remove /gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/remove.txt \
  --bsize 100 \
  --force-step1 \
  --out fit_bin_out

Fitting null model
 * bim              : [/gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/snp1519.bim] n_snps = 8080951
 * fam              : [/gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/snp1519.fam] n_samples = 1519
   -removing individuals specified by --remove
 * bed              : [/gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/snp1519.bed]
 * phenotypes       : [/gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/regenie_phenotype.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 1518
 * covariates       : [/gss2/data_sri5k20x/a_a_hjb20181119/jiangfenfen/regenie_analysis/data/regenie_covariates.txt] n_cov = 10
   -number of individuals with covariate data = 1519
 * number of individuals used in analysis = 1518
 * number of observations for each trait:
   - 'Y1': 1518 observations
   -residualizing and scaling phenotypes...done (0ms) 
 * # threads        : [27]
 * block size       : [100]
 * # blocks         : [80820] for 8080951 variants
 * # CV folds       : [5]
 * ridge data_l0    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * ridge data_l1    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * approximate memory usage : 7GB
 * setting memory...done

Chromosome 1
 block [1] : 100 snps  (1ms) 
   -residualizing and scaling genotypes...done (10ms) 
   -calc working matrices...done (1ms) 
   -calc level 0 ridge...done (45ms)
。
。
。
 block [80820] : 68 snps  (0ms) 
   -residualizing and scaling genotypes...done (0ms) 
   -calc working matrices...done (0ms) 
   -calc level 0 ridge...done (3ms) 

 Level 1 ridge...
Start time: Fri Nov 18 21:15:12 2022

**What's wrong with that?**

**Comment by joellembatchou** [comment]
Hi,

We recommend using block sizes of 1,000 in step 1 to avoid having a very large number of ridge predictors while retaining low memory usage. Also, step 1 only requires sufficient amount of variants to get good genome-wide coverage [eg directly genotyped SNPs]  so you should apply QC to your set of 8M variants to reduce it to a smaller number [eg 500K] to make step 1 less computationally burdensome.

Check the [FAQ](https://rgcgithub.github.io/regenie/faq/#step-1) or [recommendations](https://rgcgithub.github.io/regenie/recommendations/) for more details.

**Comment by danrans123** [comment]
Thank you very much for your answer, the issue has been resolved
