### ISSUE TITLE
Saving effect size estimates from Step 1

### ISSUE THREAD

**Issue by dougspeed** [rgcgithub/regenie#360]
Hi both, Ive just tried REGENIE, and so far, I think the documentation is wonderful, and the program is very easy to run (two simple commands, and with very good screen output).

Is it possible to print out the SNP effect size estimates corresponding to the (non-LOCO) PRS computed in Step 1. I would like to see how this performs for predicting left-out samples (and in particular, compare it to predictions from my software and Bolt)

Thanks, Doug

**Comment by dougspeed** [comment]
Hi, I see my question is a duplicate of one of the closed ones, and the answer is "no, it is not possible to obtain effect size estimates". (Sorry, I did not originally notice that most previous questions were hidden).
Thanks

**Comment by dougspeed** [comment]
Specifically, a duplicate of #211

**Comment by joellembatchou** [comment]
Hi Doug,

Indeed such a feature is not available in the software (we don't have a tentative date by when this would be available).

Cheers,
Joelle

**Comment by dougspeed** [comment]
Thanks for the fast response.

**Comment by dougspeed** [comment]
Hi Joelle

following up on this - now I think I understand the method a bit better, it seems there is not a single set of effect sizes. Instead, it seems that there are K sets, where K is the number of CV folds. For example, if K=5, then there will be a set of effect sizes that make the PRS for the first 20% of individuals, then a second set of effect sizes that make the PRS for the second 20% of individuals, etc. 

1 - Is my understanding above correct?
2 - Am I correct to say that the predicted genetic effect of Individual i does not depend on data from Individual i (except that this individual will have contributed when choosing the best level-1 ridge regression parameter)

Thanks
