### ISSUE TITLE
Questions about joint test of interaction test.

### ISSUE THREAD

**Issue by WZo0o** [rgcgithub/regenie#362]
Hello, I have some questions about joint test in interaction test. Could you tell me why?

Why do joint test in interaction test？
What does joint test mean for interaction test?
How to interpret the results of the joint test？

**Comment by joellembatchou** [comment]
Hi,

Please check documentation:
https://rgcgithub.github.io/regenie/overview/#step-2-interaction-testing

Cheers,
Joelle

**Comment by WZo0o** [comment]
Thanks for your help
