### ISSUE TITLE
problem with LOVO follow up

### ISSUE THREAD

**Issue by IoannaTach** [rgcgithub/regenie#363]
I am afraid I amstill having problems running LOVO (see closed ticket from last year "problem with LOVO". Please see log file with error below. I have used "--check-burden-files" with no issues and all the variant IDs in the annaotation file are present in the bim file. The mask file "/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/flexnonsyn_mask.txt" contains "Mask1 flexnonsyn". If I run the same code after excluding the flag '--mask-lovo "UMOD,flexnonsyn,0.99" \', the code runs fine (I used value 0.99 because I want all variants included, they are prefiltered to have MAF<<1%). Any ideas please?

Start time: Fri Dec  9 16:08:03 2022

              |=============================|
              |      REGENIE v3.1.2.gz      |
              |=============================|

Copyright (c) 2020-2022 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : /projects/cgr/users/kvrf354/CKD_portfolio_2022/UMOD/UMOD_PURECKD_flexnonsyn_recessive_LOVO.log

Options in effect:
  --step 2 \
  --bed /projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/output/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn_2022_06_16_output \
  --chr 16 \
  --covarFile /projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step1_PCs/Covariates_EURandUnrelated_PCs_TotalSyn.txt \
  --phenoFile /projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step1/Phenotypes_EURandUnrelated.txt \
  --phenoColList PURECKD \
  --covarColList Sex,Total.Sample.Variant.syn,Total.Sample.Variant.flexnonsyn,PC_EURandUnrelated_1,PC_EURandUnrelated_2,PC_EURandUnrelated_3,PC_EURandUnrelated_4,PC_EURandUnrelated_5,PC_EURandUnrelated_6,PC_EURandUnrelated_7,PC_EURandUnrelated_8,PC_EURandUnrelated_9,PC_EURandUnrelated_10,PC_EURandUnrelated_11,PC_EURandUnrelated_12,PC_EURandUnrelated_13,PC_EURandUnrelated_14,PC_EURandUnrelated_15,PC_EURandUnrelated_16,PC_EURandUnrelated_17,PC_EURandUnrelated_18,PC_EURandUnrelated_19,PC_EURandUnrelated_20 \
  --catCovarList Sex \
  --bt \
  --af-cc \
  --firth \
  --approx \
  --pThresh 0.01 \
  --build-mask comphet \
  --test recessive \
  --pred /projects/cgr/users/kvrf354/CKD_portfolio_2022/REGENIE_step1/fit_bin_out_portfolio_recessive_flexnonsyn_pred.list \
  --bsize 400 \
  --check-burden-files \
  --anno-file /projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/flexnonsyn_16_annotation_UMOD.txt \
  --set-list /projects/cgr/users/kvrf354/CKD_portfolio_2022/UMOD/flexnonsyn_16_genelist_UMOD.txt \
  --mask-def /projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/flexnonsyn_mask.txt \
  --mask-lovo UMOD,flexnonsyn,0.99 \
  --out /projects/cgr/users/kvrf354/CKD_portfolio_2022/UMOD/UMOD_PURECKD_flexnonsyn_recessive_LOVO

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/output/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn_2022_06_16_output.bim] n_snps = 5442739
 * fam              : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/output/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn_2022_06_16_output.fam] n_samples = 347946
 * bed              : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/output/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn/caf_pedmap_combined_step2_collapsing_flexnonsyn_flexnonsyn_2022_06_16_output.bed]
 * phenotypes       : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step1/Phenotypes_EURandUnrelated.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 312037
 * covariates       : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step1_PCs/Covariates_EURandUnrelated_PCs_TotalSyn.txt] n_cov = 23
   -number of individuals with covariate data = 347946
 * number of individuals used in analysis = 312037
 * case-control counts for each trait:
   - 'PURECKD': 42747 cases and 269290 controls
 * LOCO predictions : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/REGENIE_step1/fit_bin_out_portfolio_recessive_flexnonsyn_pred.list]
   -file [/projects/cgr/users/kvrf354/CKD_portfolio_2022/REGENIE_step1/fit_bin_out_portfolio_recessive_flexnonsyn_1.loco] for phenotype 'PURECKD'
 * annotations      : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/flexnonsyn_16_annotation_UMOD.txt] 
   +number of annotations categories = 2
 * masks            : [/projects/cgr/users/kvrf354/CKD_portfolio_2022/extract_pedmap_step2_phewas/flexnonsyn_mask.txt] n_masks = 0
ERROR: no masks are left to be included in the analysis.

**Comment by joellembatchou** [comment]
Can you try with the most recent release? Also, can you check whether there are any special characters in the annotation file or mask definition file? (e.g. `head flexnonsyn_16_annotation_UMOD.txt | cat -A` and `cat -A flexnonsyn_16_annotation_UMOD.txt`)
