### ISSUE TITLE
all quant traits stop if 1 trait has <10 values

### ISSUE THREAD

**Issue by dvh13** [rgcgithub/regenie#366]
Hi team,

I am running multiple qts in a --phenoFile. However if only one qt has less than 10 (?) discrete values, regenie errors and stops for all quant traits. It should only not run the individual trait with <10 discrete values, and allow the rest to proceed.

this below from a male-only analysis, obviously there wont be many progesterone results, but I dont want all the other traits to stop too!
REGENIE v3.2.1.gz
ERROR: phenotype 'progesterone.mean' has very few unique values (=6). If you really want to analyze it as a QT, use `--force-qt`.

I dont especially want to use --force-qt

thanks, david

**Comment by joellembatchou** [comment]
Hi David,

This requirement has been relaxed so it will only check if a BT is being analyzed as a QT (see commit f5d559f1062949575a5598db92a984a319e22a1a). This should avoid the error you are experiencing.  Note that you will need to re-compile the software with this update.

Cheers,
Joelle
