### ISSUE TITLE
quant traits --apply-rint

### ISSUE THREAD

**Issue by dvh13** [rgcgithub/regenie#367]
Joelle,

Can you change the documentation website to make it clear that --apply-rint needs to be included in both step1 and step2.

thanks for your feedback

wasnt obvious to us that needed for both steps

thanks!

david

**Comment by joellembatchou** [comment]
Hi David,

Thanks for pointing that out; it is now clear in the documentation.

Cheers,
Joelle

**Comment by dvh13** [comment]
also please make it clear that --sex-specific options needs to be run on both step1 and step2 for traits. i.e. no just using -sex-specific in step2
