### ISSUE TITLE
Specifying --par-region without a genome build causes the following argument to be ignored

### ISSUE THREAD

**Issue by Wainberg** [rgcgithub/regenie#370]
Specifying `--par-region` without a genome build is supposed to default to hg38. However, running `regenie --step 1 --bed foo --phenoFile foo.pheno --bsize 1000 --par-region --foo --out foo` gives:

```
Options in effect:
  --step 1 \
  --bed foo \
  --phenoFile foo.pheno \
  --bsize 1000 \
  --par-region --foo \
  --out foo
```

Notice how `--foo` is treated as part of `--par-region` rather than as its own argument. If the argument after `--par-region` is a real option instead of `--foo`, its effect is ignored. (For instance, I tried `--par-region --print-prs` and wondered why the PRS wasn't being saved.)

**Comment by Wainberg** [comment]
Looks like this was fixed in the latest build. Just need to update the documentation at https://rgcgithub.github.io/regenie/options to remove the part I've highlighted:

![image](https://user-images.githubusercontent.com/7513967/210461098-1eecc53d-a6a5-454c-aa80-037865523bfa.png)

**Comment by joellembatchou** [comment]
Hi,

`--par-region` requires an argument so if you want to use the default "hg38", either use `--par-region hg38` or omit the option altogether.

Cheers,
Joelle

**Comment by Wainberg** [comment]
Yep, it's fixed in the latest build, but the documentation at https://rgcgithub.github.io/regenie/options still needs updating to remove the part that says "[default=hg38]".

**Comment by joellembatchou** [comment]
Not sure what you mean as the default build assumed in REGENIE to determine the bounds for the PAR regions is hg38.

**Comment by Wainberg** [comment]
Oh my bad! I thought that PAR regions weren't treated differently from the rest of the X chromosome by default. All good then.
