### ISSUE TITLE
Do I need to remove SNPs with high LD in step 2

### ISSUE THREAD

**Issue by linnabrown** [rgcgithub/regenie#374]
Dear author,

I would like to know do I need to remove SNPs with high LD in step 2 when regressing on continous values. Since the association step seems that it need to perform association with the outcome and the independent SNPs.

**Comment by joellembatchou** [comment]
Hi,

You don't need to prune for LD. Step 2 performs association testing in parallel for each SNP so the results will not be impacted by LD pruning (only impact would be reducing the total number of SNPs which would be analyzed). The association test is performed between the phenotype and each SNP (after adjusting for covariates).

Cheers,
Joelle
