### ISSUE TITLE
lovo analysis for AF<0.01

### ISSUE THREAD

**Issue by alice-gio** [rgcgithub/regenie#375]
Hi!
I am trying to run a lovo analysis for a burden test, for a certain mask having an allele frequency threshold set at 0.001 (ex. "--mask-lovo gene, M1,0.001"). However, I got results for the allele frequency threshold 0.01". 
Is there something am I missing?

Thanks!!
Best regards, 
Alice

**Comment by joellembatchou** [comment]
Hi Alice,

Can you include the full REGENIE log?

Cheers,
Joelle
