### ISSUE TITLE
Step 2 error message with --interaction 

### ISSUE THREAD

**Issue by mcolosimo-p4** [rgcgithub/regenie#376]
We passed in the wrong covariate name to `--interaction` and got 

      * covariates       : [covariates.txt] ERROR: not all covariates specified are found in the covariate file.

It tooks us a little while to figure out that we mixed up the name. I think it would have been helpful if the check for `w_interaction` is moved up.

See https://github.com/rgcgithub/regenie/blob/master/src/Pheno.cpp#L530 to this:

```
  // check all covariates specified are in the file
  if(params->w_interaction && !params->interaction_snp && !params->interaction_prs && (np_inter != 1))
    throw "cannot find the interaction covariate specified in the covariate file.";

  params->n_cov = keep_cols.count(); 
  if( (int)filters->cov_colKeep_names.size() != params->n_cov ) 
    throw "not all covariates specified are found in the covariate file.";
```

**Comment by joellembatchou** [comment]
Hi,

Thank you for the suggestion; it will be incorporated in the next release.

Cheers,
Joelle
