### ISSUE TITLE
ERROR: vector::_M_default_append

### ISSUE THREAD

**Issue by pwu4** [rgcgithub/regenie#381]
Perform GWAS with UK Biobank Bgen files.
Regenie Step 2 
Options in effect:
  --step 2 \
  --ref-first \
  --bgen /mnt/home/Bulk/Imputation/Calls/ukb22828_c3_b0_v3.bgen \
  --sample /mnt/home/Bulk/Imputation/Calls/ukb22828_c3_b0_v3.sample \
  --phenoFile ad_risk_by_proxy_wes.phe \
  --covarFile ad_risk_by_proxy_wes.phe \
  --phenoCol ad_by_proxy \
  --extract ad_risk_by_proxy_wes.snplist \
  --pred ad_by_proxy_pred.list \
  --use-relative-path \
  --out SDD_assoc_chr3 \
  --bt \
  --approx \
  --firth-se \
  --firth \
  --covarCol age \
  --covarCol sex \
  --covarCol pc{1:10} \
  --bsize 1000 \
  --minMAC 5 \
  --pThresh 0.01 \
  --threads 80 \
  --gz

ERROR: vector::_M_default_append

**Comment by joellembatchou** [comment]
Hi,

Can you include the full log?

**Comment by pwu4** [comment]
It seems that the bgen filed downloaded from UKB is broken. (I downloaded a shared large dataset(~100G) by wget, i.e., ukb22828_c3_b0_v3.bgen) I checked the integrity of the data and got a similar warning.

bgenix -g ukb22828_c3_b0_v3.bgen 

-------------

Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

terminate called after throwing an instance of 'std::length_error'
what(): vector::_M_default_append
Aborted (core dumped)
