### ISSUE TITLE
Variant filtering including inter-chromosomal LD in step 1 of regenie

### ISSUE THREAD

**Issue by viva1109** [rgcgithub/regenie#383]
Hi, I am Kangjin Kim a postdoc in Brigham Women's Hospital.
I love this software. Very fast and nice.

I am suffering some problems when I am using WGS data which I did not face when I was using SNP data.

[First issue]
One of them was that there were too many variants. The criteria the original paper of regenie used is maf 0.01, LD pruning 1K window size, 100 window step, R2<0.9 (with additional hwe, missing filtering).
The resulting number of variants I have with this criteria was far more than > 1M which was not recommended. So, I extracted only SNPs based on the SNP list of my SNP data and did more aggressive pruning with R2<0.3 which results in 890K number of variants. 
I think this makes sense because the purpose of step 1 is to capture genome-wide polygenic effects with a smaller set of variants. Do you think this filtering step make sense? 

[Second issue or question]
Is the guideline of >1M just about the computational time efficiency or violation of it can affect validity of performance of regenie?

[Third issue]
Another issue was excluding inter-chromosomal LD variants. It is mentioned in the original paper (https://www.nature.com/articles/s41588-021-00870-7#MOESM1). But you know that  calculating LDs across whole chromosome with plink and getting empirical cutoff for significant LD takes a lot of time and hard drive space. (Using ldstore for this is a good way, but that software could not find a certain form of SNP id (chr:physicalposition:allele1:allele2) from the bgen file. I am working on how to fix it.) I couldn't find any issue about this. Can I skip this step? Or can it be handled in some other way? 

Bests,

Kangjin

**Comment by joellembatchou** [comment]
Hi Kangjin,

(1) Yes, your approach to obtain the set of step 1 variants looks very reasonable. 
(2) The recommendation of ~500K variants is that this should be sufficient to capture genome-wide polygenic effects and including more variants just adds to the computation burden. 
(3) The issue with interchomosomal LD being present in the data for step 1 is that the LOCO predictions may then still capture some of the effect of a tested SNP (eg if that SNP is in high LD with a SNP on another chromosome which is associated with the trait). So this can result in decreased power performance.

Cheers,
Joelle
