### ISSUE TITLE
LOG10P range is not between 0 and 1.

### ISSUE THREAD

**Issue by wilsonava** [rgcgithub/regenie#384]
<img width="878" alt="Screenshot 2023-02-08 at 12 52 57 PM" src="https://user-images.githubusercontent.com/87376889/217612043-c53f05d8-d228-4414-972d-1ec929b93ccf.png">

<img width="597" alt="Screenshot 2023-02-08 at 12 50 24 PM" src="https://user-images.githubusercontent.com/87376889/217611880-0e2977c1-eec2-43bb-9a1d-44d1f6560675.png">

I am reviewing my results from my GWAS analyses and I noticed that my QQ plots looked abnormal.  After investigating I noticed that the range for the LOG10P generated was between 0 and 18.  

REGENIE (v3.1.1)

Step1: 
run_regenie_cmd="regenie --step 1 --out M238_results \
 --bed ukb22418_allQC_mrg_prnd_cohort_lo38_v3 \
 --phenoFile m2_pheno_phe.txt \
 --covarFile m2_covariates.txt \
 --phenoCol copd_only --covarCol age \
 --covarCol sex_rec --covarCol py_rec \
 --covarCol PC1 --covarCol PC2 \
 --covarCol PC3 --covarCol PC4 \
 --covarCol PC5 --covarCol PC6 \
 --covarCol PC7 --covarCol PC8 \
 --covarCol PC9 --covarCol PC10 \
 --bsize 1000 --bt --loocv --gz --threads 16 "

Step2: 
for chr in {1..22}; do
  run_regenie_cmd="regenie --step 2 --out assoc.c${chr} \
    --bed ${data_field}_c${chr}_b0_v1 \
    --phenoFile m2_pheno_phe.txt --covarFile m2_covariates.txt \
    --bt --approx --firth-se --firth --extract WES_c${chr}_snps_qc_pass.snplist \
    --phenoCol copd_only --covarCol age --covarCol sex_rec --covarCol py_rec --covarCol PC1 \
    --covarCol PC2 --covarCol PC3 --covarCol PC4 --covarCol PC5 --covarCol PC6 --covarCol PC7 \
    --covarCol PC8 --covarCol PC9 --covarCol PC10 --pred M238_results_pred.list --bsize 200 \
    --pThresh 0.05 --minMAC 3 --threads 16 --gz"

**Comment by joellembatchou** [comment]
Hi,

Could you rerun with the most recent REGENIE version?

Cheers,
Joelle

**Comment by Antonio-Nappi** [comment]
Why do you expect a log10Pvalue range between 0 and 1? Regenie applies the -log10 at the pvalues so it can easily go up to other values, if the signal is very strong
