### ISSUE TITLE
can REGENIE be compiled without BGEN support?

### ISSUE THREAD

**Issue by freeseek** [rgcgithub/regenie#387]
I wanted to recompile REGENIE with debugging symbols to identify the source of some memory leaks but I find it impossible to compile the BGEN library on my system (Ubuntu 22.10). Is there a possibility to turn off support for BGEN at compilation time? I could not find a way to do so

**Comment by joellembatchou** [comment]
Hi,

Unfortunately no as it would require quite a lot of work on adapting the code (perhaps trying compilation through docker would help?).

Cheers,
Joelle
