### ISSUE TITLE
Genomic control

### ISSUE THREAD

**Issue by ZhiyiZhu0226** [rgcgithub/regenie#388]
Hello, 
I have run a GWAS on a quantitative trait of a large sample size (n = 480,000), and I was wondering how REGENIE counts for genomic inflation. I know specifying covariates (PCs, age, sex, etc) helps with the genomic inflation, but I'm not sure if additional corrections exist. Specifically, I wonder if REGENIE uses lambda GC to do the genomic control correction. Is it necessary to GC correct the output pvals for REGENIE, or does REGENIE already do the GC correcting while running step 2?

**Comment by joellembatchou** [comment]
Hi,

REGENIE does not compute lambdaGC (this can be done in a post-processing step) though REGENIE used a whole-genome regression approach to correct for population structure and relatedness which are important sources of confounding in GWAS and can lead to inflation in tests. Note that lambdaGC will not be sufficient to confounding from polygenicity (perhaps look into LD score regression).

Cheers,
Joelle
