### ISSUE TITLE
SBAT joint test results missing when SBAT is used alone without ACAT

### ISSUE THREAD

**Issue by vonalven** [rgcgithub/regenie#393]
Hi,

I have a question concerning the SBAT joint test. I'm trying to use the SBAT joint test and I have the following problem:
- When the option --joint acat,sbat is set, the results table has results for both ACAT and SBAT using Regenie v3.2.5_mkl
- When the option --joint acat is set, he results table has results for ACAT using Regenie v3.2.5_mkl
- But, when option --joint sbat is set, the results table doesn't have results for SBAT using Regenie v3.2.5_mkl, although the execution log states that the option —joint sbat is in use and that "list of joint tests run on burden masks: SBAT"

If I try to specify the joint SBAT test alone, without ACAT in Regenie v3.2.0_mkl, SCAT results are present in the output results table.
If I try to specify the joint SBAT test alone, without ACAT in Regenie v3.2.4_mkl (the last before v3.2.5), SCAT results are again NOT present in the output results table.

Below the regenie command, were I tested the following Regenie versions as mentioned above: 
Regenie v3.2.5_mkl
Regenie v3.2.0_mkl
Regenie v3.2.4_mkl

./regenie_v3.2.4.gz_x86_64_Linux_mkl \
	--step 2 \
	 --bgen c21.bgen \
	--sample c21.sample \
	--phenoFile continuousTrait.tsv \
	--covarFile continuousTrait.tsv \
         --pred continuousTrait_rgstep1_results_pred.list \
	--set-list annot.sets.txt.gz \
	--anno-file annot.annotations.txt.gz \
	--mask-def masks.masks \
	 --extract c21.snplist \
	 --out continuousTrait_rgstep2_burden_results_c21 \
	--phenoCol pheno \
	--covarColList sex,age \
	--bsize 200 \
	--aaf-bins 0.001,0.01,0.05,0.1 \
	--joint sbat \
	--write-samples \
	--write-mask \
	--write-mask-snplist \
	--gz \
	--ref-first \
	--verbose;

In the Regenie v3.2.5_mk release it is stated that "Use ACAT to get SBAT p-value across POS/NEG models and use it in GENE_P". Does this mean that ACAT is required to compute SBAT p-values in the new Regenie versions?

Here the system OS and GCC info:

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thanks!
Giacomo

**Comment by joellembatchou** [comment]
Hi Giacomo,

Thank you for catching this bug; it is now fixed (b426a22f13615810e28ee101ee0eac396761997e).

Cheers,
Joelle
