### ISSUE TITLE
gene-based output file missing result 

### ISSUE THREAD

**Issue by wojiaolianer** [rgcgithub/regenie#394]
Hello,

I'm using regenie to analysis gene-based testing. And my gene-based output file produced by --step2 come to noting, and no obvious error presented in log file. I'm not sure what went wrong, any help would be greatly appreciated!

There is my code and log file

`for i in {1..22};do
./regenie --step 2 \
  --bed ./ukb23158_c${i}_RHTN_QC \
  --covarFile ./RHTN_cov.txt \
  --phenoFile ./RHTN.pheno \
  --phenoCol PHENO \
  --bt \
  --pred ./ukb23158_RHTN_QC3_pred.list \
  --anno-file ./lof.annotations \
  --set-list ./lof.setlist \
  --mask-def ./lof.masks \
  --aaf-bins 0.2 \
  --write-mask-snplist \
  --bsize 200 \
  --out ./ukb23158_c${i}_RHTN_QC
done`

`Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [./ukb23158_c1_RHTN_QC.bim] n_snps = 2586066
 * fam              : [./ukb23158_c1_RHTN_QC.fam] n_samples = 153388
 * bed              : [./ukb23158_c1_RHTN_QC.bed]
 * phenotypes       : [./RHTN.pheno] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 153388
 * covariates       : [./RHTN_cov.txt] n_cov = 14
   -number of individuals with covariate data = 153388
 * number of individuals used in analysis = 153388
 * case-control counts for each trait:
   - 'PHENO': 6999 cases and 146389 controls
 * LOCO predictions : [./ukb23158_RHTN_QC3_pred.list]
   -file [./ukb23158_RHTN_QC3_1.loco.gz] for phenotype 'PHENO'
 * annotations      : [./lof.annotations] 
   +number of annotations categories = 2
 * masks            : ./lof.masks] n_masks = 1
 * aaf cutoffs      : [ 1 : 0.2 ] + singletons
 * set file         : [./lof.setlist] n_sets = 1022
WARNING: Detected 7134 sets with only unknown variants (these are ignored).
 * threads        : [51]
 * tested sets    : [1022]
 * max block size   : [200]
 * rule used to build masks : max
 * approximate memory usage : 971MB
 * writing list of variants for each mask in file [./ukb23158_c1_RHTN_QC_masks.snplist]
 * using minimum MAC of 5 (masks with lower MAC are ignored)

Chromosome 1 [1022 sets in total]
   -reading loco predictions for the chromosome...done (238ms) 
   -fitting null logistic regression on binary phenotypes...done (324ms) 
 set [1/1022] : SAMD11 - 3 variants...
     -reading in genotypes and building masks...done (80ms) 
 set [2/1022] : NOC2L - 2 variants...
     -reading in genotypes and building masks...done (21ms) 
 set [3/1022] : KLHL17 - 3 variants...
     -reading in genotypes and building masks...done (72ms) 
 set [4/1022] : LOC107985528 - 31 variants...
     -reading in genotypes and building masks...done (418ms) 
 set [5/1022] : PLEKHN1 - 3 variants...
     -reading in genotypes and building masks...done (29ms) 
 set [6/1022] : PERM1 - 2 variants...
     -reading in genotypes and building masks...done (27ms) 
 set [7/1022] : HES4 - 2 variants...
     -reading in genotypes and building masks...done (27ms) 
 set [8/1022] : ISG15 - 1 variants...
     -reading in genotypes and building masks...done (17ms) 
 set [9/1022] : AGRN - 2 variants...
     -reading in genotypes and building masks...done (18ms) 
 set [10/1022] : RNF223 - 2 variants...
     -reading in genotypes and building masks...done (24ms) 
...
Association results stored separately for each trait in files : 
* [./ukb23158_c1_RHTN_QC_PHENO.regenie]

Number of ignored tests due to low MAC : 0`

**Comment by joellembatchou** [comment]
Hi,

Can you rerun using `--nb 1 --write-mask-snplist --debug` (so only testing the first set and printing out some debugging information as well as the ID of variants included in mask)?

Cheers,
Joelle
