### ISSUE TITLE
infinitely small p-values 

### ISSUE THREAD

**Issue by gamalazim** [rgcgithub/regenie#395]
In Regenie step 2 output, I have experienced p-values smaller than 1.0e-5000. These values require special libraries to represent numbers beyond long doubles in C/C++ (long doubles are precise to the 4932nd decimal -- LDBL_MAX in float.h/limits.h = 1.18973e+4932). I explored the Regenie code online for libraries such as [MPFR](https://www.mpfr.org/) or [GMP](https://gmplib.org/) but was not able to find them linked. Can you please clarify which high-precision libraries Regenie is using to represent such infinitely small numbers? Just to exclude MKL, I found that those were not compiled to handle such high precision values. If those small numbers are not supposed to happen, it is also important to know.

Thanks for your help.

**Comment by chrchang** [comment]
plink2 library code includes a function to render p-values like this from internal log-p-values (which can be stored in ordinary float64s), as well as the corresponding reader function.

**Comment by gamalazim** [comment]
Hi Chris,
Thank you for stating that Plink2 can handle p-values smaller than long doubles (< 1.0e-4932). As you mentioned, in your case, this was done by design which is comforting. In my question above, I was asking if Regenie has something similar in place, whether custom-code as in Plink2 or via any of the libraries I listed above.
Thanks again for the info!

**Comment by chrchang** [comment]
While regenie doesn't currently use plink2's log-p-value printer or scanner functions, p-values are represented in log form all over the regenie codebase.

**Comment by gamalazim** [comment]
Changing p-values to logs does not solve the problem but thanks for trying to answer my question. I still hope that someone from the Regenie developers can answer.

**Comment by chrchang** [comment]
The point is that many p-value calculations can naturally be correctly expressed in log space, I did this in plink2 years ago, and there has been obvious effort by the regenie developers to do this.  I don't understand why you have not bring up even one example where you think the <1e-4932 p-value is actually wrong; without such an example, I claim there is no "problem" to be "solved".

**Comment by gamalazim** [comment]
Again this is not my question at all. Please read my question again. Thank you.

**Comment by chrchang** [comment]
I did read your question, and my response directly addresses it.  Many p-value calculations aren't difficult to do in log space if you put in the effort.  regenie clearly tries to do this.  If you found what you believe to be a MISTAKE IN THEIR IMPLEMENTATION, please bring that up.  But if you still don't believe that they were even trying...

**Comment by gamalazim** [comment]
Why are you answering on their behalf? What 'MISTAKE' are you referring to in your capitalized/angry answer above? When you say 'regenie clearly tries to do this'. What is 'this' that Regenie is trying to do? Can you point out 'this' in the code or the documentation?

**Comment by joellembatchou** [comment]
Hi,

REGENIE computes log10 p-values from the test statistic and also outputs the p-values in -log10 format (LOG10P column in sumstats file) and so can store very small p-values (e.g. p-value of 10^-5000 corresponds to 5000 on -log10 scale which can be stored as a double).

Cheers,
Joelle

**Comment by chrchang** [comment]
I was answering because I am a domain expert in this area who implemented log-space p-value calculations in my own code and can easily see that regenie tries to do the same.

A mistake would be a log-p-value that you believe to be off by e.g. >1%.  It is not the mere existence of a p-value below 5e-324 or even 1e-4932; that's normal for a sufficiently large GWAS.  You have only mentioned the latter, not the former.

As for code, see e.g. https://github.com/rgcgithub/regenie/blob/master/src/Regenie.cpp#L1550 .

**Comment by gamalazim** [comment]
Thanks Joelle for your answer. That makes sense.
