### ISSUE TITLE
Does the argument for --test need to match between step1 and step2?

### ISSUE THREAD

**Issue by ilevantis** [rgcgithub/regenie#396]
I am interested in running association with regenie using the additive, recessive, and dominant models.

For each of these models does step1 need to be run seperately specifying the model with the `--test` parameter? Or can I run step1 a single time and use the output for multiple runs of step2 each with a different model?

**Comment by joellembatchou** [comment]
Hi,

`--test` is only applicable in step 2 to specify the coding to apply to the tested variants; I have made note to throw an error if it is used in step 1 for clarity.

Thanks,
Joelle
