### ISSUE TITLE
"one of the folds has only cases/controls for phenotype" in step 1 for well-balanced case/control

### ISSUE THREAD

**Issue by christopherdkoch** [rgcgithub/regenie#397]
I'm running step 1 of Regenie for a binary trait without about 7K cases and about 5K controls, using the default of 5 folds. Unexpectedly, I'm getting the error "ERROR: one of the folds has only cases/controls for phenotype." I would expect this error to only occur for phenotypes with large case/control imbalance. Could you please provide guidance?

**Comment by joellembatchou** [comment]
Hi,

Can you try using leave-one-out cross validation with `--loocv`? It seems one of the cross-validation folds only has cases (or all controls).

Cheers,
Joelle

**Comment by christopherdkoch** [comment]
Thanks, Joelle. I tried and it works with --loocv. I'm surprised though that it failed with 5 CV folds and ~7K cases and ~5K controls - shouldn't those sample sizes be more than sufficient to avoid having folds with only cases or only controls?

**Comment by joellembatchou** [comment]
Hi,

The order of Individuals in REGENIE is determined by that in the genotype file. If you rearrange the phenotype data based on that order, it seems one of the blocks of 2400 individuals has only cases/controls (it is indeed quite surprising).

Cheers,
Joelle

**Comment by christopherdkoch** [comment]
Is there a downside to always using --loocv if runtime is not a concern?

**Comment by joellembatchou** [comment]
No, as shown in REGENIE paper, we found k-fold Cv & LOOCV to give similar p-values.
