### ISSUE TITLE
PGEN input / Rsq/INFO values

### ISSUE THREAD

**Issue by MatthewMaher** [rgcgithub/regenie#398]
I was using regenie v3.2.5.2 with pgen input and the output contains an INFO column described in the documentation: 

"**_With BGEN/PGEN files with dosages, the imputation INFO score is provided (IMPUTE info score for BGEN and Mach Rsq for PGEN)._**"

However I noticed that **nearly 25% of the values in the INFO column exceeded 1.000,** which I believe is by definition not possible for Mach Rsq.

I tried to delve into the code a bit (too much coffee!) and I believe I located the calculations for Mach Rsq (performed for pgen input) in **compute_aaf_info()** in **src/Geno.cpp**.   I may not be fully comprehending things (the coffee started wearing off) but it seems like the calculation is proceeding based on diploid dosages (0.0-2.0), but I _believe_ calculating the Mach Rsq value (described [here](https://genome.sph.umich.edu/wiki/Minimac3_Info_File)) requires the haploid dosages - otherwise no distinction would be drawn between a diploid dosage of 1.0 arising from [ 0.0 / 1.0 ] as opposed to [ 0.5 / 0.5 ]  - I believe if all samples had the former haploid dosages, the Rsq would be 1.0, while if all samples had the later haploid dosages, the Rsq would be 0.0. 

I believe the [PGEN format ](https://github.com/chrchang/plink-ng/blob/master/pgen_spec/pgen_spec.pdf) supports (section 2.3.7) _optional_ phased dosages, which would allow calculation of Minimac Rsq. But perhaps regenie is not currently reading those from the pgen, since they are not needed for the GWAS?

I _believe_ (but definitely not certain) that BGEN format(s) also support optional phased dosages. 

Could you explain the rationale for the BGEN/PGEN --> INFO/Rsq split described in the documentation excerpt above?    I believe either data format could hold data generated from either imputation engine, so I'm unclear of the reason for this defined behavior.  But again, I might well be misunderstanding something and would love to be enlightened.

Thanks for Regenie - a great tool!

**Comment by joellembatchou** [comment]
Hi,

Check this response:
https://github.com/rgcgithub/regenie/issues/333#issuecomment-1249659134

As stated in the linked paper, Mach Rsq can be greater than 1.

Cheers,
Joelle

**Comment by MatthewMaher** [comment]
Hi Joelle - Sorry for this very late follow-up comment on this - a couple things I thought worth mentioning/suggesting: 

I agree (as per the paper you cite) that the Mach R2 statistic can go above 1, which caused some confusion for myself (and others - e.g. the commenter for issue #333).   The reason for the confusion, I suspect, can be two-fold: 

1.  My best understanding is that the **Mach** R2 statistic became more or less obsolete with the arrival several years ago of the successor tool (**Mini**Mac), which [redefined](https://genome.sph.umich.edu/wiki/Minimac3_Info_File) (but did not rename!) R2 - and thus the current R2 now only goes from 0 to 1, much like the INFO score from IMPUTE (that all UKBB users are familiar with).   MiniMac(3/4) is the imputation engine behind the widely used Michigan and TopMed Imputation Servers.   So when most people today speak of "R2", I believe they mean MiniMac R2.  Reflecting these two conflicting definitions of "R2", I would note that PLINK2 [supports](https://www.cog-genomics.org/plink/2.0/filter#mach_r2_filter) separate filters for each version.    

2.  The term "INFO" seems to often get conflated with "R2".  My best understanding is that, speaking most strictly, INFO is the imputation quality statistic produced by IMPUTE.   But the paper you cited (by the authors of IMPUTE, it is worth noting) perhaps caused a broadening in the term's meaning by describing all the enumerated metrics as "information measures", which I think is then easily/commonly shortened to... "INFO".   But I don't believe the Michigan *mac teams use that terminology.  So when an output file has a column header of "INFO" but the values are a different metric (R2), there's possible confusion, even if both statistics were on the same 0-1 scale. 

So I think the current regenie functionality has the potential for confusion in a couple ways, if I understand things correctly: 

1.  The same exact command will produce different results depending on whether the input file is pgen vs bgen (since the --minINFO is overloaded as an R2 filter).   I would think that if R2 filtering were to be done, the user should be required to explicitly ask for it with e.g. --minR2   or --minMinimacR2  i.e. the user should be required to understand what metric is in use. 

2.  If the reported quality scores are R2 values, then the column heading should say R2, rather than INFO.  That seems to be at the root of the commenter's confusion in issue #333.    

3.  and just to repeat the earlier point, any reference to "R2" should, I believe, pertain to the MiniMac R2, rather than the Mach R2, which I believe is obsolete. 

---------
In my particular use case, I support various researchers who all seem to want to have GWAS run with different imputation quality cutoffs - and since the cohorts were imputed via TopMed or Michigan and a baseline filtering cutoff was supplied to and performed on the server, the filtering regime is minimac R2.   But when different teams want different filtration cutoffs, that now requires using PLINK2 --minimac3-r2-filter to create cloned filesets with very progressively stricter cutoffs.  But if regenie had --minMinimacR2 (or some such), then that would not be necessary.  I hope that makes sense. 

Anyway, thanks for regenie - an excellent tool.
-Matt

**Comment by Ojami** [comment]
@MatthewMaher interesting poin you made. Just out of curiosity, can you please explain how the definition of [Mach r2](https://static-content.springer.com/esm/art%3A10.1038%2Fnrg2796/MediaObjects/41576_2010_BFnrg2796_MOESM3_ESM.pdf) is different from the [minimac3 implementation](https://github.com/Santy-8128/Minimac3/blob/master/src/ImputationStatistics.cpp#L49):
```
double ImputationStatistics::Rsq(int marker)
   {
   if (count[marker] < 2)
      return 0.0;

   double f = sum[marker] / (count[marker] + 1e-30);
   double evar = f * (1.0 - f);
   double ovar = 0.0;

   if((sumSq[marker] - sum[marker] * sum[marker] / (count[marker] + 1e-30))>0)
        ovar=(sumSq[marker] - sum[marker] * sum[marker] / (count[marker] + 1e-30)) / (count[marker] + 1e-30);

   return ovar / (evar + 1e-30);
   }
```

Best/Oveis

**Comment by MatthewMaher** [comment]
I'm no expert but it seems Mach R2 is based on diploid dosages rather than haploid dosages as for minimac3/4.  So not only is the minimac R2 the currently-in-use metric, I would think it is also the more accurate as it is based on more information.  And it doesn't exceed 1, which is what started all the confusion!

I was unaware of these competing definitions of R2 until Joelle's response to my initial query.  I then inquired with the Michigan folks (in my typical long-winded way), and got confirmation and brief descriptive comments which you can read here: 

https://groups.google.com/g/minimac4-help/c/LGefsWsE9cY/m/Lc7bmoFRAQAJ

-Matt
