### ISSUE TITLE
How to interpret LOCO predictions for binary traits

### ISSUE THREAD

**Issue by hrushikeshloya** [rgcgithub/regenie#399]
Hi Joelle,

I'm trying to make sense of the loco predictions file output from Regenie after running step 1 for binary traits. 

Am I correct in understanding these are the LOCO genetic effects (and not genetic + covariate effects)? (i.e. W^T \eta in equation 10?) and the last line of the LOCO file corresponds to chr 23 that accounts for sex chromosomes? 

So in order to get \hat{p} in equation 28, you add the covariate effects and 'expit' the result (expit = 1/(1+e^{-x}))? I've been trying to generate the test statistics like this but they don't seem to match the ones generated from Regenie, so wondering if there is any flaw in my thinking. 

Do you perform any phenotype scaling/adjustments while calculating the logistic score test statistics? 

Hrushi

**Comment by joellembatchou** [comment]
Hi Hrushi,

Sorry for the delay in replying back. The LOCO predictions are the genetic effects where covariate effects have been adjusted for (we project covariate effects from the genotypes and include them as an offset in the logistic model).

Cheers,
Joelle
