### ISSUE TITLE
how to extract/exclude variants in step2?

### ISSUE THREAD

**Issue by yingxi-kaylee** [rgcgithub/regenie#40]
Hi,

I have a BGEN file with a large number of variants, but only want to test a small subset. Step 1 can be done by using --extract option, yet this doesn't seem to work for step2. REGENIE tests all the variants in my BGEN file. Do you know how to test only the subset in step2?

Thanks a lot!

**Comment by joellembatchou** [comment]
Refer to #22 

For now, you would need to create a BGEN file with only the variants you wish to test for step 2.

**Comment by joellembatchou** [comment]
This feature has been added to Regenie v1.0.6.5.

**Comment by yingxi-kaylee** [comment]
Thanks so much for your work and your high efficiency!
