### ISSUE TITLE
Running regenie on non-human data

### ISSUE THREAD

**Issue by ChriKub** [rgcgithub/regenie#401]
Hi,

I am trying to run regenie (v. 3.2.5.2 - installed using Conda) on a non-human species with more than 23 chromosomes. At the moment step 1 fails when it encounters a chromomsome name > 23. When I downsample the file to contain chromosome 1-23 it finishes.
```
 * bim              : [plink_test.bim] ERROR: unknown chromosome code in bim file at line 553561
```
Is there a way to allow more chromosomes? 

Thanks,
Chris

**Comment by joellembatchou** [comment]
Hi Chris,

See `--nauto` (https://rgcgithub.github.io/regenie/options/#options).

Cheers,
Joelle
