### ISSUE TITLE
The N value in the result file is the same

### ISSUE THREAD

**Issue by Jlftm** [rgcgithub/regenie#403]
Hi,

I‘m using regenie to conduct a GWAS analysis, the program ran normally and output results, but the N value of the result file is the same. I don't know which step is wrong, and below is my code.

step1：
`regenie \
  --step 1 \
  --bed ukb_cal_allChrs \
  --extract qc_pass_bt.snplist \
  --keep qc_pass_bt.id \
  --phenoFile ukb_total_phe_bt.txt \
  --covarFile ukb_newcov_bt.txt \
  --bt \
  --bsize 1000 \
  --out anx_step1_bt
`
step2：
`  regenie \
  --step 2 \
  --bgen ukb22828_c1_b0_v3.bgen \
  --ref-first \
  --sample ukb22828_c1_b0_v3.sample \
  --phenoFile ukb_total_phe_bt.txt \
  --covarFile ukb_newcov_bt.txt \
  --bt \
  --firth --approx --pThresh 0.01 \
  --pred anx_step1_bt_male_pred.list \
  --bsize 400 \
  --out anx_bt_chr1
`

**Comment by Jlftm** [comment]
![image](https://user-images.githubusercontent.com/107736983/227725464-73140eb5-0edd-4cd7-a932-729395b75bb4.png)
here is a part of the result

**Comment by carbocation** [comment]
If the data are imputed, isn't that expected?
