### ISSUE TITLE
Phenotype prep for UKBiobank data

### ISSUE THREAD

**Issue by lilipeng** [rgcgithub/regenie#404]
what is the regenie command to convert UKB phenotype data (binary, quantitative) in the phenotype format for Regenie step 1?
https://rgcgithub.github.io/regenie/options/#phenotype-file-format
Is there a tool in Regenie to convert UKB phenotypes so it reads "IID FID Y1 Y2"?

**Comment by joellembatchou** [comment]
Hi,

There is no tool to convert to the phenotype format as it is quite a simple format and fairly standard across many GWAS software. You can use programs like R/Python to generate the phenotype file.

Cheers,
Joelle
