### ISSUE TITLE
Consider relaxing assert( tmp_snp.ID == rsid )

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#407]
The UK Biobank TOPMed imputed BGEN files don't have any rsID information (it's "." for every variant). This is also true for their BGI files. In some sense, this is not a problem - we can populate rsIDs in the .BGI files while leaving the BGEN files untouched.

However, REGENIE does not appear to permit BGEN and BGI files having different rsid values. Specifically, this appears to be enforced at [assert( tmp_snp.ID == rsid );](https://github.com/rgcgithub/regenie/blob/e18f1d6f60312c593c0e8e79892c38b763603cad/src/Geno.cpp#L253). While the other checks make sense to me (e.g., making sure that the variant size matches), this seems unnecessarily restrictive and could perhaps be replaced with chr:pos:ref:alt checks or something similar so that the rsid field in the BGI files can be modified.

https://github.com/rgcgithub/regenie/blob/e18f1d6f60312c593c0e8e79892c38b763603cad/src/Geno.cpp#L253

**Comment by joellembatchou** [comment]
Hi,

Thanks for pointing this out. We will make note to relax this in the next release.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
This is now done in [newest release](https://github.com/rgcgithub/regenie/releases/tag/v3.2.8).

Cheers,
Joelle
