### ISSUE TITLE
.psam header does not have the correct format.

### ISSUE THREAD

**Issue by MikeKazz** [rgcgithub/regenie#409]
Hi
Here is my .psam file:
```
#FID	#IID	SEX
1_1	1_1	NA
2_2	2_2	NA
3_3	3_3	NA
4_4	4_4	NA
5_5	5_5	NA
6_6	6_6	NA
9_9	9_9	NA
10_10	10_10	NA
11_11	11_11	NA
```

but I get this error:

```
  Fitting null model
   * pvar             : [all.common_independent_snps.pvar] n_snps = 241678
   * psam             : [all.common_independent_snps.psam] ERROR: header does not have the correct format.
```

**Comment by chrchang** [comment]
Header line should read "#FID  IID  SEX".  Note that there should be only one '#', at the beginning of the line.

**Comment by MikeKazz** [comment]
> Header line should read "#FID IID SEX". Note that there should be only one '#', at the beginning of the line.

Problem solved. Thank you so much.
