### ISSUE TITLE
minMAC option

### ISSUE THREAD

**Issue by yingxi-kaylee** [rgcgithub/regenie#41]
Dear REGENIE team,

Regarding the --minMAC option, what's the sample size of MAC? Say I have a BGEN file of 400K samples, but I only test 40K samples using the --keep option. Is the MAC based on 400K or 40K samples?

Thanks!

**Comment by joellembatchou** [comment]
If using `--keep`, the MAC will be computed only from the genotyped samples in the `--keep` file. You can use option `--write-samples` to get the sample IDs used for each trait analyzed in step 2 of Regenie.

**Comment by yingxi-kaylee** [comment]
I see. Thanks!
