### ISSUE TITLE
pgen/bgen dosage input - hardcall threshold

### ISSUE THREAD

**Issue by SoCadiou** [rgcgithub/regenie#414]
Hi developers,

I understand from [#issue114](https://github.com/rgcgithub/regenie/issues/114) that when the input is a pgen with dosage, regenie uses the dosage and not the hardcall. I would like to know:  1. if that means that there is an internal hard call conversion? 2. if yes, what is the threshold used? 3. if the behaviour (preferential use of dosage if available, potential threshold) is the same when the input is a bgen with dosages? 4. what about the potential conversion when the input is a bgen with raw genotype probabilities?

Many thanks!

**Comment by joellembatchou** [comment]
Hi,

(1-2) REGENIE will analyze the dosages as-is in the association tests.
(3-4) BGEN contains genotype probabilities which will be converted to dosages prior to running the association tests.

Cheers,
Joelle
