### ISSUE TITLE
Covariates file 

### ISSUE THREAD

**Issue by mariamaitoumelloul** [rgcgithub/regenie#416]
Hi developers,

I have a few questions about using regenie for GWAS.
1-Should I include the 10 principal components as covariates, or is this redundant with what step 1 is doing for the analysis?
2-Should I include the covariate file in both step 1 and step 2, or is it already integrated in step 1's results?

Many thanks!!

**Comment by joellembatchou** [comment]
1 - Yes we still recommend to include PCs as covariates.
2 - Covariates should be specified in both step 1 & step 2.

Cheers,
Joelle
