### ISSUE TITLE
Force tested allele?

### ISSUE THREAD

**Issue by alyssacl** [rgcgithub/regenie#422]
Is there a way to force tested allele in regenie?

**Comment by joellembatchou** [comment]
Hi,

You cannot do that directly in REGENIE (ie it determines allele based on genotype file though you can use `--ref-first` with BGEN/BED format to switch the reference allele across all sites). You could add a post-processing step where you flip beta if you want to switch the tested allele. Also, software like [PLINK](https://www.cog-genomics.org/plink/2.0/data#ref_allele) have options to set the reference allele.

Cheers,
Joelle
