### ISSUE TITLE
Are there any differences between `--phenoCol` and `--phenoColList`? Can both be used interchangeably safely?

### ISSUE THREAD

**Issue by etrh** [rgcgithub/regenie#428]
Does it matter which one I use if I want to list 100 phenotypes for example? I understand that one is comma-separated and the other should be done like this `--phenoCol p1 --phenoCol p2 --phenoCol p3 --phenoCol p4 ... --phenoCol p100`. But under the hood, does regenie interpret these differently for statistics or for any other thing? Thanks

**Comment by joellembatchou** [comment]
Hi,

No, you can use either option.

Cheers,
Joelle
