### ISSUE TITLE
Question about different N number in step 1 and 2 

### ISSUE THREAD

**Issue by ImFran** [rgcgithub/regenie#431]
Hi, 
i am new to REGENIE and I was wondering why my N number are different when performing the step 1 (N=2059) and the step 2 (N=392). 
I assumed that the number in my step 2 was the same in the step 1, due to the fact that I used the same pheno and covar files. 
It is due to the imputed genotypes files or other problems that probably I am missing?
How should I fix it?

Thank you for your kind help, 
Francesca

**Comment by joellembatchou** [comment]
Hi Francesca,

Could you include the logs of your step 1 & 2 runs?

Thanks,
Joelle

**Comment by ImFran** [comment]
Dear Joelle, 
thank you for your reply. 
Attached the .log of the two steps.


[LOG.chr13.regenieStep2.txt](https://github.com/rgcgithub/regenie/files/12231014/LOG.chr13.regenieStep2.txt)
[LOG.regenieStep1.txt](https://github.com/rgcgithub/regenie/files/12231015/LOG.regenieStep1.txt)

**Comment by joellembatchou** [comment]
Hi Francesca,

Can you check the FID/IID specified in genotype files and if they match those in the phenotype file?

For example in step 1 PLINK BED files (assumes phenotype file is tab-delimited)
> grep -cwFf <(cut -f1,2 PHENOMENA_4RegenieSTEP1.fam | tr ' ' '\t') filePheno_avNVS_Regenie_2.txt

For step 2 PLINK PGEN files:
> grep -cwFf <(cut -f1,2 PHENOMENA_13.Step2.psam | tail -n +2 ) filePheno_avNVS_Regenie_2.txt

Cheers,
Joelle
