### ISSUE TITLE
Is the --bgi option deprecated in regenie 3.2.9?

### ISSUE THREAD

**Issue by dianacornejo** [rgcgithub/regenie#436]
Hello, I'm trying to run some code like below in the DNAnexus RAP system by using an applet and it's giving me the error 
```ERROR: Option ‘bgi’ does not exist```

The code I'm running is:

```
regenie \
--step 2 \
--threads=16 \
--bgen=toy_data_chr1.bgen \
--bgi=toy_data_chr1.bgen.bgi \
--sample=toy_example.sample \
--ref-first \
--phenoFile=pheno_toy.tsv \
--covarFile=covar_toy.tsv \
--pred=fit_bin_out_pred.list  \
--bt \
--bsize=1000 \
--firth  \
--approx  \
--out test_1
```

I'm not sure if there's something wrong with the code that I cannot see or simply the `--bgi` option has been deprecated in newer versions of the software. I'll appreciate any insight. thank you

**Comment by joellembatchou** [comment]
Hi,

Option `--bgi` was introduced in [v3.2.8](https://github.com/rgcgithub/regenie/releases/tag/v3.2.8), which version are you using? Note that in your use case where the BGI file name matches with that of the BGEN file (ie <BGEN_FILE>.bgi), you don't need to specify option `--bgi`; REGENIE will automatically look for the BGI file with that name pattern and if it exists it will use it.

Cheers,
Joelle
