### ISSUE TITLE
Phenotype-dependent sample inclusions with `--remove`

### ISSUE THREAD

**Issue by msponcey** [rgcgithub/regenie#437]
Hello all, 

I am running GWASs in the UKB on around 50 traits for which the sample inclusions differ by phenotype due to different control criteria and excluded testing sets. 

The documentation states that "also, multiple files can be specified for --extract/--exclude/--keep/--remove by using a comma-separated list"; this feature would seem to apply in my case. However, a previous issue (https://github.com/rgcgithub/regenie/issues/119) posted here implies that the use of multiple files passed to `--remove` will apply each exclusion criteria to individuals across *all* phenotypes. 

Is there an option in REGENIE that allows for phenotype-dependent sample exclusions? If not, I imagine any other parallelization scheme will not take advantage of the unique capabilities of REGENIE when analyzing many phenotypes.

Best,
Spencer

**Comment by joellembatchou** [comment]
Hi Spencer,

We recommend to run multi-trait REGENIE across phenotypes that share similar missingness patterns (<15% missingness per-trait) as REGENIE will perform mean-imputation for the missing values in step 1 (in step 2 it analyzes only the non-missing samples for each trait). The sample exclusion filters are applied to all traits so it is best to cluster traits based on missingness patterns and run REGENIE on each trait cluster.

Cheers,
Joelle
