### ISSUE TITLE
 Inquiry Regarding Genetic Burden Analysis Using Regenie in UK Biobank

### ISSUE THREAD

**Issue by Li-mengjie** [rgcgithub/regenie#438]
Hi,

I hope this message finds you well. I am currently using Regenie to perform a genetic burden analysis for single gene mutations within the UK Biobank dataset. Specifically, I have executed step 2 of the analysis, utilizing the --extract-setlist option to specify the set of single gene mutations for analysis. I have a few questions regarding my approach and the output I obtained.

Firstly, I am uncertain about the appropriateness of my methodology. By solely running step 2 and employing the --extract-setlist parameter, am I on the right track for conducting a single gene mutation burden analysis?

Additionally, I am interested in acquiring insights into the mutation distribution for the included population, as well as obtaining mutation profiles for each participant. Is it possible to achieve this using the current methodology?

Lastly, I attempted to incorporate the write-samples parameter; however, the output provided only the FID and IID identifiers for participants included in the analysis. How can I extract more comprehensive information while utilizing this parameter?

I greatly appreciate your expertise in this matter and look forward to your guidance. Thank you for your time and assistance.

**Comment by joellembatchou** [comment]
Hi,

> Firstly, I am uncertain about the appropriateness of my methodology. By solely running step 2 and employing the --extract-setlist parameter, am I on the right track for conducting a single gene mutation burden analysis?

Yes this option is what you want to use to focus the association analysis on specific genes. As you are analyzing UKB, did you do some QC to handle relatedness/population structure as it seems you are bypassing step 1?

> Additionally, I am interested in acquiring insights into the mutation distribution for the included population, as well as obtaining mutation profiles for each participant. Is it possible to achieve this using the current methodology?

Do you mean like average number of ALT alleles across individuals for specific gene region? REGENIE will report allele frequencies for the burden masks which are obtained by collapsing all variants in gene together.

> Lastly, I attempted to incorporate the write-samples parameter; however, the output provided only the FID and IID identifiers for participants included in the analysis. How can I extract more comprehensive information while utilizing this parameter?

That is the intended behavior of that option (see doc [here](https://rgcgithub.github.io/regenie/options/#options)). Please be more specific as to what extra information you want REGENIE to provide.

Cheers,
Joelle
