### ISSUE TITLE
Why is it impossible to run step 1 with 22 separate .bed files on each chromosome?

### ISSUE THREAD

**Issue by jennyujin22** [rgcgithub/regenie#439]
Dear regenie team,

This is yujin kim who is a graduate student in South Korea.

First, thank you for your awesome tool.
 
I'm new to regenie and my knowledge of statistics is limited..

Could you please explain the statistical reason why step 1 cannot be run with 22 separate bad bim fam files on each chromosome ? #212 (https://github.com/rgcgithub/regenie/issues/212)

I just assume that Genotype matrx(G) have to cover the whole genome for estimating each SNP effect size.

I'd greatly appreciate any help you can offer. Thank you

Best regard,

Yujn kim

**Comment by joellembatchou** [comment]
Hi,

It is more of a implementation limitation; we did not add functionality for REGENIE to parse genetic data across multiple files  It is possible  to do but we currently do not have bandwidth to implement this and it is not a high-priority feature.

Cheers,
Joelle
