### ISSUE TITLE
 PgrGet1D() error 6 with pgen file

### ISSUE THREAD

**Issue by dorks81** [rgcgithub/regenie#44]
Hi I ran a quantitative analysis using bgen files (step2) which worked great without any problems. I now want to run the same analysis with pgen files but received an error during step2. I am using the same step1 file for both the bgen and pgen step 2 inputs. I am using regenie v1.0.6.4

Thank you

Options in effect:
  --step 2 \
  --pgen pgen/chr22/chr22.1 \
  --covarFile quant.covar.txt \
  --phenoFile quant.txt \
  --pred quant_pred.list \
  --keep keep.samples \
  --gz \
  --bsize 1000 \
  --pThresh 0.01 \
  --threads 4 \
  --verbose \
  --out chr22.1.pgen_firth

Chromosome 22 [66 blocks in total]
   -reading loco predictions for the chromosome...done (573ms)
block [1] : done (36832ms)
block [2] : done (37752ms)
block [3] : PgrGet1D() error 6

**Comment by joellembatchou** [comment]
Hi,

This error message is generated from the PGEN library so I will have to take a closer look to see what it corresponds to. In the meanwhile, I've made a small change in the functions which calls onto the PGEN library to read in the genotype data (commit https://github.com/rgcgithub/regenie/commit/d99bf2de4e15d06229d4c10036c48605afaa5535). Could you re-compile and check if that addresses your issue?

Cheers,
Joelle
