### ISSUE TITLE
Asking for suggestions for permutation test

### ISSUE THREAD

**Issue by saulpierotti** [rgcgithub/regenie#444]
Hi, thanks a lot for developping REGENIE.
I am planning to set a significance threshold via permutation testing and wanted to ask your opinion on when is it most appropriate to perform the permutations.

My intuition would be to perform step1 without permutation (so to get correct LOCO whole-genome corrections) and then permuting the phenotype x times before running step 2.

Does this make sense or do you think is better to permute before step1?

**Comment by joellembatchou** [comment]
Hi,

Are you talking about permuting the residualized phenotype (i.e. after projecting out the step 1 predictions & other covariates [e.g. PCs])? If it is the raw phenotype then I don't think it would make sense to permute the trait at step 2 and use the step 1 predictions based on the original trait since the entries won't match to the same individuals.

Cheers,
Joelle

**Comment by saulpierotti** [comment]
No I would permute the genotypes so that the phenotypes still align to the correct predictions... Just the gt would be mismatched to the prediction/pheno (null hypotesis of no effect), and would jointly permute all the GT to maintain the LD structure.

**Comment by saulpierotti** [comment]
Sorry I mis-explained in the original question, I meant to permute the phenotypes and predictions jointly, or equivalently to permute the GT

**Comment by joellembatchou** [comment]
Yes then in that case I think it is fine permuting at step 2 stage.

**Comment by saulpierotti** [comment]
Thanks!

**Comment by Richard1F** [comment]
Hi! Just a follow-up question. Considering the input-output nature of running Regenie for obtaining a p-value, does it make sense to permute the raw phenotype data before step 1 and then rerun the whole step1+step2 based on the permuted phenotype as a 'null control'. Thanks!

**Comment by yjf326** [comment]
Hi, just a follow-up question. I would like to know whether it makes sense to permute the raw phenotype data before running regenie and then rerun the step1+step2 to obtain the null p-value. My thought was that given the input-output nature of association analysis, it will also work well but I am not sure. Any insight? Thanks!

**Comment by joellembatchou** [comment]
Right you could do it that way but then this would be quite computationally intensive as you would need to run step 1 & 2 for each permuted phenotype replicate.
