### ISSUE TITLE
handling non-float AFREQ in `--aaf-file`

### ISSUE THREAD

**Issue by hassanfa** [rgcgithub/regenie#446]
For gene burden testing when supplying a file with AF via `--aaf-file`, at https://github.com/rgcgithub/regenie/blob/80413caac605e8c2eb30ec29dca53e76e181f2bd/src/Geno.cpp#L3566 and/or https://github.com/rgcgithub/regenie/blob/80413caac605e8c2eb30ec29dca53e76e181f2bd/src/Geno.cpp#L3592 it tries to convert the string to float as much as possible via `stof`. But `stof` fails when facing a non-float in the second column.

For example, providing an aaf-file (from Gnomad's AF) with the following structure:
```
1-20620-C-T 0.301119
1-20628-A-G 0.404054
1-21674-C-T 0.0531183
1-24912-G-A 0.0841655
1-28253-G-C 0.03125
1-28343-G-C .
1-28354-C-T 0.0989583
1-28376-G-A 0.0989583
1-28376-G-C 0.0989583
1-28494-T-C 0.0989583
1-28511-G-A 0.134752
```
will not inform the user what the error is. And regenie will throw the following error:
```
Error: stof
```
and exit.

I think either updating document or skipping the AFs that cannot be converted to float may come handy.

**Comment by joellembatchou** [comment]
Hi,

We recommend you pre-process the AAF file to remove entries with "." prior to passing it to REGENIE (we will make that clearer in the documentation).

Cheers,
Joelle
