### ISSUE TITLE
the --sex-specific option

### ISSUE THREAD

**Issue by humanpaingeneticslab** [rgcgithub/regenie#447]
Hello,

If I use regenie with the "--sex-specific female" option and I specified a SEX column in the covariables file: what happens? The SEX column will have no variation - so it's essentially constant. Is that covariable removed from the covar matrix? Is it left in the covar matrix because it would be mathematically benign?

Thanks!

**Comment by joellembatchou** [comment]
Hi,

REGENIE applies a transformation to the covariate matrix to remove collinear variables (so sex would be removed as it would be perfectly correlated with the intercept column).
Note that the sex information for "--sex-specific" is taken from the genotype file (i.e. FAM/PSAM file for PLINK input or SAMPLE file for BGEN). 

Cheers,
Joelle
