### ISSUE TITLE
Regenie v1.0.6.7 pre-compiled fails on missing "libmvec."

### ISSUE THREAD

**Issue by jbsysadmin** [rgcgithub/regenie#45]
Greetings.
When doing the following:

ldd /nfs/<internal_share>/regenie-1.0.6.7/regenie_v1.0.6.7.gz_x86_64_Linux

I get:

`libmvec.so.1 => not found`

Can this be resolved within Centos 7.x?

I resorted to the binary because the build-from-source process of dependency bgen-1.1.7 doesn’t consolidate or assemble everything that regenie build needs. No combination of PATH/LD_LIBRARY_PATH remedies that. ( I had a custom-compiled gcc-9.3-x86_64 for that attempt.)

**Comment by joellembatchou** [comment]
Hi,

A regenie binary for Centos 7 is available at https://github.com/rgcgithub/regenie/releases/tag/v1.0.6.7. Alternatively, you should specify the path to the BGEN library after installing it using `make BGEN_PATH=<path_to_BGEN_library>`.

Cheers,
Joelle
