### ISSUE TITLE
Different result between regenie and plink

### ISSUE THREAD

**Issue by genoplan-ian** [rgcgithub/regenie#453]
Hello. 
I performed a GWAS analysis using regenie and Plink, but the results are significantly different. 
I've attached the logs for each analysis and the Manhattan plots of the results. 

regenie log & manhattan
![image](https://github.com/rgcgithub/regenie/assets/111419807/bba27d32-3a61-40d9-89c0-d7aeccce5453)
![image](https://github.com/rgcgithub/regenie/assets/111419807/b7165019-172e-4a07-b89e-f3dad636ad33)

plink log & manhattan
![image](https://github.com/rgcgithub/regenie/assets/111419807/af5c29e3-a866-4a2f-895c-66e3334d98e5)
![image](https://github.com/rgcgithub/regenie/assets/111419807/eb77ad5d-836a-4e5a-9d6e-733f82097c65)

The version of regenie I used is 3.2.9, and I used Plink2.

if there are any issues with my analysis process or if you know the root causes, I would greatly appreciate your help.

Best regards, 
Ian

**Comment by dianacornejo** [comment]
@genoplan-ian Do you have related individuals in your sample? Regenie is a LMM that can deal with that type of case whereas Plink does not (possibly generating lots of false positives). Also is your trait binary, quantitative?

**Comment by genoplan-ian** [comment]
Hi diana,

To address your two questions, firstly, we applied --rel-cutoff 0.125 of Plink to remove related individuals. Secondly, we conducted both binary and quantitative trait analyses, and both yielded similar results. The example image attached is the result of the binary trait analysis, which used --bt --firth --approx --pThresh 0.01, while the quantitative trait analysis employed --apply-rint.

**Comment by joellembatchou** [comment]
Hi,

Can you include the full logs from REGENIE and PLINK?

**Comment by genoplan-ian** [comment]
[plink_gwas.log](https://github.com/rgcgithub/regenie/files/13343136/plink_gwas.log)
[regenie_step1.log](https://github.com/rgcgithub/regenie/files/13343279/regenie_step1.log)
[regenie_step2_chr22.log](https://github.com/rgcgithub/regenie/files/13343280/regenie_step2_chr22.log)

Hi,

I am attaching the Regenie step1, step2, and Plink GWAS analysis logs.
The data used for both Regenie and Plink analyses is identical.

The input data names in the log files have been intentionally modified.

**Comment by joellembatchou** [comment]
Can you check the estimated odds ratio scatterplot to see if the difference is also present in the effect sizes?

And can you include the sumstats output for a few of those top hits on chr6 & 7 (you can blank variant info) for both PLINK and REGENIE?

**Comment by genoplan-ian** [comment]
![OR_plink_regenie](https://github.com/rgcgithub/regenie/assets/111419807/f909413c-6d58-4ed4-8ba1-a6d43a97f638)
I am attaching the OR plots based on the positions of CHR6 and CHR7 (REGENIE exponentiated BETA).
The effect sizes seem quite similar between the two.

[plink2_gwas_significant.txt](https://github.com/rgcgithub/regenie/files/13370849/plink2_gwas_significant.txt)
[regenie_gwas_significant.txt](https://github.com/rgcgithub/regenie/files/13370850/regenie_gwas_significant.txt)

Additionally, I am attaching the GWAS summary statistics for the loci that were significant in plink2 (SNPID, CHR, POS have been removed).

**Comment by genoplan-ian** [comment]
Oh, I've identified the part where I made a mistake. Thank you for your assistance.
