### ISSUE TITLE
Can regenie take different covariates for different phenotypes?

### ISSUE THREAD

**Issue by Aliceinwonderland821** [rgcgithub/regenie#455]
Hi regenie developers,

Can regenie take different covariate list for different phenotypes through --covarColList option? 
e.g. I have Phenotype A, B, C, and I want to use ageA, ageB, ageC as covariates for each of the phenotype. Can I specify those in regenie?

Thank you

**Comment by joellembatchou** [comment]
Hi,

REGENIE applies the input covariates to all phenotypes analyzed so you would need to perform separate runs.

Cheers,
Joelle
