### ISSUE TITLE
Computing burden without association to phenotype

### ISSUE THREAD

**Issue by scienception** [rgcgithub/regenie#458]
Hi I'd like to compute the burden, meaning the number of SNPs with MAF<0.01 within a gene using Regenie. I AM NOT interested in doing an association test, so I guess I have to provide a dummy phenotype file.

I am interested in getting for each person whether it has 0 variants, heterozygous variants or homozygous variants. I have been struggling to find the correct flag for producing such output.

Any help would be appreciated.

**Comment by joellembatchou** [comment]
Hi,

Please look [here](https://rgcgithub.github.io/regenie/options/#example-run) for an example run to compute and write out burden masks. A modified version for your use case would be like

```{bash}
./regenie \
  --step 2 \
  --bed genofile \
  --phenoFile dummy_pheno.txt \
  --ignore-pred \
  --anno-file anno_file.txt \
  --set-list set_file.txt \
  --mask-def mask_file.txt \
  --aaf-bins 0.1,0.05 \
  --write-mask \
  --write-mask-snplist \
  --bsize 200 \
  --out compute_masks
```

Indeed, you do have to provide a dummy phenotype file and here we can use `--skip-test` to skip the association testing. Also, you can use `--write-mask-snplist` if you want to know which variants went into the burden masks.

Cheers,
Joelle
