### ISSUE TITLE
Burden test results missing values for ALLELE0, ALLELE1, A1FREQ, BETA, SE

### ISSUE THREAD

**Issue by zillurbmb51** [rgcgithub/regenie#465]
Hi,

I was trying to run burden test using regenie in ukbiobank. My command was as follows:
```
for i in {1..22}; do
    run_regenie_burden="regenie \
    --step 2 --pred fit_snps_chr${i}_pred.list \
    --bgen ukb23159_c${i}_b0_v1.bgen \
    --ref-first \
    --sample ukb23159_c${i}_b0_v1.sample \
    --phenoFile lipid_pheno_sep13_with_labels_caucasian_norealtive.csv \
    --covarFile covarite_sep23_age_sex_20pc.csv \
    --set-list ukb23158_500k_OQFE.sets.txt.gz \
    --anno-file ukb23158_500k_OQFE.annotations.txt.gz \
    --mask-def ldl_custom_masks.txt \
    --aaf-bins 0.01,0.001 --nauto 23 \
    --bsize 200 --extract-sets nmr_gene_sets_ready.txt \
    --write-mask-snplist \
    --vc-tests skato,acato-full \
    --out metabolimics_skato_acato_chr${I}"
done
```

It gives me summary stats with CHR, GENPOS, LOG10P etc (attached). But the results is missing values for the above mentioned columns. Not sure what I did wrong. Any help?
[metabolimics_skato_acato_chr9_VLDL_Cholesterol.regenie.txt](https://github.com/rgcgithub/regenie/files/13265723/metabolimics_skato_acato_chr9_VLDL_Cholesterol.regenie.txt)
[VLDL_Cholesterol_merged.regenie.txt](https://github.com/rgcgithub/regenie/files/13265724/VLDL_Cholesterol_merged.regenie.txt)

**Comment by Lloyd-LiuSiyi** [comment]
Hi @zillurbmb51, I've faced exactly the same problem. Did you find any clue?

**Comment by Lloyd-LiuSiyi** [comment]
Hi @zillurbmb51, I had similar NA values for those columns you mentioned. Developers have clarified in issues #327 and #319 that since SKAT is a joint test it does not yield an estimated effect size. So there's nothing you did wrong.
Hope you find it helpful.

**Comment by joellembatchou** [comment]
As @Lloyd-LiuSiyi mentioned, this is expected behavior for the gene-based tests that do not compute effect sizes like SKAT and ACAT-V.
