### ISSUE TITLE
Chi square param was -nan, but must be > 0 !

### ISSUE THREAD

**Issue by dineshpeace** [rgcgithub/regenie#468]
Hi I am working on chromosome segment of 20 MB, associating quantitative variables for ~20 K samples.
Script is as below  
![image](https://github.com/rgcgithub/regenie/assets/34877292/2e6beb45-2915-44cc-ac23-e71ab6148d03)
Error observed below
![image](https://github.com/rgcgithub/regenie/assets/34877292/cbc85019-137d-417b-9b16-35d0df65ea35)

To add some further background, in Step 1, the loco file was successfully generated in accordance with expectations. We are experiencing this error specifically in Step 2, and we haven't been able to identify the source after carefully reviewing all of the documentation and performing integrity checks on the input data.

The same script works fine, when I remove the related samples by plink threshold of 0.175.

Kindly suggest
Dinesh

**Comment by joellembatchou** [comment]
Hi Dinesh,
 
Which REGENIE version are you using (if not the latest, can you try with the latest REGENIE [v3.3](https://github.com/rgcgithub/regenie/releases/tag/v3.3))? 
 
If the error persists, can you re-run with `--debug --nb 5` and attach the corresponding step 2 log file? 
Also, can you try selecting a single phenotype (using `--phenoCol`) and see if the error persists?
 
Cheers,
Joelle
