### ISSUE TITLE
step1 with step 2 used same variant

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [rgcgithub/regenie#469]
hi Dear
 if I use Whole Exome Sequencing (WES) variants in the first step of Regenie, and then use the same variants in the second step, will it affect the results?

hq

**Comment by joellembatchou** [comment]
As @Lloyd-LiuSiyi suggested, we recommend running set 1 on a set of variants that has genome-wide coverage and then run step 2 on an extended set of variants like from WES or imputed data.

Cheers,
Joelle
