### ISSUE TITLE
Difference between logisitc regression coefficients and SE with --ignore-pred flag in step 2

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#47]
Hi REGENIE team,

First, congrats/thanks for the great and efficient regenie!
I have a general question regarding step 2 with`--ignore-pred` flag. So, because no prediction input from step 1 exists, regenie performs a simple logistic regression in such a case. However, I realized there is a difference between estimated coefficients and standard errors in this case compared to for example R `glm` output. This is especially the case for rarer variants. As an example, I tested a variant with MAF of ~0.001 (under both additive and dominant models, with a sample size ~430 K), and coefficients from `glm` and regenie were -0.197 and -0.179, and SEs were 0.449 and 0.408, respectively (although their X2 are quite similar). I was wondering what may be happening here? 
The difference between coefficients and SE becomes small as the MAF increases (I tested for another variant with MAF of ~0.27).

Appreciate your help!
Best/Oveis

P.S: no SPA or Firth was applied here.

**Comment by joellembatchou** [comment]
Hi,

Regenie uses a logistic regression score test whereas in R's `glm` function a Wald test (these are asymptotically equivalent tests but we chose a score test in Regenie as it uses SE estimates based on the null model).

Cheers,
Joelle

**Comment by Ojami** [comment]
I see. Tanx for the clarification!

Best
