### ISSUE TITLE
Output p-value format of Regenie

### ISSUE THREAD

**Issue by evatosco** [rgcgithub/regenie#473]
Hello there!

I have some questions about the output p-value field of Regenie and its interpretation. I have seen in the paper that you consider "p-values in REGENIE-FIRTH and SAIGE below 0.05 (fallback p-value threshold for Firth/SPA correction, respectively)" for variants in supplementary tables, but when I look at the gene-based (or region-based) tests output directly, the column name suggests that p-values are in a different format:

```
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA.Y1 SE.Y1 CHISQ.Y1 **LOG10P.Y1** EXTRA
1 33773016 A1.M1.singleton ref M1.singleton 0.00122249 818 ADD 0.814433 1.59121 0.261971 0.215547 NA
1 33773016 A1.M1.0.01 ref M1.0.01 0.0018315 819 ADD 0.185867 1.33284 0.0194466 0.0510524 NA
1 33773016 A1.M1.all ref M1.all NA 822 ADD-ACATO NA NA 0.0194466 0.0510524 NA
1 33773016 A1.M1.all ref M1.all NA 822 ADD-ACATV NA NA 0.0194466 0.0510524 NA
```
The column name for the p-value is _**LOG10P.Y1**_. So I would really need to confirm if these p-values are actually log(10) of the real p-value, or how they actually are calculated, to adjust my significance thresholds.

If I need to select as significant genes those with a plain p-value < 0.001, for example, how would I have to do that? Would the threshold be -log(p-value) < 3 then (with the minus sign)?
Also, how would you recommend to adjust for multiple testing? Including all genes as the total or including all tests even if each gene has been tested more than once, including different types of tests?

Sorry in advance if this is a newbie question but I can't find the clarification in the release paper and that "log" in the column name has confused me a lot.

Thanks!
Eva

**Comment by joellembatchou** [comment]
Hi Eva,

LOG10P.Y1 refers to the -log10(p-value) for the association test between the variant and the first phenotype.

> If I need to select as significant genes those with a plain p-value < 0.001, for example, how would I have to do that? Would the threshold be -log(p-value) < 3 then (with the minus sign)?

You'd filter to variants where log10(p) > 3.

> Also, how would you recommend to adjust for multiple testing? Including all genes as the total or including all tests even if each gene has been tested more than once, including different types of tests?

You can adjust for number of genes as well as statistical tests performed (e.g. burden, skat, acat-v, ...).

Cheers,
Joelle
