### ISSUE TITLE
Error running an analysis

### ISSUE THREAD

**Issue by akhilpampana** [rgcgithub/regenie#474]
Hello, 

I have performed gwas analysis using regenie on an overall dataset of 480k individuals in ukbiobank. I haven't had any issues with the analysis run. Phenotypes generated are normalized residuals as was performed in recent ukbiobank nature papers. But when I am trying to perform a race-stratified analysis with the race-stratified residuals generation for the phenotype, I am getting nan loco values in the null model. I am not sure what could be the issue. May I know how to resolve this or suggest any workaround to bypass the issue?

The analysis was performed on chromosome X and here is the code I have been using to run the analysis 

Residuals were generated by means of linear regression accounting for all the covariates that were used in the recent proteomics paper. 

```
./regenie_v3.2.9.gz_x86_64_Linux_mkl --step 1 --bed merged_chrx --phenoFile pheno.txt --keep eur_hare_our.samples --bsize 1000 --phenoColList pheno --out chrx_eur 
```

Regards
Akhil

**Comment by akhilpampana** [comment]
Any updated would be appreciated

**Comment by joellembatchou** [comment]
Hi,

REGENIE step 1 is meant to be run on a set of variants capturing genome-wide coverage (not just on a single chromosome). Check [FAQ](https://rgcgithub.github.io/regenie/faq/#step-1).

Cheers,
Joelle
