### ISSUE TITLE
Regenie produces inflated P-values

### ISSUE THREAD

**Issue by Hepit** [rgcgithub/regenie#475]
Hello,

I was recently using regenie to run a gwas for which I didn't expect more than a few dozen significant hits, and ended up getting several tens of thousands. Out of curiosity, I reran the logistic association on a few hundred variants using regenie (--ignore-pred), plink, and R's glm(). R and plink output P-values that are very close to each other, and then regenie's are a fair amount more significant. (Logistic regression was run with the same two covariates and set of samples in all cases.)

As you can see in the graph below, R in red and plink in green overlap perfectly, and regenie in blue is above. Also the y-axis label is erroneous and should read -log10(p).

Is this expected despite the inclusion of --ignore-pred?

Logs are attached just in case.

Thanks !
[sample_p-values.tsv.txt](https://github.com/rgcgithub/regenie/files/13602737/sample_p-values.tsv.txt)
[step2_nopred.log](https://github.com/rgcgithub/regenie/files/13602738/step2_nopred.log)
[plink.log](https://github.com/rgcgithub/regenie/files/13602740/plink.log)
![plink_vs_regenie_P_comparison](https://github.com/rgcgithub/regenie/assets/84938795/fec49ed0-ec49-42ca-bc20-947c20a516b6)

**Comment by Hepit** [comment]
Good point about the firth - that seems to have resolved the issue. For the record, I'm including an updated version of the graph from my previous post. 
![plink_vs_regenie_P_comparison_100snps](https://github.com/rgcgithub/regenie/assets/84938795/8f28af60-c8f6-4cf2-b03a-30e2bbc44769)



However, I did go back and run the same thing on a few thousand variants instead of just 100, and on a few rare occasions there was a noticeable difference between the p-values, as you can see on the second graph below (eg at that blue dot right before the 2000 mark, plink p = 0.034, regenie p = 0.0038). (Black lines mark P = 0.05 and P =  0.01.)

![plink_vs_regenie_P_comparison_3000snps](https://github.com/rgcgithub/regenie/assets/84938795/1fa369b1-cee5-40e8-9745-bdac475a2d8a)


As far as I'm concerned that's not a huge problem and I'd consider this resolved, but I figured I'd point it out in case you wanted to address it. I'm attaching [a stats file](https://github.com/rgcgithub/regenie/files/13746387/stats_comparison.tsv.txt) (regenie output + plink output) for that blue outlier and the other one to its right. (Also I'm running this on ~250 000 samples, and all variants have MAC >= 5.)

Thanks for your help !

**Comment by joellembatchou** [comment]
I noticed for these two variants you included that "FIRTH?_plink" column is N which I believe indicates Firth not being used in PLINK? P_regenie_nofirth is closer to P_plink though difference could be due to the different tests being used (REGENIE uses score test whereas PLINK uses Wald) though these are asymptotically equivalent.

**Comment by Hepit** [comment]
Good to know. Thanks again for your help !
