### ISSUE TITLE
Viewing level 0 predictions saved by keep-l0

### ISSUE THREAD

**Issue by rafmagnus** [rgcgithub/regenie#478]
Hi.
I recently ran REGENIE using the --keep-l0 option to inspect the predictions from the level 0 model. However, these files (e.g. *_job1_l0_Y) are on a binary format and I don't seem to be able to figure out the structure of these files to inspect. 
How would one go around inspecting the contents of these files? 
Br.

**Comment by joellembatchou** [comment]
Hi, 

The file stores a NxP matrix of level 0 predictors column-wise, where N are samples and P are the ridge predictors (the order of samples is the same as that in the genotype data [e.g. fam file with PLINK BED]). 

Cheers,
Joelle

**Comment by rafmagnus** [comment]
So something like this seems to work (in python code)

import struct
import numpy as np

n = #number of samples
p = #number of ridge values

data_type = 'd'
element_size = struct.calcsize(data_type)

with open('*_job1_l0_Y', 'rb') as file:
    binary_data = file.read()

format_string = '<' + data_type * (len(binary_data) // element_size)
matrix_data = struct.unpack(format_string, binary_data)

matrix = np.array(matrix_data).reshape((n, p))
