### ISSUE TITLE
Suggestions to improve user experience

### ISSUE THREAD

**Issue by ecirulli** [rgcgithub/regenie#48]
Hi, I love the easy use and quick speed of REGENIE. I've just used it to do analyze a few thousand phenotypes in some large exome cohorts and had a few suggestions to improve the user experience.
1) The frequency of the variants is in the results (.regenie) file, but it isn't broken down by counts in cases and ctrls. I had been using SAIGE prior to this and really appreciated that SAIGE gave the option to give the case and ctrl carrier counts and total sample sizes in the results. This saves me from subsequent processing steps.
2) I love being able to run 50 phenotypes at a time in REGENIE and the speedup that ensues. However, I have noticed that when one of the 50 phenotypes has a problem (such as the sample size being too small for 5-fold cross-validation), the entire step 1 run fails and stops. This can mostly be gotten around by setting sample size cutoffs and/or switching to --loocv, but it would be nice if one bad phenotype didn't stop the others from running, and/or if it automatically switched to --loocv when there weren't enough cases for the usual cross validation.
3) I notice that with case sample sizes <250, the model in step 1 will fail to converge about 1-2% of the time (I'm sure this varies by dataset), and it's more likely to fail to converge as the sample size decreases (the error is 'Level 1 logistic did not converge. LOCO predictions calculations are skipped.'). While this doesn't cause step 1 to fail, when I then try to run step 2, even on just 1 phenotype that worked in step 1, then step 2 will fail with the error that the pred.list file doesn't include  50 files. I can get around this by hacking the list file to include another filename and creating a fake version of the corresponding file, but it would be a lot more straightforward if step 2 simply didn't require that all 50 (or however many) files be present and could handle missing a few of them.

Thank you, and I've really enjoyed using this software!

**Comment by joellembatchou** [comment]
Hi,

Thank you for the very helpful feedback! To further address some of your points:
(1) There is an option `--htp COHORT_NAME` you can use which will give you a more detailed output for the step 2 results (genotype counts broken down by cases/controls as well as other information).
(2) Great point, the default behavior of Regenie is to switch to LOOCV when the sample size is below 5K. I will look into also switching to LOOCV by default with low case counts as well (i.e. even if sample size is above 5K). Note that we have been working on reducing the failed convergence issues in the logistic regressions of step 1 with low case counts (most recent attempt is in Regenie v1.0.6.3).
(3) If you don't include the failed phenotype when using `--phenoCol/--phenoColList` options in step 2 of Regenie, then it should run fine as it won't look for the failed phenotype in the pred.list file. 
For example, as the phenotype name is in the first column of the pred.list file, you could use that to get the list of traits (e.g. `phenoList=$(awk '{print $1}' pred.list | paste -sd,)` and  in Regenie use `--phenoColList $phenoList`)


Cheers,
Joelle
