### ISSUE TITLE
regenie produces slightly different output depending on the number of phenotypes processed jointly

### ISSUE THREAD

**Issue by hguturu** [rgcgithub/regenie#486]
For example, if I run step2 with 10 phenotypes the statistics are slightly different than if I run step2 with 2 phenotypes with all other inputs the same. The numbers are different enough that `np.isclose` fails, but if I plot them out they are visually close enough (at least for one example file). This is using `regenie_v3.4.gz_x86_64_Centos7_mkl.zip` on Ubuntu 18.04. This trend seems to hold when I scale up to 50 phenotypes. Is this expected and is there a way to avoid? More generally I want to know if there are cases where these numeric differences get magnified and if its better for me to run phenotypes individually or jointly.

# Example
##  Run with 10 Phenotypes
```sh
./tools/regenie --step 2 --bed data/genotypes_filtered --ref-first --phenoFile phenotypes.tsv --covarFile covariates.txt \
    --covarColList Age,Age2,Age*Sex,Age2*Sex,PC{1:20} --catCovarList Centre,Sex --maxCatLevels 22 \
    --pred data/ukb_step1_pred.list --bsize 400 --threads 8 --apply-rint \
    --out all
```
## Run with 2 Phenotypes (3 and 5)
```sh
./tools/regenie --step 2 --bed data/genotypes_filtered --ref-first --phenoFile phenotypes.tsv --covarFile covariates.txt \
    --covarColList Age,Age2,Age*Sex,Age2*Sex,PC{1:20} --catCovarList Centre,Sex --maxCatLevels 22 \
    --pred data/ukb_step1_pred.list --bsize 400 --threads 8 --apply-rint \
    --phenoColList 3,5  \
    --out select35
```

## Logic to verify results - using phenotype 3 as example
```py
import pandas as pd
import numpy as np

# Load
all_3_df = (
    pd.read_table("all_3.regenie", sep=" ")
    .set_index(["CHROM", "GENPOS", "ID", "ALLELE0", "ALLELE1", "TEST"])
    .drop(columns=["EXTRA"])
)
select35_3_df = (
    pd.read_table("select35_3.regenie", sep=" ")
    .set_index(["CHROM", "GENPOS", "ID", "ALLELE0", "ALLELE1", "TEST"])
    .drop(columns=["EXTRA"])
)

# Check equivalence - most are not equivalent except for A1FREQ and N
all_3_df.eq(select35_3_df).agg(["all", "sum"])
# 	A1FREQ 	N 	BETA 	SE 	CHISQ 	LOG10P
#all 	True 	True 	False 	False 	False 	False
#sum 	12089 	12089 	20 	7 	7 	9

# Check if numerically close - again most aren't considered close
pd.Series(
    np.isclose(
        all_3_df[["BETA", "SE", "CHISQ", "LOG10P"]],
        select35_3_df[["BETA", "SE", "CHISQ", "LOG10P"]],
        equal_nan=True,
    ).sum(axis=0),
    index=["BETA", "SE", "CHISQ", "LOG10P"],
)
#BETA      87
#SE        48
#CHISQ     37
#LOG10P    60

# Plot
import seaborn as sns
join_df = all_3_df.join(
    select35_3_df, lsuffix="_all", rsuffix="_select35"
).melt(ignore_index=False)
join_df[["metric", "run_type"]] = join_df["variable"].str.split("_", expand=True)
join_df = join_df.drop(columns=["variable"]).set_index("metric", append=True)
sns.relplot(
    data=join_df.pivot(columns="run_type", values="value").reset_index(),
    x="all",
    y="select35",
    col="metric",
    col_order=["A1FREQ", "N", "BETA", "SE", "CHISQ", "LOG10P"],
    col_wrap=3,
    hue="metric",
    facet_kws={"sharex": False, "sharey": False},
)
```
![image](https://github.com/rgcgithub/regenie/assets/2645632/51a82b90-19d8-4645-8f37-40b40b48d10c)

**Comment by hguturu** [comment]
I now understand what is driving the difference. `regenie` drops a sample if its missing a value in all the phenotypes, but keeps it if it has a non-nan value in any phenotype.

E.g. If we are processing phenotypes 3, 5 and 6 and `sampleA` is has NA for 3 and 5, but a non-nan for 6. If we process all the phenotypes together the `sampleA` is retained, but if if we do `--phenoColList 3,5`, then `sampleA` is dropped. Unclear why this matters since without `--force-impute`, I thought `step2` doesn't test the samples with missing phenotypes anyways?

Looking at the log differences below it looks like `number of individuals used in analysis = 45012` for when only 3 and 5 phenotypes are selected and `number of individuals used in analysis = 45397` for when all the phenotypes are used. And when I checked it was indeed the case that for phenotpyes 3 and 5 only 45012 have non-nan at either spot. But its unclear why that translates to different statistics for each phenotype.


* Select 3 and 5
```
Association testing mode with fast multithreading using OpenMP
 * bim              : [./data/genotypes_filtered.bim] n_snps = 12968
 * fam              : [./data/genotypes_filtered.fam] n_samples = 45412
 * bed              : [./data/genotypes_filtered.bed]
 * phenotypes       : [./phenotypes.tsv] n_pheno = 2
   -number of phenotyped individuals  = 45012
 * covariates       : [./covariates.txt] n_cov = 26
   -number of individuals with covariate data = 45412
 * number of individuals used in analysis = 45012
   -applying RINT to all phenotypes
 * number of observations for each trait:
   - '3': 44219 observations
   - '5': 43968 observations
 * LOCO predictions : [./data/ukb_step1_pred.list]
   -file [/data/step1_1.loco.gz] for phenotype '3'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_2.loco.gz] for phenotype '5'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -residualizing and scaling phenotypes...done (0ms)
 * # threads        : [8]
 * block size       : [400]
 * # blocks         : [33]
 * approximate memory usage : 319MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)
```

* All
```
Association testing mode with fast multithreading using OpenMP
 * bim              : [./data/genotypes_filtered.bim] n_snps = 12968
 * fam              : [./data/genotypes_filtered.fam] n_samples = 45412
 * bed              : [./data/genotypes_filtered.bed]
 * phenotypes       : [./phenotypes.tsv] n_pheno = 10
   -number of phenotyped individuals  = 45397
 * covariates       : [./covariates.txt] n_cov = 26
   -number of individuals with covariate data = 45412
 * number of individuals used in analysis = 45397
   -applying RINT to all phenotypes
 * number of observations for each trait:
   - '3': 44219 observations
   - '5': 43968 observations
   - '6': 44219 observations
   - '9': 43401 observations
   - '12': 44041 observations
   - '14': 43633 observations
   - '17': 44457 observations
   - '19': 44637 observations
   - '20': 44721 observations
   - '24': 43633 observations
 * LOCO predictions : [./data/ukb_step1_pred.list]
   -file [/data/step1_1.loco.gz] for phenotype '3'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_2.loco.gz] for phenotype '5'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_3.loco.gz] for phenotype '6'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_4.loco.gz] for phenotype '9'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_5.loco.gz] for phenotype '12'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_6.loco.gz] for phenotype '14'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_7.loco.gz] for phenotype '17'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_8.loco.gz] for phenotype '19'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_9.loco.gz] for phenotype '20'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -file [/data/step1_10.loco.gz] for phenotype '24'
    + 1 individuals with missing LOCO predictions will be ignored for the trait
   -residualizing and scaling phenotypes...done (2ms)
 * # threads        : [8]
 * block size       : [400]
 * # blocks         : [33]
 * approximate memory usage : 327MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)
```

**Comment by joellembatchou** [comment]
Hi,

Please check the [missing phenotype data](https://rgcgithub.github.io/regenie/overview/#missing-phenotype-data) section on the website. REGENIE will mean-impute missing values so the step 1 output will be different using a subset of the phenotypes unless the missingness patterns is the same across all the phenotypes. This will carry over to step 2 where you will get slightly different p-values. This was also covered in the REGENIE paper where as you also find, there was small changes in the p-values between multi-trait and single-trait runs but the tradeoff in computational speed favored multi-trait runs. 

Cheers,
Joelle

**Comment by hguturu** [comment]
Hi Joelle, I am not re-running step 1 which does imputation and multi-trait runs. I am re-running only step 2 with the same step 1 models, which is why I was surprised when the results where different if I run step 2 on 2 phenotypes or 10 phenotypes since my understanding for step 2 is no imputation and each phenotype is handled separately. Unless I am misunderstanding step 2 and it also does multi-trait optimization.

E.g.
```
./tools/regenie --step 2 --bed data/genotypes_filtered --ref-first --phenoFile phenotypes.tsv --covarFile covariates.txt \
    --covarColList Age,Age2,Age*Sex,Age2*Sex,PC{1:20} --catCovarList Centre,Sex --maxCatLevels 22 \
    --pred data/ukb_step1_pred.list --bsize 400 --threads 8 --apply-rint \
    --out all
```
vs
```
./tools/regenie --step 2 --bed data/genotypes_filtered --ref-first --phenoFile phenotypes.tsv --covarFile covariates.txt \
    --covarColList Age,Age2,Age*Sex,Age2*Sex,PC{1:20} --catCovarList Centre,Sex --maxCatLevels 22 \
    --pred data/ukb_step1_pred.list --bsize 400 --threads 8 --apply-rint \
    --phenoColList 3,5  \
    --out select35
```

The only difference is the `--phenoColList 3,5` flag. All other inputs are the same.

**Comment by joellembatchou** [comment]
So in step 2, the step that projects out covariate effects is done once using all traits (where missing values are mean-imputed) but the association test ignores individuals who had missing phenotypes (this is only fo QTs; for BTs multi-trait and single trait analyses at step 2 will give the same results).

**Comment by hguturu** [comment]
Ah got it, that explains the difference! Thank you! And glad the differences are known to be small, so I will be fine running many traits in parallel.

The only risk, I have is I might have rather different missing rate profiles in the phenotypes, so I might have to investigate if I need to split the phenotypes up, because its hard for me to assess "similar missing rate profiles".

There is no way to force regenie to treat QT individually right?

**Comment by joellembatchou** [comment]
No, you would have to run them in separate REGENIE calls.

**Comment by hguturu** [comment]
Figured as much. Was hoping if there was a flag to do the runs to save on the extra overhead of reloading the data and common processing multiple times. But, this clarifies things. Thank you!
