### ISSUE TITLE
Question on plink files

### ISSUE THREAD

**Issue by scienception** [rgcgithub/regenie#489]
What does it mean for a person to have a genotype M1.0.01 M1.0.01 (a variant passing the filter in both "alleles"), when the data has not been phased?

**Comment by nshrine** [comment]
There is a deleterious homozygous variant in the set?

**Comment by joellembatchou** [comment]
Hi,

This would mean they are homALT for at least one of the markers included in that M1 1% mask. Check the [website diagram](https://rgcgithub.github.io/regenie/options/#options_1) explaining how the burden masks are constructed by default from the single variant sites.

**Comment by scienception** [comment]
Makes sense. Thank you! 
Just one more question. These AAF thresholds are based on what? In your documentation it's stated that it's not MAF. So what exactly is the ALT allele? what is taken as REF?
I wanted to filter by MAF<0.01. Is this possible?

**Comment by scienception** [comment]
Never mind, I just read about the AAF file. Just to be sure. The output of:
`plink2 --bgen file.bgen --sample file.sample --freq`, could serve as this file, am I right?

**Comment by joellembatchou** [comment]
Yes the output AAF from PLINK `--freq` can be passed to REGENIE with `--aaf-file`. Note that this file stores AAF so when using `--aaf-bins 0.01` in REGENIE, this would keep only variants with AAF<1% as determined by the input AAF file.

**Comment by scienception** [comment]
Thanks! I think PLINK1.9 outputs the MAF and not the AAF, which is what I need. In that case, passing the output of  `plink --bfile file  --freq` to `--aaf-file` will filter for MAF<1% right?
I'm interested only in getting the masks. Not on running association studies. (Just in case this is relevant).

**Comment by joellembatchou** [comment]
So REGENIE would not do any allele flipping; perhaps the best workaround is to generate a new genotype file where the REF allele is always the major one (e.g. in plink2 using `--maj-ref`) and then passing this file to REGENIE. As you are only interested in the masks, you can use `--skip-test` to skip the association testing.

Cheers,
Joelle
