### ISSUE TITLE
gene-based analysis

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#49]
Will regenie support gene-based analysis such as SKAT, SKAT-O etc. Thanks.

**Comment by joellembatchou** [comment]
Hi,

We are working on implementing gene based testing in Regenie; we will post on the main page when it is available.

Cheers,
Joelle

**Comment by xiekunwhy** [comment]
Hi,

Hoping gene based testing implemented coming soon.

Best,
Kun

**Comment by ggstatgen** [comment]
Hi Regenie developers,

Any updates on a gene-based testing implementation? Thanks so much for your work so far.

**Comment by joellembatchou** [comment]
Hi,

This is ongoing work and we will notify users when this feature is available.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Hi,

Just to update you that it is now possible in Regenie v2.0 to perform gene or region-based association testing. See [documentation](https://rgcgithub.github.io/regenie/options/#burden-testing) for more details.

Cheers,
Joelle

**Comment by ggstatgen** [comment]
Awesome - thank you very much for this Joelle.

May I just ask - does the team recommend to do pre-filtering of per-gene variants to avoid including mixing variants of opposite effect (if known- say putative LOF and GOFs) or say to remove low-confidence missense that might reduce power? My understanding is that some methods are more sensitive to this 'poor variant contamination' whereas other (eg SKAT) appear to be more robust.

Where does REGENIE stand wrt this? Many thanks for the work you're putting into this.

**Comment by joellembatchou** [comment]
Yes, the way Regenie generates creates masks by collapsing sites is more powerful when variant effects are in same direction. We have plans to incorporate variance-component tests like SKAT.

**Comment by ggstatgen** [comment]
> Yes, the way Regenie generates masks by collapsing across variants is more powerful when variant effects are in same direction. We have plans to incorporate variance-component tests like SKAT.

Thank you very much for this Joelle - would you advise to prefilter the annotated missense/pLOF variants by MAF to try and exclude most variants with supposed 'gain' effects (supposing GOF might be mediated by rare variation in general)? Any other filtering you'd recommend doing to try and avoid loss of power  due to possible opposite direction of effects?

**Comment by rgcgithub** [comment]
Take a look at the --aaf-bins option. This allows you to specify a set of allele frequency bins. The masks that you specify are then applied (and tested for association) in each of these bins.
