### ISSUE TITLE
Covariates that are exclusive to step 1 or step 2

### ISSUE THREAD

**Issue by nshrine** [rgcgithub/regenie#490]
The documentation says that you should have the same covariates in step 1 and step 2, but what about where you have covariates that are exclusive to step 1 and step 2 e.g. for the genotyping data used for step 1 you have the genotyping array as a covariate but for the WES data in step 2 you have the WES batch as a covariate?

**Comment by joellembatchou** [comment]
This should be fine as long as the covariates are not highly correlated with the phenotype of interest; alternatively, you could retain the array covariates in step 2 even if they are not relevant (with large N the penalty of having irrelevant covariates is negligible).
