### ISSUE TITLE
Regenie rejects valid pvar files

### ISSUE THREAD

**Issue by Wainberg** [rgcgithub/regenie#492]
https://github.com/rgcgithub/regenie/blob/51968de00af50a4ec35b79ab600879e928be5a7c/src/Geno.cpp#L791-L796 and https://github.com/rgcgithub/regenie/blob/51968de00af50a4ec35b79ab600879e928be5a7c/src/Geno.cpp#L888-L893 reject pvar files if the columns aren't in the usual order - but the [pvar specification](https://www.cog-genomics.org/plink/2.0/formats#pvar) allows optional columns and doesn't require the columns to be in any particular order if a header is specified. It would be good for regenie to support all valid pvar files.

**Comment by joellembatchou** [comment]
Hi,

Thank you for the feedback. This is now handled in [v3.4.1](https://github.com/rgcgithub/regenie/releases/tag/v3.4.1).

Cheers,
Joelle
