### ISSUE TITLE
Is it possible to compute LD between two masks?

### ISSUE THREAD

**Issue by scienception** [rgcgithub/regenie#496]
For example between geneA.M1.0.01 and geneA.M2.0.01? Where the former, for example, contains synonymous variants and the other missense variants. 

What are the flags to be used? I am guessing `--compute-corr -ld-extract info.txt`

But how does info.txt look like?

mask geneA.M1.0.01 geneA
mask geneA.M2.0.01 geneA

**Comment by joellembatchou** [comment]
Hi,

Yes that looks right (check [doc](https://rgcgithub.github.io/regenie/options/#output_3)). You'd use the same input flags as you would when computing burden masks (i.e. `--set-list --anno --mask-def --aaf-bins`). 

Cheers,
Joelle

**Comment by scienception** [comment]
Thank you! Could you please point me to where this is done in the code? I was looking at this script but it seems just parsing rather than Pearson correlation computation. 
https://github.com/rgcgithub/regenie/blob/master/scripts/parseLD.r

**Comment by joellembatchou** [comment]
check the documentation: https://rgcgithub.github.io/regenie/options/#ld-computation
You would run this using the REGENIE software (that parseLD.r script is just to read the output binary file that contains the correlation information).

**Comment by scienception** [comment]
All right, I just wanted to know in which script the computation was done since the data isn't phased. Could you please send me the link to the script? I would appreciate it :) it is just for learning purposes. Thanks!

**Comment by joellembatchou** [comment]
https://github.com/rgcgithub/regenie/blob/master/src/Data.cpp#L4173
