### ISSUE TITLE
Hail Implementation of Regenie Burden Testing

### ISSUE THREAD

**Issue by GHawkes93** [rgcgithub/regenie#498]
Hi Joelle,

I hope you're well

We were wondering if there were any plans, which you were aware of or indeed part of, to implement regenie's burden testing with Hail, specificially for All of Us? I know that there is a single variant version of regenie which has been built, but was built before burden testing was implemented.

Cheers,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth,

I am not aware of any plans for the development of regenie's functionality in Hail.

Cheers,
Joelle
