### ISSUE TITLE
feature request: select a range of phenotypes

### ISSUE THREAD

**Issue by yuchang-wu** [rgcgithub/regenie#499]
I'm wondering whether you can allow selecting phenotypes using something like `--phenoColList trait1:trait50`? I have to run GWAS on many traits, and it's quite tedious to manually type the name of each trait. 

Thanks!
Yuchang

**Comment by joellembatchou** [comment]
Hi Yuchang,

This is already available using [parameter expansion](https://rgcgithub.github.io/regenie/options/#input), e.g. `--phenoColList trait{1:50}`.
<img width="853" alt="image" src="https://github.com/rgcgithub/regenie/assets/65199080/8bbd64c7-dab7-45b8-a87e-6f7ffc68dce3">

**Comment by yuchang-wu** [comment]
thanks!
