### ISSUE TITLE
Reference and alternative allele

### ISSUE THREAD

**Issue by yingxi-kaylee** [rgcgithub/regenie#50]
Dear REGENIE team,

The documentation says allele 0 is reference and allele 1 is alternative in step 2's output. But I got the opposite value for my downstream polygenic risk score calculation, compared to using GWAS results from other softwares. Could you confirm allele 0/1 is reference/alternative? Thank you!

Bests,
Kaylee

**Comment by joellembatchou** [comment]
Hi Kaylee,

Indeed, in the Regenie output file, the association results reported are with respect to ALLELE 1. 

Cheers,
Joelle

**Comment by LeahBoettger** [comment]
Hello! I actually have found a similar problem: a certain SNP in my analysis has a A1Freq of >0.7 but when plotting genotypes against that specific phenotype, I see that the Ref allele is way more common in my dataset. I cannot really reconcile this information - would you be able to give me some clarity?
