### ISSUE TITLE
Robust SE when conducting interaction studies: the impact of phenotype scaling? --force-robust undocumented?

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#501]
Hi Joelle,

I realize that this question is more statistical than technical, but I hope you might have some insights from real-case scenarios. REGENIE applies the HC3 sandwich estimator for common variants with quantitative traits. However, the choice of scaling (untransformed, log, or RINT) can significantly affect the significance of the interaction term. For some highly skewed quantitative traits in the UK Biobank, I observed that using untransformed or log transformation is more powerful compared to RINT when testing GxE interactions. However, for a common GWAS, summary stats of nontransformed or log-transformed data are more inflated than RINT (favoring RINT). So, my question is, how safe and robust is REGENIE's current approach if one opts for simple log-transformation for interaction studies? Does HLM perform better (in which REGENIE notifies the user to apply RINT beforehand)?

Thanks!
Oveis

---
UPDATE:
` ("force-robust", "use robust SE instead of HLM for rare variant GxE test with quantitative traits")`

Apparently some flags are not reported in the current documentation. Is there any specific reason for this? There is a lot of literature arguing over the use of nonlinear transformations of the outcome and their effect on GxE, vQTL, etc.. So, it seems useful if one runs different simulations using robust SE, HLM or none to compare the inflation/deflation.
Also, when the outcome is not RIN transformed, REGENIE still tries to fit the null HLM model even for common variants, and setting `--rare-mac` to a large value does not change this behavior.

PS: there seems to be a typo when HLM fit fails:
<https://github.com/rgcgithub/regenie/blob/0e3c8f4e1acfd60392f5e4daf1a62cc9c933a1f4/src/HLM.cpp#L156>

**Comment by joellembatchou** [comment]
Hi,

The issue with robust SE (e.g. HC3) is that it gets inflated with rare variants. Otherwise, the test should be well-calibrated (for nontransformed or transformed traits). For rare variants, the workaround we derived is to use HLM, but the main caveat with this approach is it assumes normally distributed phenotypes so if that assumption does not hold, the test may not be well calibrated. We currently have not worked out another workaround for rare variant testing.

**Comment by igumnov-daniel** [comment]
I confirm that regenie v4.0 tries to fit HLM even if variants are filtered with `--minMAC`. Only `--force-impute` helps. Should we create a new issue about that?
