### ISSUE TITLE
How REGENIE deal with missing genotype data while calculating LOCO score

### ISSUE THREAD

**Issue by qzhang314** [rgcgithub/regenie#503]
Hi,

I'm just wondering how REGENIE deal with the missing genotype data while calculating the LOCO score, does it use the mean imputed value for the missing sites or just force it to be 0 (homo ref)?

Thanks,
Qian

**Comment by Ojami** [comment]
REGENIE mean imputes missing genotypes. See [here ](https://github.com/rgcgithub/regenie/issues/70)also.
