### ISSUE TITLE
How to deal with INFO score for chromosome X?

### ISSUE THREAD

**Issue by nandobonf** [rgcgithub/regenie#504]
Dear authors, I am performing some association analyses on chromosome X (UKBB data) and I notices many SNPs with INFO between 1 and 1.5. I then ran a sex stratified analysis and saw that INFO score is ok for females and distributes around 2 in males. 
How to fix this?

NB: I followed the conversion to plink PFILES to ensure correct allele coding (0,2) in haploid individuals (males). Therefore the step2 is ran on the PLINK files.

**Comment by Ojami** [comment]
PLINK bed/pgen only stores dosage information. So, this behavior is expected since Mach Rsq can be > 1. This has been covered in #333 and #398 .

**Comment by nandobonf** [comment]
Sure, Mach Rsq can be >1, and we know this. But for chr X almost all SNPs have INFO>1, which is quite different from what shown in Marchini & Hovie (https://www.nature.com/articles/nrg2796). This inflates all downstream analyses, for example setting the standard filtering at INFO>0.6 or INFO>0.8, will cause no SNP filtered out. In addition, INFO score will be very different for same SNPs in sex specific analyses (see figure below). 
This really does not look good to me...

The only solution is to use INFO scores provided by UKBB and just discard the INFO score re-calculated by REGENIE, at least for chromosome X.

![image](https://github.com/rgcgithub/regenie/assets/30171461/f112072e-0120-4fbe-8553-bffcb257e94f)

**Comment by Ojami** [comment]
> The only solution is to use INFO scores provided by UKBB and just discard the INFO score re-calculated by REGENIE, at least for chromosome X.

I totally agree on that, and this is in fact what we did before converting original UKBB BGEN to PGEN for sex chroms. So, irrespective of REGENIE's internal Mach R2, all variants are kept in this way.

**Comment by nandobonf** [comment]
Ok thanks! This can be closed, but it would be good to add a "warning" to the Regenie documentation about the issue.
