### ISSUE TITLE
not enough variants

### ISSUE THREAD

**Issue by vanessapitz** [rgcgithub/regenie#505]
I’m working on a rare variant project, running burden tests on multiple datasets. Sadly, one of them only has 600k exonic variants to begin with, a number which then dramatically drops using the –mac 100 flag. All those filters make me end up with 611 variants and then I keep getting the error that there’s not enough variants available to analyze in step2.
 
Question 1) What is the minimum number of variants that can be used here?
Question 2) Is there any way to bypass this? I followed the entry here to conduct my analysis on rare variants https://github.com/rgcgithub/regenie/issues/60
 
Any pointers appreciated -thanks!

**Comment by Ojami** [comment]
Can you share your log file possibly run via `--debug` flag?

**Comment by joellembatchou** [comment]
Hi,

Are you referring to step 1 or step 2? If it is step 1, this should be run on common variants preferably directly genotyped SNPs (we recommend ~500k). If it is step 2, you can pass any number of variants (so all 600k) and then apply post-QC filters (e.g. MAC).

Cheers,
Joelle
