### ISSUE TITLE
--ref-first for pgen pvar psam files

### ISSUE THREAD

**Issue by uelandte** [rgcgithub/regenie#506]
Hello!

Hoping to follow up on a previous discussion at #324  with a clarifying question on --ref-first. How does --ref-first interpret plink2 pgen/pvar/psam files?

The documentation mentions only bed/bim/fam files and bgen files, in that it will "Specify to use the first allele as the reference allele for BGEN or PLINK bed/bim/fam file input [default is to use the last allele as the reference]"

The default .pvar column order for the first four columns is POS ID REF ALT

Should --ref-first be applied to all regenie runs that take pgen/pvar/psam files as inputs? In other words, will it function similarly to the BIM file mentioned in the thread above where it looks at the last two columns?

Thanks for your time!
Thomas

**Comment by joellembatchou** [comment]
Hi Thomas,

`--ref-first` is not need for PGEN format as the REF/ALT columns are directly specified in the PVAR file so there is no ambiguity (ie the reference allele is taken as the one specified in the REF column).

Cheers,
Joelle

**Comment by lindenb** [comment]
@joellembatchou Hi, so if I use a **PGEN** **AND** `--ref-first `, my alleles will be swapped anyway ? Can you please confirm this ? (I'm asking because I've got some nice results with PGEN and NOT --ref-first  :-)   )
