### ISSUE TITLE
Testing for interaction in gene-based test

### ISSUE THREAD

**Issue by ape4fld** [rgcgithub/regenie#508]
Hello,

Is it possible to test for sex interaction effects with regenie gene-based tests?

Thanks in advance!

Frida

**Comment by nikotzoumas** [comment]
https://rgcgithub.github.io/regenie/options/#interaction-testing

**Comment by ape4fld** [comment]
Thanks for the link, can it also be applied to burden testing or only for single variant tests?

Cheers,

Frida

**Comment by nikotzoumas** [comment]
Yes if you read the documentation looks like you can specify, but haven't tried myself!

**Comment by joellembatchou** [comment]
Yes as @nikotzoumas pointed, you can build burden masks and then tests them for interaction.
