### ISSUE TITLE
All individuals have missing/invalid values for all traits

### ISSUE THREAD

**Issue by som-soremekun** [rgcgithub/regenie#510]
I am getting the error below for step 1 regenie.
I have used this script for other datasets and had no issues.

How can i resolve thhis issue?

Options in effect:
  --force-step1 \
  --step 1 \
  --bed /home/././imputation/ugr500k \
  --extract ugrqc_pass.snplist \
  --keep ugrqc_pass.id \
  --phenoFile /home/././imputation/ugrid_64042 \
  --phenoCol t2d \
  --covarFile /home/././imputation/ugrid_64042 \
  --covarCol sex,age,age2,bmi \
  --bsize 1000 \
  --bt \
  --loocv \
  --threads 4 \
  --lowmem \
  --out /home/././imputation/step1_t2d

Fitting null model
 * bim              : [/home/././imputation/ugr500k.bim] n_snps = 500000
   -keeping variants specified by --extract
   -number of variants remaining in the analysis = 131058
 * fam              : [/home/././imputation/ugr500k.fam] n_samples = 6412
   -keeping only individuals specified by --keep
 * bed              : [/home/././imputation/ugr500k.bed]
 * phenotypes       : [/home/././imputation/ugrid_64042] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
ERROR: all individuals have missing/invalid values for all traits.

I have checked previous issues and most of the solutions were for the sample files to be passed to the bgen file. But I am using bed files here, which needs no sample file.

I have also confirmed that the some individual IDs in the phenotype file (ugrid_64042) are also in the plink .fam file
grep 197814_B03_APP5117345_197814_B03_APP5117345 ugrid_64042
197814_B03_APP5117345_197814_B03_APP5117345 197814_B03_APP5117345_197814_B03_APP5117345 APP5117345 0 0 48.531139 2355.2715 20.4

other files include:
head ugrqc_pass.snplist 
1_764648
1_785301

head ugrqc_pass.id
0       197814_A03_APP5117343_197814_A03_APP5117343
0       197814_A04_APP5117354_197814_A04_APP5117354

Thank you

**Comment by PreciousEunice** [comment]
Thank you very much!  It worked for me too.
