### ISSUE TITLE
Will regenie support non-human dataset?

### ISSUE THREAD

**Issue by xiekunwhy** [rgcgithub/regenie#52]
Hi,

Will regenie well support non-human dataset? As non-human species gwas demand are increasing.

Best,
Kun

**Comment by joellembatchou** [comment]
Hi Kun, 

There is a `--nauto` argument to specify different number of autosomal chromosomes for non-human analyses. 

Cheers,
Joelle

**Comment by xiekunwhy** [comment]
I will try it, thank you.

Best,
Kun
