### ISSUE TITLE
Question about prediction in Step 1

### ISSUE THREAD

**Issue by Youpu-Chen** [rgcgithub/regenie#526]
Hi there.

According to the UKBB tutorial, I was a little bit confused.

Can I build the Step 1 prediction model for each chromosome (and run Step 2 for each chromosome using the chromosome-level Step 1 results), instead of using the whole genome PLINK bed file?
Because the latter took a long time for each run...

I'll really appreciate it if you could give me a hint!

Hongpu

**Comment by joellembatchou** [comment]
Hi Hongpu,

Step 1 is run across the genome so you should use a genotype file that combines variants genome-wide (hence the hint in the UKBB tutorial to merge the genotype files across chromosomes for step 1).

Cheers,
Joelle
