### ISSUE TITLE
covariance of interaction and snp terms

### ISSUE THREAD

**Issue by Julie-LB** [rgcgithub/regenie#528]
I am working on a sex-specific analysis and I would like to perform a meta-analysis of the joint effect of the snp-sex interaction and snp effects (2df test) (the meta-analysis method is Manning et al. 2011). For that meta-analysis, I require the covariance of the snp-sex interaction and snp terms. However, this covariance is not present in the outputs of REGENIE -interaction option.

I was wondering if you have an idea on how to obtain this covariance from REGENIE and if it is possible?

**Comment by Ojami** [comment]
I am pretty sure REGENIE performs such kDF tests. See [here](https://rgcgithub.github.io/regenie/overview/#step-2-interaction-testing):

> 𝐻0:𝛽=𝛾=0 which tests both main and interaction effects for the SNP

**Comment by Julie-LB** [comment]
Yes, it does, but it only provides the chi square test and P-value, but not he covariance of the main and interaction terms.

**Comment by Ojami** [comment]
In that case you can use `--print-vcov` flag (**undocumented**) which write variance-covariance matrix to a file. Note that you may apply `--no-condtl` depending on the interaction term you're applying.
