### ISSUE TITLE
Question about using phenotype files for different populations in two steps

### ISSUE THREAD

**Issue by xiashuting** [rgcgithub/regenie#529]
Hi, Thank you for your work.
I have a question about the populations of step1 and step2. Can I use phenotype files from all populations for model building in step1, then use phenotype files from different races in step2 for correlation studies？

**Comment by Ojami** [comment]
If you mean multi-ancestry GWAS, I would suggest to run separate GWAS on each ancestry and then meta-analyze (e.g., with METAL software).
