### ISSUE TITLE
Genotyped data for step 1>1M variants

### ISSUE THREAD

**Issue by chirrie** [rgcgithub/regenie#530]
I am trying to run step1 of association test in Regenie; however, the total number of genotyped variants after strict QC is still > 1 m. Does using >1M using --force step 1, although not recommended, affect results  or does it contribute to false positives?

**Comment by Ojami** [comment]
You can still lower it down in LD pruning step (`indep-pairwise` in PLINK). Please see also #497 . As per second question, if you have related individuals (also cryptic relatedness would be a problem), then most probably yes, that would inflate your summary stats. You can try, and check with lambda GC or intercept of LDSC. 

Hope this helps
Oveis

**Comment by joellembatchou** [comment]
Hi,

As @Ojami mentioned, you can use LD pruning to reduce the number of step 1 variants. The aim in this step is to capture genome-wide polygenic effects so usually you don't need to use >1M variants as this incurs a larger compute expense (we recommend ~500K).

Cheers,
Joelle

**Comment by frahimov** [comment]
Dear joellembatchou,
The All of Us program provides a list of 130,660 autosomal, bi-allelic SNPs (AF > 0.1%) LD-pruned with a cutoff of r2 = 0.1.  Would you recommend using the same set of SNPs in  step 1? Thank you
