### ISSUE TITLE
Annotation information could not be read

### ISSUE THREAD

**Issue by PreciousEunice** [rgcgithub/regenie#532]
Hi Joelle!

I am running a gene-based test and this error keeps on appearing.

ERROR: annotation information could not be read. Perhaps check variant IDs matches those in the genotype file?

I double checked the annotation file, I tried using with and without chr for Chromosome.  I also tried space and tab separated.  These are the upper rows of the annotation file (reference allele then alternate allele)

chr1:156051589:G:GC     MEX3A   frameshift_variant
chr1:156051616:C:T      MEX3A   synonymous_variant
chr1:156051982:CCCT:C   MEX3A   5_prime_UTR_variant
chr1:156052078:G:T      MEX3A   5_prime_UTR_variant

This are upper rows of the plink .bim file.  (alternate allele then reference allele)
1       rs773021630     0       156051589       GC      G
1       .       0       156051616       T       C
1       .       0       156051982       C       CCCT
1       rs762737573     0       156052078       T       G

These is the upper row of the vcf file which was the original file of the transformed .bim file  (reference allele then alternate allele)
chr1    156051589       rs773021630     G       GC
chr1    156051616       .       C       T
chr1    156051982       .       CCCT    C
chr1    156052078       rs762737573     G       T 

This is my log file

 |=============================|
              |      REGENIE v3.4.1.gz      |
              |=============================|

Copyright (c) 2020-2024 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : output/test_bin_out_firth_geneBased_ts.log

Options in effect:
  --step 2 \
  --ignore-pred \
  --bed input/coding_variants_annovar_hg19 \
  --phenoFile input/phenotype_ts.txt \
  --phenoCol Y1 \
  --covarFile covariate_ts.txt \
  --covarColList computed_sex,PC1,PC2 \
  --catCovarList computed_sex \
  --bsize 200 \
  --bt \
  --firth \
  --approx \
  --pThresh 0.01 \
  --htp COHORT_NAME \
  --anno-file input/annotations_snpeff.txt \
  --set-list set_list_snpeff.txt \
  --mask-def input/mask_snpeff.txt \
  --aaf-bins 0.1,0.05 \
  --write-mask \
  --check-burden-files \
  --pred output/fit_bin_out_pred_geneBased_ts.list \
  --out output/test_bin_out_firth_geneBased_ts

Association testing mode (joint tests) with fast multithreading using OpenMP
 * bim              : [input/coding_variants_annovar_hg19.bim] n_snps = 9188
 * fam              : [input/coding_variants_annovar_hg19.fam] n_samples = 2649
 * bed              : [input/coding_variants_annovar_hg19.bed]
 * phenotypes       : [input/phenotype_ts.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 1671
 * covariates       : [input/covariate_ts.txt] n_cov = 3
   -number of individuals with covariate data = 1671
 * number of individuals used in analysis = 1671
 * case-control counts for each trait:
   - 'Y1': 854 cases and 817 controls
 * no step 1 predictions given. Simple logistic regression will be performed
Intel MKL WARNING: Support of Intel(R) Advanced Vector Extensions (Intel(R) AVX) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library will use Int
el(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions instead.
 * annotations      : [input/annotations_snpeff.txt] 
ERROR: annotation information could not be read. Perhaps check variant IDs matches those in the genotype file?

Thank you very much!

**Comment by Ojami** [comment]
Your variant ids in BIM and anno files do not match: you have `rs773021630` in BIM while `chr1:156051589:G:GC` in annofile. Since you're BIM file appears to use rsIDs instead of variant IDs, the easiest way is to modify variant ID in your BIM file to be consistent with your annofile.
