### ISSUE TITLE
Step1 Firth fails to converge when running several phenotypes together

### ISSUE THREAD

**Issue by alterecho11** [rgcgithub/regenie#534]
Hello,

I encountered an issue where Step 1 gives a warning that Firth fails to converge when running several phenotypes together. However, when I run each phenotype individually, the Firth estimates are written successfully.

I used one input file with FID, IID, covariates and several columns with different pheno definitions/status.

Multipheno slurm script that fails to converge:
```
#!/bin/bash
#SBATCH -J regtest
#SBATCH -t 1-00:00:00
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --mem=25G

ml regenie/3.2

regenie \
 --step 1 \
 --bed ... \
 --phenoFile .../A_multipheno.txt \
 --phenoCol A,A_excl,A_b50,A_a50 \
 --covarFile .../A_multipheno.txt \
 --covarColList yob,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
 --bt \
 --lowmem \
 --write-null-firth \
 --bsize 1000 \
 --ref-first \
 --out .../output_step1/regtest \
 --threads 16;
```

Individual pheno script that works smoothly:
```
#!/bin/bash
#SBATCH -J regtest
#SBATCH -t 1-00:00:00
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --mem=16G

ml regenie/3.2

regenie \
 --step 1 \
 --bed ... \
 --phenoFile .../A_for_regenie_new.txt \
 --phenoCol A \
 --covarFile .../A_for_regenie_new.txt \
 --covarColList yob,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
 --bt \
 --lowmem \
 --write-null-firth \
 --bsize 1000 \
 --ref-first \
 --out .../output_step1/regtest \
 --threads 16;
 ```

Is there something additional that must be adjusted to ensure that Firth estimates are written when running several phenos?

I appreciate any suggestions!

**Comment by joellembatchou** [comment]
Hi,

What is the missingness pattern across the traits analyzed in the run?

**Comment by alterecho11** [comment]
The 'A' column has only 1 and 0. For the other three, I coded some individuals as 'NA' based on the exclusion criteria.

```
-number of individuals with covariate data = 126773
* number of individuals used in analysis = 126773
 * case-control counts for each trait:
   - 'A': 14002 cases and 112771 controls
   - 'A_excl': 8988 cases and 87792 controls
   - 'A_b50': 9466 cases and 112771 controls
   - 'A_b50': 4536 cases and 112771 controls
```
   
  The log file did not mention any other irregularities or missing data.

**Comment by joellembatchou** [comment]
We've pushed a fix to address your issue (you'll need to git pull & compile from source)
