### ISSUE TITLE
the p value for ADD-INT_SNP is unresonable

### ISSUE THREAD

**Issue by Zzaroro** [rgcgithub/regenie#535]
Hello,

When I run the interaction test, the interaction term shows significant results, with a log10 p-value of 8.85233. The p-value for the SNP from the marginal test without the interaction term is not significant (log10 p-value = 0.307568), but it becomes significant after including the interaction term, with a log10 p-value of 9.22603. Do you know what is happening here? 

Thank you.

**Comment by Zzaroro** [comment]
Hello, here is the full summary, please have a look at it. My question is how the -log10p value for the snp in marginal test without the interaction term is l0.307568, but became significant with log10 p-value = 8.85233 after implementing the interaction term. Thank you.

17 50832044 chr17_50832044_C_T C T 0.0149013 5570 ADD-CONDTL -0.20024 0.291771 0.470997 0.307568 NA
17 50832044 chr17_50832044_C_T C T 0.0149013 5570 ADD-INT_SNP 13.071 2.1182 36.6619 8.85233 NA
17 50832044 chr17_50832044_C_T C T 0.0149013 5570 ADD-INT_SNPxbmi -0.657266 0.109348 38.3402 9.22603 NA
17 50832044 chr17_50832044_C_T C T 0.0149013 5570 ADD-INT_2DF NA NA 38.724 8.4088 NA

**Comment by Ojami** [comment]
These are two different models:
`ADD-CONDTL` is equivalent to a typical GWAS without interaction and adjusting for BMI
whole `ADD-INT_SNP` is the main effect when SNPxBMI term is included in the model. When you have interaction term in the model, interpretation of main effects become tricky. Maybe you can draw a forest plot based on different strata of BMI (e.g. < 25, >=25 and >= 30) to see how the variant affect individuals in different BMI strata.

**Comment by Zzaroro** [comment]
Thank you! That is really helpful!
