### ISSUE TITLE
cannot write log file

### ISSUE THREAD

**Issue by sorghuW** [rgcgithub/regenie#538]
Dear regenie development team,

I've installed regenie v3.5 using apptainer on hpc (apptainer pull docker://ghcr.io/rgcgithub/regenie/regenie:v3.5.gz). When trying to run the analysis, I encountered an error indicating "ERROR: Cannot write log file ...". Here's the full script to run my analysis:

module load apptainer/1.0.0
apptainer run /stornext/Bioinf/data/lab_bahlo/users/wang.pa/software/regenie_v3.5.gz.sif regenie \
  --step 1 \
  --bed grmSNPsEuro \
  --phenoFile pheno.txt \
  --covarFile covariates.txt \
  --bsize 1000 \
  --lowmem \
  --lowmem-prefix regenie_tmp_preds_all \
  --bt \
  --write-null-firth \
  --out ../regenie/step_1_out/step_1

Are you able to identify the cause of the error and advise how I can fix it?

Many thanks, 
Patrick

**Comment by dvg-p4** [comment]
Might be an issue with your apptainer bind paths -- is `../regenie/step_1_out/step_1` under your home directory?

Try:

```bash
apptainer run /stornext/Bioinf/data/lab_bahlo/users/wang.pa/software/regenie_v3.5.gz.sif \
  echo hello > ../regenie/step_1_out/step_1
```

If that fails too, the issue isn't with regenie, you just need to point your output somewhere that is mounted within the container (or alternatively, bind the desired output path with apptainer's [`--bind`](https://apptainer.org/docs/user/latest/bind_paths_and_mounts.html#user-defined-bind-paths)

**Comment by joellembatchou** [comment]
Hi Patrick

This seems like there are some permissions issues. Perhaps check you have writing access to the "../regenie/" folder?

Cheers,
Joelle
