### ISSUE TITLE
how the proportion of trait variance explained by causal SNPs is defigned

### ISSUE THREAD

**Issue by mgretsova** [rgcgithub/regenie#540]
Dear regenie support team,

Can you please explane, how your tool restrict the proportion of variants explained by random effect, so it won't explane the hole variabiality of the data, but only part of it?
In supplementary materials to regenie paper it is mentioned that amount of snps used for random effect is restricted by fixing h2 (genetic hertability score). It is mentioned that it should be between 0 and 1, but I didn't find any explanation of how this score is defigned in each particular dataset.
In my case, it seems, that if I have more snps to the random effect then the genomic inflation factor becomes lower and in some cases the model is overcorrected. So, how should one choose amount of SNPs for the first step?

Best
Maria

**Comment by joellembatchou** [comment]
Hi Maria,

Please check the documentation: https://rgcgithub.github.io/regenie/faq/#step-1

It seems part of your question is asking about the grid of ridge shrinkage parameters used in step 1. We essentially generate predictions based on each parameter and then take an ensemble approach to combine these predictions (so letting the data determine the best weighting combination).

Cheers,
Joelle
