### ISSUE TITLE
SNP has low variance.

### ISSUE THREAD

**Issue by Isabella678** [rgcgithub/regenie#542]
Hi, i have the same problem.
I want to perform rare variants (MAF < 1%) analysis in Regenie, and have tried many times to follow your earlier advice to others, but still encounter the same error: Uh-oh, SNP chr1_1337985_T_C;chr1_1337983_TCTG_T;chr1_1337985_T_G has low variance (=0.000000).        
I can show your my code: 
` plink2--pgen "$PGEN_FILE" \
             --pvar "$PVAR_FILE" \
             --psam "$PSAM_FILE" \
             --maf 0.01 \
             --mac 100 \
             --write-snplist allow-dups \
             --out out_step1`
`plink2 --pgen "$PGEN_FILE" \
             --pvar "$PVAR_FILE" \
             --psam "$PSAM_FILE" \
             --max-maf 0.01 \
             --mac 100 \
             --write-snplist allow-dups \
             --out out_step2`
And then, i run the regenie:
`regenie  --pgen "$PGEN_FILE" \
         --phenoFile "$PHENO_FILE" \
         --extract "$SNPLIST" \
         --out "$OUTPUT_PREFIX" \
         --threads 10 \
         --step 1 \
         --lowmem \
         --lowmem-prefix lwmem_tmp \
         --bsize 100 \
         --pThresh 0.05 \
         --force-step1 \
         --force-qt`
but at step1, i still got error with the same problem...i am very frustrated...
![1722323160626](https://github.com/user-attachments/assets/023d2b80-a490-42c4-962c-538dbbb270ab)
Could you please gave me some advices? 
Thanks!
Isabella

_Originally posted by @Isabella678 in https://github.com/rgcgithub/regenie/issues/33#issuecomment-2257630717_

**Comment by dvg-p4** [comment]
Are those variants so rare that they're not present at all? "Variance = 0.0" sounds like they might have AAC = 0. (Or AAF = 1.0)

**Comment by Isabella678** [comment]
> Are those variants so rare that they're not present at all? "Variance = 0.0" sounds like they might have AAC = 0. (Or AAF = 1.0)这些变异是如此罕见，以至于它们根本不存在吗？“Variance = 0.0”听起来像是AAC = 0。(Or AAF = 1.0）

I just filtered the MAF values according to less than 0.01, but it seems that those with MAF = 0 were not excluded. Is this the reason?

**Comment by Isabella678** [comment]
> Are those variants so rare that they're not present at all? "Variance = 0.0" sounds like they might have AAC = 0. (Or AAF = 1.0)

But my research is focused on rare variants, so I have already filtered the MAF values, only retaining variants with MAF < 0.01. How should I modify my parameters to use regenie for the analysis of rare variants?

Thanks.

**Comment by Ojami** [comment]
In step 1, you should use common variants of high quality (e.g. directly genotyped or high coverage from WGS/WES). Please [see here](https://www.nature.com/articles/s41586-021-04103-z) for more details:

> We included in step 1 of REGENIE (that is, prediction of individual trait values based on the genetic data) array variants with MAF > 1%, <10% missingness, Hardy–Weinberg equilibrium test P > 10−15 and linkage disequilibrium (LD) pruning (1,000 variant windows, 100 variant sliding windows and r2 <0.9). We excluded from step 1 any SNPs with high inter-chromosomal LD, in the major histocompatibility (MHC) region, or in regions of low complexity.

The whole purpose of step 1 is to find the best genetic predictors of your phenotype to remove cryptic relatedness/population stratification. This can ideally be achieve by independent common variants. Once you generated your `pred` file, then you may move to step 2 (unless you want to skip step 1, which is OK as long as you are sure about the homogeneity of your cohort). For rare variant analysis, instead of testing each rare variant separately, [check gene-/region-based tests](https://rgcgithub.github.io/regenie/options/#gene-based-testing). 

Cheers
Oveis

**Comment by Isabella678** [comment]
> In step 1, you should use common variants of high quality (e.g. directly genotyped or high coverage from WGS/WES). Please [see here](https://www.nature.com/articles/s41586-021-04103-z) for more details:
> 
> > We included in step 1 of REGENIE (that is, prediction of individual trait values based on the genetic data) array variants with MAF > 1%, <10% missingness, Hardy–Weinberg equilibrium test P > 10−15 and linkage disequilibrium (LD) pruning (1,000 variant windows, 100 variant sliding windows and r2 <0.9). We excluded from step 1 any SNPs with high inter-chromosomal LD, in the major histocompatibility (MHC) region, or in regions of low complexity.
> 
> The whole purpose of step 1 is to find the best genetic predictors of your phenotype to remove cryptic relatedness/population stratification. This can ideally be achieve by independent common variants. Once you generated your `pred` file, then you may move to step 2 (unless you want to skip step 1, which is OK as long as you are sure about the homogeneity of your cohort). For rare variant analysis, instead of testing each rare variant separately, [check gene-/region-based tests](https://rgcgithub.github.io/regenie/options/#gene-based-testing).
> 
> Cheers Oveis

Thank you very much for your response. Following your advice, I first included only the variants with MAF greater than 0.01 in step 1 to generate the prediction file for step 2. The code for step 1 is as follows:
regenie --pgen "$PGEN_FILE" \
        --phenoFile "$PHENO_FILE" \
        --out "$OUTPUT_PREFIX" \
        --threads 10 \
        --step 1 \
        --lowmem \
        --force-qt \
        --bsize 100
Then, for the second step, I used the following code:
regenie --step 2 \
       --pgen "$PGEN_FILE" \
       --covarFile "$COV_FILE" \
       --phenoFile "$PHENO_FILE" \
       --bt \
       --firth --approx \
       --pred out_step1_pred.list \
       --anno-file "$ANNO_FILE" \
       --set-list "$SET_LIST" \
       --mask-def "$MASK_FILE" \
       --write-mask \
       --bsize 200 \
       --aaf-bins 0.01 \
       --minMAC 10 \
       --check-burden-files \
       --vc-maxAAF 0.01 \
       --out "$OUTPUT_PREFIX"
After that, I obtained the .regenie file. Is this the correct approach?
Thanks.

**Comment by Isabella678** [comment]
Thank you very much for your response. Following your advice, I first included only the variants with MAF greater than 0.01 in step 1 to generate the prediction file for step 2. The code for step 1 is as follows:
```
regenie --pgen "$PGEN_FILE" \
        --phenoFile "$PHENO_FILE" \
        --out "$OUTPUT_PREFIX" \
        --threads 10 \
        --step 1 \
        --lowmem \
        --force-qt \
        --bsize 100
```
Then, for the second step, I used the following code:
```
regenie --step 2 \
       --pgen "$PGEN_FILE" \
       --covarFile "$COV_FILE" \
       --phenoFile "$PHENO_FILE" \
       --bt \
       --firth --approx \
       --pred out_step1_pred.list \
       --anno-file "$ANNO_FILE" \
       --set-list "$SET_LIST" \
       --mask-def "$MASK_FILE" \
       --write-mask \
       --bsize 200 \
       --aaf-bins 0.01 \
       --minMAC 10 \
       --check-burden-files \
       --vc-maxAAF 0.01 \
       --out "$OUTPUT_PREFIX"
```
After that, I obtained the .regenie file. Is this the correct approach?
Thanks.

**Comment by Ojami** [comment]
What's the reason for `--force-qt` in step 1? Also, you forgot to include `covarFile` in step 1. Other than that, it seems OK. 

Cheers/Oveis

**Comment by Isabella678** [comment]
Dear Oveis,

I would like to express my gratitude for your prompt response. The reason for employing the `--force-qt` flag is due to my phenotype being a binary variable. Without this parameter, I encountered the following error:

`ERROR: phenotype 'neuro_sz' has very few unique values (=2). If you really want to analyze it as a QT, use `--force-qt`.`

Regarding the covariate file, I appreciate your suggestion, and I have already included it in step 1.

Additionally, I have a question about gene-based analysis. I have defined my mask file into three Masks as follows:

`##MASKS=<Mask1="frameshift,stopgain,startloss,stoploss"; Mask2="nonsynonymous"; Mask3="nonframeshift">`

Upon obtaining the .regenie file, I noticed that some results underwent Firth correction (out of 17,824 gene sets, 2,403 gene sets underwent Firth correction). Subsequently, I used the obtained LOG10P values for multiple testing correction, and the P-values were almost all 1. I am curious if the Firth correction is necessary in step 2. 
If I were to use FDR or Bonferroni correction, would it be sufficient to correct within each Mask rather than correcting all results together (for example, with n=17,824)?

I look forward to your insights on this matter.

Best regards,
Isabella

**Comment by Ojami** [comment]
It helps if you post the full log (you can also use `--debug` for more detailed log).  

> The reason for employing the --force-qt flag is due to my phenotype being a binary variable. Without this parameter, I encountered the following error:

ERROR: phenotype 'neuro_sz' has very few unique values (=2). If you really want to analyze it as a QT, use --force-qt.

Then you should treat your phenotype as a binary trait (`--bt` flag).  Treating bt as qt is a clear example of model misspecification. 

> Upon obtaining the .regenie file, I noticed that some results underwent Firth correction (out of 17,824 gene sets, 2,403 gene sets underwent Firth correction). Subsequently, I used the obtained LOG10P values for multiple testing correction, and the P-values were almost all 1. I am curious if the Firth correction is necessary in step 2.

The necessity of Firth's penalty depends on numerous factors, among them: case/control imbalance and the freq. of genetic predictors. In the context of gene-/region-based tests, Firth penalty is usually recommended ([See here](https://www.frontiersin.org/journals/genetics/articles/10.3389/fgene.2014.00187/full)). By default REGENIE falls back to Firth correction if nominal p-values are below `--pThresh` (default is 0.05). So 2,403 genes in your case had a nominal p < 0.05. 

> If I were to use FDR or Bonferroni correction, would it be sufficient to correct within each Mask rather than correcting all results together (for example, with n=17,824)?

This has also been covered [here](https://www.biorxiv.org/content/10.1101/2023.02.22.529560v1) and already implemented in REGENIE, so you can use joint GENE_P values which accounts for all mask/aaf combinations. Then you can apply your multiple testing correction method (FDR, FWER, etc) to GENE_P (or other joint p-values that REGENIE offers). 

Last but not least, always check the inflation of your test statistics (wether you end up with joint tests or either of masks).
Hope this helps.

Good luck!
Oveis

**Comment by Isabella678** [comment]
Hi,

Thank you for your response. After changing to Firth, the number of test failures has indeed decreased significantly. 

However, I have a few more questions that require your assistance:
Question1, For the analysis based on single-variants, the code I used is: 
```
regenie --step 2 \
        --pgen "$PGEN_FILE" \
        --covarFile "$COV_FILE" \
        --phenoFile "$PHENO_FILE" \
        --bt \
        --firth \
        --pred "$PRED_FILE" \
        --minMAC 1 \
        --bsize 200 \
        --aaf-bins 0.01 \
        --vc-maxAAF 0.01 \
        --test additive \
        --print-pheno \
        --out "$OUTPUT_PREFIX"
```
and part of the log is as follows. 
```
Association testing mode with fast multithreading using OpenMP
 * pvar             : [./Final_QCed_MAF3.1.pvar] n_snps = 2401754
 * psam             : [./Final_QCed_MAF3.1.psam] n_samples = 32500
 * pgen             : [.Final_QCed_MAF3.1.pgen] 
 * phenotypes       : [./phenoFile.tsv] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes
   -number of phenotyped individuals with no missing data = 32500
 * covariates       : [./new_final_covariate.txt] n_cov = 7
   -number of individuals with covariate data = 32500
 * number of individuals used in analysis = 32500
 * case-control counts for each trait:
   - 'neuro': 1645 cases and 30855 controls
 * LOCO predictions : [./regenie/out_step1_bt_pred.list]
   -file [./regenie/out_step1_bt_1.loco] for phenotype 'neuro'
 * # threads        : [63]
 * block size       : [200]
 * # blocks         : [12021]
 * approximate memory usage : 669MB
 * using minimum MAC of 1 (variants with lower MAC are ignored)
 * using Firth correction for logistic regression p-values less than 0.05
 * Number of tests with Firth correction : 90331
Number of failed tests : (0/90331)
Number of ignored tests due to low MAC : 791169
```
It shows that 90,331 were tested successfully, and 791,169 were ignored due to low MAC. However, in the result file, there are a total of 1,609,585 variant results, with the 'extre' column all showing as NA, providing no information on which variants were tested successfully. 
![1728869583362](https://github.com/user-attachments/assets/4f79d991-6053-4732-b4b5-3c8e27d03723)
Generally, shouldn't we only perform multiple corrections on the variants that were tested successfully? I'm not sure if my understanding is correct.

Question2, Can Regenie accept annotation results categorized by Annovar? Or is it only compatible with snpEFF or VEP? The annotation file I input is based on Annovar annotation information to define PTV, Dmis, and Missense.

Question3, For the gene-based analysis, the code I used is:
```
regenie --step 2 \
        --pgen "$PGEN_FILE" \
        --covarFile "$COV_FILE" \
        --phenoFile "$PHENO_FILE" \
        --bt \
        --vc-tests skato \
        --pred "$PRED_FILE" \
        --anno-file "$ANNO_FILE" \
        --set-list "$SET_LIST" \
        --mask-def "$MASK_FILE" \
        --aaf-file "$AAF_FILE" \
        --rgc-gene-p \
        --write-mask \
        --bsize 200 \
        --aaf-bins 0.01 \
        --minMAC 10 \
        --check-burden-files \
        --vc-maxAAF 0.01 \
        --out "$OUTPUT_PREFIX"
```
and I defined four Masks, which are: 
```
Mask1 PTV
Mask2 Dmis
Mask3 PTV,Dmis
Mask4 Dmis,Missense
```
The results for each gene are numerous. For example, for the A3GALT2 gene
![1728869581873](https://github.com/user-attachments/assets/c0162c6f-087b-4431-a942-4fe1c1fb10b4)
Do I only need to extract the GENE_P results for multiple corrections? Or do I need to extract and correct separately based on each Mask for each type of test, such as extracting and separately correcting Mask1's ADD-SKATO, ADD-SKAT, and ADD-SKATO-ACAT, to analyze the association analysis results in different tests for each variant type defined by each Mask?

Looking forward to your reply, thanks!
Isabella

**Comment by joellembatchou** [comment]
Hi Isabella,

Question 1: The log indicates that out of the all the variants tested, 90331 of them had uncorrected p-value < 0.05 hence Firth was applied to these. So in your sumstats file output, most of the variants were not tested with Firth due to a large p-value.

Question 2: REGENIE can accept annotations from various sources as long as you make them compatible with the [input format](https://rgcgithub.github.io/regenie/options/#annotation-input-files).

Question 3: We recommend as a first pass to use GENE_P to identify significant gene signals as GENE_P aggregates signals across masks & AAF within a gene. Once those genes have been identify, you can then do deep dives to understand what is driving the signal.

Cheers,
Joelle
