### ISSUE TITLE
Using regenie for PheWAS with phenotypes with different missingness patterns

### ISSUE THREAD

**Issue by nshrine** [rgcgithub/regenie#543]
I am trying to use regenie to run a PheWAS in UK Biobank across 1400 binary traits, some of which are only defined for a small number of samples leading to a huge range in missingness across the phenotypes in 400K samples.

I see in the paper you only chose sets of QT and BT phenotypes with very low (often 0) missing rates.

Noting that for step 1:
"Hence, we recommend to analyze traits in groups that have similar missingness patterns with resonably low amount of missingness (<15%)."
https://rgcgithub.github.io/regenie/recommendations/#pre-processing

In order to obtain phenotype groups with low missingness I calculated the binary distance between phenotypes where each individual is coded (0/1) for missing/non-missing data for the phenotype. I then clustered the distance matrix by hclust and then in each cluster of phenotypes with similar missingness patterns removed samples with complete missing data for all the phenotypes in the cluster. I then recalculated the missing rates across phenotypes for the samples left in each cluster. I found I could get the missing rate down to <15% for all phenotypes if I used 120 clusters (R code below).

This means I have to run regenie step 1 120 times  in order to analyse my 1400 phenotypes.

Am I missing something or any better suggestions?

Thanks
Nick

```
#Create a phenotype(p) x individual(n) matrix from phenotype data such that 0=missing, 1=non-missing
pheno.m <- pheno %>%
  select(-FID, -IID) %>%
  mutate(across(everything(), ~is.na(.) %>% ifelse(0, 1))) %>%
  as.matrix %>%
  t

#Create p x p pairwise binary distances between phenotypes
pheno_dist <- dist(pheno.m, method="binary")

#Hierarchical cluster distances then select 120 groups
pheno_groups <- pheno_dist %>%
  hclust(method="ward.D2") %>%
  cutree(k=120) %>% 
  enframe(name="pheno", value="group") %>%
  mutate(group=factor(group))

#Calculate phenotype missingness after removing samples that do not contribute to any phenotype in a group
pheno_missing <- pheno_groups %>%
  group_by(group) %>%
  group_map(~pheno %>% select(c(FID, IID, .x$pheno)) %>% filter(if_any(.x$pheno, ~!is.na(.)))) %>%
  map_df(~summarise(., across(c(-FID, -IID), ~sum(is.na(.)/length(.)))) %>%
    pivot_longer(everything(), names_to = "pheno", values_to = "missing"),
      .id = "group")
  
#Maximum missing rate for any phenotype is <15%
> pheno_missing %>% arrange(desc(missing))
  group pheno   missing
   <chr> <chr>     <dbl>
 1 4     P2007     0.127
 2 88    P560.2    0.122
 3 88    P555.21   0.121
 4 88    P561.1    0.120
 5 88    P556.1    0.120
 6 88    P560.1    0.119
 7 88    P560.3    0.118
 8 88    P556      0.117
 9 88    P555.1    0.116
10 88    P559      0.115
```

**Comment by joellembatchou** [comment]
Hi Nick,

This looks fine (it is actually the strategy that we use internally to generate phenotype clusters with similar missingness patterns).

Cheers,
Joelle
