### ISSUE TITLE
Strange Meta-Analysis Behaviour

### ISSUE THREAD

**Issue by GHawkes93** [rgcgithub/regenie#545]
Hi Joelle - I hope you are well

I've noticed some slightly strange behaviour with regenie and strata meta-analysis.

I have performed a GWAS of a quantitative trait in the whole UKB cohort (N = 450K EUR), and am trying to compare those estimates (BETA, SE, L10P) with a meta-analysis (fixed-effect) of the same phenotype split into three non-overlapping strata (N =150k x 3, from the same individuals).

I'm finding that the meta-analysis and the joint p-values are quite wildly different, as a function of the p-value (e.g. one variant goes from L10P = 220 in the joint analysis to 125 in the meta-strata). 

The effect sizes seem to be consistent in meta-strata vs. joint: the differences appear to be driven by larger SE's in the strata.

When I perform the same analysis in R, using a single 3% MAF SNP as an example, the p-value from a meta-analysis of the strata is equal to the p-value in the joint model (with effect sizes again being consistent).

I ran Step1 on all three strata in a single run, and run Step2 on all three together. I also adjusted for the same covariates as the joint-model.

Could you please advise on what could be causing this?

Best wishes,
Gareth

**Comment by GHawkes93** [comment]
I should add I'm using regenie v3.3!

**Comment by joellembatchou** [comment]
Hi Gareth,

Could you include the log (at least the header part) corresponding to your MEGA vs META analysis? Also for your R example, was that taking one of the variant which showed very different p-values between the two analyses?

Cheers,
Joelle

**Comment by GHawkes93** [comment]
Hi Joelle,

I think we narrowed this down to having multiple non-overlapping phenotypes (0% overlap) in Step1. I hadn't appreciated the fact that regenie produces worse Step1-PRS estimates in these cases.

Does that sound about right to you?

Cheers,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth, 

Yes we recommend multi-trait mode be run on phenotypes that share similar missingness patterns.

Cheers,
Joelle
