### ISSUE TITLE
Quantitative phenotype processing - scaling, rint, and residualisation.

### ISSUE THREAD

**Issue by diegojehu** [rgcgithub/regenie#546]
Hi,

I was hoping I could ask for a bit of more detail on how Regenie processes quantitative phenotypes. I am currently considering if I should do the process myself, or use Regenie's implementation of rank-based inverse normal transformation (RINT) and let Regenie calculate the residuals of the phenotype based on the regression of the phenotype on the covariates. 

To be able to decide which way to go, I realised I have a couple of questions. Specifically, I would like to know:

- **RINT**: How does regenie implement the rank-based inverse normal transformation when adding the flag `--apply-rint`? (Directions to the code would suffice if easier!).
- **Scaling**: What does regenie do when it "scales" the quantitative phenotypes. Does it divide the values by the standard deviation? I've noticed that scaling happens even when using the `--apply-rint` flag. Does this mean that this "scaling" step takes place irrespective of whether RINT has been applied? Is there a way to turn the scaling off? Or is there a good reason not to turn this scaling step off?
- **Residualising**: I understand that when covariates are provided, the phenotype is residualised based on the regression of the phenotype on the covariates. Does this step happen before or after RINT when `--apply-rint` is used?
- To be sure, if I wanted to ask Regenie to process the phenotype as provided (as I would have done the RINT and residualising myself), all I need to do is **not** use the flag `--apply-rint` and **not** provide any covariate files. Is this correct?

Thank you!
Diego

**Comment by Ojami** [comment]
REGENIE RINT function (see eq. 1 of[ this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2921808/) with `c = 3/8`):
https://github.com/rgcgithub/regenie/blob/98b158c7aab6e63587d58a8401132fd775e95c99/src/Pheno.cpp#L1786-L1822
For scaling, you're (almost) correct. It divides the residuals by their RMS. As mean is already zero, this is equivalent to SD. 
https://github.com/rgcgithub/regenie/blob/98b158c7aab6e63587d58a8401132fd775e95c99/src/Pheno.cpp#L1636-L1638
AFAIK, scaling is applied regardless of the phenotypic transformation.
Also transformation happens before residulaization:
https://github.com/rgcgithub/regenie/blob/98b158c7aab6e63587d58a8401132fd775e95c99/src/Data.cpp#L2166-L2167


> To be sure, if I wanted to ask Regenie to process the phenotype as provided (as I would have done the RINT and residualising myself), all I need to do is not use the flag --apply-rint and not provide any covariate files. Is this correct?

It seems extra work, no? But I guess you could easily test this once without RINT and covariates and once with both.
Hope this helps.

Oveis

**Comment by diegojehu** [comment]
Dear Oveis,

Many thanks for the detailed response and cross-reference to the INT equation used by Regenie and relevant lines in code. I'll do a few runs to check if I obtain the expected outcomes. If nothing unexpected comes up, I'll close the issue.

Thanks again!
Diego

**Comment by HDTian** [comment]
Thanks for the detailed and helpful discussion. May I ask if there is now more definitive information on the specific order of rank-based inverse normal transformation (RINT) and residualizing (ie, adjusting covariate)?  

I think more people would prefer to first obtain the residuals and then rint the residuals, but it seems that REGENIE has finished the RINT before running prep_run (adjust for covariate). So I'd consider manually transforming the phenotype data.

Greatly appreciate any information provided. 
Best,
Haodong

**Comment by joellembatchou** [comment]
Hi Haodong,

Yes REGENIE first RINTs before adjusting for covariate effects.
