### ISSUE TITLE
Annotation information could not be read

### ISSUE THREAD

**Issue by Lillllian** [rgcgithub/regenie#549]
Hi Joelle!

I am also running a gene-based test and this error keeps on appearing. I took the reference of the previous similar question and in my case the two files have exact the same format. But still, every time I ran the code I got "ERROR: annotation information could not be read. Perhaps check variant IDs matches those in the genotype file?". The example data works fine, though.

 the annotation file looks like
1:15777[b37]A,G	DDX11L1	downstream_gene_variant
1:16949[b37]A,C	DDX11L1	downstream_gene_variant
1:18849[b37]C,G	DDX11L1	downstream_gene_variant
1:52238[b37]T,G	OR4G4P	upstream_gene_variant
1:57292[b37]C,T	OR4G4P	downstream_gene_variant
The plink .bim file looks like
1  1:15777[b37]A,G  0  15777  G  A
1  1:16949[b37]A,C  0  16949  C  A
1  1:18849[b37]C,G  0  18849  G  C
1  1:52238[b37]T,G  0  52238  G  T
1  1:57292[b37]C,T  0  57292  T  C

This is my log file

Start time: Wed Aug 28 22:44:03 2024

              |===========================|
              |      REGENIE v3.5.gz      |
              |===========================|

Copyright (c) 2020-2024 Joelle Mbatchou, Andrey Ziyatdinov and Jonathan Marchini.
Distributed under the MIT License.
Compiled with Boost Iostream library.
Using Intel MKL with Eigen.

Log of output saved in file : /home/disk3/lily/ukbbgwas/code/analysis/specific/regenie/analysis/20240728_ldpruned_output/gene-based/regenie/amplitudetest_bin_out_firth.log

Options in effect:
  --step 2 \
  --bed merged.LDpruned \
  --covarFile covar_age_sex_combination_pc10_new.txt \
  --phenoFile 30835_amplitude.txt \
  --qt \
  --pred ukb_step1_continuous_pred.list \
  --anno-file annotations_FINAL.txt \
  --set-list set_list.txt \
  --mask-def masks.txt \
  --aaf-bins 0.1,0.05 \
  --write-mask \
  --bsize 200 \
  --out test_bin_out_firth

Association testing mode (joint tests) with fast multithreading using OpenMP  
 * bim              : [merged.LDpruned.bim] n_snps = 1092871
 * fam              : [merged.LDpruned.fam] n_samples = 55634
 * bed              : [merged.LDpruned.bed]
 * phenotypes       : [30835_amplitude.txt] n_pheno = 1
   -dropping observations with missing values at any of the phenotypes        
   -number of phenotyped individuals with no missing data = 55634
 * covariates       : [covar_age_sex_combination_pc10_new.txt] n_cov = 15
   -number of individuals with covariate data = 55634
 * number of individuals used in analysis = 55634
 * number of observations for each trait:
   - 'amplitude': 55634 observations
 * LOCO predictions : [ukb_step1_continuous_pred.list]
   -file [ukb_step1_continuous_1.loco] for phenotype 'amplitude'
   -residualizing and scaling phenotypes...done (0ms) 
 * annotations      : [annotations_FINAL.txt] 
ERROR: annotation information could not be read. Perhaps check variant IDs matches those in the genotype file?

Thank you so much for checking!

**Comment by git-jemiller** [comment]
Hi Lillian, 
This may have to do with your variant ID. I had a similar problem when using commas. You may want to swap them for underscores or colons. I'm also not sure about the brackets, but maybe those are fine. 

In plink you can use `--set-all-var-ids` to change the IDs (https://www.cog-genomics.org/plink/2.0/data#set_all_var_ids). 

Hope this helps!

**Comment by joellembatchou** [comment]
Hi,

As stated by @git-jemiller, please avoid using commas in your variant ID as this is causing the error.

Cheers,
Joelle
