### ISSUE TITLE
regenie v3.6 portability

### ISSUE THREAD

**Issue by GHawkes93** [rgcgithub/regenie#552]
Hi,

I've noticed that the most recent release (v3.6) isn't as portable as previous versions - I'm being errored out for not having libraries installed:

./regenie: /lib/x86_64-linux-gnu/libmvec.so.1: version `GLIBC_2.35' not found (required by ./regenie)
./regenie: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./regenie)

This is particularly difficult in (e.g.) DNANexus environments. 

Is this easily fixable?

Thanks for your help
Gareth

**Comment by jerome-f** [comment]
This is a compiler/binutils issue. I fixed it by pulling the conda recipe and building it. You can use this https://github.com/jerome-f/regenie/blob/master/binary/regenie-3.6-h6578b86_0.tar.bz2 and then build with conda/mamba

```
mamba create -n regenie
mamba activate regenie
mamba install /path/regenie-3.6-h6578b86_0.tar.bz2 

mamba -n regenie run regenie -h
```

**Comment by joellembatchou** [comment]
Hi Gareth,

Sorry about that, we recently had to switch to Ubuntu 22 which I think caused the error you got. Will try to compile a binary with Ubuntu 20 and post it on the release page. Alternatively, as Jerome mentioned you could go the conda route or use the published docker image?

Cheers,
Joelle

**Comment by dvh13** [comment]
We had this too but slightly different error "while loading shared libraries: libbz2.so.1.0"

Solution was to use one of these (though still on 3.5):

https://anaconda.org/bioconda/regenie
https://quay.io/repository/biocontainers/regenie

d

**Comment by joellembatchou** [comment]
@GHawkes93 Please try the [new binary ](https://github.com/rgcgithub/regenie/releases/download/v3.6/regenie_v3.6.gz_x86_64_ubuntu20_mkl.zip) posted on the v3.6 release page which was compiled with a Ubuntu 20.04 docker image.

**Comment by GHawkes93** [comment]
Perfect - it works now, thanks very much Joelle!
