### ISSUE TITLE
FIRTH regression on burden output

### ISSUE THREAD

**Issue by vanessapitz** [rgcgithub/regenie#554]
Hi there, I'm running a burden analysis in regenie and trying to somehow get effect size and SE as output. I know this is a different analysis than just basic association testing, but I was still hoping someone had some pointers for me. 
I've used --firth and --firth-se but nada. 
Any help is greatly appreciated!! Thank you

**Comment by Ojami** [comment]
with `--frith` flag REGENIE applies Firth correction to burden test statistics as long as the nominal P falls below `--pThresh` (0.05 by default). What seems to be the problem then?

**Comment by joellembatchou** [comment]
Hi,

The effect size and SE are displayed in the BETA and SE columns of the [output sumstats file](https://rgcgithub.github.io/regenie/options/#output).

Cheers,
Joelle
