### ISSUE TITLE
Run time when using .pgen files 

### ISSUE THREAD

**Issue by LeahBoettger** [rgcgithub/regenie#559]
Hello, 

I'm running Regenie for around 20 quantitative traits on the UKB data. As I'm including the X chromosome, I opted to use .pgen files for step 2. Previously, when I did the same without the X chromosome using .bgen files, this only took a few hours but now step 2 has been running for 10+ hours for a single chromosome. I've allocated enough resources and I'm running every chromosome in parallel. 

Can you explain to me if this is normal when using pgen files/ the X chromosome? 

All the best,

**Comment by joellembatchou** [comment]
Hi,

Are all the input files across chromosomes in PGEN format or are you using BGEN for non-chrX and PGEN for chrX?

**Comment by LeahBoettger** [comment]
Hi! Thanks for the quick reply!

I'm using pgen for all chromosomes. I can run the all others using bgen files but this does not solve my issue as processing of one pgen file takes >24 h

**Comment by LeahBoettger** [comment]
Hi there! 
I actually figured it - I had some problems with the pgen file. It now ran perfectly fine within 24 h (I think it was less than 15 actually). 

Thank you so much!
