### ISSUE TITLE
How to use regenie to perform simple regression like fastGWA-lr?

### ISSUE THREAD

**Issue by xiekunwhy** [rgcgithub/regenie#56]
Hi,

How to use regenie to perform simple regression like fastGWA-lr?

Best,
Kun

**Comment by joellembatchou** [comment]
Hi Kun, 

To perform SLR you can run step 2 of Regenie using option `--ignore-pred` which will bypass including polygenic effect predictions from step 1 of Regenie in the model.

Cheers,
Joelle

**Comment by xiekunwhy** [comment]
Hi Joelle,

Thank you for your reply, and I have two other questions:

1) Many reviewers ask us to provide marker R2( or pve) when we want to publish our gwas results(non-human species project). And do you have any suggestions to get marker pve according to regenie results? Can I use formula R2 = 2p(1-p)*Beta^2, where p is one allele's frequency?

2) Can I use genetic covariates like PCA/structure results or just non-genetic covariates like age, gender are accepted?

Best,
Kun

**Comment by joellembatchou** [comment]
Hi Kun,

(1) Yes as the reported effect size is on the original scale for the allele 1 specified. 
(2) You can use principal components as covariates (it is generally recommended to include these to correct for population stratification).

Cheers,
Joelle

**Comment by xiekunwhy** [comment]
Hi Joelle,

Thank you for your reply, and I am waiting for gene/region-base implemented regenie version :).

Best,
Kun
