### ISSUE TITLE
number of covariates

### ISSUE THREAD

**Issue by dvh13** [rgcgithub/regenie#560]
We are currently using 20 common variant PCs, age, age2 as quant and gender as categorical covariates.
Seeing some signals in burden tests (~50k exomes) that might be artefacts.
Thinking of adding in 20 rare variant PCs.

Question: any limit to number of PCs for covariates? More a 'do you lose power in regenie if too many covariates' question?

thanks, david

**Comment by joellembatchou** [comment]
Hi David,

At this large N=50k there will be low penalty from including 20 more covariates.

Cheers,
Joelle

**Comment by dvh13** [comment]
super helpful. thanks.
