### ISSUE TITLE
Effect in regenie output

### ISSUE THREAD

**Issue by PreciousEunice** [rgcgithub/regenie#566]
Hi!  I cannot see the definition of Effect column in the output file.  And when I calculate, it is not the Odds Ratio based from the beta.  What is the meaning of the Effect column and how was it computed?

Thank you.

**Comment by Ojami** [comment]
Hi, do you mean `Beta` column? can you post an excerpt from the output summary stat?

**Comment by Ojami** [comment]
It seems you're using non-native output format. Are you using `--htp` flag? Effect is equivalent to beta column from native format in this case.

**Comment by joellembatchou** [comment]
The Effect columns corresponds to the odds ratios for binary traits (for quantitative traits it is the same as the BETA column in the native output format).
