### ISSUE TITLE
TEST_FAIL on single gene

### ISSUE THREAD

**Issue by GiuliaBrunelli** [rgcgithub/regenie#569]
Hi, I'm running Regenie Step2 on UK biobank RAP using swiss army knife.
This is my code:
length=23
start=1
for (( j=${start}; j<${length}; j++ ));
####while [ "$j" -le 21 ]
do out_name="BC_burden_chr${j}train${GeneList}_${endID}_lo38" ;
run_regenie_step2="regenie --step 2
--bt
--lowmem
--check-burden-files
--write-mask-snplist
--pred ${step1_output_prefix}_pred.list
--bed ${ukb_exome_id}_c${j}_b0_v1
--keep ${train_test_file}
--extract ${VariantList}
--exclude ${variants_toremove_file}
--phenoFile ${pheno_file}
--covarFile ${pheno_file}
--phenoCol breast_cancer
--covarColList age,genetic_PC_array{1:10}
--set-list ${set_list_file}
--anno-file ${annotation_file}
--mask-def ${mask_definition_file}
--firth --approx
--firth-se
--maxstep-null 2 
 --maxiter-null 70000
--aaf-bins ${aaf_bins}
--bsize 1000
--out ${out_name}
--threads 16 --gz"; 

dx run swiss-army-knife -iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.bed"
-iin="${input_dir}/${VariantList}"
-iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.bim"
-iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.fam"
-iin="${output_dir_step1}/${step1_output_prefix}_pred.list"
-iin="${output_dir_step1}/${step1_output_prefix}_1.loco"
-iin="${input_dir}/${pheno_file}"
-iin="${variants_toremove_path}/${variants_toremove_file}"
-iin="${data_file_dir}/tmp/${set_list_file}"
-iin="${input_dir}/${annotation_file}"
-iin="${input_dir}/${mask_definition_file}"
-iin="${input_dir}/${train_test_file}"
-icmd="${run_regenie_step2}"
--tag="Step 2 ${GeneList} chr${j}"
--instance-type "mem1_ssd1_v2_x16"
--destination="${output_dir_step2}/" --brief --yes;
done
The job complete, and I have results for the major part of the genes. However for PALB2 when considering the MAF < 0.01 the test fails, but it doesn't for singleton. I tried to increase the maximum number of iterations and decrease the maxstep-null, but still same problem. Below some pictures of my output files:
from the .regenie.gz file
<img width="959" alt="image" src="https://github.com/user-attachments/assets/7c3241ed-69e8-410e-b4c0-ea8f7f0a58c1">

from the mask.snplinst file
<img width="925" alt="image" src="https://github.com/user-attachments/assets/42de786b-8bb9-4008-84da-29b7c9264e8d">

from the mask_report file
<img width="862" alt="image" src="https://github.com/user-attachments/assets/693540ae-b687-431a-8590-4e9eb53bd844">
How can I avoid the test to fail for PALB2?

**Comment by Ojami** [comment]
Can you use `--debug` flag and pos the log file for that gene (are you using also `--minMAC` ?).

**Comment by GiuliaBrunelli** [comment]
I am not using -minMAC, why?

Il gio 21 nov 2024, 15:01 Oveis Jami ***@***.***> ha scritto:

**Comment by GiuliaBrunelli** [comment]
Hi,here the log with the --debug flag for gene PALB2.
This is the log of the swiss army knife app:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/e13214fc-0b65-485b-8fe6-7d9813b3c86a">

This is from the .log file produced by Regenie:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/66932f7d-4638-4ed9-9400-910f4bbb13bb">

**Comment by Ojami** [comment]
Can you please post the full log file (use the paperclip icon to upload your log file, you can remove sensitive info such as RAP project id, but please keep debugging info)? 
A couple of suggestions:
1. Can you try `skip-fast-firth` to see if you still get the same convergence issue? 
2. If above did not work, remove `--approx` from your cmd and try again.

3. Can you try `write-null-firth` in step 1 and use it via `use-null-firth` in step 2? Keep `--maxstep-null` small and `--maxiter-null` large as you already did.

To speed up the debugging, you don't need to run the full chromosome. Instead use `--extract-sets` to test only variants in your gene of interest. 

Best/Oveis

**Comment by nikotzoumas** [comment]
FYI, as this has caught me out before, the default --minMAC is 5, so if you want all variants included change this to 0.5. But this shouldn't be the cause of the failed testing here.

**Comment by GiuliaBrunelli** [comment]
Hi! it worked removing the flag --approx, can you explain why?
You can find the log files attached.
[job-Gx231pQJ79ky1Y94vkbGf4Fx_Swiss Army Knife.txt](https://github.com/user-attachments/files/17902077/job-Gx231pQJ79ky1Y94vkbGf4Fx_Swiss.Army.Knife.txt)
[BC_burden_chr16_train_ListFree_wes_bc_Female_RFAssignedEU_OthTm_lo38.log](https://github.com/user-attachments/files/17902090/BC_burden_chr16_train_ListFree_wes_bc_Female_RFAssignedEU_OthTm_lo38.log)
Thanks for the help!

**Comment by Ojami** [comment]
Glad it worked! With `--approx` flag, REGENIE uses the fast implementation of Firth's penalty (approximate LRT). 

Best/Oveis

**Comment by joellembatchou** [comment]
Thanks @Ojami for debugging this! Great to hear your convergence issue was addressed using exact Firth.
