### ISSUE TITLE
About WES testing

### ISSUE THREAD

**Issue by solivehong** [rgcgithub/regenie#572]
hi team 

Do you have any suggestions for the sampleset with only wes? 
many cases sample only have WES sample without array to do step 1

all the best 
hong

**Comment by nikotzoumas** [comment]
Hi, not sure if this helps, but you could either make the pred files in Step 1 using only the WES data as input, or go straight to Step 2 and use the flag --ignore-pred to skip loading the predictions file and disable the LOCO framework, using standard regression models instead.

**Comment by solivehong** [comment]
@nikotzoumas so thank for u help，i will try it

**Comment by joellembatchou** [comment]
Hi,

We don't recommend using only WES data for step 1 as the aim is to capture polygenic effects genome-wide. Perhaps you could use a filtered set of imputed variants as a pseudo-array input to step 1?

Cheers,
Joelle

**Comment by solivehong** [comment]
> Hi，
> 
> We don't recommend using only WES data for step 1 as the aim is to capture polygenic effects genome-wide. Perhaps you could use a filtered set of imputed variants as a pseudo-array input to step 1?
> 
> Cheers， Joelle

@joellembatchou thanks

about pseudo do u have any step detail? This is the first time I've heard about the way.

**Comment by joellembatchou** [comment]
I mean using imputed data which should have genome-wide coverage and applying QC like imputation info score to reduce the number of variants to something like 500K or so. We don't recommend this by default but it can be one approach if you don't have high quality directly genotyped SNP data available.

**Comment by solivehong** [comment]
> I mean using imputed data which should have genome-wide coverage and applying QC like imputation info score to reduce the number of variants to something like 500K or so. We don't recommend this by default but it can be one approach if you don't have good quality directly genotyped SNP data available.

Thank you very much for your idea. At the same time, I have an idea to use UKB WGS as pseudo and single cell or bulk without genome data to do eQTL genome analysis. Recently, I saw the SAIGE-QTL in TenK1K to detect rare variants. we can use a larger genome as a pseudo genome to increase the power to detect rare variants
