### ISSUE TITLE
Errors in --keep option

### ISSUE THREAD

**Issue by amymariemason** [rgcgithub/regenie#578]
I want to run a GWAS using regenie on a subset of the participants in All of Us, so I provided a keep file.  I get this error:

`ERROR: sample_eur.txt doesn't exist for option --keep`

This is the command I used

```
regenie \
    --step 1 \
    --bgen "${bgen_file}" \
    --sample  "${sample_file}" \
    --phenoFile "${pheno_file}" \
    --phenoColList "${phen_col}" \
    --covarFile "${cov_file}" \
    --catCovarList sex \
    --covarColList age,age2,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10\
    --bsize 1000 \
    --verbose \
    --"${trait}" \
    --keep "${keep_file}" \
    --apply-rint \
    --ref-first \
    --out "${prefix}"_step1_chr"${chrom}" 
```

If I do not include the keep command, as below, there is no issue and the GWAS runs. 

```
regenie \
    --step 1 \
    --bgen "${bgen_file}" \
    --sample  "${sample_file}" \
    --phenoFile "${pheno_file}" \
    --phenoColList "${phen_col}" \
    --covarFile "${cov_file}" \
    --catCovarList sex \
    --covarColList age,age2,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10\
    --bsize 1000 \
    --verbose \
    --"${trait}" \
    --apply-rint \
    --ref-first \
    --out "${prefix}"_step1_chr"${chrom}"

```
This is confusing me as the file is definitely there & I have triple-checked the name is correct. The file was created by the same R program that outputs the pheno and the covar file, into the same folder, and regenie is not throwing any error on reading those. 

I have tried:
- switching from windows line ends to unix
- outputting as a space seperated .txt file
- outputting as a tab seperated .tsv file 

In each case, the file contains only the FID and IID with no headers, as instructed on your website 
"Sample inclusion/exclusion file format 
No header. Each line starts with individual FID IID. Space/tab separated." 

Any idea why it is struggling to find/open the file? Unfortunately, I am working on the All of Us Workbench so I can't share files for reproducibility.

**Comment by amymariemason** [comment]
Nevermind - it's an issue with how the AoU platform is localising files, not regenie!

**Comment by rimamust** [comment]
Hi, I am getting the same error with DNA nexus platform. I made sure the file exists but kept on getting the same error. Any thought?

**Comment by joellembatchou** [comment]
Hi,

Can you include the REGENIE log?
