### ISSUE TITLE
Analyze genome partitioned in chunks

### ISSUE THREAD

**Issue by mmaalvarez** [rgcgithub/regenie#582]
Hello,
I have my data partitioned into vcfs, meaning that 1 vcf contains 1 genome chunk, another vcf the next genome chunk, etc. In total I have the genome partitioned into ~1400 such chunks.
My question is, is it safe to analyze it like this? I know that the --bsize flag further partitions the genome, but I'm unsure anyway if this is a good practice, or I should merge all the vcf chunks pre-regenie.
Thanks,
Miguel

**Comment by Ojami** [comment]
If you're talking about step 2 (assuming each chunk has only data from a specific chromosome), then yes it's totally fine. You can finally `cat` all chunks of summary stats after REGENIE finished all jobs.  In practice, `--bsize` acts in a similar way.

**Comment by mmaalvarez** [comment]
Thanks for your answer. And for step 1 is it a problem?

**Comment by Ojami** [comment]
For step 1 you ideally should use a subset of high quality directly genotyped markers (~500 K markers are enough). Please see [REGENIE docs](https://rgcgithub.github.io/regenie/faq/#step-1)  and [here](https://github.com/rgcgithub/regenie/issues/497#issuecomment-1997417589) for more info.

**Comment by mmaalvarez** [comment]
Thanks a lot
