### ISSUE TITLE
Could regenie distinguish quantitative and binary covariates automatically? 

### ISSUE THREAD

**Issue by Esther19960123** [rgcgithub/regenie#61]
I found that there is no command to distinguish quantitative from binary covariate. I want to ask whether regenie could identify different kinds of covariates automatically. And could regenie deal with population stratification and relatedness so that PCA components are not needed

**Comment by joellembatchou** [comment]
Hi,

For your 1st question, see #21.

For your second question, similar to other LMM-based methods, we recommend to include principal components as covariates to adequately adjust for population structure. 

Cheers,
Joelle

**Comment by Esther19960123** [comment]
> Hi,
> 
> For your 1st question, see #21.
> 
> For your second question, similar to other LMM-based methods, we recommend to include principal components as covariates to adequately adjust for population stratification.
> 
> Cheers,
> Joelle

Thanks very much! I got it.
