### ISSUE TITLE
Seg fault on example run / test

### ISSUE THREAD

**Issue by JoniColeman** [rgcgithub/regenie#63]
Hi,

I have compiled ReGenie v1.0.6.7 from source (no BLAS/LAPACK routines, STATIC = 0). 

The installation appears to complete appropriately (regenie is made), but on running test_bash.sh I get the following error:

`test/test_bash.sh: line 63: 27901 Segmentation fault      ./$regenie_bin $rgcmd
Step 1 of REGENIE did not finish successfully. Update to most recent REGENIE version (using 'git pull') and re-compile the software (using 'make clean && make').`

This is the latest update, so the suggested help doesn't solve.

System data:
GNU/Linux, release 3.10.0-1062.9.1.el7.x86_64

**Comment by joellembatchou** [comment]
Hi,

Did the Regenie command for step 1 output anything or did  the seg fault occur at the start of the command (i.e. without any output)?

Cheers,
Joelle

**Comment by JoniColeman** [comment]
Hi, thanks for the quick response. It dies pretty much immediately (output below):

    Start time: Tue Dec  1 13:27:17 2020

              |==============================|
              |      REGENIE v1.0.6.7.gz     |
              |==============================|

    Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
    Distributed under the MIT License.
    Compiled with Boost Iostream library.

    Log of output saved in file : fit_bin_out.log

    Options in effect:
      --step 1 \
      --bed /scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/example \
      --exclude /scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/snplist_rm.txt \
      --covarFile /scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/covariates.txt \
      --phenoFile /scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/phenotype_bin.txt \
      --remove /scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/fid_iid_to_remove.txt \
      --bsize 100 \
      --bt \
      --lowmem \
      --lowmem-prefix tmp_rg \
      --out fit_bin_out

    Fitting null model
     * bim              : [/scratch/users/k1204688/Public/tools/regenie-1.0.6.7/example/example.bim] n_snps = 1000
    Segmentation fault

**Comment by joellembatchou** [comment]
Could you check if it runs successfully with one of the [Linux pre-compiled binaries](https://github.com/rgcgithub/regenie/releases/tag/v1.0.6.7)?

**Comment by JoniColeman** [comment]
Unfortunately the GLIBC on the cluster is too old to use the binaries (GLIBC 2.17).

I have now tried recompiling not including the Boost-IO library – that leads to the same issue as reported in #58. 

I will try the conda approach again – I tried this previously but had issues with dependency clash.

**Comment by joellembatchou** [comment]
Is it on Centos? (in which case there is also a Centos 7 pre-compiled binary)

**Comment by JoniColeman** [comment]
Edit - the Centos binary worked - thank you!
