### ISSUE TITLE
Regenie running slowly on some datasets

### ISSUE THREAD

**Issue by demodw** [rgcgithub/regenie#64]
Hi,

We have encountered some weird behavior with regenie. We have, up until now, been working on a dataset containing 93k individuals, and regenie have always been super fast and very good to utilise all CPUs. Each block would take approximately 5k ms, with 25 CPUs.

We have now gotten a new dataset, containing 112k individuals. What is surprising is that each block now takes 40k-45k ms, and we cannot understand why. Regenie is most of the time using only one CPU. We have confirmed with the admin team that IO is not degraded in any way. 

We're using regenie v1.0.3 since we are having trouble compiling it on our CentOS system.

Any advice on how to debug this issue?

**Comment by joellembatchou** [comment]
Could you provide a snippet of the log (for the 93k run and the 112k run)? In step 1, the reading and scaling of the genotype data in blocks is essentially done single-threaded. The computation of the ridge predictors should be multi-threaded.

There is a [pre-compiled Centos7 binary](https://github.com/rgcgithub/regenie/releases/tag/v1.0.6.7) available for Regenie 1.0.6.7 in case you want to use a more recent version.

Cheers,
Joelle

**Comment by demodw** [comment]
Hi Joelle,

Thanks for the reply. I'll need to get it exported from our secure server first. step 1 runs fine, the issue is in step 2.

One thing I noticed after submitting this issue is that we have phased data in the new bgen files. Could this be an issue? The info scores are also negative, which should not be possible.

Cheers,
David

**Comment by joellembatchou** [comment]
Hi David,

Regenie does not handle phased data in BGEN files (I will enforce a check for this in the code). Also, are these files in the BGEN v1.2 format with 8-bit encoding (we have implemented a faster multi-threaded implementation of step 2 for this BGEN format)?

Cheers,
Joelle

**Comment by demodw** [comment]
Hi Joelle,

The phasing seemed to be the problem. Once I removed it, and made sure it was 8-bit encoded, it's running super fast again.

For others with the same issue, I removed the phasing with plink2:

````
plink2 --bgen chr1.bgen ref-first --sample chr1.sample --make-pgen erase-phase --out chr1
plink2 --pfile chr1 --export bgen-1.2 bits=8 --out chr1.bgen_v1.2
````
Could probably be more elegant, but it works.

Thanks for the help!

David

**Comment by joellembatchou** [comment]
Hi David,

Great to hear. I'd just like to point that Regenie does accept PGEN file format so you could skip the second command and just pass the PGEN file output from the first command to Regenie as `--pgen chr1`.

Cheers,
Joelle
