### ISSUE TITLE
BGEN file converted by PLINK2

### ISSUE THREAD

**Issue by Cloufield** [rgcgithub/regenie#65]
Hi,
I am wondering how regenie handles dosage data in step2.
Currently, the data I have is in VCF format,  and I noticed that _Step 2 of regenie can be sped up with BGEN files by using v1.2 format with 8 bits encoding (genotype file can be generated with PLINK2 using option `--export bgen-1.2 'bits=8'`)_
But PLINK2 documents say _you cannot use PLINK 2 to losslessly convert between e.g. BGEN sub-formats._
Is this a thing I should be concerned about?

**Comment by joellembatchou** [comment]
Hi,

Regenie can handle BGEN dosage data (option `--bgen,--sample`). As REGENIE only uses dosages it is fine to use PLINK2 for conversion (indeed, on the same paragraph it states '*(But if the next program in your pipeline is e.g. BOLT-LMM, which only cares about dosages, it's fine to use PLINK 2 for conversion.)*'.

Cheers,
Joelle

**Comment by Cloufield** [comment]
Hi Joelle,

Thank you so much for your help.

Best regards,
He
