### ISSUE TITLE
Specify which position range to include?

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#66]
For Stage 2, one of the options is:

flag | value type  | required? | meaning
-----| ----- | ------ | ------
--chr | INT | Optional | specify which chromosomes to test in step 2 (use for each chromosome to include)

To enhance parallelization of Stage 2, it would be great to be able to further specify the range of positions (base pairs) to include. That would permit, e.g., splitting chromosome 1 inference into several separate jobs to take advantage of multi-machine parallelism. Or is there already a way to do this that I have missed in the documentation?

**Comment by joellembatchou** [comment]
Hi,

This is a feature that has previously been requested and that we are working on adding to Regenie. For now, you could obtain the list of variant IDs in the regions you’d like to test in parallel and pass that to `--extract` in Regenie.

Cheers,
Joelle

**Comment by carbocation** [comment]
Thank you!

**Comment by joellembatchou** [comment]
FYI this feature has been implemented in Regenie v1.0.6.8 (c9d62bbfb92eb49930a9135a19d1e97699f7aa10)

Cheers,
Joelle
