### ISSUE TITLE
Intuition around block size for stage 2

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#67]
Is it possible to provide an intuition about choice of block size for stage 2? Is a larger block size expected to be faster for stage 2, assuming sufficient RAM? (I was going to email this question, but figured other people could benefit from understanding the answer. Not sure if there is a happy medium somewhere between github issues and direct emails.)

**Comment by joellembatchou** [comment]
Hi,

As variants are tested in parallel in step 2 (and the results are the same regardless of what block size is used), a major factor to consider when selecting the block size is the amount of memory required given the sample size (~8BN bytes where B is block size and N is the sample size).  For example, in large scale applications (e.g. UKB), we would recommend to use block size ~500 (so would use about 2Gb of memory assuming N=500K).

Cheers,
Joelle

**Comment by carbocation** [comment]
Thank you, that is very helpful to better understand the RAM usage. If we have more RAM, does a larger block size speed up step 2?

As an example, if I happen to have a terabyte of RAM on the machine running step 2, is there any speed advantage to using a block size of 5,000 instead of 500? (I can also profile this empirically.)

**Comment by joellembatchou** [comment]
I see; we have not found the computational timing to improve by using very large block sizes in step 2.

Cheers,
Joelle

**Comment by carbocation** [comment]
Good to know and thanks for your reply!
