### ISSUE TITLE
Slow level 1 in step 1.

### ISSUE THREAD

**Issue by FrederikFilip** [rgcgithub/regenie#69]
I'm running on 1 continuous phenotype, 8392533 variants, and 4435 samples.
Level 0 block-wise ridge regression runs smoothly.

However, when I get to level 1, the multithreading stops and it's running for multiple days (haven't stopped yet) on a single thread.
The latest log is:
```
Level 1 ridge...
   -on phenotype 1 ([PHENONAME])... 
```
I have used the parameters:
```
--bsize 1000
--lowmem tmpdir
```
and using the precompiled version REGENIE v1.0.6.7.gz for linux.

Any suggestions on how I can improve the call?

Thank you

**Comment by carbocation** [comment]
I'm not affiliated with the software, but from what you have described, you are using a very large number of SNPs to create your GRM in step 1 - over 8 million SNPs. The authors used [469,000](https://rgcgithub.github.io/regenie/performance/) SNPs for Step 1 in their examples. The authors may have more specific advice for you, but in the meantime, you may want to consider [reducing the number of SNPs used in step 1](https://rgcgithub.github.io/regenie/faq/).

**Comment by joellembatchou** [comment]
Hi,

Please check the FAQ page<https://rgcgithub.github.io/regenie/faq/> of the Regenie website where we added recommendations as for how many variants should be run in Step 1. The issue with the speed is due to 8M+ variants being used in the Step 1 run.

Cheers,
Joelle

**Comment by FrederikFilip** [comment]
Great, that makes sense.
Thank you.
