### ISSUE TITLE
make regenie

### ISSUE THREAD

**Issue by fmurgia** [rgcgithub/regenie#7]
Hi,
I am trying to make regenie on linux, but it throws an error.

Here is the last part of the log:

g++ -O3 -ffast-math -std=c++11 -o src/main.o -c src/main.cpp -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//3rd_party/boost_1_55_0 -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38/ -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//genfile/include/ -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//3rd_party/zstd-1.1.0/lib  -fopenmp
g++ -O3 -ffast-math -std=c++11 -o src/Data.o -c src/Data.cpp -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//3rd_party/boost_1_55_0 -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38/ -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//genfile/include/ -I/user/federicom/apps/bgen/gavinband-bgen-44fcabbc5c38//3rd_party/zstd-1.1.0/lib  -fopenmp
In file included from /usr/include/c++/4.8.2/vector:62:0,
                 from src/Data.hpp:27,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = std::basic_ofstream<char>; _Args = {std::basic_ofstream<char, std::char_traits<char> >}]’:
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<std::basic_ofstream<char>*>; _ForwardIterator = std::basic_ofstream<char>*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<std::basic_ofstream<char>*>; _ForwardIterator = std::basic_ofstream<char>*]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<std::basic_ofstream<char>*>; _ForwardIterator = std::basic_ofstream<char>*; _Tp = std::basic_ofstream<char>]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:281:69:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = std::basic_ofstream<char>*; _ForwardIterator = std::basic_ofstream<char>*; _Allocator = std::allocator<std::basic_ofstream<char> >]’
/usr/include/c++/4.8.2/bits/vector.tcc:556:42:   required from ‘void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::basic_ofstream<char>; _Alloc = std::allocator<std::basic_ofstream<char> >; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/4.8.2/bits/stl_vector.h:667:41:   required from ‘void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::basic_ofstream<char>; _Alloc = std::allocator<std::basic_ofstream<char> >; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
src/Data.cpp:3816:33:   required from here
/usr/include/c++/4.8.2/bits/stl_construct.h:75:7: error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from src/Data.hpp:34:0,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/fstream:599:11: note: ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>& ’
In file included from /usr/include/c++/4.8.2/iostream:39:0,
                 from src/Data.hpp:29,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iostream:39,
                 from src/Data.hpp:29,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/ios:42:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iostream:39,
                 from src/Data.hpp:29,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/bits/ios_base.h:786:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iostream:39,
                 from src/Data.hpp:29,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from src/Data.hpp:34:0,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>& ’
/usr/include/c++/4.8.2/fstream:72:11: note: ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8.2/ios:43:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iostream:39,
                 from src/Data.hpp:29,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from src/Data.hpp:34:0,
                 from src/Data.cpp:27:
/usr/include/c++/4.8.2/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
make: *** [Makefile:44: src/Data.o] Error 1

Best,

Federico

**Comment by joellembatchou** [comment]
Could you try compiling with a more recent version of gcc (moveable streams are not supported before GCC 5.1) ?

**Comment by fmurgia** [comment]
Hi, 
regenie was successfully compiled with gcc 8.3.
