### ISSUE TITLE
missing genotypes

### ISSUE THREAD

**Issue by olszewskip** [rgcgithub/regenie#70]
Hi,
apologies, it's probably stated somewhere in the documentation or the preprint, but I cannot seem to find an answer:

How does Regenie treat missing genotypes, e.g. `01` in plink's bed files?

**Comment by joellembatchou** [comment]
Hi,

Missing genotypes are imputed with per SNP averages.

Cheers,
Joelle

**Comment by olszewskip** [comment]
Thanks for a quick answer :)
Best

**Comment by joellembatchou** [comment]
Hi @dvg-p4 it is now clarfied in: https://rgcgithub.github.io/regenie/faq/#step-2. Thank you
