### ISSUE TITLE
intercept covariate

### ISSUE THREAD

**Issue by olszewskip** [rgcgithub/regenie#71]
Hi!
Again, apologies if this is stated explicitly somewhere, but:

Is a covariate column of ones (an intercept) automatically included (or somehow unnecessary), or should I add it by hand to my covarFile if I want the intercept in my null model?

**Comment by joellembatchou** [comment]
Hi,

It is automatically included.

Cheers,
Joelle

**Comment by olszewskip** [comment]
Thanks!
