### ISSUE TITLE
Slow Results on 1 Phenotype

### ISSUE THREAD

**Issue by idinsmore1** [rgcgithub/regenie#74]
Hi there,

I'm using regenie on a set of ~560,000 snps for step 1 with 36627 samples for a quantitative phenotype. Step 1 is taking ~2.2 hours to complete while step 2 takes 6 minutes, which seems to be the opposite of what was described in the biorxiv paper.
I have a machine with 104 threads available with 512 GB of RAM. This is my code for step 1:
./regenie \
  --step 1 \
  --bed OMNI_noXY_stringent \
  --phenoFile OMNI_eGFR_vals.tsv \
  --covarFile OMNI_unrelated_covars_regenie.tsv \
  --bsize 1000 \
  --lowmem tmpdir/regenie_tmp_preds \
  --threads 104 \
  --out OMNI_step1_eGFR

I'm wondering if this is typical timing for this kind of task? Thanks!

**Comment by joellembatchou** [comment]
Hi,

This should not be taking this much time (with N=36627, M=560K, B=1000 and 1QT using 104 threads); using these same parameters (but a machine with 36 threads), I ran step 1 on Regenie v1.0.7 and it took 21.6 mins.

Which Regenie version are you using and in the log, does it say # threads [104]? Also, if you have `htop` installed on your machine, do you see all threads being used? Alternatively, there are [pre-compiled Regenie binaries](https://github.com/rgcgithub/regenie/releases) that you could use instead.

Note: To specify a path for `--lowmem` use `--lowmem-prefix` so in your case it would be `--lowmem --lowmem-prefix tmpdir/regenie_tmp_preds` (this was corrected on the website example as well)

Cheers,
Joelle

**Comment by idinsmore1** [comment]
Hi Joelle, 

Thanks for the response. This is using the precompiled binary for Centos7 (I renamed it regenie for ease of use), I checked htop while it was running and regenie appeared to be using all the threads. I'll make sure to change the command with --lowmem as you stated. Thanks for your help!

Best,
Ian

**Comment by idinsmore1** [comment]
Joelle,

Here is a clip of the log where I tried a binary trait but am having almost the same results, so you can see the run times for each block on the level 0 regressions for step 1, if that would be helpful at all
[regenie_issues.log](https://github.com/rgcgithub/regenie/files/5896050/regenie_issues.log)

**Comment by joellembatchou** [comment]
As discussed by email, there is now a [Centos7 pre-compiled binary with Intel MKL](https://github.com/rgcgithub/regenie/releases/tag/v2.0-latest) which should help with the runtime differences.

**Comment by joellembatchou** [comment]
As discussed by email, there is now a [Centos7 pre-compiled binary with Intel MKL](https://github.com/rgcgithub/regenie/releases/tag/v2.0-latest) which should help with the runtime differences.
