### ISSUE TITLE
Regenie to estimate beta for rare variants

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#75]
Hi Joelle, 

I am wondering how regenie to estimate beta for very rare variants (MAF<0.0001)? I find the beta sometime looks wearied for these very rare variants. 

Thanks.

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

I am assuming you are asking for binary traits (for quantitative traits, it is the OLS estimate). For Firth, the effect size is estimated from a logistic model with Firth penalty. For SPA, it is obtained by using the SPA p-value and the standard error from standard logistic model (which with unbalanced traits may be prone to inflation). 

With highly unbalanced traits, we have found through simulations that for ultra-rare variants, the effect size estimates from Firth were more reliable (i.e. closer to the simulated value) than those from SPA.

Cheers,
Joelle
