### ISSUE TITLE
UK Biobank Exome analysis

### ISSUE THREAD

**Issue by samkleeman1** [rgcgithub/regenie#76]
Hi,

Many thanks for making this incredible package, we are very excited to use it!

I had a couple of questions about the burden analysis in UK biobank exome data (we have downloaded the data for the release of 200k subjects):

1) What SNPs would you use for step 1? Would you recommend using 500k SNPs from the paired genotype array data? Or to use a downsampled set of the exome variants?
2) Do you have annotation list/mask list files generated for the UK Biobank dataset that you are open to sharing?

Kind regards,

Sam Kleeman
Phd Student, Cold Spring Harbor Laboratory, NY

**Comment by rgcgithub** [comment]
Hi Sam,

Glad you are finding REGENIE useful.

Yes - for UK Biobank we recommend using the array genotypes for Step 1. See our paper here for more details https://www.biorxiv.org/content/10.1101/2020.06.19.162354v2 but we also have a tab of the webpage that details UKBB best-practice https://rgcgithub.github.io/regenie/recommendations/ The idea of Step 1 is to use a set of SNPs that do a good job of capturing the polygenicity of the trait (and implicitly accounting for relatedness and population structure in the sample). So having a good covering of the common variants in the genome is a good idea. A downsampled set of the exome data wouldn't do as good a job for that i.e associated non-coding variants not in high LD with the exome would not be captured.

We can't at this stage share annotation files. We've put some advice on webpage about how you could generate them. But we are already working on putting a set of annotation files together for the 450k exome dataset that will made available to approved researchers later this year. 

I hope that helps,

Jonathan

**Comment by webhash** [comment]
Hi Team,

Just opened the regenie page and was glad to see that now you support the burden test directly ... this would save a lot of cycles. 



@samkleeman1 @rgcgithub hello , may you be kind enough to share some pointers for approaches taken for variant quality calling ? ukbb exome data is missing a lot of annotation required for variant calling, how did you tackle this issue ? any pointers please ?

**Comment by samkleeman1** [comment]
From my perspective, I am downloading the UKB exome VCF files (7TB). I will annotate the variants in the VCF format using SnpEff. Then, I am planning to do some variant filtering in Hail using parameters recommended in the Medrxiv paper (e.g. read depth) before exporting back as PLINK files. It is quite frustrating that the PLINK files were released entirely unannotated and unfiltered.

**Comment by ggstatgen** [comment]
Hello everyone - thanks for the insightful discussion - May I just ask everyone - would recommend LD-pruning the variants in the UKBB SNP-chip dataset used for REGENIE's phase 1, eg

`plink [...]
 --hwe 1E-15 \
 --maf 0.01 \
 --geno 0.1 \
 --indep-pairwise 50 5 0.05 \
 --out [...]
`

Thanks!

**Comment by Lloyd-LiuSiyi** [comment]
Hi @rgcgithub Jonathan,
        I'm new to annotation, and I'm wondering if you have made some annotation files available, which is gonna be so helpful.

Thanks!
Siyi

**Comment by joellembatchou** [comment]
Hi Siyi,

REGENIE annotation files for UKBB WES analysis have been made available on the RAP; perhaps you could use these for reference.

Cheers,
Joelle

**Comment by Lloyd-LiuSiyi** [comment]
Hi @joellembatchou, I've successfully made use of `ukb23158_500k_OQFE.annotations.txt.gz`. Thanks for your helpful suggestion!
