### ISSUE TITLE
Docker image instructions

### ISSUE THREAD

**Issue by jzluo** [rgcgithub/regenie#77]
Hi, the instructions for docker (https://github.com/rgcgithub/regenie/wiki/Using-docker) authenticate to ghcr.io, but then pull from docker.pkg.github.com, which doesn't work (no basic auth credentials error). Authenticating to docker.pkg.github.com does work, as expected. 
Is Regenie migrated to the Container Registry from the Packages Registry yet? If so, the registry address needs to be changed to the new ghcr.io address. Otherwise, the login address should be docker.pkg.github.com rather than ghcr.io

Thank you!

**Comment by joellembatchou** [comment]
Hi,

Thank you for the notice, this has been fixed on the Wiki page.

Cheers,
Joelle
