### ISSUE TITLE
PED file construction

### ISSUE THREAD

**Issue by wwilman** [rgcgithub/regenie#78]
Hi, 
we have encountered a problem while using regenie that concerns the Phenotype file.
It seems that the tool does not see phenotypes occurring in the file - it notices the phenotypes column but the issue is: 
regenie ERROR: All individuals have missing/invalid phenotype values
The phenotypes are marked by 0 1 and tab-delimited. 
We tried to change .fam file into Phenotype file, but this did not work either and the same error occurred.
Is there any way to tackle this issue?

Kinds regards,
Wiktoria Wilman
MSc Bioinformatic Student

**Comment by joellembatchou** [comment]
Hi,

Regenie can read in tab/space delimited phenotype file. Are you using `--phenoCol/--phenoColList` to specify phenotype columns in file and how many columns are present in the phenotype file? 

If you do `cat -A phenoFile.txt | head -n 3` to view first three rows with special characters visible, are there any special characters in the file?

**Comment by wwilman** [comment]
Hi, 
thank you for your questions! It turned out line break character to be the problem that prevented regenie from correct view of the file
But the answers:
No, I haven't used --phenoCol/--phenoColList and the first three rows looked just fine.
Thank you again and sorry for bothering with such trivial problem.
