### ISSUE TITLE
with-bgi removed in version 2.xx?

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#79]
I'm running `./regenie_v2.0.1.gz_x86_64_Linux_mkl --helpFull` and no longer see a reference to `--with-bgi` (which also causes the program to halt when passed). Has this option been removed? (Asking because it's still [referenced in the docs](https://github.com/rgcgithub/regenie/blob/master/docs/docs/options.md).)

**Comment by joellembatchou** [comment]
Yes `--with-bgi` has been removed starting v1.0.6.9. By default, Regenie will assess whether a .bgi file exists and if it does, it will be used.

Cheers,
Joelle
