### ISSUE TITLE
Special casing UK Biobank bgi files for single-digit autosomes

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#80]
I haven't fully bisected the commits to see where this started, but I think that around 7489b0cbafb79792a7f0d684a0a0c9b8b3ced5da the UK Biobank .bgi files for autosomal chromosomes 1-9 started causing issues when the `--chr` flag is passed to `regenie`. (Specifically: `ERROR: No variant left to include in analysis.`)

I think this is happening because in the .bgi, the chromosomes are encoded as '01', '02', ... etc., rather than how they are represented in the .bgen (which is '1', '2'). (It's also possible that this affects only the Broad's UK Biobank .bgi files, but I don't have a way to check that.) This may just be a UK Biobank issue that is not worth special-casing. But I wanted to mention it here.

**Comment by joellembatchou** [comment]
Hi,

This should be fixed in commit d83d98924903c663dd86861d63667261e70a4143.

Cheers,
Joelle
