### ISSUE TITLE
P values when --bt is passed but not --firth or --spa

### ISSUE THREAD

**Issue by carbocation** [rgcgithub/regenie#81]
When running a binary trait GWAS (`--bt`), if neither of the optional `--firth` nor `--spa` are passed, which method is used to compute P values? I don't believe that I've found this in the documentation or the FAQ, but might have missed it.

**Comment by joellembatchou** [comment]
Hi,

It uses a logistic regression score test [(pages 41-42 of bioRxiv paper)](https://www.biorxiv.org/content/10.1101/2020.06.19.162354v2).

Cheers,
Joelle

**Comment by carbocation** [comment]
Fantastic, thank you for your help. (I can close this issue if you want, or leave it open in case you want to adjust the documentation.)

**Comment by joellembatchou** [comment]
This has now been clearly stated in the [documentation](https://rgcgithub.github.io/regenie/overview/#binary-traits).
