### ISSUE TITLE
Different genome build used for phase 1 VS phase 2 data

### ISSUE THREAD

**Issue by ggstatgen** [rgcgithub/regenie#82]
Hi

Does it matter for Regenie if the genome build used for the variants in phase I are not the ones used for the variants in phase II?

Whilst setting up a Regenie run to look at associations on the UKBB 200k WES set, I noticed that the original UKBB genotype chip data I plan on using for phase 1  is in GRCh37/hg19, whereas the 200k WES are in GRCh38/hg38.

How to deal with this? Will Regenie use the rsIDs in the ukb_cal_allChrs.bim for phase I or will it make use of the coordinates instead? 

Is a liftover of sorts needed? Many thanks in advance.

**Comment by rgcgithub** [comment]
If you use the chip data in Step 1 and the WES data in Step 2 it shouldn't matter if the chip data is GRCh37/hg19 and the WES data is GRCh38/hg38. When testing a SNP in Step 2 using the LOCO scheme REGENIE conditions on a PRS constructed from all other chromosomes. It doesn't matter what the SNP coordinates are when building that PRS. 

However, it would probably recommend that you do liftover the GRCh37/hg19 data to GRCh38/hg38. Just for the sake of avoiding any confusion of any other analysis you might want to do that combines the chip and WES data.

I hope that helps,

Jonathan

**Comment by ggstatgen** [comment]
Many thanks for the speedy reply Jonathan - it helps a lot.
