### ISSUE TITLE
Regenie on UKB Exomes

### ISSUE THREAD

**Issue by ConnorBarnhill** [rgcgithub/regenie#83]
Hello, 

First, thank you for your contributions. Amazing work.

We're looking to run the regenie method on UKB Exomes. I understand your recommendation to use genotype arrays in step one. My question is, there shouldn't be any downside to including samples in step one with array data that don't have exome data, correct? I would think the more data you have to build the polygenic risk model, the better.

Also, in the preprint publication I saw that you limited the analysis to white British, but that isn't included in the recommendations. I understand the model is meant to be robust to sample relatedness, but will it be robust to genetic diversity as well? Or should analyses still be performed separately by genetic ancestry and combined after the fact?

**Comment by rgcgithub** [comment]
Hi Connor, good question. Yes, there are more samples with array data (~500k) than exome data (~200k) currently. So if you use all the array samples in Step 1 it is reasonable to assume you would build a better PRS, and that should be a good thing to use for the 200k samples with exome data. If the exome samples were different in some way it might cause a bias, but I don't think there is any reason why they should be.

You are right that in our pre-print we just used white british, but in the revised version of the paper (soon to appear) we have extended that to samples of european ancestry and it all works well. You could also go to the full dataset, or split out by continental ancestry and combine via some type of meta-analysis. In each case, current thinking is also to include some genetic PCs as covariates.

I hope that helps,

Jonathan

**Comment by ConnorBarnhill** [comment]
That's helpful, thank you for your input. I will keep an eye out for the revised paper.
