### ISSUE TITLE
NA's generated during association analysis

### ISSUE THREAD

**Issue by dianacornejo** [rgcgithub/regenie#85]
Dear @joellembatchou, 

I've found out that after running some association analyses there are NA's being generated in the LOG10P column.

`17 21298407 17:21298407:T:C T C 0.499997 ADD -6.10684 2.70234 5.10686 NA`

Just wondering if you have any insight on why this might be happening?

Thank you

**Comment by joellembatchou** [comment]
Hi,

With Firth or SPA corrections (which I assume you are using), `NA` is printed in the p-value column to indicate that the correction failed (so the beta/se/chisq values reported are from standard logistic regression score test).

Cheers,
Joelle

**Comment by dianacornejo** [comment]
Hi, @joellembatchou 

Thanks it solves my question!

Diana

**Comment by Shicheng-Guo** [comment]
> Hi,
> 
> With Firth or SPA corrections (which I assume you are using), `NA` is printed in the p-value column to indicate that the correction failed (so the beta/se/chisq values reported are from standard logistic regression score test).
> 
> Cheers,
> Joelle

How to avoid this situation? I find 'NA' might always come out when it is very significant.  Thanks.

**Comment by joellembatchou** [comment]
We don't yet have a way to avoid this situation though it often occurs for variants which are very rare in cases and where you would expect the standard logistic regression score test to be inflated.
