### ISSUE TITLE
step 2 questions

### ISSUE THREAD

**Issue by ConnieXuhm** [rgcgithub/regenie#86]
hi @rgcgithub,
I am conducting regenie step2, and following is my code :
```
./regenie_v1.0.6.7.gz_x86_64_Linux  --step 2 --bgen 0225_all.bgen --sample regenie_sample.sample --phenoFile regenie_phenotype_bin.txt --phenoCol all,all_exoc,del,del_exoc --cc12 --covarFile regenie_phenotype_cov.txt --bsize 400 --bt --threads 20 --firth --approx --pThresh 0.005 --pred step1_regenie_pred.list --out step2_regenie
```
And I met the error:
```
Options in effect:
  --step 2 \
  --bgen 0225_all.bgen \
  --sample regenie_sample.sample \
  --phenoFile regenie_phenotype_bin.txt \
  --phenoCol all,all_exoc,del,del_exoc \
  --cc12 \
  --covarFile regenie_phenotype_cov.txt \
  --bsize 400 \
  --bt \
  --threads 20 \
  --firth \
  --approx \
  --pThresh 0.005 \
  --pred step1_regenie_pred.list \
  --out step2_regenie \
  --maxstep-null 5 \
  --maxiter-null 50000

Association testing mode with multithreading using OpenMP
 * bgen             : [0225_all.bgen]
   -summary : bgen file (v1.2 layout, compressed) with 2816 anonymous samples and 8793807 variants.
   -sample file: regenie_sample.sample
 * phenotypes       : [regenie_phenotype_bin.txt] n_pheno = 3
   -number of phenotyped individuals = 2816
 * covariates       : [regenie_phenotype_cov.txt] n_cov = 8
   -number of individuals with covariate data = 2816
 * number of individuals used in analysis = 2816
 * LOCO predictions : [step1_regenie_pred.list] n_files = 3
   -file [/data/Hengmin_Xu/xvhengmin/*./20210201/SAIGE/step1_regenie_1.loco] for phenotype 'all'
   -file [/data/Hengmin_Xu/xvhengmin/*./20210201/SAIGE/step1_regenie_2.loco] for phenotype 'all_exoc'
   -file [/data/Hengmin_Xu/xvhengmin/*./20210201/SAIGE/step1_regenie_3.loco] for phenotype 'del'
 * # threads        : [20]
 * block size       : [400]
 * # blocks         : [21993]
 * approximate memory usage : 18MB
 * using minimum MAC of 5 (variants with lower MAC are ignored)
 * using fast Firth correction for logistic regression p-values less than 0.005

Chromosome 1 [1747 blocks in total]
   -reading loco predictions for the chromosome...done (4ms) 
   -fitting null logistic regression on binary phenotypes...
     WARNING: Fitted probabilities numerically 0/1 occured (for phenotype #2).done (19ms) 
   -fitting null Firth logistic regression on binary phenotypes...ERROR: Firth penalized logistic regression failed to converge for phenotype: all_exoc. Try decreasing the maximum step size using `--maxstep-null` (currently=5) and increasing the maximum number of iterations using `--maxiter-null` (currently=50000).
```
I tried several parameter of maxstep-null and maxiter-null, however, it still has the error.
Could you please tell me how to fix it? Or is it matter if I drop the --firth command?
By the way, when I drop the --firth command, it runs, but has the warning:
```
WARNING: Fitted probabilities numerically 0/1 occured (for phenotype #2).done (19ms)
```
Thanks!

**Comment by joellembatchou** [comment]
See the [FAQ](https://rgcgithub.github.io/regenie/faq/) page on the Regenie website. How many cases are there for the trait? 

Low case-counts can cause convergence issue in logistic regression (from the log it happened both in the standard and Firth corrected logistic regression). I am not sure if it can be fixed without increasing the sample size. 

You can drop the `--firth` but if the trait is highly imbalanced you may get inflation for your tests on rare variants (alternatively, there is SPA correction available [using `--spa`] but it will get conservative in extreme chase-control imbalance scenarios).

Cheers,
Joelle

**Comment by SamiFarashi** [comment]
Hi @joellembatchou ,
Using regenie for multiple qts:
"Linear regression is then used to test association of the residualized phenotype and the genetic marker."
Can you clarify what does exactly regenie do to residualize the phenotype?
Thanks,
Sami

**Comment by joellembatchou** [comment]
Hi Sami,

Please check Eqns (3) and (6) in the online Methods section of the REGENIE paper.](https://doi.org/10.1038/s41588-021-00870-7)

Cheers,
Joelle

**Comment by GiuliaBrunelli** [comment]
Hi, I have a similar issue. I'm running Regenie Step2 on UK biobank RAP using swiss army knife. 
This is my code:
length=23
start=1
for (( j=${start}; j<${length}; j++ ));
####while [ "$j" -le 21 ]
do out_name="BC_burden_chr${j}_train_${GeneList}_${endID}_lo38" ; \
run_regenie_step2="regenie --step 2 \
--bt \
--lowmem \
--check-burden-files \
--write-mask-snplist \
--pred ${step1_output_prefix}_pred.list \
--bed ${ukb_exome_id}_c${j}_b0_v1 \
--keep ${train_test_file} \
--extract ${VariantList} \
--exclude ${variants_toremove_file} \
--phenoFile ${pheno_file} \
--covarFile ${pheno_file} \
--phenoCol breast_cancer \
--covarColList age,genetic_PC_array{1:10} \
--set-list ${set_list_file} \
--anno-file ${annotation_file} \
--mask-def ${mask_definition_file} \
--firth --approx \
--firth-se \
--aaf-bins ${aaf_bins} \
--bsize 1000 \
--out ${out_name} \
--threads 16 --gz"; \


dx run swiss-army-knife -iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.bed" \
-iin="${input_dir}/${VariantList}" \
-iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.bim" \
-iin="${exome_path}/${ukb_exome_id}_c${j}_b0_v1.fam" \
-iin="${output_dir_step1}/${step1_output_prefix}_pred.list" \
-iin="${output_dir_step1}/${step1_output_prefix}_1.loco" \
-iin="${input_dir}/${pheno_file}" \
-iin="${variants_toremove_path}/${variants_toremove_file}" \
-iin="${data_file_dir}/tmp/${set_list_file}" \
-iin="${input_dir}/${annotation_file}" \
-iin="${input_dir}/${mask_definition_file}" \
-iin="${input_dir}/${train_test_file}" \
-icmd="${run_regenie_step2}" \
--tag="Step 2 ${GeneList} chr${j}" \
--instance-type "mem1_ssd1_v2_x16" \
--destination="${output_dir_step2}/" --brief --yes; \
done
The job complete, and I have results for the major part of the genes. However for PALB2 when considering the MAF < 0.01 the test fails, but it doesn't for singleton. I tried to increase the maximum number of iterations and decrease the maxstep-null, but still same problem. Below some pictures of my output files:
from the .regenie.gz file
<img width="854" alt="image" src="https://github.com/user-attachments/assets/a7b99148-1c6d-4b77-989a-65b9332f75a5">
from the mask.snplinst file
<img width="881" alt="image" src="https://github.com/user-attachments/assets/9cd61457-e82b-435f-a336-0e8241af62ba">
from the mask_report file
<img width="862" alt="image" src="https://github.com/user-attachments/assets/dc16a41f-82f0-466b-b266-5b8628f1ffe7">
How can I avoid the test to fail for PALB2?

**Comment by joellembatchou** [comment]
Hi, you can use `--debug` to try to get more information about why the test is failing. Perhaps you can try with exact Firth (omitting `--approx`) or with SPA (using `--spa` instead of `--firth`).

Cheers,
Joelle

**Comment by freblisna** [comment]
I had the same error as @ConnieXuhm for Firth logistic regression failing to converge on step 2 (mine was without the warning for the non-firth logistic regression). What strangely worked for me is that I had been using --threads 4 and I set it to --threads 1. I'm not sure why this helped but it cleared the error and regenie proceeded as normal for chromosome 1. However, it then crashed again at chromosome 2 with the same error.

My command below:
``` 
regenie --step 2 --pgen prep_datasets/1_QC_genetic_data/data_acaf_maf/amr_merged --extract gwas/variants/amr_variants_STEP2.txt --keep gwas/participants/gwas_aou_amr_Female_participants.txt --phenoFile gwas/phenos/gwas_aou_amr_Female_pheno.txt --phenoCol gwas_aou_amr_Female --covarFile gwas/covars/gwas_aou_amr_Female_covars.txt --covarColList SEX,AGE,PC1,PC2,PC3,PC4,PC5 --pred gwas/regenie/gwas_aou_amr_Female_step1_pred.list --firth --approx --pThresh 0.01 --bt --ref-first --threads 1 --bsize 2000 --strict --verbose --out gwas/regenie/gwas_aou_amr_Female_step2
```
