### ISSUE TITLE
Inverse transformation to quantitative trait is implemented in Regenie? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#87]
Dear Regenie team,

whether REGENIE implemented inverse transformation to quantitative traits or we need to do it beforehand to run Regenie?

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

RINTing is not yet implemented in Regenie but we will add it to the list of features to add in the software. For now, you will have to do it prior to running Regenie.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Now available in v2.2 using `--apply-rint`.
