### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [rgcgithub/regenie#88]
[jw@cn06 regenie]$ make VERBOSE=1 -j1
(cd ./external_libs/mvtnorm/;make)
make[1]: Entering directory '/data/jw/regenie/external_libs/mvtnorm'
make[1]: 'libMvtnorm.a' is up to date.
make[1]: Leaving directory '/data/jw/regenie/external_libs/mvtnorm'
g++ -O3 -Wall -pedantic -ffast-math -std=c++11 -Wno-unused-local-typedefs -Wno-deprecated-declarations -Wno-long-long -fPIC -DVERSION_NUMBER=\"2.0.1\" -o src/Data.o -c src/Data.cpp -I/3rd_party/boost_1_55_0 -I./external_libs/pgenlib/ -I./external_libs/pgenlib//simde/ -I./external_libs/pgenlib//include/ -I./external_libs/cxxopts/include/ -I -I./external_libs/eigen3/ -I/genfile/include/ -I/3rd_party/zstd-1.1.0/lib -I/db/include/ -I/3rd_party/sqlite3 -I./external_libs/ -fopenmp
In file included from src/Data.cpp:30:
src/Regenie.hpp:55:10: fatal error: Eigen/Dense: No such file or directory
   55 | #include "Eigen/Dense"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:134: src/Data.o] Error 1
[jw@cn06 regenie]$

**Comment by joellembatchou** [comment]
Hi,

From the compilation line, it seems the 'BGEN_PATH' variable is not set (`**-I** -I./external_libs/eigen3/`). Either set it inside the Makefile (in the line with `BGEN_PATH=`) or pass it in the make command (ie `make BGEN_PATH=<path_to_installed_bgen_lib>`). 

Cheers,
Joelle

**Comment by LutzWeischerFujitsu** [comment]
:-)
