### ISSUE TITLE
Burden Tests - relationship between --aaf-bins and --minMAC arguments

### ISSUE THREAD

**Issue by ggstatgen** [rgcgithub/regenie#89]
Dear Regenie developers

I have been testing the new burden functionality and have a question regarding the relationship between `--aaf-bins` and the `--minMAC` arguments.

I have not explicitly set the `--minMAC` - I understand this means it is set to a default of 5 - this seems to be reflected by the runtime log which states

`* using minimum MAC of 5 (masks with lower MAC are ignored)`

It would appear the filter is working as, at completion, I get lines similar to the following:

`Number of ignored tests due to low MAC : 10908`

I have, however, set `--aaf-bins 0.1,0.05`

which is reflected in the logs as follows

`* aaf cutoffs      : [2 : 0.05 0.1 ] + singletons`

So my doubt is about the meaning of that 'singleton'. If I understand correctly, any variant observed in <=5 samples will not be considered further for association testing. So what does the program consider as a 'singleton' when --aaf-bins is set?

**Comment by joellembatchou** [comment]
The minimum MAC filter is not applied to single variant sites when generating the burden masks (so only monomorphic sites are excluded when building masks).

As stated in the log "using minimum MAC of 5 (**masks** with lower MAC are ignored)", the minMAC filter will be applied to the generated masks (this is only applied when using the 'max' or 'comphet' rules which will generate masks with values in [0,2] like actual single variants). 

Cheers,
Joelle

**Comment by ggstatgen** [comment]
I see thanks so MAC here refers to minimum allele count of the whole mask rather than a variant. Thanks for the clarification and sorry for missing the bit above!
