### ISSUE TITLE
Step 1 model training to specific genomic region

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#90]
Dear Joelle, 

I am wondering can I only train the model to a specific genomic region (eg. only HLA region) in step 1 and use received model on new data with step 2? 

Thanks. 

Shicheng

**Comment by rgcgithub** [comment]
Dear Shicheng,

You could do that technically, but it is not what we recommend. The main purpose of Step 1 is to obtain a genome-wide prediction, which serves to control for polygenicity, relatedness and ancestry. If you only use a small subset of the genome you would not be accounting for this effects. It would depend on the trait and how much relatedness and ancestral diversity you have in your dataset. 

I hope that helps,

Jonathan
