### ISSUE TITLE
regenie to multiple population

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#91]
Dear Joelle and Jonathan, 

In regenie manual, the example limited the analysis in White British individuals. Is there anything we should be careful when we use it in mixed populations including Asian, AF and EU. 

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

We have also done further simulation analyses to full European ancestry UKB samples (will be in revised version of the paper) and method remains well calibrated. For mixed populations, you could either analyze the full dataset (we do recommend to include PCs as covariates) or analyze within each population and carry out meta-analyses.

Cheers,
Joelle
