### ISSUE TITLE
Step 2 output discrepancies

### ISSUE THREAD

**Issue by kazo7929** [rgcgithub/regenie#92]
Dear authors,

Thanks for this software! I am really enjoying using it.

I am writing to ask about 2 issues I've run into.
1. I ran a GWAS on 33 traits, and for one of the traits I got a line count in the result file that differs from the other 32. The difference is 273 SNPs, which is a drop in the bucket, but I would like to understand what caused it. I looked at the differing SNPs, and they are low MAF (<0.01) variants from different chromosomes.
2. My script goes through an array of chromosomes, and for one of the chromosomes (no. 2) the job terminated before processing all the blocks and without outputting any error, but also without printing the time elapsed. This too resulted in missing SNPs in the results file, 500K this time, so I reran the job, and it completed successfully. It is possible that this error is attributable to my institution's server job scheduler, but I am noting it here in case others have run into the same problem.

**Comment by joellembatchou** [comment]
Hi,

(1) Was it a binary trait and if so was it using Firth/SPA? Variants for which these fail are not included in the sum stats file (and this would differ based on the trait).
If not, perhaps these variants have low minor allele counts for the trait? (assuming missingness pattern is different across these 33 traits)

Cheers,
Joelle

**Comment by kazo7929** [comment]
Thanks, Joelle.
Yes, it was a binary trait analysed with Firth.
