### ISSUE TITLE
Questions on the GRM or kinship

### ISSUE THREAD

**Issue by Jia21** [rgcgithub/regenie#94]
Dear REGENIE team,

I am wondering whether REGENIE could handle the GRM or kinship matrix problem. As I read the paper of REGENIE, the formula did consider the genetic relatedness matrix. But in the REGENIE input, we actually don't need to pre-calculate GRM or kinship matrix and input the kinship matrix or GRM, therefore I am wondering RENEGIE could handle this problem inside of the algorithm.

Thanks a lot! 
Elaine

**Comment by joellembatchou** [comment]
Hi Elaine,

We have addressed this question in the [FAQ tab](https://rgcgithub.github.io/regenie/faq/) of the Regenie website.

Cheers,
Joelle

**Comment by Jia21** [comment]
Thank you, that's great helpful!

**Comment by brettva** [comment]
@joellembatchou 

Apologies for being dense, but does this mean that similar to SAIGE you don't have to exclude related samples prior to analysis. I am trying to understand if that is what is meant by this sentence in the [FAQ](https://rgcgithub.github.io/regenie/faq/):

"we bypass having to use the GRM K and use the polygenic effect estimates X^β to control for population structure when testing variants for association."

Thank you so much, the tool has been very user friendly and the documentation is great!

**Comment by joellembatchou** [comment]
Hi,

Regenie accounts for population structure and relatedness in Step 1 through the estimation of genome-wide polygenic effect component from the whole genome regression model. The paper includes simulations with various amounts of relatedness present (see Extended Data Figs. 5 & 6).

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Hi Amber,

1. Yes GCTA uses a linear mixed model approach (integrating out the SNP effects) whereas REGENIE uses whole genome regression (directly modeling the SNP effects)
2. In REGENIE step 1, the [level 1  model](https://rgcgithub.github.io/regenie/overview/#cross-validation-level-1) includes all the level 0 block predictors.

Cheers,
Joelle
