### ISSUE TITLE
Regenie slower with more CPUs involved

### ISSUE THREAD

**Issue by idinsmore1** [rgcgithub/regenie#95]
Hello Regenie Team,

Thanks for making this great tool. My team and I have been doing some testing with the regenie docker image on a remote server (96 cores, 1.5TB RAM), and we've come across some strange behavior. It seems that regenie is performing optimally with up to 16 cpus allocated to it, but then past that we see a significant drop off in performance. We tested regenie with --threads set to 32 and 1, just to see if that had any effect. The testing set was a group of plink files that contained information for  2444 samples with snps solely from Chromosome 1. The results can be seen below.

### --threads 32 example command
docker run -t -i \\
--cpuset-cpus=0-31 \\
-m 32000m -v /data:/data:z \\
-u $(id -u):$(id -g) \\
docker.pkg.github.com/rgcgithub/regenie/regenie:v2.0.1.gz regenie \\
    --step 1 \\
    --bed /data/test \\
    --covarFile /data/covariates.tsv \\
    --phenoFile /data/pheno.tsv \\
    --exclude /data/snps.tsv \\
    --bsize 1000 \\
    --bt \\
    --threads 32 \\
    --verbose \\
    --out /data/step1_out

| CPUs | RAM (Gb) | Time (s) |
|------|------|------|
| 4 | 16 | 15 |
| 8 | 16 | 13 |
| 8 | 32 | 13 |
| 16 | 16 | 12 |
| 16 | 16 | 13 |
| 32 | 16 | 49 |
| 32 | 32 | 30 |
| 64 | 16 | 74 |
| 64 | 32 | 79 | 

### --threads 1 example command 
docker run -t -i \\
--cpuset-cpus=0-31 \\
-m 32000m -v /data:/data:z \\
-u $(id -u):$(id -g) \\
docker.pkg.github.com/rgcgithub/regenie/regenie:v2.0.1.gz regenie \\
    --step 1 \\
    --bed /data/test \\
    --covarFile /data/covariates.tsv \\
    --phenoFile /data/pheno.tsv \\
    --exclude /data/snps.tsv \\
    --bsize 1000 \\
    --bt \\
    --threads 1 \\
    --verbose \\
    --out /data/step1_out

| CPUs | RAM (Gb) | Time (s) |
|---|---|---|
| 4| 16 | 23.61 |
|4 | 32 | 21.82 |
| 8 | 16 | 21.24 |
| 8 | 32 | 18.9 |
| 16 | 16 | 18.48 |
| 16 | 32 | 20.84 |
| 32 | 16 | 56.76 |
| 32 | 32 | 197.38 |
| 64 | 16 | 261.77 |
| 64 | 32 | 254.42 | 

We chose to use the docker image for this testing so we could specifically control the cpus and RAM allocated to the process, as the precompiled binary files seemed to try to grab more computation power than --threads should have allowed. Thanks for reviewing, and we appreciate any insight on to why this could be happening!

EDIT: Since this post, we have also tested setting --threads =  --cpuset-cpus, and found that performance definitely improved across the board for each setting, but the same dropoff in overall performance was found above 16 CPUs.

**Comment by fmurgia** [comment]
Hi idinsmore1,
did you notice same performance with Step2 also?

**Comment by idinsmore1** [comment]
Hi fmurgia,

I just ran a quick test on some exome sequencing data we have for step 2 using the results from what I had posted above. This is what we found:

| CPUs | RAM (Gb) | Time (s) |
| ---- | ---- | ---- |
| 4 | 16 | 0.34 |
| 8 | 16 | 0.26 | 
| 16 | 16 | 0.38 |
| 32 | 16 | 1.74 | 
| 64 | 16 | 1.4 | 

The pattern is still there, but this is a small sample set just for testing, so I do not know how this would extend at scale.

**Comment by joellembatchou** [comment]
Hi,

I tried the same run as you on an AWS EC2 instance (c5.24xlarge) with 96 threads and 192GB of memory. I did this testing here on a single BT with 10 covariates.

**Using N=2500 samples and M=38,397 variants on chromosome 1**

| CPUs | RAM (Gb) | Time (s) |
| ---- | ---- | ---- |
| 4 | 32 | 11.50 |
| 8 | 32 | 10.36 | 
| 16 | 32 | 9.79 |
| 32 | 32 | 133.34 | 

Example command:
```
docker run -t -I \
  --cpuset-cpus=0-3 \
  -m 32g \
  -u $(id -u):$(id -g) \
  -v /src/:/data/ \
  docker.pkg.github.com/rgcgithub/regenie/regenie:v2.0.1.gz regenie \
  --step 1 \
  --bed /data/test_2500N \
  --covarFile /data/covariates_2500N.tsv \
  --phenoFile /data/pheno_2500N.tsv \
  --chr 1 \
  --bsize 1000 \
  --bt \
  --threads 4 \
  --verbose \
  --out /data/step1_2500N_out
```

**Using N=25,000 samples and M=10,000 variants on chromosome 1**

| CPUs | RAM (Gb) | Time (s) |
| ---- | ---- | ---- |
| 4 | 32 | 24.73 |
| 8 | 32 | 23.28 | 
| 16 | 32 | 21.57 |
| 32 | 32 | 202.8 | 

Example command:
```
docker run -t -I \
  --cpuset-cpus=0-3 \
  -m 32g \
  -u $(id -u):$(id -g) \
  -v /src/:/data/ \
  docker.pkg.github.com/rgcgithub/regenie/regenie:v2.0.1.gz regenie \
  --step 1 \
  --bed /data/test_25000N \
  --covarFile /data/covariates_25000N.tsv \
  --phenoFile /data/pheno_25000N.tsv \
  --chr 1 \
  --bsize 1000 \
  --bt \
  --threads 4 \
  --verbose \
  --out /data/step1_25000N_out
```

As you mentioned, the timing past 16 threads decreases quite a lot and using 32 threads takes much longer than 16.

Looking into the logs, the slower timings occur when performing the ridge regression operations within blocks (which is done in Regenie using Eigen library with Intel MKL). Furthermore, in the 32 threads setting with N=2,500, blocks with same size have timings for the same operation ranging from 200ms to 12s so I think suspect this might be due to overhead from thread creation.

I will investigate this further and get back to you. Thank you for pointing this out.

Cheers,
Joelle

**Comment by joellembatchou** [comment]
Hi,

To follow up on this, I did further testing on larger sample size:

**Using N=250,000 samples and M=10,000 variants on chromosome 1**
| CPUs | RAM (Gb) | Time (s) |
| ---- | ---- | ---- |
| 4 | 32 | 208.72 |
| 8 | 32 | 193.46 | 
| 16 | 32 | 190.36 |
| 32 | 32 | 183.92 |

So the worse performance with 32 threads compared to 16 is not observed here which suggests that what was observed at N=2500 was most likely due to overhead from thread creation being a lot more expansive relative to the amount of work done by each thread. 

As Regenie is geared for large sample size problems (e.g. UKB-sized data sets), I don't think this would apply (though if working on smaller data sets, it does point out that it is not necessary [and in some cases can be more expansive] to use a large number of threads).

Cheers,
Joelle

**Comment by idinsmore1** [comment]
Great, thanks for following up on this Joelle, we really appreciate it!

Best,
Ian

From: Joelle Mbatchou ***@***.***>
Reply-To: rgcgithub/regenie ***@***.***>
Date: Sunday, April 4, 2021 at 7:36 PM
To: rgcgithub/regenie ***@***.***>
Cc: "Dinsmore, Ian R." ***@***.***>, Author ***@***.***>
Subject: [External] Re: [rgcgithub/regenie] Regenie slower with more CPUs involved (#95)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


Hi,

To follow up on this, I did further testing on larger sample size:

Using N=250,000 samples and M=10,000 variants on chromosome 1
CPUs
RAM (Gb)
Time (s)
4
32
208.72
8
32
193.46
16
32
190.36
32
32
183.92

So the worse performance with 32 threads compared to 16 is not observed here which suggests that what was observed at N=2500 was most likely due to overhead from thread creation being a lot more expansive relative to the amount of work done by each thread.

As Regenie is geared for large sample size problems (e.g. UKB-sized data sets), I don't think this would apply (though if working on smaller data sets, it does point out that it is not necessary [and in some cases can be more expansive] to use a large number of threads).

Cheers,
Joelle

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frgcgithub%2Fregenie%2Fissues%2F95%23issuecomment-813116777&data=04%7C01%7Cirdinsmore1%40geisinger.edu%7C7adfc6e7363641c25c3508d8f7c27570%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637531761861179133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LgvI%2FeTMKlK%2BrngTC03AmMpxqGwAIkHfeVTX0Om3h2U%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASUL6YB2I4GOQ7TUEZM5NBTTHDZXPANCNFSM4ZVKYNNQ&data=04%7C01%7Cirdinsmore1%40geisinger.edu%7C7adfc6e7363641c25c3508d8f7c27570%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637531761861179133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XRFmUkAN%2F37hYRXCzOZTiB7lbELblEjdRpYCIkN39wg%3D&reserved=0>.


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by carbocation** [comment]
> I tried the same run as you on an AWS EC2 instance (c5.24xlarge) with 96 threads and 192GB of memory. I did this testing here on a single BT with 10 covariates.
> 
> **Using N=2500 samples and M=38,397 variants on chromosome 1**
> 
> CPUs	RAM (Gb)	Time (s)
> 4	32	11.50
> 8	32	10.36
> 16	32	9.79
> 32	32	133.34

Hoping to double check my understanding of the benchmark in this thread. It appears that running regenie with 4 cores takes as long as running regenie with 16 cores. Is this just a function of the Dockerized version intentionally being permitted to use 4 threads for the purpose of the benchmark? I.e., if permitted to use all available cores (or perhaps N-1), I would still expect a 16-core machine with 16 threads to run regenie faster than a 4-core machine with 4 threads.

**Comment by joellembatchou** [comment]
Right, as far as elapsed time, using 16 threads would be faster than using 4 threads overall. Part of why there is not so much difference between the timings in the examples ran above is because (1) the file reading for bed format is not multi-threaded [this will be improved in the next Regenie version] (2) the parts that are multi-threaded [ridge regressions at level 0 and 1] are not requiring much work relative to the file reading which is taking the most time.

**Comment by jzluo** [comment]
> 
> 
> Right, as far as elapsed time, using 16 threads would be faster than using 4 threads overall. Part of why there is not so much difference between the timings in the examples ran above is because (1) the file reading for bed format is not multi-threaded [this will be improved in the next Regenie version] (2) the parts that are multi-threaded [ridge regressions at level 0 and 1] are not requiring much work relative to the file reading which is taking the most time.

Is reading bgen or pgen format also single-threaded?

**Comment by joellembatchou** [comment]
BGEN reading for step 1 is single threaded (this will be changed in the next release for BGEN v1.2 with 8-bit encoding) and PGEN for both Step 1 & 2 is single-threaded (we aim to also have it multi-threaded in the future).

**Comment by joellembatchou** [comment]
Genotype file reading has now been improved in v2.2; see [here](https://rgcgithub.github.io/regenie/performance/#new-timings-improvements) for details.

**Comment by Jeremy37** [comment]
I have noticed that Regenie v3.5 is still much slower when given 16 threads than when given 8. Example below.

**Part of the output with 16 threads:**
 * covariates       : [data/covariates/ukb_covariates.exome.with_rare_pcs.tsv] n_cov = 66
   -number of individuals with covariate data = 423614
 * number of individuals used in analysis = 423542
 * number of observations for each trait:
   - 'LDL_direct': 403272 observations
   - 'Standing_height': 422358 observations
 * LOCO predictions : [results/quant/regenie/all_ancestry/step1_bsize1k_l1_pred.list]
   -file [results/quant/regenie/all_ancestry/step1_bsize1k_l1_30.loco] for phenotype 'LDL_direct'
    + 1181 individuals with missing LOCO predictions will be ignored for the trait
   -file [results/quant/regenie/all_ancestry/step1_bsize1k_l1_54.loco] for phenotype 'Standing_height'
    + 1246 individuals with missing LOCO predictions will be ignored for the trait
   -residualizing and scaling phenotypes...done (74ms) 
 * threads        : [16]
 * block size       : [200]
 * blocks         : [301]
 * approximate memory usage : 2GB
 * using minimum MAC of 5 (variants with lower MAC are ignored)

Chromosome 21 [301 blocks in total]
   -reading loco predictions for the chromosome...done (1020ms) 
 block [1/301] : done (2070ms) 
 block [2/301] : done (1901ms) 
 block [3/301] : done (17051ms) 
 block [4/301] : done (35507ms) 
 block [5/301] : done (1901ms) 
 block [6/301] : done (2335ms) 
 block [7/301] : done (1895ms) 
 block [8/301] : done (34234ms) 
 block [9/301] : done (35712ms) 
 block [10/301] : done (35642ms) 
 block [11/301] : done (1905ms) 


**Part of the output with 8 threads:**
 * covariates       : [data/covariates/ukb_covariates.exome.with_rare_pcs.tsv] n_cov = 66
   -number of individuals with covariate data = 423614
 * number of individuals used in analysis = 423542
 * number of observations for each trait:
   - 'LDL_direct': 403272 observations
   - 'Standing_height': 422358 observations
 * LOCO predictions : [results/quant/regenie/all_ancestry/step1_bsize1k_l1_pred.list]
   -file [results/quant/regenie/all_ancestry/step1_bsize1k_l1_30.loco] for phenotype 'LDL_direct'
    + 1181 individuals with missing LOCO predictions will be ignored for the trait
   -file [results/quant/regenie/all_ancestry/step1_bsize1k_l1_54.loco] for phenotype 'Standing_height'
    + 1246 individuals with missing LOCO predictions will be ignored for the trait
   -residualizing and scaling phenotypes...done (99ms) 
 * threads        : [8]
 * block size       : [200]
 * blocks         : [301]
 * approximate memory usage : 2GB
 * using minimum MAC of 5 (variants with lower MAC are ignored)

Chromosome 21 [301 blocks in total]
   -reading loco predictions for the chromosome...done (1465ms) 
 block [1/301] : done (2627ms) 
 block [2/301] : done (2452ms) 
 block [3/301] : done (2787ms) 
 block [4/301] : done (2604ms) 
 block [5/301] : done (2690ms) 
 block [6/301] : done (2804ms) 
 block [7/301] : done (2751ms) 
 block [8/301] : done (2724ms) 
 block [9/301] : done (2557ms) 
 block [10/301] : done (2610ms) 
 block [11/301] : done (2595ms)
