### ISSUE TITLE
SKAT and SKAT-O Tests

### ISSUE THREAD

**Issue by GHawkes93** [rgcgithub/regenie#96]
Hi,

Many thanks for providing this software again.

I was wondering whether the development team have any plans to expand the gene-based testing to include SKAT and SKAT-O tests, for genes with bi-directional SNP effects?

Thanks again,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth,

Indeed, we have planned to add variance-component tests to REGENIE (e.g. SKAT, and optimally SKAT-O). We will notify users when that is available in the software.

Cheers,
Joelle
