### ISSUE TITLE
step 1 error

### ISSUE THREAD

**Issue by paniscusJr** [rgcgithub/regenie#97]
I’m getting the following error when I run step 1 using the UK Biobank data. I am running regenie from the docker image (v2.0.1). I made sure that I have permissions to write in the tmpdir directory. The output seems ok and was able to complete step 2. 

From step 1 log:

Level 1 ridge...
   -on phenotype 1 (ldl_direct_f30780_0_0)...ERROR : Cannot read temporary /tmpdir/regenie_tmp_preds_l0_Y1
 min value
  0.75  : Rsq = 0.0975257, MSE = 0.902398
  0.99  : Rsq = 0.0975526, MSE = 0.902522
  * making predictions...writing LOCO predictions...done (34207ms) 

List of blup files written to: [/02_GWAS/ukb_step1_LDL_pred.list]

**Comment by joellembatchou** [comment]
Hi,

Is the output you posted exactly what is printed in the log? (The format of the ERROR message does not match with what is coded in C++). Furthermore, the software should exit after the error message so it is strange it keeps on running.

Could you retry with the newest docker image (for Regenie v2.0.2)?

Cheers,
Joelle
