### ISSUE TITLE
Regenie Step 2 Burden Testing -- Blank Output

### ISSUE THREAD

**Issue by JiayiHelenZhou** [rgcgithub/regenie#98]
Hello,

we were running Regenie step 2 to do burden testing using the UK biobank data and some issues came up. The output file produced by the step 2 command is empty even though we expect to see more variants contained in it. 

The command we used:
1. With ` --anno_file` and ` --mask_def` in the regenie step 2 command:
```
  regenie \
    --step 2 \
    --bed ukb23155_c22_b0_v1.plink.exome.filtered \
    --phenoFile output/regenie_burden/phenotype_burden.regenie_phenotype \
    --covarFile output/regenie_burden/phenotype_burden.regenie_covar \
    --phenoColList ASTHMA,T2D \
    --bt \
    --firth \
    --approx \
    --pred output/regenie_burden/phenotype_burden_ASTHMA_T2D.regenie_pred.list \
    --anno-file annotation_file.txt \
    --set-list set_list_file_chr22.txt \
    --extract-sets keep_gene.txt \
    --mask-def mask_file.txt \
    --aaf-bins 0.99 \
    --write-mask \
    --build-mask max \
    --bsize 1000 \
    --check-burden-files \
    --out ukb23155_c22_b0_v1.plink.exome.filtered_burden_T2D.regenie
```
The output we have:
```
##MASKS=<mask1="LoF">
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P
```
Only the mask and header were shown in the output. We do expected to see at least a couple variants in the output, such as variant 22:15528177:C:Tand 22:16962748:CCT:C, since we manually checked for their existence in the input files (bed file, annotation file, and set list file). In addition, we also set the --aaf_bins to 0.99 to avoid over-filtering.

As a comparison, we tried to run the command without --anno_file and --mask_def parameters. The output is not empty this time. 
The command we used:
2. Without ` --anno_file` and ` --mask_def` in the regenie step 2 command:
```
  regenie \
    --step 2 \
    --bed ukb23155_c22_b0_v1.plink.exome.filtered \
    --phenoFile output/regenie_burden/phenotype_burden.regenie_phenotype \
    --covarFile output/regenie_burden/phenotype_burden.regenie_covar \
    --phenoColList ASTHMA,T2D \
    --bt \
    --firth \
    --approx \
    --pred output/regenie_burden/phenotype_burden_ASTHMA_T2D.regenie_pred.list \
    --set-list set_list_file_chr22.txt \
    --extract-sets keep_gene.txt \
    --aaf-bins 0.99 \
    --write-mask \
    --build-mask max \
    --bsize 1000 \
    --check-burden-files \
    --out ukb23155_c22_b0_v1.plink.exome.filtered_burden_T2D.regenie
```
The output we have:
```
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P
22 15528179 22:15528179:G:T G T 0.0238095 147 ADD 1.19844 0.823429 2.11825 0.836979
22 15528558 22:15528558:G:A G A 0.0125 200 ADD -0.198519 1.06524 0.0347305 0.0694781
22 15528913 22:15528913:C:T C T 0.3775 200 ADD -0.116563 0.226555 0.264712 0.216882
22 15529064 22:15529064:C:T C T 0.124352 193 ADD -0.0243028 0.362856 0.00448585 0.0238333
22 15690112 22:15690112:C:T C T 0.0928962 183 ADD -0.310406 0.367281 0.714268 0.400083
22 15690179 22:15690179:G:A G A 0.0125628 199 ADD -2.56923 1.71961 4.55106 1.48283
22 15690314 22:15690314:C:T C T 0.0142045 176 ADD 0.648681 0.963532 0.453243 0.300336
22 15690536 22:15690536:A:G A G 0.0289474 190 ADD 0.614123 0.675468 0.82661 0.439789
22 15690591 22:15690591:G:A G A 0.0126263 198 ADD 0.0364513 0.981778 0.00137847 0.0130568
22 15690624 22:15690624:G:A G A 0.0131579 190 ADD -0.0877885 1.02319 0.0073614 0.0307582
```
(Above is showing the first 10 lines in the output.)

We have tested out this burden testing using Regenie v2.0.2, and the environment I was working in is Ubuntu 20.04. 
Could you please offer us some insight on why this is happening and how to tackle this problem? 

I have sent all relevant data to the email address: joelle.mbatchou@regeneron.com.

Thank you so much!

**Comment by joellembatchou** [comment]
Hi,

All the variants in the mask are monomorphic, hence are skipped from the analysis. I've sent you some code that you can use to double check.

Cheers,
Joelle

**Comment by JiayiHelenZhou** [comment]
I see! Thank you so much!

**Comment by ludgergoeminne** [comment]
Dear Joelle

I am trying to run REGENIE's burden testing on the DNA nexus portal with UK Biobank's whole exome sequencing data,
and I am having a similar issue: I also get a blank output file for my gene _GCDH_.

Nonetheless, I am testing with very broad custom masks:
```
M2 LoF,missense(0/5),missense(5/5),missense(>=1/5),synonymous
M3 LoF,missense(0/5),missense(5/5),missense(>=1/5)
M4 LoF
```
I think that most of my variants are not monomorphic; for example, I tested variant "19:12896058:T:C" before in the genotyping data, and its allelic distribution in UK Biobank is 487609 - 389 - 1 (TT - CT - CC, respectively), while its annotation is "missense(5/5)". I also get a result for it if I test the variants separately.

I also tested with the example gene _PCSK9_ given [here](https://dnanexus.gitbook.io/uk-biobank-rap/science-corner/using-regenie-to-generate-variant-masks), and there, I get an output for M2 and M3 (starting from --aaf-bins 0.05 and higher). Here, I don't understand why I get a different result for --aaf-bins 0.5 and --aaf-bins 0.99? I'm not sure if --aaf-bins indicates the maximal minor allele frequency for a variant to be included in the mask or the maximal alternative allele frequency to be included in the mask. If it is the latter, is there a way to do the inclusion based on minor allele frequency?

This is the input I have been giving to REGENIE. For now, I am still testing without step 1:
```
    ./regenie_v2.2.4.gz_x86_64_Linux_mkl \
    --step 2 \
    --ignore-pred \
    --bed ${genotype_prefix_GCDH} \
    --ref-first \
    --phenoFile $phenotype_file_WBA \
    --covarFile $phenotype_file_WBA \
    --remove "/opt/notebooks/exclude_WBA.txt" \
    --phenoColList whole_body_fat_percentage,systolic_blood_pressure \
    --covarColList age_first_visit,sex_male,age_first_visit_X_sex_male,pc_{1:10} \
    --set-list "${path_to_450kwes_helper_files}/ukb23149_450k_OQFE.sets.txt.gz" \
    --anno-file "${path_to_450kwes_helper_files}/ukb23149_450k_OQFE.annotations.txt.gz" \
    --mask-def "custom_masks.masks" \
    --extract "/opt/notebooks/keep_variants_GCDH.txt"  \
    --aaf-bins 0.01,0.05,0.5,0.99999 \
    --bsize 200 \
    --out REGENIE_output/GCDH_WBA_burden
```

Could you suggest me what I am doing wrong here?

Best regards

Ludger Goeminne

**Comment by EstelLec** [comment]
Hello,
I am running Regenie step 2 to do burden testing using the UK biobank data WES 450k on UKB RAP (regenie v2.2.4) and I have a similar issue, and I would need your help.
I run this command :
```
regenie --step 2 --bed ukb${data_field}_c${chr}_b0_v1 --out assoc_gene.c${chr}\
    --ref-first \
    --phenoFile ${ped_file} --covarFile ${ped_file}\
    --extract WES_c${chr}_snps_qc_pass.snplist\
    --phenoCol SBPZvalues --phenoCol DBPZvalues \
    --covarCol Age --catCovarList Eth,Sex --covarCol PC{1:10} \
    --pred All_results_pred.list --bsize 200 \
    --minMAC 3 --threads 16 --gz \
    --set-list ukb23149_450k_OQFE.sets.txt.gz \
    --anno-file ukb23149_450k_OQFE.annotations.txt.gz \
    --mask-def ukb23149_450k_OQFE.masks \
    --aaf-bins 0.1,0.05,0.01,0.001 \
    --write-mask-snplist 

```
And the log shows 307 sets running :
```
Chromosome 13 [307 sets in total]
-reading loco predictions for the chromosome...done (1760ms) 
set [1/307] : 66 variants...
-reading in genotypes and building masks...done (97ms) 
set [2/307] : 7 variants...
-reading in genotypes and building masks...done (16ms) 
```
But there is only one gene in my output. It seems it runs on 307 genes, am I wrong ? I have the same problem for all chromosomes, sometimes there is no gene at all in the output.
How could I correct this ? 
Thank you

**Comment by scienception** [comment]
@ludgergoeminne aaf-bins refers to the AAF rather than MAF, were you able to figure out a workaround for this?
